### ISSUE TITLE
UPnP Port Mapping failing on Android and Linux

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7865] opened 2019-01-01 19:39 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I was going to test netplay with @cucholix from my shield and I realized it wasn't opening ports properly.
I checked my router and the mappings were not being added.

I added an error message and it's now just printing UPnP Port Mapping failed.
I can't add any more messages because the code is part of libretro-common and that doesn't have any logging

### Expected behavior

Ports should be mapped automatically

### Actual behavior

UPnP mapping is failing

### Steps to reproduce the bug

1. Start a game
2. Start netplay host

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment] 2019-01-01 23:07
@fr500 I suppose this worked before? It sounds like a massive pain, but bisecting might be the best way to narrow it down. Otherwise you might be able to debug it more with plain `printf` debugging?

**Comment by fr500** [comment] 2019-01-01 23:58
I really couldn't tell and building for android is in fact a pita like you said

**Comment by fr500** [comment] 2019-01-02 00:42
Just tried on linux, it failed there too

**Comment by orbea** [comment] 2019-01-02 01:10
I seem able to reproduce it.
```
[INFO] [netplay] Waiting for client ...
[ERROR] Failed to set up netplay sockets.
[WARN] Failed to initialize netplay.
```

**Comment by orbea** [comment] 2019-01-02 19:31
@fr500 Is this a duplicate of issue https://github.com/libretro/RetroArch/issues/4550?

**Comment by fr500** [comment] 2019-01-02 23:36
yes

**Comment by fr500** [comment] 2019-02-06 14:48
Ok, the linux thing was a network issue.
Android is still failing tho.

**Comment by slav0nic** [comment] 2019-08-14 20:12
looks like UPNP feature not enabled in Lakka too, `HAVE_BUILTINMINIUPNPC/HAVE_MINIUPNPC` not set?

**Comment by LootusMaximus** [comment] 2019-08-14 21:35
This worked for me when i tried last on android. Been a few months

**Comment by michael-myers** [comment] 2021-11-01 00:03
I believe this issue also affects the macOS client, RetroArch version 1.9.12.

To confirm that UPnP does work on your network and RetroArch _should_ be able to set up a port forward rule (but it can't), you can use the following in a Python interpreter:

```shell
pip3 install upnpy
```

```python
Python 3.9.7 (default, Sep  3 2021, 12:37:55) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import upnpy
>>> devices = upnp.discover()
>>> device = upnp.get_igd()

// if the last line above fails:
>>> devices
[Device <Philips hue (192.168.254.69)>, Device <Philips hue (192.168.254.69)>, Device <Philips hue (192.168.254.69)>, Device <Frontier-NVG468MQ>, …]
>>> device = devices[3]
>>> device
Device <Frontier-NVG468MQ>

// continuing:
>>> device.get_services()
[<Service (Layer3Forwarding) id="L3Forwarding1">, <Service (WANCommonInterfaceConfig) id="WANCommonIFC1">, <Service (WANIPConnection) id="WANIPConn1">, <Service (WANPPPConnection) id="WANPPPConnection">, <Service (LANHostConfigManagement) id="LANHostConfigManagement1">]
>>> service = device['WANPPPConnection']
>>> service.get_actions()
[<Action name="GetInfo">, <Action name="GetUserName">, <Action name="GetStatusInfo">, <Action name="SetUserName">, <Action name="SetPassword">, <Action name="RequestConnection">, <Action name="RequestTermination">, <Action name="ForceTermination">, <Action name="GetPortMappingNumberOfEntries">, <Action name="AddPortMapping">, <Action name="DeletePortMapping">]
>>> service.AddPortMapping.get_input_arguments()
[{'name': 'NewRemoteHost', 'data_type': 'string', 'allowed_value_list': []}, {'name': 'NewExternalPort', 'data_type': 'ui2', 'allowed_value_list': []}, {'name': 'NewProtocol', 'data_type': 'string', 'allowed_value_list': ['TCP', 'UDP']}, {'name': 'NewInternalPort', 'data_type': 'ui2', 'allowed_value_list': []}, {'name': 'NewInternalClient', 'data_type': 'string', 'allowed_value_list': []}, {'name': 'NewEnabled', 'data_type': 'boolean', 'allowed_value_list': []}, {'name': 'NewPortMappingDescription', 'data_type': 'string', 'allowed_value_list': []}, {'name': 'NewLeaseDuration', 'data_type': 'ui4', 'allowed_value_list': []}]
>>> service.AddPortMapping(NewRemoteHost='',NewExternalPort=89,NewProtocol='TCP',NewInternalPort=8989,NewInternalClient='192.168.254.28',NewEnabled=1,NewPortMappingDescription='Test port mapping from UPnPy.',NewLeaseDuration=0)
{}
>>> service.GetPortMappingNumberOfEntries()
{'NewPortMappingNumberOfEntries': '1'}
```

In another tab, use a Python2 quick HTTP server on port 8989:
```shell
python -m SimpleHTTPServer 8989
```

In a browser, access your external IP and port 89, and watch the UPnP port forward actively working.

**Comment by LibretroAdmin** [comment] 2022-09-03 03:58
@Cthulhu-throwaway Can we close this?

**Comment by michael-myers** [comment] 2022-10-02 00:15
I just tested with macOS 12 (x86-64) and RetroArch 1.11.0. The UPnP Port Mapping bug is fixed and I see a successful port mapping now.

**Comment by LibretroAdmin** [comment] 2022-10-02 01:53
Good to hear macOS is now fixed.

**Closed** 2022-10-02 01:54 UTC
Labels: platform: android, platform: linux, bug: netplay
