### ISSUE TITLE
[iOS] Please implement mouse grab for cases of physical mice use

### ISSUE THREAD

**Issue by TyroneSlothrop** [libretro/RetroArch#15483] opened 2023-07-15 18:14 UTC
Description:
- Mouse grab option available in desktop versions of RetroArch is not well supported on iOS: the current mouse emulates a 'click to drag' method forcing one to tap/drag which is fine with pen or finger, but hindering with a physical mouse.

Expected behaviour:
- Bluetooth/connected physical mouse's movement should not require depressing the primary button to move the cursor.

Actual behaviour:
- One has to hold down left mouse button to move the curosr which is unaccessible/unergonomic, less precise and frustrating.

Additional notes:
- I don't have swift/c knowledge but it seems like the issue is with EmulatorTouchMouse.touchesMoved where the event tracking the cursor is only done whilst the primary button is depressed. If this could be made to factor in the ReatroArch mouse grab setting then this could potentially be used to keep updating the location of the cursor, without causing regressions for other input types (notably those players using touch input)
- Compare two videos attached, one is desktop, other on iOS (iPhone): the former is much faster and precise in navigating the game (footage of public domain game).

Environment information:
- On iOS 13+
- Only input driver available is 'cocoa' and controller driver options are 'mfi' (always used), or 'hid' (never used)

On desktop:
![Desktop mouse control](https://github.com/libretro/RetroArch/assets/1816777/2bea2142-d492-44e4-b922-6cd374c5877c)

On iPhone:

https://github.com/libretro/RetroArch/assets/1816777/c15aeb1f-12dd-48a0-811f-d5225071d897

**Comment by PatrickStankard** [comment] 2024-02-07 22:26
It seems like proper mouse support was added in 13.4 based on [this issue](https://github.com/libretro/RetroArch/issues/10769), is that the iOS version you're running? Also, what core are you running?  What version of RetroArch?

**Comment by TyroneSlothrop** [comment] 2024-02-08 21:42
Thank you so much for having a look. Goal here is to be able to use a bluetooth mouse in 'mouse grab' mode such that the pointer moves with the mouse for e.g. strategy and point and click games, or utilities (tracker/paint software on Amiga), as well as general Win9X navigation on DosBox PURE.

My setup:
 iPhone 11 Pro Max, iOS 17.3
 RA version 1.17.0 (Git version 429e83745e)
 Bluetooth logitech POP mouse

Retroarch settings: 
 Automatic Mouse Grab: on
 Auto Enable 'Game Focus' mode: on

Cores (non-exhaustive) with versions, most as of Feb 4th 2024:
 PUAE 5.0.0 2cad13f
 DOSBox-pure 0.9.9
 ScummVM eba4a8679-2.9.0git
 Numero 1.1 19354c9 

Only the following works:
 1- with no additional options, for all above cores then the pointer just remains unmoved as I move the mouse - pointer can move if I use a controller/analog stick though

 2- with iOS's 'assistive touch' mode on AND the RA 'Touch mouse enabled' (the little iOS-specific mouse icon in retroarch bar at top), then:
- I can control the menu with the mouse and click into options as I would expect
- for cores though, I need to hold down a mouse button whilst moving the mouse for the cursor to move (so 'hold and drag')

So 2 is just mimicking one's finger with the mouse and not exactly what I want (which is to use the mouse as a mouse to be grabbed and just control the pointer).

I'm happy to help test anything - my current thinking is just that the mouse is not 'recognised' by iOS RA itself properly.

**Comment by PatrickStankard** [comment] 2024-02-09 15:35
When you launch a core, open the in-game quick menu and see if there is anything under "Core Options" or "Controls" that lets you update the input to mouse, instead of a pointer. The default hotkey for opening the quick menu is F11, but if you don't have a keyboard, you can reassign it to something else by going to `Settings > Input > Hotkeys > Menu Toggle`

**Comment by PWarren471** [comment] 2024-05-25 07:07
Just wanted to add that I see the same issue on retroarch 1.18.3 with the PUAE Amiga core when playing Cannon Fodder on IOS. Just wondering if a definite fix has been added?

There also seems to be an issue when holding the left mouse button down and clicking the right button (to throw a grenade in the game)... It's like the left click action is locked in and you have to press right click left click to unlock it.

**Comment by 0507spc** [comment] 2024-06-08 01:08
Mouse / trackpad both seem to work on iPad (and have multiple co troller options for the mouse). iPhone is missing these. 

iPad works with focus mode on.

**Comment by michael-leroy** [comment] 2024-07-17 07:00
I am having this issues as well. This is what I am using.
M4 IPad Pro
External USB mouse and Smart Keyboard trackpad.
Retro arch - 1.19.1 (app store version)
Dosbox-pure - 0.9.9

I tried every option. Bound mouse grab to a button and it appears to do nothing as well. Game focus on/off appears to make no difference with mouse input. Pretty much makes any mouse controlled game (Quake, Fallout 2) impossible to play. I have tried UTM-SE and an external USB mouse works properly. Perhaps something can be modified to allow mouse cursor lock for an external mouse?

Click to drag makes sense with a touch bad but once you have the apple trackpad or external mouse it’s less than ideal.

**Comment by michael-leroy** [comment] 2024-07-18 03:21
I have a partial solution @TyroneSlothrop . In main RA settings —> user interface —> on screen overlay, turn off enable overlay lightgun, mouse and pointer. After this you wont need to hold left click to have the cursor move.

Now we just need a solution so there is not a double mouse cursor (the round ipadOS and the Windows 98 cursor). Baby steps I guess.

**Comment by michael-leroy** [comment] 2024-08-13 20:55
I am not 100% familiar with RA code, but looking at input/drivers/cocoa_input.m there appears to be nothing implemented to do mouse grab on iPad. Perhaps the code needs to be expanded to handle iPad differently than an iPhone as well? Physical mice are not really supported on an iPhone, but is on an iPad.

Other apps like UTM SE, iDOS 3 and Minecraft support proper mouse grab and you can play these games on ipad with a physical mouse as intended. No double cursors.

I would attempt this myself and do a PR, but I don't really have a way to test the code. (no way to make a ios/ipados build and get it on my ipad.) Apple sure makes it a hassle. Probably why nobody is really keen to fix an issue like this.

**Closed** 2024-08-22 19:11 UTC
Labels: platform: ios

**Comment by michael-leroy** [comment] 2024-08-23 19:36
@warmenhoven thanks for this addition! I actually started to work on this as well, but you beat me to it! I will try it tonight.

Do you think mouse support could be improved even further by including features offered in iOS 14 (GameController/GCmouse)?

https://developer.apple.com/videos/play/wwdc2020/10617

**Comment by warmenhoven** [comment] 2024-08-23 20:37
I did originally start down the GCMouse route but didn't find that it integrated well with how cocoa_input already thinks about input, nor how the trackpad on the Magic Keyboard really wants to be used, and couldn't figure out a way to get GCMouse and the PointerInteraction stuff to work together in a way that made sense. I think the fixed up interaction is pretty good and works well enough with both the trackpad and a Bluetooth mouse. If there's something that still amok I'm happy to take another look.

**Comment by michael-leroy** [comment] 2024-08-24 00:24
@warmenhoven your change, while a welcome improvement, does not seem to lock the system cursor in place. This means for example in a game like Quake (under dosbox-pure) you can't continuously look left/right with the mouse. Once the hidden system cursor hits the edge of the screen the mouse input stops working. Or if you move the mouse to the upper right far enough the quick settings menu will open.

I did ensure I had mouse grab set to on in RA-->input and game focus mode on.

UTM SE and Minecraft don't suffer from these problems with mouse input so it should be possible to fix.

Looking at Apple's docs it seems something like this needs to be implemented:

```swift
class GameViewController: UIViewController {
    
    var shouldLockPointer: Bool = true
    
    override var prefersPointerLocked: Bool {
        return self.shouldLockPointer
    }
    
    func disablePointerLock() {
        self.shouldLockPointer = false
        self.setNeedsUpdateOfPrefersPointerLocked()
    }
}
```
From there you will have to track movement deltas instead of just the cursor changing position.

Please forgive me if I am way off. I am pretty new to iOS stuff, but I really want to do what I can to help so RA can use a mouse as well as it can on Windows. The OS (iPadOS 13.4 or 14.0) is not the limiting factor in this case.

Perhaps this issue should be reopened? I can submit a new issue if you want to track it there. I will be glad to test any changes you want from a testing branch if you want.

**Comment by warmenhoven** [comment] 2024-08-24 00:27
Ah, I see what you're saying. I'll take a look. Thanks.

**Comment by warmenhoven** [comment] 2024-08-25 02:57
It's a little bit more complicated than that; when the pointer is locked, the pointer interaction events no longer fire, so the only way to get the information on mouse movement is using GCMouse, and now I see why I was having a hard time getting the two to work together in a way that made sense. I think I might have a good path forward now.

**Comment by TyroneSlothrop** [comment] 2024-08-26 16:04
Hi guys - first thanks to Eric for the recent changes - secondly sorry to be dumb here, but using a build from Saturday including this PR I still didn't get the 'grab' to work on an iPhone with bluetooth mouse - what settings do I need for pUAE? Is it the lightpen? Or should the little mouse icon in the top bar just work?

**Comment by warmenhoven** [comment] 2024-08-26 18:26
https://github.com/libretro/RetroArch/pull/16933

@TyroneSlothrop probably you need this as well.

**Comment by michael-leroy** [comment] 2024-08-26 18:40
> #16933
> 
> @TyroneSlothrop probably you need this as well.

Taking a looking at this PR, this looks very promising! I will try it out tonight.

**Comment by michael-leroy** [comment] 2024-08-28 19:11
@warmenhoven I got a chance to try this the other day. This is certainly an improvement, but it still does not fully fix the issue. The system cursor can still open the quick settings and app dock. It's not bound/locked to the confines of the RA/emulator running.

A way to test it is to load up any FPS in say dosbox-pure with mouse support (shareware Quake is ok and enable +mlook in the game console.) and continuously look left or right. Right now with the current behavior the attempt to look left/right will stop once the system cursor hits the end of the viewable area creating a bouncing effect.

I attempted to find another project that has this done correctly as a reference, but the only one I could really find was UTM. Maybe some clues are here? https://github.com/utmapp/UTM/blob/main/Platform/iOS/Display/VMDisplayMetalViewController%2BPointer.m

Seems like a bounding box is needed to contain the pointer/cursor? This part looks promising.

```swift
- (UIPointerRegion *)pointerInteraction:(UIPointerInteraction *)interaction regionForRequest:(UIPointerRegionRequest *)request defaultRegion:(UIPointerRegion *)defaultRegion {
#if !TARGET_OS_VISION
    if (@available(iOS 14.0, *)) {
        if (self.prefersPointerLocked) {
            return nil;
        }
    }
#endif
    // Requesting region for the VM display?
    if (interaction.view == self.mtkView && self.hasTouchpadPointer) {
        // Then we need to find out if the pointer is in the actual display area or outside
        CGPoint location = [self.mtkView convertPoint:[request location] fromView:nil];
        CGPoint translated = location;
        translated.x = CGPointToPixel(translated.x);
        translated.y = CGPointToPixel(translated.y);
        
        if ([self isPointOnVMDisplay:translated]) {
            // move vm cursor, hide iOS cursor
            [self.cursor updateMovement:location];
            return [UIPointerRegion regionWithRect:[self.mtkView bounds] identifier:@"vm view"];
        } else {
            // don't move vm cursor, show iOS cursor
            return nil;
        }
    } else {
        return nil;
    }
}
```

**Comment by warmenhoven** [comment] 2024-08-28 19:50
Like this?

https://github.com/user-attachments/assets/0cdc5718-8770-48a7-9cf0-6c94bd2e749e

It's working for me.

**Comment by warmenhoven** [comment] 2024-08-28 19:57
@michael-leroy I don't suppose you're on discord? It might be easier to talk things through there.

**Comment by michael-leroy** [comment] 2024-08-28 21:25
> @michael-leroy I don't suppose you're on discord? It might be easier to talk things through there.

I did another build from master and I can reproduce what you showed in the video above. But try holding the mouse button as you turn. It does not seem like you can hold the mouse button and move the cursor at the same time. I will reach out on discord. Need to make an account...
