### ISSUE TITLE
[Android] [F-Droid] Current Status of LibRetro F-Doird Repository

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#11922] opened 2021-01-21 12:14 UTC
Not a bug report, just asking if [LibRetro F-Droid Repo](https://fdroid.libretro.com/repo/) is deprecated. The last update dates back to last November while IIRC it should be nightly release like the one in [buildbot](https://buildbot.libretro.com/nightly/android/).

BTW, I notice there is RetroArch Plus on Play Store as mentioned in [LibRetro news](https://www.libretro.com/index.php/retroarch-android-new-versions-for-play-store-please-read/). If F-Droid repo is not reprecated, would there be two versions of RetroArch in it?

I see there are #4247, #6446 and #7940 so I assmue this is the right place to ask the question.

**Comment by QmwJlHuSg9pa** [comment] 2021-01-25 06:15
Similarly, I have recently noticed that https://f-droid.org/packages/com.retroarch (as well as com.retroarch.a32 and com.retroarch.aarch64) now 404s.

**Comment by delvier** [comment] 2021-04-09 02:08
Even though 1.9.1 came out a few days ago, indeed there is still no update on the repo. Since F-Droid is listed on Android download section without strike-through line, the repo needs to be updated or unlisted from the download page.

**Comment by GitJamz** [comment] 2021-04-24 13:41
I came here after noticing I cant install retroarch from fdroid... nothing happens when you click on install

**Comment by bluemonkeysuit07** [comment] 2021-06-06 09:48
F-Droid repository is still at version 1.9 from november . will retroarch releases continue to be released?

**Comment by hizzlekizzle** [comment] 2021-06-07 01:53
There's a guy who has historically set up the fdroid stuff for us. He's been busy for the past few months but has popped in long enough to say that he intends to get it going again soon(TM)

**Comment by aaronhatesregex** [comment] 2021-06-07 05:28
Thanks for the clarification! I guess now we just need a little patience then 😄.

**Comment by mase76** [comment] 2021-06-14 07:31
Maybe we should file a request in fdroid-data. But I am not sure, if Retroarch is fully compliant for F-droid.

**Comment by hizzlekizzle** [comment] 2021-06-14 13:08
RetroArch itself is / should be, but many of the cores are not, and I recall they didn't like that it can download "non-free" cores, despite including the license information in the program so users know what they're getting.

**Comment by huupoke12** [comment] 2021-12-11 11:07
Hi, it has been 6 months since the last update. Can you give an update on the current status please? Thank you.

**Comment by Slavko-P** [comment] 2022-02-06 14:53
As of writing this, Retroarch is still at 1.9.0_GIT. Isn't there a way to automate this on each new release?

**Comment by Littlemac123** [comment] 2022-02-14 20:38
is making a f-droid repo auto update the stable really that complicated ?
~~sorry if i sound rude <3

**Comment by denilsonsa** [comment] 2022-03-11 15:19
Having an up-to-date f-droid-compatible repository would be very convenient for users. (And some people would prefer a repository with just releases versions, other people would prefer nightly builds: #7940)

Currently, the latest version from the f-droid repository is 1.8.4 from November 2020.
And, due to #12181, the latest version from Google Play Store is 1.9.12 from November 2021.
We are in March 2022 and the latest release is 1.10.1.

To make the matters worse for the end-user, both Google Play and the f-droid repository are still listed as official ways to download RetroArch: https://retroarch.com/?page=platforms

![Screenshot of the RetroArch download page](https://user-images.githubusercontent.com/121676/157895268-f2c967a4-a60a-4c66-978b-14919f6a8b19.png)

This leads to users downloading outdated versions without noticing, which can lead to obsolete bug reports and support requests, and also extra time spend by the user to manually install (side-load) a recent version.

**Comment by gouchi** [comment] 2022-03-15 09:05
@Ferk According to the [reply from your post](https://forum.f-droid.org/t/what-about-a-libre-edition-retroarch-apk/17526) on the F-Droid forum, we should indeed consider "Libre Edition" RetroArch apk with Libretro cores bundled.

**Comment by QmwJlHuSg9pa** [comment] 2022-03-15 23:51
From the linked thread:

> So the free cores that are GPL-compatible would be bundled in the Retroarch apk, any non-free or license-incompatible core would be excluded, and the downloader that allows obtaining external cores would be disabled.

Who would actually desire this behaviour?

I appreciate the F-Droid project because it gives me freedom and privacy by default (as opposed to the Google ecosystem/Google Play store experience). I don't understand why one would want these artificial restrictions imposed -- I mean, doesn't F-Droid explicitly tolerate "anti-features"? And why force bundling of cores?

FWIW, my preference would be for the vanilla APKs (nothing bundled, nothing disallowed) currently available from the RetroArch website.

**Comment by mase76** [comment] 2022-03-16 07:11
I would also prefer to bundle no cores and keep the downloader enabled.

**Comment by IzzySoft** [comment] 2022-04-02 20:30
Closely related: there's an [inclusion request](https://gitlab.com/fdroid/rfp/-/issues/1933) pending with us at F-Droid. Is there any chance we can process that? The scanners found a couple of issues, so it's currently™ (for 4 month) waiting for feedback. Could one of you please take a look and see if that can be solved? Thanks in advance!

**Comment by hizzlekizzle** [comment] 2022-04-03 00:39
The bitmap font is for the RGUI menu, which would be good to keep around if at all possible. I'm not sure about the build.gradle thing.

**Comment by IzzySoft** [comment] 2022-04-03 10:05
Ah, that `.bin` is just a font – OK, there should be no problem with that. Leaves us with the Google Services which seemingly are included (which is what that gradle thing means):

```gradle
dependencies {
  implementation 'com.google.android.play:core:1.8.0'
}
```

That's a show stopper, as it's proprietary.

**Comment by IzzySoft** [comment] 2022-06-05 09:32
Just in case GitLab notifications are missed: the RFP at F-Droid is currently stuck waiting for the question concerning literal version numbers needed for automated update checking (you're using [dynamic values](https://github.com/libretro/RetroArch/blob/master/pkg/android/phoenix/build.gradle#L42) currently). Details [here](https://gitlab.com/fdroid/rfp/-/issues/1933#note_937360830), an answer is highly appreciated.

**Comment by Ferk** [comment] 2022-06-05 12:35
I think those are being manually updated in the manifest when there's a new release, aren't they?
https://github.com/libretro/RetroArch/blob/8b5b1ce96dcba293c4abb65333687b69757907bc/pkg/android/phoenix/AndroidManifest.xml#L5-L6

**Comment by IzzySoft** [comment] 2022-06-05 13:17
I was pointing to the `build.gradle` – and there it wasn't set to "fixed values" with the last release. But thanks for the pointer, I'll update the RFP with that detail. Once the merge request was opened, we'll see if checkupdates is looking at the Manifest as well.

**Comment by IzzySoft** [comment] 2022-06-18 10:36
Besides that there's no merge request opened yet, any chance we can get the app's metadata (description, screenshots etc) in [Fastlane structures](https://gitlab.com/-/snippets/1895688) here in the app's repo, so you stay in control of it (and F-Droid simply pulls it along with the other updates)?

**Comment by farmerbb** [comment] 2022-06-18 16:34
@IzzySoft I opened a PR with the Play Store metadata added to the repo in Fastlane format, do you mind double checking and make sure the structure is correct?

**Comment by IzzySoft** [comment] 2022-06-18 18:00
Wow, even filled multiple layers of (screen size specific) screenshots! Thanks a lot, looks very good! I'll leave a note on the RFP. Can you give me another ping once you've tagged the next release (as bot and build look for Fastlane at the tag)?

**Comment by KingDuckZ** [comment] 2022-07-19 16:55
I've been looking at this and I thought I'd see something a few days ago. A bit disappointed to see the due date moved by a whole month :( how likely is it that the 15th of August is accurate?

**Comment by IzzySoft** [comment] 2022-08-14 08:36
@KingDuckZ the due date is just a reminder for us to check back with upstream should nothing happen – which is why I'm here again now (the reminder fired, as the next due-date was reached). Seems there#s still no new tag. As @farmerbb seems to be active on Github (according to his profile), is there any chance now for an ETA on the next tag?

**Comment by farmerbb** [comment] 2022-08-14 22:03
@IzzySoft I don't have any insight on when releases or tags are made, sorry.

**Comment by IzzySoft** [comment] 2022-08-14 22:34
Thanks Braden – then who does? @LibretroAdmin seems to have suggested you would, but it looks like I misunderstood the suggestion then. F-Droid is just waiting for a new tag to be able to pick up again.

**Comment by hizzlekizzle** [comment] 2022-08-14 23:50
It is libretroadmin who makes the tags/releases, we just haven't done a stable in >4 months. It's probably about time to do so, though, and if that's what's holding us up, we should consider doing it ASAP.

**Comment by IzzySoft** [comment] 2022-08-15 06:41
Just let us know please (here or at the RFP) when it's available. Thanks a lot!

**Comment by hizzlekizzle** [comment] 2022-08-15 20:17
I spoke with him today and it sounds like we might have something going within the next week or so. I'll be sure we ping you here once it's done. Thanks!

**Comment by IzzySoft** [comment] 2022-09-13 03:31
Due-date of the RFP was reached for the third time now, but it seems this is still hung. Will lift it one more time – but we don't want to keep it open eternally I guess :wink:

**Comment by LibretroAdmin** [comment] 2022-09-13 05:15
It's taking us time to get a new stable out. We hope to have something out before the end of this month.

**Comment by hizzlekizzle** [comment] 2022-09-30 13:56
@IzzySoft the new tag was just added. Let us know if we need to do anything else on our end.

**Comment by IzzySoft** [comment] 2022-09-30 20:17
Thanks! I've removed the due date from the RFP and triggered another issuebot scan. If results permit, hopefully it will be picked up for a merge request soon.

**Comment by hizzlekizzle** [comment] 2022-09-30 20:52
Thanks! Keep us posted if we need to do anything else to get it rolling :)

**Comment by IzzySoft** [comment] 2022-10-01 11:27
We'll at least ping you from the RFP then. As building your app is far beyond my expertise, I've pinged another maintainer who promised to take a look. Might still take a little as I guess his queue is well filled, so please bear with us :wink:

**Comment by licaon-kter** [comment] 2022-10-05 13:53
Feedback pls: https://gitlab.com/fdroid/rfp/-/issues/1933#note_1125250001

**Comment by hizzlekizzle** [comment] 2022-10-05 14:53
Does the changelog need to be in a specific format? Or could we just copy our main CHANGES.md into that location with the version string as the name?

**Comment by licaon-kter** [comment] 2022-10-05 15:05
Just a .txt file with some (not huge though) info on changes

**Comment by LibretroAdmin** [comment] 2022-10-05 18:30
We have a file called CHANGES.md in the root of the repository, is there not a possibility you guys can just copy and paste that on your end in some way to form the package? That way we wouldn't have to duplicate files and keep maintaining it whenever we push an update.

**Comment by hizzlekizzle** [comment] 2022-10-05 19:29
oh yeah, we wouldn't want our full changelog there, I suppose :O

**Comment by Vinfall** [comment] 2022-10-11 08:38
For a BAD practice, you can just point it to a fixed URL like https://www.libretro.com/index.php/category/blog/ or https://github.com/libretro/RetroArch/blob/master/CHANGES.md, if that's what remains before shipping RetroArch onto F-Droid (at last).

Tutanota did that for [their F-Droid package](https://f-droid.org/en/packages/de.tutao.tutanota/):
```
New in version {{xxx}}
see: https://github.com/tutao/tutanota/releases
```

Again this is BAD as it per se tells nothing, but if I read right, we are shipping the tagged stable releases, so checking the url a few times a year is not that bad for me.

**Comment by licaon-kter** [comment] 2022-10-11 09:00
So much talk about a bit of text, but no one tested the actual APK? :)

**Comment by Vinfall** [comment] 2022-10-11 10:25
@licaon-kter Sorry I should have clarified that I'm not a contributor, just a passer-by user giving random suggestions I think up that may help the developers.

***

I downloaded the APK from RFP, and made a quick test on two devices (regular phone running Android 12 & Switchroot running Android 10), here is the only problem I could find:

- **Symptom**:
	- Initial start of the app complains about missing assets
	- Go back button, five navigate buttons in the buttom, some characters in system information render incorrectly
- **Speculation**: Because of the missing assets
- **Solution**: After downloading the assets using the online updater, all issues are gone.
- **Suggestion**: the developer could add a bit instruction on this.

The features I tested that work:
- download cores/assets, update installed core
- bluetooth controller
- run standalone cores with auxiliary system files (Cave Story NX Engine)
- database query

I didn't test other features like import content, GLSL shaders, cheats, achievements etc, but I think it's supposed to be ok❤️

**Comment by licaon-kter** [comment] 2022-10-11 10:36
Thanks for testing, I'm not aware on how this should work _(can the assets be bundled in the APK or is their license problematic so we resort to downloading?)_.

**Comment by hizzlekizzle** [comment] 2022-10-11 17:55
licenses on assets should be fine/compatible. Can your recipe fetch them from a URL at bundle-time?

**Comment by licaon-kter** [comment] 2022-10-11 18:39
Maybe, where are they and why aren't they in the repo here?

**Comment by hizzlekizzle** [comment] 2022-10-11 19:41
They're all in here:
http://buildbot.libretro.com/assets/frontend/
We don't include them in the main RetroArch repo for a few reasons, including that they're frequently their own thing managed by individuals outside of RetroArch itself (e.g., I manage the shaders, which are used by a few different programs outside of RA), and adding a few hundred MBs of images to every repo clone would be a real drag, among other reasons.

**Comment by IzzySoft** [comment] 2022-10-11 20:48
> adding a few hundred MBs of images to every repo clone would be a real drag

Then maybe git submodules could work for this?

**Comment by licaon-kter** [comment] 2022-10-11 20:50
Well, it's not like the APK can't be huge... but does it need to? :)

**Comment by Vinfall** [comment] 2022-10-12 13:04
> is making a f-droid repo auto update the stable really that complicated ? ~~sorry if i sound rude <3

As many people wondering why it takes so much time waiting, I tried to set up a self-hosted RetroArch nightly repo and it's surprising easy. Basically it's just a few commands to init the repo & write a script w/ crobjob to automate the update.

For anyone interested:
- [Sample repo](https://github.com/Vinfall/fdroid-server): you can scan https://github.com/Vinfall/fdroid-server/blob/main/repo/index.png or add `https://raw.githubusercontent.com/Vinfall/fdroid-server/main/repo?fingerprint=C3A7B8145FB872B67C48E7BA9E6A079E582DDCF5AAFD00F6143E91B8F45187F6` to F-Droid client to see the result. Please note there is actually no app hosted as it will abuse GitHub & I don't plan to maintain it.
- [My blog with some details about setting it up](https://blog.vinfall.com/posts/2022/10/github-actions-101-continued/)

For RetroArch team, if you are interested in setting up a nightly repo (hopefully it can be integrated into your CI!), I'm willing to help🤟🏼

**Comment by licaon-kter** [comment] 2022-10-25 20:50
Any news here? I mean... if the tested APK is okay we can merge already, fyi ;)

**Comment by Vinfall** [comment] 2022-10-26 02:40
I think the test apk is fine, see https://github.com/libretro/RetroArch/issues/11922#issuecomment-1274470419.

There are only two minor issues dangling:
- **Changelog** (located in https://github.com/libretro/RetroArch/blob/master/CHANGES.md but it's huge, my suggestion: https://github.com/libretro/RetroArch/issues/11922#issuecomment-1274317270)
- **Bundle assets or not** (located in https://buildbot.libretro.com/assets/frontend/assets.zip but it's huge as well (100M+), [relevant snap recipe](https://github.com/libretro/retroarch-snap/blob/master/snapcraft.yaml#L219). I don't have a preference as I'll update assets after installation anyway)

Personally I want to see RetroArch on F-Droid sooner, but it's still up to the developers.

**Comment by hizzlekizzle** [comment] 2022-10-26 16:33
for the assets, if it works okay with just the 'glui' assets (i.e., the ones for the default android menu), we can save a lot of space by just shipping with it. That leaves Android TV / Shield users without assets, but whatever.

For the changelog, can the recipe just do something like 'head 25 CHANGES.md > $release_hash.txt' or whatever?

**Comment by Vinfall** [comment] 2022-10-27 02:04
> For the changelog, can the recipe just do something like 'head 25 CHANGES.md > $release_hash.txt' or whatever?

I get this command to output the latest changelog:
```bash
cat CHANGES.md | sed --silent "/\# ${new_version}/,/\# /p" | head --lines -2
```

- `\# ${new_version}` matches the latest version, which can be replaced by something like `versionName` in the recipe?)
- `\# ` matches the last version heading (Markdown H1)
- `head` removes the last two lines (last version heading, as I don't know how to do non-greedy match in sed...)

@hizzlekizzle But it also output changelog on other platforms, is that acceptable?

There are too many tags to exclude and I have no idea where to start. Simply grep `ANDROID` would exclude other improvements like `PLAYLISTS`, `INPUT`, `LOCALIZATION` etc.

**Comment by hizzlekizzle** [comment] 2022-10-27 02:16
I think it's fine to include everything, yeah.

**Comment by Vinfall** [comment] 2022-10-27 02:22
> For the assets, if it works okay with just the 'glui' assets (i.e., the ones for the default android menu), we can save a lot of space by just shipping with it. That leaves Android TV / Shield users without assets, but whatever.

From RetroArch settings it seems that assets are located in private app directory (`/data/user`). So I can't help much about this without rebuilding the app with glui assets myself.

@licaon-kter Is it possible to run another build with changelog and glui assets bundled (it's right inside assets.zip, just unarchive it and there is a `glui` folder)? As there is already [a new release](https://github.com/libretro/RetroArch/releases/tag/v1.12.0), I guess the recipe needs to change anyway.

**Comment by denilsonsa** [comment] 2022-10-27 05:49
> ```shell
> cat CHANGES.md | sed --silent "/\# ${new_version}/,/\# /p" | head --lines -2
> ```
>  […]
>     * `head` removes the last two lines (last version heading, as I don't know how to do non-greedy match in sed...)

You can try something like this (untested):

```shell
sed --silent "
  /\# ${new_version}/,/\# / {
    /\# ${new_version}/p;  # ← optional
    /\# /d;
    p
  }" CHANGES.md
```

The optional line will include the "new version" header in the output. Then, the following line will delete any header in that range, then it will print any remaining lines. You can also eliminate the newlines and keep everything in one line if needed (but then it's less readable).

**Comment by Vinfall** [comment] 2022-10-28 07:34
> > For the assets, if it works okay with just the 'glui' assets (i.e., the ones for the default android menu), we can save a lot of space by just shipping with it. That leaves Android TV / Shield users without assets, but whatever.
> 
> From RetroArch settings it seems that assets are located in private app directory (`/data/user`). So I can't help much about this without rebuilding the app with glui assets myself.

I managed to get it working by changing the Assets directory in the setting to external storage like `/storage/emulated/0/fdroidtest/assets` and placed extracted `glui` assets in the folder. All icons seem to work this time. So I assume bundling glui assets would be enough for F-Droid packaging (it's just 1.19MB zipped!).

**Comment by licaon-kter** [comment] 2022-10-31 08:54
Regarding the changelog, this just got merged so maybe it's easier to setup? https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1240

**Comment by licaon-kter** [comment] 2022-10-31 08:55
@Vinfall which commit I should build for `glui` ?

**Comment by Vinfall** [comment] 2022-11-01 01:29
Not sure since I'm not a contributor and know little about Android packaging💔. Also I don't know how does `recipe fetch them from a URL at bundle-time` would work as was mentioned in https://github.com/libretro/RetroArch/issues/11922#issuecomment-1275068095. You'd better ask hizzlekizzle or LibretroAdmin instead.

AFAIK from release tag https://github.com/libretro/RetroArch/tree/v1.12.0, it should be https://github.com/libretro/RetroArch/commit/840c4481ab7cb0720025c30ea609d16e60927a02.

**Comment by hizzlekizzle** [comment] 2022-11-01 03:49
Yes, that's the commit. For the assets, if you can just fetch the whole bundle with the recipe and then `rm -f !(assets/glui)` or whatever to nuke everything but the GLUI icons, we should be good.

**Comment by licaon-kter** [comment] 2022-11-01 04:53
Re: default.txt, not really, it expects them to be there on the publish phase, so somehow maybe your release workflow can create it before tagging.

**Comment by hizzlekizzle** [comment] 2022-11-01 14:42
oh ok. gotcha. Yeah, I would think that's probably doable. @LibretroAdmin what do you think? Can you run a script to dump (or just manually copy/paste) the applicable changelog lines into a file named "default.txt" for the fdroid changelog? That will avoid needing to know the release hash/ID.

**Comment by Vinfall** [comment] 2022-11-15 02:32
> Can you run a script to dump (or just manually copy/paste) the applicable changelog lines into a file named "default.txt" for the fdroid changelog? That will avoid needing to know the release hash/ID.

What needs to change for this? I can raise a PR if the team is busy. That is, if I know where to start.

I can achieve this via https://github.com/libretro/RetroArch/issues/11922#issuecomment-1292866779, but that's Linux-specific and I don't know how the building process work (along with the right location for the script, or `default.txt`).

**Comment by hizzlekizzle** [comment] 2022-11-15 14:33
It could probably be added to the regular Android build process, if you have any familiarity with that.

**Comment by Vinfall** [comment] 2022-11-16 03:49
Not so much, sadly. How about GitHub Action? I notice that there are quite a few CI in your workflows, can I add one more to **automatically dump the changelog when `CHANGES.md` is changed or there is a new tagged release**? This can be easily done for me and doesn't require manual check once set up, so everyone should be happy!

**Comment by Vinfall** [comment] 2022-12-13 00:39
> There are only two minor issues dangling:
> 
>     * **Changelog** (located in https://github.com/libretro/RetroArch/blob/master/CHANGES.md but it's huge, my suggestion: [[Android] [F-Droid] Current Status of LibRetro F-Doird Repository #11922 (comment)](https://github.com/libretro/RetroArch/issues/11922#issuecomment-1274317270))
> 
>     * **Bundle assets or not** (located in https://buildbot.libretro.com/assets/frontend/assets.zip but it's huge as well (100M+), [relevant snap recipe](https://github.com/libretro/retroarch-snap/blob/master/snapcraft.yaml#L219). I don't have a preference as I'll update assets after installation anyway)
> 
> 
> Personally I want to see RetroArch on F-Droid sooner, but it's still up to the developers.

Hi, now that [v1.14.0](https://github.com/libretro/RetroArch/releases/tag/v1.14.0) is out with `default.txt` in place, we can proceed. Building the APK with glui bundled should be enough, see quoted comment for the right place and remember to minimize the size by sth. like `rm -f !(assets/glui)` in the recipe.

**Comment by licaon-kter** [comment] 2022-12-13 06:06
Will update recipe asap

**Comment by Vinfall** [comment] 2022-12-15 02:54
I tested the APK and it seems that the glui assets are missing. Is it fetched upon building? If not, you can try to add the assets into the recipe like the `prebuild` lines (not sure how the recipe works):

```yml
Builds:
  - versionName: 1.14.0
    versionCode: 1597175255
    commit: ad89b0c655fc1d25adfcdf40268e95c5d0391111
    ...
    prebuild:
      # ↓ These two lines
      - curl -S https://buildbot.libretro.com/assets/frontend/assets.zip --output assets.zip
      - unzip assets.zip 'glui/*' -d 'assets' && rm assets.zip
      # ↑ These two lines
      - sed -i -e '/versionCode System/d' -e '/versionName "${/d' build.gradle
    ndk: r22
```

This would fetch the assets and place it under `./assets/glui`, is this the right place? @hizzlekizzle

**Comment by hizzlekizzle** [comment] 2022-12-15 03:17
I'm not super-familiar with the Android build process, but if anything in the working directory (./) gets bundled, yeah, assets/glui is the proper structure.

**Comment by licaon-kter** [comment] 2022-12-15 04:35
I'll have a look at the license/contents of the assets next ond bundle them if ok.

**Comment by licaon-kter** [comment] 2022-12-15 09:07
> https://buildbot.libretro.com/assets/frontend/assets.zip

Umm, unversioned file is odd... so basically if I build today I get a set of assets, if I build tomorrow I might get another?

**Comment by licaon-kter** [comment] 2022-12-15 10:12
@Vinfall 
>  `- unzip assets.zip 'glui/*' -d 'assets' && rm assets.zip`

So we download 110Mb, extract ONLY 2Mb (glui) and delete the rest? why?

**Comment by Vinfall** [comment] 2022-12-15 11:21
> Umm, unversioned file is odd... so basically if I build today I get a set of assets, if I build tomorrow I might get another?

Because assets are somewhat like rolling-release I guess? They should come from https://github.com/libretro/retroarch-assets and RetroArch clients on other platforms simply dump the archive as well (see [this snap recipe](https://github.com/libretro/retroarch-snap/blob/a56c1f641da2a016c62ceaac8fb8a8d64a439592/snapcraft.yaml#L230-L249)). You can change the url to `https://github.com/libretro/retroarch-assets/archive/master.tar.gz` but that doesn't have regular tagged versions either.

> So we download 110Mb, extract ONLY 2Mb (glui) and delete the rest? why?

I think it comes down to two points:
- Glui is required for basic icon rendering, which means it's essential to make the app behave normally. The downloading step is required due to the fact that the assets do not come with https://github.com/libretro/RetroArch but locates at https://github.com/libretro/retroarch-assets.
- The whole assets are large and bundling them all does not offer much benefit. Most importantly, users can update the assets inside the app themselves. Deleting the rest makes sure the app size is reasonable and saving F-Droid bandwidth.

Actually it's brought up in https://github.com/libretro/RetroArch/issues/11922#issuecomment-1275261274, if F-Droid is satisfied with a huge apk and can handle the traffic, I think not deleting the other assets is fine.

**Comment by Vinfall** [comment] 2022-12-15 11:28
> I'll have a look at the license/contents of the assets next ond bundle them if ok.

From https://github.com/libretro/retroarch-assets/blob/master/COPYING, it should be CC-BY-4.0 license.

**Comment by licaon-kter** [comment] 2022-12-15 11:33
>  https://github.com/libretro/retroarch-assets/archive/master.tar.gz but that doesn't have regular tagged versions either.

But maybe we/you can specify the exact commit that the project is using exactly?  eg https://buildbot.libretro.com/stable/1.14.0/android/RetroArch_aarch64.apk is using what?

> Glui is required for basic icon rendering, which means it's essential to make the app behave normally. 

There we no reports that my test APKs are broken, so not sure how this works. 

> The whole assets are large and bundling them all does not offer much benefit. 

The project site APKs are >180Mb: https://retroarch.com/?page=platforms so why not slim those down too then? 

Speaking of those, F-Droid likes to have APKs reproducible if possible so having the APK contents match your own is a goal.

**Comment by licaon-kter** [comment] 2022-12-15 11:34
> From https://github.com/libretro/retroarch-assets/blob/master/COPYING, it should be CC-BY-4.0 license.

Yup, saw it later.

> if I build tomorrow I might get another?

wow, one hour difference and it changed :(
I wanted to put the hash sum of the file so we can check it before built, that's not feasible now

**Comment by licaon-kter** [comment] 2022-12-15 11:38
@Vinfall
> unzip assets.zip 'glui/*' -d 'assets' 

I forgot to ask, where (relative to the repo root) does the `assets` folder needs to be? `media/assets/` ? `media/` ?

**Comment by Vinfall** [comment] 2022-12-15 12:44
> But maybe we/you can specify the exact commit that the project is using exactly? eg https://buildbot.libretro.com/stable/1.14.0/android/RetroArch_aarch64.apk is using what?
> Speaking of those, F-Droid likes to have APKs reproducible if possible so having the APK contents match your own is a goal.
>  I wanted to put the hash sum of the file so we can check it before built, that's not feasible now

I agree with the reproducibility issue. I checked https://github.com/libretro/libretro-super but could not find the recipe. @LibretroAdmin can you tell how the assets at https://buildbot.libretro.com/assets/frontend/assets.zip are updated? If the asset update is triggered by commits, it should be easy. If not, the process should generate a hash to make APKs reproducible.

***

> I forgot to ask, where (relative to the repo root) does the `assets` folder needs to be? `media/assets/` ? `media/` ?
> There were no reports that my test APKs are broken, so not sure how this works.

Honestly speaking idk about these questions, hopefully some RetroArch dev working on Android part can answer this. But I think the command itself should extract it to the right place, i.e. `<repo-root>/assets`.

**Comment by licaon-kter** [comment] 2022-12-15 14:51
Been reading https://docs.libretro.com/development/retroarch/compilation/android/#prep-work but appears not to be up to date.

eg. https://github.com/libretro/RetroArch/blob/master/fetch-submodules.sh is not mentioned and that clones assets too

**Comment by denilsonsa** [comment] 2022-12-20 07:04
> (though I am still unsure the difference between 64 and non-bit-named versions)

I'm also confused about the different versions. The [official download page](https://www.retroarch.com/?page=platforms) lists three direct download links for Android `.apk` files. One is clearly 32-bit (`_ra32`), another is clearly 64-bit (`_aarch64`), and another has no suffix (is it a combined 32+64 version?). There is no explanation to their differences in the download page. I know [the Play Store versions were split into two](https://www.libretro.com/index.php/retroarch-android-new-versions-for-play-store-please-read/), but people wouldn't know it from the download page. I can also understand the bigger version has more built-in cores, but I found the core list nowhere.

This comment is a bit off-topic, we could create a new issue about properly explaining/documenting the different versions.

**Comment by Vinfall** [comment] 2023-02-19 05:24
> wow, one hour difference and it changed :( I wanted to put the hash sum of the file so we can check it before built, that's not feasible now

I looked at how GNU/Linux distros packages assets, but it did not help much :(

- [retroarch-assets](https://tracker.debian.org/pkg/retroarch-assets) in Debian Package Tracker shows the package has [reproducibility](https://tests.reproducible-builds.org/debian/rb-pkg/retroarch-assets.html), but that's because Debian hosts its own fork [here](https://salsa.debian.org/games-team/libretro/retroarch-assets).
- RetroArch template in [void-packages](https://github.com/void-linux/void-packages/blob/master/srcpkgs/retroarch/template) has checksum of the main app (not assets), but that's because `xgensum` from `xtools` generates it beforehand.

I still have no idea how to make assets reproducible.

@LibretroAdmin can you answer my question at https://github.com/libretro/RetroArch/issues/11922#issuecomment-1353007066, i.e. how the assets at https://buildbot.libretro.com/assets/frontend/assets.zip are updated?

Is the assets update triggered by commits? If not, where can I find the build recipe?

**Comment by gknutson1** [comment] 2023-03-12 01:30
@denilsonsa @WingofaGriffin 
Download (64 bit) (`RetroArch_aarch64.apk`) is 64-bit. 
Download (32 bit) (`RetroArch_ra32.apk`) is 32 bit.
Download (`RetroArch.apk`) is both.

I agree that it's a bit confiusing, and should be documented better - maybe rename the one marked just as "Download" to "Download (32/64bit)", or "Download (Both)"?

FYI, APK files are actually just zip files, and all supported architectures are listed as folders in the /lib directory of the APK.

Here is a nice little `bash` function that uses `unzip` to check:

```
#!/bin/bash

# This script checks what arcitecture an apk is by examining the contents of the /lib directory of the apk using unzip

[[ ! $(command -v unzip) ]] && echo "unzip is not installed" 1>&2 && exit 1

for file in "$@"; do
    [[ ! -f "$file" ]] && echo "\"$file\" is not a file" 1>&2 && continue
    # Use unzip to list all the files in the /lib folder of the zip file
    libfiles=$(unzip -l "$file" 'lib/*' 2> /dev/null)
    [[ $? != 0 ]] && echo "unzip could not process \"$file\", file does not contain a /lib directory, or no folders exist in /lib" 1>&2 && continue
    # extract the names of the folders in /lib, which are the supported architectures of the apk
    archlist=$(echo "$libfiles" | grep -oP 'lib/\K[^/]+(?=/)')
    echo -e "$file:\n$archlist\n"
done
```

Here is the result on running this script on the three RetroArch APKs:

```
❯ ./check_apk_arch.sh RetroArch*
RetroArch.apk:
arm64-v8a
x86_64
x86
armeabi-v7a

RetroArch_aarch64.apk:
arm64-v8a
x86_64

RetroArch_ra32.apk:
x86
armeabi-v7a
```

**Comment by Slavko-P** [comment] 2023-04-15 19:42
What's the current status on this issue? On a Galaxy S8+, a release from two years ago is still the latest version.

**Comment by Vinfall** [comment] 2023-04-16 01:20
We are stuck at the reproducibility issue of RetroArch assets which update too fast and therefore cannot generate a checksum to satisfy F-Droid requirement. Without it users need to manually download assets using built-in updater to make the app behave normally. If the dev decides that is acceptable (and maybe F-Droid gives an exemption I guess), the app can get on F-Droid right away.

**Comment by hizzlekizzle** [comment] 2023-04-16 04:08
I think we're fine with pretty much whatever needs to happen.

We identified a reduced number of assets that would provide a basic usability with the default mobile menu, right? Can we just put that static archive somewhere? Will that satisfy the checksum issue?

**Comment by licaon-kter** [comment] 2023-04-16 06:54
It would be acceptable without repro too, but... I did not see any conclusion being drawn here and upstream being okay with the workflow. 

Repro is nicer indeed.

**Comment by Vinfall** [comment] 2023-04-16 09:18
> We identified a reduced number of assets that would provide a basic usability with the default mobile menu, right? Can we just put that static archive somewhere? Will that satisfy the checksum issue?

All the answers are yes. You can put it at somewhere like https://buildbot.libretro.com/assets/frontend/assets-minimal.zip and leave it alone. As long as it's not changed quite frequently, everything should be fine.

**Comment by hizzlekizzle** [comment] 2023-04-17 14:38
Ok, great. Here's a link: http://buildbot.libretro.com/assets/frontend/glui_minimal_assets.zip

I checked to make sure it worked well enough with GLUI to get someone started, and they can always fetch the rest if they need it. That archive includes an 'assets' directory that can drop directly into the RetroArch bundle.

**Comment by Vinfall** [comment] 2023-04-18 02:16
Nice work, thanks! @licaon-kter Can you update the recipe ([v1.15.0](https://github.com/libretro/RetroArch/releases/tag/v1.15.0) is out since last test build) and add glui assets (check https://github.com/libretro/RetroArch/issues/11922#issuecomment-1352490913 for reference, although the file path is different) to have another test build?

**Comment by Vinfall** [comment] 2023-04-21 02:33
Thank you for the kind words. To clarify, the assets issue is resolved now and we just need some patience. The app should be on F-Droid soon™️. I don't have a GitLab account so if anyone can point https://gitlab.com/fdroid/rfp/-/issues/1933 to [my comment above](https://github.com/libretro/RetroArch/issues/11922#issuecomment-1512339593), that should help.

**Comment by licaon-kter** [comment] 2023-04-22 08:45
Yes, I've built it, has icons, the interface scaling at 100% is huge :))

**Comment by licaon-kter** [comment] 2023-04-22 08:54
Here's the APK to test: https://gitlab.com/fdroid/rfp/-/issues/1933#note_1363070834

Note that this was not tested for repro.

What was the last conclusion on that possibility?

**Comment by Vinfall** [comment] 2023-04-23 01:35
> Note that this was not tested for repro. What was the last conclusion on that possibility?

The minimal assets are static, you can generate a checksum and it will not update as the main asset bundle does. I hope that would suffice.

***

As for the APK, it works fine on my phone (running Android 12) and WSA. Tested features: playlist, cover, cores (Mesen-S, 2048) and wireless controller.

**Comment by Vinfall** [comment] 2023-04-25 02:11
By that standard (app content matches), there is currently no viable solution and thus not reproducible. And the dev is fine with that. (Hopefully another one can contribute to RetroArch build infrastructure and make the app reproducible in the future.)

For the second question, it's a separate issue (misleading download page & three confusing variants). Now that F-Droid builds are not reproducible and pack only small assets, we can go ahead with a universal apk (aka `RetroArch.apk`) and do not build the other two variants (`RetroArch_aarch64.apk` or `RetroArch_ra32.apk`).

Given that the test apk itself works and F-Droid & RetroArch dev agrees on the unreproducible status, I think it's perfectly fine now to have the app on F-Droid.

**Comment by licaon-kter** [comment] 2023-04-25 03:46
Great, will push it through :)

**Comment by licaon-kter** [comment] 2023-04-25 11:46
Merged: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12964

**Comment by hizzlekizzle** [comment] 2023-04-25 12:58
That's very exciting news! Thanks for all the work guys!

And yes, there's no need for the 3 different flavors in this case.

**Comment by linsui** [comment] 2023-04-27 08:16
https://monitor.f-droid.org/builds/log/com.retroarch/1597175256#site-footer The build failed due to a known issue of AGP 4.1.x.

**Comment by Vinfall** [comment] 2023-05-02 02:39
The build seems to get fixed and RetroArch is available on F-Droid now at https://f-droid.org/en/packages/com.retroarch.

**Closed** 2023-05-05 00:56 UTC
Labels: platform: android

**Comment by licaon-kter** [comment] 2023-05-16 09:09
@Vinfall cores downloads worked? It fails for me today :( ref: https://forum.f-droid.org/t/retroarch-and-cores/22320

**Comment by Vinfall** [comment] 2023-05-17 02:21
Yes, it's working for me. I tried the apk on F-Droid (https://f-droid.org/repo/com.retroarch_1597175256.apk) and it worked as well. Maybe you need to "Update Core Info Files" first before trying to download cores.🤔 I tend to update everything before using.

My steps FYI:
1. Download and install from F-Droid
2. Grant storage permission
3. Online Updater -> Update Core Info Files
4. (When it finishes unpacking) Core Downloader -> 2048
5. Go back to main menu and start by loading core 2048
6. It works

**Comment by licaon-kter** [comment] 2023-05-17 03:54
Ah, indeed 👍, I guess the hosted version (from retroarch itself) already has that inside since the APK is 9 times bigger.

**Comment by selurvedu** [comment] 2023-06-14 18:40
Great job, everyone! I think it is now safe to replace the F-Droid link on the [RetroArch Downloads page](https://retroarch.com/?page=platforms). Adding a discontinuation note on the [old repo front page](https://fdroid.libretro.com/website/) along with a link to the new place at f-droid.org may be a good idea as well.

I looked for a repo for website-specific issues, but couldn't find one, so commenting here instead.
