### ISSUE TITLE
Netplay status

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3729] opened 2016-10-04 04:33 UTC
@GregorR there are some bad regressions from your initial changes to netplay.
All of these were tested under these conditions:
- Wired ethernet
- Server, Windows 10 x64, latest trunk
- Client. NVidia Shield Portable running lollipop, latest trunk

Nestopia
- works, syncs beautifully and everything seems fine after 10 minutes
  regression: going to the menu on either side and back causes and instant desync. Testing your improvements two weeks ago it was perfect, it would resync when going back from the menu. Never re-syncs

FCeumm
- works, syncs beautifully and everything seems fine after 10 minutes
  regression: going to the menu on either side and back causes and instant desync. Testing your improvements two weeks ago it was perfect, it would resync when going back from the menu. Never re-syncs

Snes9x
- desyncs often, at times input is still being transmitted back and forth but the client doesn't register input (even it's own input) anymore.

Picodrive
- see nestopia/fceumm

Genesis Plus GX
- crashes on android when netplay connects (ie, if I start client with no server available it doesn't crash)

Other caveats:
- messages are printed for too long, and with some recent change it seems the OSD now is really a queue so stuff prints out of order.
- I see saved slot #0 at random, when connecting, this is worrying, netplay shouldn't flush saves to disk.

**Comment by twinaphex** [comment] 2016-10-04 05:12
@GregorR Let's make this the main priority for now. Radius is getting very concerned about these netplay regressions so let's make sure we get these first out of the way before doing anything else again on netplay.

**Comment by GregorR** [comment] 2016-10-04 11:36
I'm having major troubles reproing any problems. Can you post your configuration files (ideally for both devices)? I can only assume that there's something conflicting with netplay.

**Comment by GregorR** [comment] 2016-10-04 12:50
(The other reason I'm so confused is that the difference between the last time it was reported working well and now has all been superficial. The netplay menu was most of the changes, and the only changes to the netplay impl were renaming some variables and moving stuff out of global...)

**Comment by twinaphex** [comment] 2016-10-04 13:09
@GregorR Can you conduct some netplay tests together with @fr500 when he gets back later today?

**Comment by GregorR** [comment] 2016-10-04 13:10
I certainly can try!

**Comment by twinaphex** [comment] 2016-10-04 13:11
Cool. Hope we can get to the bottom of this.

**Comment by fr500** [comment] 2016-10-04 15:01
PC config
http://hastebin.com/ejofomawaf.ini

**Comment by fr500** [comment] 2016-10-04 15:04
Android config
http://hastebin.com/oxoyuyupiv.ini

**Comment by fr500** [comment] 2016-10-04 15:06
Desync when the menu toggles is quite easy to reproduce, just set libretro_pause to off on either side.
Only one side will pause.

With your older implementation it would resync immediately once the menu was closed. Now it never does, game keeps on chugging de-synced forever

**Comment by GregorR** [comment] 2016-10-04 15:28
libretro_pause? There exists a setting to make the menu not pause? Yeah, that's gonna cause a weird mess, because it communicates the menu as a pause situation... I'm shocked that it ever re-synced in the previous version (did you have check_frames on in that case?)

**Comment by GregorR** [comment] 2016-10-04 15:33
Yup, desync confirmed with menu_pause_libretro. That bug definitely existed two weeks ago, so I assume you had check_frames. The way I implemented remote pausing involves polling for pause situations because there's no central "this is paused" message, and if both sides disagree on who's paused, that's a definite mess. I can at least fix it so disagreeing on who's paused doesn't break everything, but I'll need to fix my pause detection.

**Comment by GregorR** [comment] 2016-10-04 15:34
(If I had to guess, I'd say netplay_pre_frame and netplay_post_frame aren't even running if menu_pause_libretro is on, which is causing them to disagree about which frame is which)

**Comment by GregorR** [comment] 2016-10-04 15:39
Feck, yup, menu_display_libretro runs core_run without any netplay preframe/postframe stuff. Ugly ugly. Right now, menu_pause_libretro is incompatible with netplay, but I'll put it on my to-fix list. I think I'm gonna have to stuff netplay things into core_run to make sure that all paths into core_run inform netplay. Then it's just a trick of making sure netplay doesn't go recursive :)

**Comment by GregorR** [comment] 2016-10-04 15:40
Presuming that all of your testing is done with menu_pause_libretro off, can you turn that on and see what happens?

**Comment by GregorR** [comment] 2016-10-05 12:18
I believe that #3740 fixes the remaining bugs. Most were due to nondeterministic cores, a few were due to code paths that ran the core without informing netplay.

**Comment by fr500** [comment] 2016-11-06 17:03
It's working mostly well now, but with Super Mario Kart in Snes9x 2010 or Snes9x (Server: PC, Client: Android) it locks up as soon as server presses a button... on android it results on an ANR.

The same cores with some other games work fine though...
I find it weird since it was the same game I tested when you first improved netplay (and worked beautifuly)

**Comment by fr500** [comment] 2017-01-14 23:30
New feedback:
**Commit:  35df333**
**Core: Nestopia, Commit: 646ee62**

Super Mario Bros. 3 (Rev A)
Test 1: 2 shield portables over wifi, check frames 30
- Initial connection: ok
- Seemed to retain sync after 10 mins, left it idle, came back  played for a while, left again, repeated
- Load state: instant disconnect

```
RetroArch [ERROR] :: CMD_LOAD_SAVESTATE received an unexpected save state size.
RetroArch [INFO] :: Netplay disconnected
```

Test 2: shied portable over wifi, PC wired, check frames 30
- Initial connection: ok
- Seemed to retain sync after 10 mins, left it idle, came back  played for a while, left again, repeated
- Load state: instant disconnect, same issue

```
RetroArch [ERROR] :: CMD_LOAD_SAVESTATE received an unexpected save state size.
RetroArch [INFO] :: Netplay disconnected
```

**Comment by fr500** [comment] 2017-01-14 23:33
Commit: 35df333
Core: Snes9x2010, Commit: 66ba123

Super Mario Kart (USA)
Test 1: 2 shield portables over wifi, check frames 30

- Initial connection: instant disconnect, client locks up

Test 2: shied portable over wifi, PC wired, check frames 30

-  Initial connection: client segfaults

Test 3: 2 instances on the same Windows box

-  Initial connection: client segfaults

**Comment by fr500** [comment] 2017-01-14 23:39
Commit: 35df333
Core: Snes9x, Commit: 2cc408c

Super Mario Kart (USA)

Test 1: 2 instances on the same Windows box

-  Initial connection: ok
- Seemed to retain sync after 10 mins, left it idle, came back played for a while, left again, repeated
- Load state: works fine

**Comment by fr500** [comment] 2017-01-14 23:44
So far the only thing that worked reliably was Snes9x git on windows

**Comment by fr500** [comment] 2017-01-14 23:50
Decided to give Snes9x2010 another shot maybe it was a game issue:

Commit: 35df333
Core: Snes9x2010, Commit: 66ba123

Super Bomberman 5 (Japan)
Test 1: 2 shield portables over wifi, check frames 30

- Initial connection: instant disconnect, client locks up

Test 2: shied portable over wifi, PC wired, check frames 30

-  Initial connection: client segfaults

Test 3: 2 instances on the same Windows box

-  Initial connection: client segfaults

**Comment by fr500** [comment] 2017-01-15 00:05
New feedback:
**Commit:  35df333**
**Core: FCEumm, Commit: doesn't show**

Super Mario Bros. 3 (Rev A)
Test 1: 2 shield portables over wifi, check frames 30
- Initial connection: ok
- Seemed to retain sync after 10 mins, left it idle, came back  played for a while, left again, repeated
- Load state: ok

Test 2: shied portable over wifi, PC wired, check frames 30
- Initial connection: can't connect because the hash doesn't show on the android core

Test 3: 2 instances on the same Windows box

- Initial connection: ok
- Seemed to retain sync after 10 mins, left it idle, came back  played for a while, left again, repeated
- Load state: ok

**Comment by fr500** [comment] 2017-01-15 18:40
**Commit:  35df333**
**Core: Picodrive, Commit: d6be4fa**
**Status: good on PC**

**Streets of Rage (USA)**
Test 1: 2 shield portables over wifi, check frames 30
- Initial connection: instant disconnect, client locks up

Test 2: shied portable over wifi, PC wired, check frames 30
- Initial connection: instant disconnect, client locks up

Test 3: 2 PCs (localhost)
- Initial connection: ok
- Seemed to retain sync after 10 mins, left it idle, came back  played for a while, left again, repeated
- Load state: ok

**Comment by fr500** [comment] 2017-01-21 17:54
One little thing, when netplay fails due to different implementation, only the client gets the error, the host only gets $NICKNAME (disconnected)

**Comment by GregorR** [comment] 2017-01-21 18:52
So apparently if you dare to mention the issue whatsoever, the PR closes it. Thanks, GitHub @_@

**Comment by Alcaro** [comment] 2017-01-21 18:54
You said "fixes http:\/\/github.com/libretro/RetroArch/issues/3729#issuecomment-274276989", which contains "fixes http:\/\/github.com/libretro/RetroArch/issues/3729" which triggered it.

But yes, this specific one sounds like a github bug.

**Comment by LibretroAdmin** [comment] 2022-09-03 02:21
@Cthulhu-throwaway How much of this still remains relevant to the present day, or have all issues here been resolved by now?

**Comment by LibretroAdmin** [comment] 2022-09-03 02:22
Going to close this one I guess as it's too long ago and it's unfair to ask of Cthulhu to dissect all this.

**Closed by LibretroAdmin** 2022-09-03 02:22 UTC
Labels: discussion, netplay
