### ISSUE TITLE
Shaders not loading on Nightly (MacOS)

### ISSUE THREAD

**Issue by kula72** [libretro/RetroArch#14190] opened 2022-07-20 08:21 UTC
## Description

Shaders do not load automatically after being saved as either a core or global present on MacOS.

### Expected behavior

After launching content with a core and selecting a shader, using the shaders menu to save the shader as a core or global present, the shader would be automatically applied the next time content was loaded.

### Actual behavior

Shaders are not being saved requiring the user to reapply manually each time content is loaded. 
Global present initially gave following error:

[WARN] [Shaders]: Root preset is not a valid shader chain because it has no shaders entry: "/Users/gareth/Library/ApplicationSupport/RetroArch/shaders/retroarch.slangp".

The contents of that file is:

#reference "shaders_slang/interpolation/bandlimit-pixel.slangp"

Removing the file and attempting to save either a core or global present removed that error from logs, but now no reference to shaders can be seen in the logs and they are not saved. Having installed stable build the issue went away with no further changes and shaders are now correctly saved.

### Steps to reproduce the bug

Launch content with a core, enable shaders, choose a shader, save the shader as either a core or global present, close the content, reopen content and observe no shader loaded.

I tested issue using Beetle-saturn and Yabause cores and a number of different shaders. 

### Bisect Results

When I upgraded to 10.1.3 nightly build fron 19th July.

### Version/Commit

10.1.3 with Metal for MacOS.

### Environment information

MacOS 12.4 on an M1 Macbook Air.

**Comment by LibretroAdmin** [comment] 2022-07-20 14:35
Can you do a bisect to see when this started happening?

**Comment by hizzlekizzle** [comment] 2022-07-20 15:05
If you're unable to compile it yourself, we have some builds here that you can test: http://buildbot.libretro.com/nightly/apple/osx/universal/

**Comment by LibretroAdmin** [comment] 2022-07-21 01:42
I've got an initial fix for this that seems to work -

> diff --git a/menu/menu_driver.c b/menu/menu_driver.c
index 09e93e1e37..0166595342 100644
--- a/menu/menu_driver.c
+++ b/menu/menu_driver.c
@@ -3793,6 +3793,10 @@ bool menu_shader_manager_save_preset_internal(
             strlcat(fullname, preset_ext, sizeof(fullname));
          }
       }
+      else
+         strlcat(fullname,
+               video_shader_get_preset_extension(type),
+               sizeof(fullname));
    }
    else
       snprintf(fullname, sizeof(fullname), "retroarch%s",

**Comment by kula72** [comment] 2022-07-21 10:58
Sorry on the bisect - I hadn't used this mac for retroarch in a while, so I'd guess previous install would be 6 months old at least before hitting 10.1.3.

I just downloaded build from today (21.7.22) and that breaks the shaders again. When first ran it did keep the shader set previously on stable but I couldn't change it (well I could but it would revert next load). So it's not saving again.

Reverting to stable and it's working again.

**Comment by hizzlekizzle** [comment] 2022-07-21 13:45
I don't think the patch from LibretroAdmin's post has been added to RetroArch yet, so the nightlies wouldn't have it.

**Comment by LibretroAdmin** [comment] 2022-07-22 00:22
This fixed the issue for me and @HyperspaceMadness . Test if it works on your end too.

https://github.com/libretro/RetroArch/commit/6cfcd749e414d2a1ebf9fc7e60b9f4a0e0976a6f

**Comment by kula72** [comment] 2022-07-22 09:13
I just pulled from Git and compiled and that now works as expected.

**Comment by gouchi** [comment] 2022-07-22 15:29
@kula72 as the issue is fixed please close this issue ;)

Thank you.

**Closed** 2022-07-22 15:29 UTC
