### ISSUE TITLE
[Vulkan] Crash on "Screenshot" and "Title" thumbnail modes in playlists

### ISSUE THREAD

**Issue by Rossco1337** [libretro/RetroArch#3244] opened 2016-07-19 05:41 UTC
Reproducible crash on selecting items in a playlist with either "Screenshot" or "Title Screen" thumbnail mode - "Boxart" mode produces no crashes.

Seems to be related to either BIOS files or games tagged (Unl) as creating a playlist without these files in the scanned folder produces no crashes.

Demonstration: [https://www.youtube.com/watch?v=95OlnwHjCzg](https://www.youtube.com/watch?v=95OlnwHjCzg). The file that crashes RetroArch in this video is "[BIOS] Nintendo Famicom Disk System (Japan) (Early).zip" containing "[BIOS] Nintendo Famicom Disk System (Japan) (Early).bin".

[Crash log (not sure if anything relevant is in here)](https://github.com/libretro/RetroArch/files/370690/log.txt)

Happy to provide any other info, this is a really awesome feature that I'd love to use!

**Comment by RobLoach** [comment] 2016-07-19 08:00
Doesn't happen here. Looks like the BIOS doesn't have an image associated with it:
https://github.com/libretro/libretro-thumbnails/tree/master/Nintendo%20-%20Famicom%20Disk%20System/Named_Snaps

**Comment by twinaphex** [comment] 2016-07-21 03:47
I can reproduce it here with the Vulkand driver, not with GL though.

It seems related to another issue we had before that prevented XMB from being able to start up at all with Vulkan (and it seems some drivers are more sensitive and prone to crashing than others when it comes to uninitialized texture data).

**Comment by fr500** [comment] 2016-09-22 05:19
Is this still an issue?

**Comment by Rossco1337** [comment] 2016-09-22 17:15
Unfortunately so. As of the latest nightly, all three modes are working in the GL video driver but only Boxart mode works without crashing in Vulkan as Twinaphex said.

**Comment by twinaphex** [comment] 2016-10-04 06:48
Probably a duplicate of another issue that already exists in here. In any case, I'm assigning @Themaister to this.

**Comment by hizzlekizzle** [comment] 2020-04-30 23:08
This seems to be fixed now, so I'm going to close this.

**Closed by hizzlekizzle** 2020-04-30 23:08 UTC
Labels: bug: major
