### ISSUE TITLE
Loading times are much longer when xinput bluetooth controller is connected (Linux)

### ISSUE THREAD

**Issue by PKGaspi** [libretro/RetroArch#8510] opened 2019-03-21 12:16 UTC
## Description

Openning RetroArch, loading content or toggling between windowed and fullscreen while a xinput controller is connected makes RetroArch loadtimes last much longer. Startup, for example, goes from very fast without the controller (almost instant, less than a second) to 22 seconds. Loading content and toggling fullscreen is more or less the same.

Connecting the device with RetroArch already open makes the menu scroll down (no buttons pressed, maybe this goes for a different issue) until up is pressed. Then, if content is loaded or fullscreen is toggled the load time is still very long.

Tested with an 8Bitdo SF30 Pro (xinput mode via bluetooth) on Archlinux. Connecting the controller via usb makes RetroArch recognize it as a generic Xbox 360 controller, while it's recognized as a 8Bitdo SF30 Pro when connected by bluetooth. No issues so far when connected via usb.

### Expected behavior

To load at about the same speed wether a device is connected or not.

### Actual behavior

Black screen stays for a long time on explained scenarios.

### Steps to reproduce the bug

1. Connect the xinput device via bluetooth.
2. Open RetroArch. See that is takes way longer to show the main menu.
3. Try loading content and toggling fullscreen to see the issue.

### Bisect Results

This issue happened to me on all 3 different Arch machines that I own. It exists since I use RetroArch (about 1.7.2).

### Version/Commit

- RetroArch: 1.7.6/9750719074

### Environment information

- OS: Archlinux.
- Controller: 8Bitdo SF30 Pro (xinput mode via bluetooth).
- Compiler: obtained from pacman official repositories.

**Comment by fmorency** [comment] 2019-03-23 03:08
I'm also having this issue. I'm using Lakka and reported issue [594] a while ago.

  [594]: https://github.com/libretro/Lakka-LibreELEC/issues/594

**Comment by tomgar** [comment] 2020-04-27 18:33
I confirm this issue is still going on with latest Retroarch v1.8.5.

If you connect the 8Bitdo SF30 Pro in DInput mode via Bluetooth, you won't experiment any delay with Retroarch. It only happens if the 8Bitdo is configured to use XInput via Bluetooth.

Not sure if there's a specific issue with this specific 8Bitdo controller or not. Another user with another Xinput device via Bluetooth could bring light to this issue.

**Comment by AlexFolland** [comment] 2021-03-20 04:26
I am experiencing this right now with the latest git build using an 8Bitdo SN30 Pro.  Here are some facts.

- I'm running Manjaro 21.0 stable with XFCE and using the `retroarch-git` AUR package.
- The gamepad works, but the only problem is a long delay on a black screen every time I start RetroArch, close content, or start content.
- I've timed the black screen delay multiple times with a stopwatch and it always lasts 25 seconds.
- With the gamepad not connected at all, there's no delay starting RetroArch.  It starts instantly, like in the next frame after I click the launcher in my XFCE panel.
- There is no delay with a PS4 gamepad connected instead.  This is only happening with the 8bitdo SN30 Pro.
- The 8bitdo SN30 Pro is connected using the "Windows" connection mode, which requires pairing it after starting it with Start+Y.
- I am able and willing to gather any requested logs for this.

**Comment by AlexFolland** [comment] 2021-03-23 00:05
It looks like a duplicate report of this issue this was posted in https://github.com/libretro/RetroArch/issues/10408 and that was never merged into this.  I will copy my comment into that report.  This report should be closed since it contains much less information now, since that one became actively updated with workarounds.

**Comment by AlexFolland** [comment] 2023-06-28 20:54
This should definitely be closed now, as the issue is resolved on top of this ticket being a duplicate.

**Closed** 2023-06-28 22:00 UTC
Labels: bug: input
