### ISSUE TITLE
[Wayland] No window border

### ISSUE THREAD

**Issue by Inglebard** [libretro/RetroArch#6278] opened 2018-02-10 18:15 UTC
Hi,
on windowed mode, there is no border. So no possibility to reduce/move/maximize/minimize/close.
The issue appear on archlinux on gnome 3 with wayland. The issue not appear on Xorg. 

### Expected behavior

Have the posibility to reduce/move/maximize/minimize/close on windowed mode.

### Version/Commit
- RetroArch: v1.7.0Compiler: GCC (7.2.1) 64-bitBuilt: Dec 31 2017

### Environment information
- OS: Archlinux

**Comment by hizzlekizzle** [comment] 2018-02-10 18:23
Does this also make it so you click through the window to whatever is behind it?

**Comment by orbea** [comment] 2018-02-10 18:26
Shouldn't window decorations be handled by either gnome3 or wayland?

**Comment by hizzlekizzle** [comment] 2018-02-10 18:43
I have this problem with my self-compiles but the snap package works fine.

**Comment by Inglebard** [comment] 2018-02-10 18:59
@hizzlekizzle 

> Does this also make it so you click through the window to whatever is behind it?
No seems to works properly like a normal window.

**Comment by Sunderland93** [comment] 2018-02-10 21:48
Probably, Retroarch need to support KDE's Server-Decoration protocol, whch already supported by GTK, KDE, Sway and MPV https://github.com/KDE/kwayland/blob/master/src/client/protocols/server-decoration.xml

**Comment by orbea** [comment] 2018-02-11 05:07
Could you help explain what KDE Server-Decorations have to do with gnome3 and wayland?

**Comment by fagoatse** [comment] 2018-02-12 21:46
@orbea read this - https://blog.martin-graesslin.com/blog/2018/01/server-side-decorations-and-wayland/

**Comment by bparker06** [comment] 2018-02-12 22:27
duplicate of #4778

**Comment by orbea** [comment] 2018-12-21 21:05
I am going to close this one in favor of issue https://github.com/libretro/RetroArch/issues/6606 which has more discussion.

**Closed by orbea** 2018-12-21 21:05 UTC
Labels: bug: wayland
