### ISSUE TITLE
Feature Request - Apple App Store support

### ISSUE THREAD

**Issue by code4you2021** [libretro/RetroArch#16451] opened 2024-04-19 13:34 UTC
Apple recently opened the App Store for emulators, it would be great if people can install Provenance directly from it.

Reference: [Apple opens the App Store to retro game emulators](https://www.theverge.com/2024/4/5/24122341/apple-app-store-game-emulators-super-apps)

**Comment by gouchi** [comment] 2024-04-19 15:18
Duplicate of #16415

Please close this issue.

Thank you.

**Closed** 2024-04-20 08:32 UTC
