### ISSUE TITLE
Closing contentless cores or content loaded from the cli it shows 'No items.'

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#5596] opened 2017-10-24 01:33 UTC
## Description

When loading content from the cli or loading a contentless core and then closing it from the quick menu with `Close Content` it will return the user to an empty quick menu with `No items.` listed instead of the playlist entry with `Run`, `Rename` and `Remove`.

### Expected behavior

When closing content it should show the playlist entry with `Run`, `Rename` and `Remove`.

Edit: The playlist menu could be from the recent history or if there is not playlist menu it could default to the root menu with `Load Content` and etc.? 

### Actual behavior

When closing content it shows an empty quick menu with `No items.` listed with contentless cores and when loading cores from the cli.

### Steps to reproduce the bug

1. Load a contentless core or a core and content from the cli with `retroarch -L /path/to/core /path/to/content`.
2. Open the quick menu with `F1` or the `menu` key/button.
3. Select `Close Content` and it will show an empty quick menu with `No items.` listed.

### Bisect Results

This appears to have always happened.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 0731bbb81cfb6d2a5bcc4726d993ed61496bd8b8

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.2.0`

**Comment by orbea** [comment] 2017-10-24 01:34
Related issues.
https://github.com/libretro/RetroArch/issues/5594 https://github.com/libretro/RetroArch/issues/5595

**Comment by orbea** [comment] 2017-10-24 17:00
I suppose what is happening is either.
* Contentless cores don't have a playlist menu to switch to.
* Cores loaded from the cli don't know what their playlist menu is

**Comment by orbea** [comment] 2017-10-24 17:02
I suppose what is happening is either.

*Contentless cores don't have a playlist menu to switch to.
* Content loaded from the cli doesn't know what its playlist menu is.

**Comment by orbea** [comment] 2017-10-24 17:02
I suppose what is happening is either.

* Contentless cores don't have a playlist menu to switch to.
* Content loaded from the cli doesn't know what its playlist menu is.

**Comment by natinusala** [comment] 2017-10-25 11:56
My guess is #2 because the quick menu is just pushed there, without actually detecting which playlist entry corresponds to the content.

**Comment by orbea** [comment] 2017-10-25 14:21
I think its both, just difference scenarios. Contentless cores loaded from the menu have the same issue.

**Comment by orbea** [comment] 2018-12-22 03:33
I've looked closer and found it happens after this line.

https://github.com/libretro/RetroArch/blob/b55ed9e3ce03619cc4b014e16690ea1900f27fac/tasks/task_content.c#L1133

**Comment by orbea** [comment] 2018-12-26 18:55
Two more ways to reproduce this.

1. `Load Core`.
2. `Start Remote RetroPad`.
3. Open quick menu.
4. `Close content`.

or

1. `Load Content`.
2. Navigate to any content (I used a snes rom).
3. Load content (I used snes9x).
4. Toggle quick menu.
5. `Close Content`.

**Comment by orbea** [comment] 2018-12-26 20:20
The relevant code is here.

https://github.com/libretro/RetroArch/blob/3548956509900ca4c6162efeaad356bc445d3ae7/menu/menu_displaylist.c#L2812

This needs to somehow bring the user back to the main menu instead of showing `No items.`.

**Comment by i30817** [comment] 2018-12-26 22:55
This is a bit outside of the suggestion, but i wouldn't mind if closing retroarch and re-opening it opened it on the last open menu, not just this at runtime. This would be cool for the history tab, among others.

**Comment by orbea** [comment] 2018-12-26 23:05
That is certainly outside the scope of this issue, but you can make a feature request and someone may implement a `Remember menu position` feature which does sound potentially useful. I'm not sure that is within my abilities at the moment though...

**Comment by fr500** [comment] 2018-12-27 02:00
So...
we're looking at this with @orbea but we can't solve it, we know what the problem is though, so this diff is a step in the right direction

```diff
diff --git a/menu/menu_displaylist.c b/menu/menu_displaylist.c
index cdf3fda1ce..d286c2ec96 100644
--- a/menu/menu_displaylist.c
+++ b/menu/menu_displaylist.c
@@ -2576,7 +2576,7 @@ static int menu_displaylist_parse_horizontal_list(
    return 0;
 }

-static int menu_displaylist_parse_load_content_settings(
+static bool menu_displaylist_parse_load_content_settings(
       menu_handle_t *menu,
       menu_displaylist_info_t *info)
 {
@@ -2809,12 +2809,8 @@ static int menu_displaylist_parse_load_content_settings(
 #endif
    }
    else
-      menu_entries_append_enum(info->list,
-            msg_hash_to_str(MENU_ENUM_LABEL_VALUE_NO_ITEMS),
-            msg_hash_to_str(MENU_ENUM_LABEL_NO_ITEMS),
-            MENU_ENUM_LABEL_NO_ITEMS,
-            MENU_SETTING_NO_ITEM, 0, 0);
-   return 0;
+      return false;
+   return true;
 }

 static int menu_displaylist_parse_horizontal_content_actions(
@@ -7081,14 +7077,22 @@ bool menu_displaylist_ctl(enum menu_displaylist_ctl_state type, menu_displaylist
          menu_entries_ctl(MENU_ENTRIES_CTL_CLEAR, info->list);
          ret = menu_displaylist_parse_horizontal_content_actions(menu, info);
          info->need_refresh = true;
-         info->need_push    = true;
+         if (ret == 0)
+            info->need_push    = true;
+         else
+            info->need_push    = false;
          break;
       case DISPLAYLIST_CONTENT_SETTINGS:
          menu_entries_ctl(MENU_ENTRIES_CTL_CLEAR, info->list);
          ret = menu_displaylist_parse_load_content_settings(menu, info);
+         if (ret)
+         {
+            info->need_refresh = true;
+            info->need_push    = true;
+         }
+         else
+            menu_displaylist_ctl(DISPLAYLIST_MAIN_MENU, info);

-         info->need_refresh = true;
-         info->need_push    = true;
          break;
       case DISPLAYLIST_INFORMATION_LIST:
          menu_entries_ctl(MENU_ENTRIES_CTL_CLEAR, info->list);

```

**Comment by fr500** [comment] 2018-12-27 02:06
The end result with this is that Load Core -> 2048 -> Close Content returns you to Main Menu properly, but Load Content from file returns you "a Main Menu" but it's not the same as the top level menu:

Real Main:

![image](https://user-images.githubusercontent.com/1721040/50462154-669bd380-0951-11e9-8587-4d195b63332e.png)

Other Main:
![image](https://user-images.githubusercontent.com/1721040/50462272-1cffb880-0952-11e9-9b72-2256a34f14b4.png)

**Comment by orbea** [comment] 2018-12-27 02:16
This works with one problem on xmb, the user still needs to press the back button to get to the root main menu.
```
diff --git a/menu/menu_displaylist.c b/menu/menu_displaylist.c
index cdf3fda1ce..4a1132e03d 100644
--- a/menu/menu_displaylist.c
+++ b/menu/menu_displaylist.c
@@ -2809,11 +2809,8 @@ static int menu_displaylist_parse_load_content_settings(
 #endif
    }
    else
-      menu_entries_append_enum(info->list,
-            msg_hash_to_str(MENU_ENUM_LABEL_VALUE_NO_ITEMS),
-            msg_hash_to_str(MENU_ENUM_LABEL_NO_ITEMS),
-            MENU_ENUM_LABEL_NO_ITEMS,
-            MENU_SETTING_NO_ITEM, 0, 0);
+      menu_displaylist_ctl(DISPLAYLIST_MAIN_MENU, info);
+
    return 0;
 }
 
```

**Comment by orbea** [comment] 2018-12-27 02:40
This is kind of better, now the user loses the tab icons until they press left or right and they are stuck with an ugly back arrow which doesn't go away....I think this is going wrong earlier and needs to be corrected earlier?
```
diff --git a/menu/menu_displaylist.c b/menu/menu_displaylist.c
index cdf3fda1ce..6263ea307a 100644
--- a/menu/menu_displaylist.c
+++ b/menu/menu_displaylist.c
@@ -2809,11 +2809,11 @@ static int menu_displaylist_parse_load_content_settings(
 #endif
    }
    else
-      menu_entries_append_enum(info->list,
-            msg_hash_to_str(MENU_ENUM_LABEL_VALUE_NO_ITEMS),
-            msg_hash_to_str(MENU_ENUM_LABEL_NO_ITEMS),
-            MENU_ENUM_LABEL_NO_ITEMS,
-            MENU_SETTING_NO_ITEM, 0, 0);
+   {
+      action_cancel_pop_default(NULL, NULL, 0, 0);
+      menu_displaylist_ctl(DISPLAYLIST_MAIN_MENU, info);
+   }
+
    return 0;
 }
 
```

**Comment by orbea** [comment] 2019-02-13 18:11
@jdgleaver By any chance would you know how to correctly solve this issue and be willing to work on it when time permits? :)

**Comment by jdgleaver** [comment] 2019-02-14 09:50
I won't make any promises until I've gone through the code to see what's involved, but sure, I'll take a look. :slightly_smiling_face: 

I have some other things I want to do first, though (currently working on an alternative menu text ticker, and then I want to see about alphabetical sorting of playlists, and then there's a memory leak in load_content() that I noticed - there's always something to do!)

**Comment by orbea** [comment] 2019-02-14 15:03
Thanks a lot! No worries if you don't make any progress, but any help with this issue would be greatly appreciated since both @fr500 and I found it hard coming up with a good fix..

**Comment by sonninnos** [comment] 2020-10-20 16:57
Seems like PR #11307 closed this issue too.

**Closed** 2020-10-20 18:28 UTC
Labels: bug: minor, bug: ui
