### ISSUE TITLE
[PS3] Retropad buttons B and A are swapped in the OZONE frontend.

### ISSUE THREAD

**Issue by Zoukambada** [libretro/RetroArch#13212] opened 2021-11-09 14:26 UTC
## Description

Retropad buttons B and A are swapped in the OZONE frontend.

### Expected behavior

If I press Retropad button B it should act as B, and if I press A, it should act as A in the menu.

### Actual behavior

Retroarch swaps buttons B and A so that makes it impossible to press the correct button and release its action according to the button icons (both in the bottom bar and port controls from core content menu). It affects not only the bottom bar legend but also the Port 1 Controls config (probably the same for other ports 2, 3, etc) and also in content menu Port 1 Controls.

### Steps to reproduce the bug

1. Fresh install Retroarch pkg.
2. OZONE theme will load boot, pay attention to the bottom bar buttons (search / back / ok). It reads Back as B (CROSS in PS3), OK as A (CIRCLE in PS3).
3. Navigate through all levels of the menu. You will realize that the buttons from the bottom bar are inverted and doesn't correspond to the icons. If you press B (CROSS) it will act as OK and will enter a menu level, if you press A (CIRCLE) you will go back to the previous menu level.
4. To check if the buttons are ok in a content, I load up Genesis Plus GX core with Mega Drive / Genesis Streets of Rage 1 rom. This game title has 3 action buttons: Genesis_A, Genesis_B, Genesis_C (which corresponds respectively as Call Police Special, Punch and Jump).
5. I check the Port 1 Controls inside Content Menu, to see if it corresponds with the image buttons, it reads Genesis_A is Y, Genesis_B is B, Genesis_C is A. I check if in the game it's really what it was meant to be and it is. But as I told before, the button bar legend icons is still wrong, it's swapped.
![Screenshot 2021-11-09 095105-01](https://user-images.githubusercontent.com/8125662/140939216-e1273468-ed4d-460b-8599-ad2f62cba96e.png)
6. Now if I go to the General Menu in Settings > Input > Port 1 controls, the Genesis layout is still correct. So I go back and check the settings Menu Controls > Menu Swap OK and Cancel Buttons. It's OFF, so I turn it ON to see what happens. The icons below in the bottom bar legend swapped and also the actions of the pressed buttons swapped. So it didn't fix the problem. Anyway, I will leave like this for the momement.
7. Now I go back to General Menu in Settings > Input > Port 1 controls and check if something is different. For the looks, it's alright. It looks like all buttons are the same and the game will work as intended. So I try to play again and test the buttons in game, it works.
![Screenshot 2021-11-09 095105-02](https://user-images.githubusercontent.com/8125662/140939222-1e58d40e-cf65-467e-bf3b-ab613f6f65ad.png)
8. Now, one more time I go to General Menu in Settings > Input > Port 1 controls and I will press all the 4 face buttons of my PS3 corresponding to the icons of the Retropad and check if the button numbers are the same. If they stay the same, the game will still work with the same button layout. After changing the buttons, B changed from 0 (CROSS) btn number to 8 (CIRCLE) and A changed from 8 (CIRCLE) btn to 0 (CROSS). It means that Genesis_B swapped with Genesis_C, so if I press the Punch button, it will Jump and vice-versa. I checked the game and the buttons really swapped. So I can't relly on the icons anymore, because they don't mean what they meant to be. Now, quit Retroarch.
![Screenshot 2021-11-09 095105-03](https://user-images.githubusercontent.com/8125662/140939224-71b69caa-f6d9-4ec9-80cf-8249f3999b1d.png)
9. Renamed the image button icons inside ozone\png\icons and relaunched Retroarch, nothing happened. So I renamed the folder icons to ZiconsZ to see what would happen if there were no icons, relaunched again, and nothing happened. The icons were there. I don't know if this is the correct behavior if the folder isn't found.
![Screenshot 2021-11-09 101946-04](https://user-images.githubusercontent.com/8125662/140939228-45233d9b-b256-49df-a8fd-cc2a293f2c79.png)
![Screenshot 2021-11-09 101946-05](https://user-images.githubusercontent.com/8125662/140939231-4be5f98a-3f70-4a11-bee6-782ca9df4953.png)
![Screenshot 2021-11-09 102556-06](https://user-images.githubusercontent.com/8125662/140939232-5ed82fea-59d5-4759-aa0f-005322dc69c9.png)

### Bisect Results

I think it happened since the OZONE theme was introduced in Retroarch PS3.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
Retroarch 1.9.0 ([xbins.org](https://xbins.org/libretro/nightly/playstation/ps3/))
Build date: Nov 18 2020

### Environment information

- OS: PS3 with firmware [CFW 4.88.2 EVILNAT (COBRA 8.3)​](https://www.psx-place.com/threads/4-88-2-evilnat-cobra-8-3-custom-firmware-cfw-cex-released.32057/)

### Additional information

- The same bug occurs with other cores. So probably it's not a core bug (for example: DOSBox-SVN core from Retroarch_PSX_CE).
- The same bug happens with [RetroArch PSX-Place Community Edition](https://www.psx-place.com/threads/retroarch-psx-place-community-edition-beta-3.32272/) by @crystalct - For it's Github repo go to https://github.com/crystalct/RetroArch_PSX_CE
Other users already reported the bug here: 
- https://www.psx-place.com/threads/retroarch-psx-place-community-edition-beta-3.32272/page-7#post-274401
- https://www.psx-place.com/threads/retroarch-psx-place-community-edition-beta-3.32272/page-14#post-290501
- https://www.psx-place.com/threads/retroarch-psx-place-community-edition-beta-3.32272/page-20#post-311596
- https://www.psx-place.com/threads/retroarch-psx-place-community-edition-beta-3.32272/page-21#post-314064

**Comment by Augusto7743** [comment] 2021-11-12 23:00
Tested 1.9.12 with a PS3 controller in Linux Ubuntu.
Button A and B are swapped because the default is both action button be how are japanese playstation console.
Try \ Settings \ Input \ Menu Control \ menu swap OK and cancel buttons

**Comment by Kormann** [comment] 2021-11-12 23:10
@Augusto7743 Before creating this issue for PS3, I already tested it in Windows and it works, probably it works in Linux for you too.

**This is a bug probably exclusive to PS3 port**. I already tried exactly what you told me. If you read my post again, and check the images, you will see that in PS3, the info/legend at the bottom where it shows the buttons and it's actions, will always display the opposite of the settings you had set in "menu swap OK and cancel buttons". No matter what you set.

**Comment by Augusto7743** [comment] 2021-11-19 04:23
What is PS3 region ? USA or Japan ?

**Comment by Kormann** [comment] 2021-11-19 13:00
I think it doesn't matter as I also tested it in RPCS3 emulator as well and btw, the firmware is universal, so it only affects BD Videos and some games when played in CRT TVs (PAL games can't play on NTSC CRT TVs).  But anyway, my console region is USA.

### Possible bug origin
**EDIT:** My RPCS3 had the same settings as my PS3 System configuration (American Region + Enter Button Assignment [Enter with Cross]). So I tried RPCS3 setting the console Region to Japan and nothing happened, but then I changed the PS3 System configuration from Enter Button with Cross to Circle (as in the Japanese default configuration). And in Retroarch everything went in sync, the CIRCLE was CIRCLE, the CROSS was CROSS. So if I navigate the menus in Retroarch's default configuration _"Menu Swap OK and Cancel Buttons set to OFF (Disabled is the Jap orientation)"_ It works... if I change to ON (Western orientation), it also works. When I remap my buttons in Input controls, it also works correctly.

So @Augusto7743 I think we found the my problem. This is not only a OZONE bug... It's Retroarch itself. Retroarch isn't detecting the PS3 System Enter Button Assignment. And because of that the bug affects Western Consoles (American, European, Oceania...), the Japanese console owners that uses their default button ps3 system scheme won't be affected, because Retroarch's default is the Japanese Orientation. If bug is fixed, the Western console will be in sync with the bottom legend and when you remap your the CIRCLE as CIRCLE, it will still be CIRCLE, and then the user will have only to change the "Menu Swap OK and Cancel Buttons set to ON" to make the CROSS enter and the game controls will maintain intact. 

@twinaphex and @Themaister  can you take a look? @crystalct ?

**Comment by Augusto7743** [comment] 2021-11-19 13:42
Hey try change the source and after compile if you known where is the default settings about the ps3 controller and the option \ Settings \ Input \ Menu Control \ menu swap OK and cancel buttons

**Comment by Kormann** [comment] 2021-11-19 14:19
The thing is I'm not a developer, damm. That's why I was reporting the bug.

**Comment by Augusto7743** [comment] 2021-11-23 09:34
You have any USB generic controller compatible with PS3 for test ? If yes try see if happen the issue.

**Comment by RobLoach** [comment] 2021-12-28 06:40
I believe this is intentional. Follows the RetroPad config:
https://www.lakka.tv/doc/Input-settings/

![](https://www.lakka.tv/doc/images/retropad_360pad.png)

**Comment by LibretroAdmin** [comment] 2022-09-01 19:07
Not a bug, RetroPad follows the Nintendo button layout, not the Xbox one.

**Closed by LibretroAdmin** 2022-09-01 19:07 UTC
