### ISSUE TITLE
revert cheat search + 24-bit search

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#7166] opened 2018-09-01 15:50 UTC
Using official 1.7.4 Retroarch windows and the new RA cheat engine is amazing! Lots more fun to use than Cheat Engine by Dark Byte (and no need to alt-tab).

Is there a way though to do 24-bit searches? RPGs like to store this often enough. Also is it possible to revert a bad search and restart from the immediate previous result?

Thanks for making Retroarch so usable and flexible. It's a modern marvel how widespread it's become.

**Comment by twinaphex** [comment] 2018-10-15 05:34
@RetroSven Any thoughts?

**Comment by RetroSven** [comment] 2018-10-15 11:53
looks like the original posted deleted their github account so I can't tell if they're reading but:

"ghost"/original submitted - yes, 24-bit searches are possible - I'll make a note of it

@Smoker1 I think you mentioned the FBA cheat searching not working in a different ticket.  Pretty much all the games in FBA should work with cheat code searching now.  Please re-try

No, there is no cheat-searching implementation for prboom as a standalone game/core.  

I'm pretty sure that "cheat search not started" issue is for when a core does not support cheating (or might have been a bug that has since been fixed).  Please re-try in the latest RA.  If it's still a problem then please provide specific steps to reproduce (specifically which core, which game, what you're doing exactly, etc)

The 3ds cheat searching/memory mapping is a bit wonky.  I have a note to investigate it at some point.

**Comment by orbea** [comment] 2018-12-24 05:02
Seems like this issue is resolved as explained in the previous comment so I am going to close this, if anyone still has a problem please let us know!

**Closed by orbea** 2018-12-24 05:02 UTC

**Comment by yamspy** [comment] 2026-03-05 11:49
Any news on the 24-bit cheat search?
