### ISSUE TITLE
[Feature Request] Be able to have playlists in non alphabetical order 

### ISSUE THREAD

**Issue by kcin2001** [libretro/RetroArch#6567] opened 2018-04-13 03:43 UTC
i would think it would be a nice feature to be able to not have your playlist be forced to be in alphabetical order and be able to just have the order be the order that the entries are in the playlist file
if i need to elaborate or move this just tell me

**Comment by kcin2001** [comment] 2018-04-13 06:07
A filepath thing would be nice to have in the information section since i sometimes get dupes and have to remove them manually to make sure i get the right one

**Comment by orbea** [comment] 2019-01-03 18:56
Related to https://github.com/libretro/RetroArch/pull/7881.

**Comment by orbea** [comment] 2019-01-07 16:48
Also a duplicate of issue https://github.com/libretro/RetroArch/issues/6422.

**Closed by orbea** 2019-01-07 16:48 UTC
Labels: feature request
