### ISSUE TITLE
Memory Leak: cocoa_input.c/cocoa_input_poll() -- get_backing_scale_factor repeatedly allocating and not releasing NSInvocation 

### ISSUE THREAD

**Issue by cutecycle** [libretro/RetroArch#4822] opened 2017-04-15 03:17 UTC
## Description

When leaving RetroArch open and idle for an extended period of time, the Memory allocation size grows over time. This can lead to it growing to multiple gigabytes over the course of hours.

### Expected behavior

RetroArch, when idiling with no cores, does not significantly increase in memory allocation size.

### Actual behavior

get_backing_scale_factor repeatedly allocates hundreds and thousands of new NSInvocation objects (300,000 544 byte objects in 40 minutes) without releasing, growing to multiple gigabytes over the course of hours.

### Steps to reproduce the bug

1. Start RetroArch.app with Mouse Support enabled 
2. Leave application open for a period of time
2a. Run Debug while viewing heap allocation to see get_backing_scale factor calls preprocessor-enabled calls for mouse position detection in the input loop 
3. This issue is averted by starting RetroArch.app with Mouse Support disabled.

### Version/Commit
```
static void cocoa_input_poll(void *data)
{
   uint32_t i;
   cocoa_input_data_t *apple = (cocoa_input_data_t*)data;
#ifndef IOS
   float   backing_scale_factor = get_backing_scale_factor();   // <-- 
#endif
    
   if (!apple)
      return;

   for (i = 0; i < apple->touch_count; i++)
   {
      struct video_viewport vp = {0};
#ifndef IOS
      apple->touches[i].screen_x *= backing_scale_factor;
      apple->touches[i].screen_y *= backing_scale_factor;
#endif
      video_driver_translate_coord_viewport_wrap(
            &vp,
            apple->touches[i].screen_x,
            apple->touches[i].screen_y,
            &apple->touches[i].fixed_x,
            &apple->touches[i].fixed_y,
            &apple->touches[i].full_x,
            &apple->touches[i].full_y);
   }

   if (apple->joypad)
      apple->joypad->poll();
   if (apple->sec_joypad)
       apple->sec_joypad->poll();

    apple->mouse_x_last = apple->mouse_rel_x;
    apple->mouse_y_last = apple->mouse_rel_y;
}
```

You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information
![screen shot 2017-04-14 at 11 11 45 pm](https://cloud.githubusercontent.com/assets/12169942/25060310/d917e102-2167-11e7-8bd7-0bb9e381b254.png)
![screen shot 2017-04-14 at 10 24 22 pm](https://cloud.githubusercontent.com/assets/12169942/25060311/d92712b2-2167-11e7-9ecd-57d0db3f9cdc.png)
![screen shot 2017-04-13 at 6 58 08 pm](https://cloud.githubusercontent.com/assets/12169942/25060312/d9271794-2167-11e7-8e6b-44a3f1e0016e.png)

- OS: Mac OS X Sierra 10.12.4, MacBook 4,2
- Compiler: Clang/LLVM 8.1.0
- Additional system information in screenshot

Xcode Instruments.app trace file coming soon: Trace is currently 900MB

**Comment by twinaphex** [comment] 2017-04-15 17:31
See if the memory leaks are fixed as of this commit -

https://github.com/libretro/RetroArch/commit/1d97a8122485c548c89272e3a80bdfb1125909fa

**Comment by cutecycle** [comment] 2017-04-15 23:34
![screen shot 2017-04-15 at 7 14 09 pm](https://cloud.githubusercontent.com/assets/12169942/25067442/b1781ad6-2211-11e7-8369-4795ce76d56d.png)
![screen shot 2017-04-15 at 7 12 25 pm](https://cloud.githubusercontent.com/assets/12169942/25067443/b1864a48-2211-11e7-8293-3f9be306f619.png)

Appears to be resolved!

**Comment by twinaphex** [comment] 2017-04-15 23:51
Good to hear!

**Comment by cutecycle** [comment] 2017-04-16 00:03
However, the Xbox 360 controller doesn't work and the menu sprites don't show... I don't know if this is related to other commits before 1d97a81.

**Comment by twinaphex** [comment] 2017-04-16 00:27
That has nothing to do with this.

You probably just need to install the assets again or point it to the directory where your assets are.

Same for the autoconfig files. When you compile from xcode, it starts with empty directories for those assets and you need to either point the directories to the right dirs or grab them from the server through 'Online Updater'.

Let me know if this is the case so that we can close this issue.

**Comment by twinaphex** [comment] 2017-04-20 07:09
Going to assume the issue is fixed then since I get no more response.

**Closed by twinaphex** 2017-04-20 07:09 UTC
