### ISSUE TITLE
[UI Bug] GLUI Playlist game mismatch

### ISSUE THREAD

**Issue by bronnel** [libretro/RetroArch#2426] opened 2015-11-18 17:05 UTC
This only happens in GLUI mode, when you click on a game title the submenu doesn't belong to the corresponding game , This issue is specific to GLUI mode and doesn't happen in XMB mode , I tested this on iOS android windows 7 and osx Yosemite, it's the same on all of them, and doesn't matter which core all are the same, and I tested this multiple times, I uploaded a video to clarify
https://www.youtube.com/watch?v=pL2AbM9cMGc&feature=youtu.be

**Comment by fr500** [comment] 2015-11-18 17:05
duplicate of https://github.com/libretro/RetroArch/issues/2334

**Closed by fr500** 2015-11-18 17:05 UTC
