### ISSUE TITLE
Closing Retroarch saves the active remap setting input_player1_analog_dpad_mode file to global config too.

### ISSUE THREAD

**Issue by kokoko3k** [libretro/RetroArch#16138] opened 2024-01-19 14:27 UTC
## Description
Closing retroarch saves the active remap file setting relative to "Input_player1_analog_dpad_mode" to global settings too.

### Expected behavior
That setting should be tied to the remap file.

### Steps to reproduce the bug

* load Ikaruga
* Quick menu, controls, Save Game remap file
* From the menu, I read that Active remap file is set to Ikaruga, good.
* Then i set Port 1, Analog to digital: Left Analog
* Analog to digital works, good.
* Quit cleanly from Retroarch. (*see note*)
* Check the remap file and it has the correct input_player1_analog_dpad_mode = "1" line, good.
* Restart retroarch
* Check the input settings without loading anything
* See that Port 1 is set to Analog to digital: Left Analog

(*note*) Note that at that point, if, before closing retroarch, one selects "close content" then the issue is not present.

### Version/Commit
1.06.0.3

### Environment information
Archlinux build.

https://github.com/libretro/RetroArch/assets/1230726/2ba054ef-1bc8-4bdf-86ad-4e8deb81cb45

**Comment by bslenul** [comment] 2024-01-20 12:18
I incorrectly assumed it wasn't happening on Windows when we talked about the issue on Discord yesterday, I had an override that prevented the issue from happening, but after removing that override I can now reproduce the issue on Windows as well. My bad!

**Comment by bslenul** [comment] 2024-01-20 14:31
Dunno if that's a proper fix but \*it seems\* to work fine if I put this block: https://github.com/libretro/RetroArch/blob/72c901a90eee3014c68479e67afa9df758d32abe/retroarch.c#L8159-L8166

after this one: https://github.com/libretro/RetroArch/blob/72c901a90eee3014c68479e67afa9df758d32abe/retroarch.c#L8177-L8187

Now the setting isn't saved in retroarch.cfg anymore when closing RA without closing content first.

**Comment by hizzlekizzle** [comment] 2024-01-20 14:43
wasn't this fixed awhile back? if so, would it make sense to bisect and see when it returned?

**Comment by bslenul** [comment] 2024-01-20 14:53
Oh interesting, you're correct I just tested 1.11.1 and the issue doesn't happen, but it happens in 1.12.0. I'll see how many steps it requires to bisect, if it's not too long I'll give it a shot.

**Comment by hizzlekizzle** [comment] 2024-01-21 00:07
@sonninnos do you have any idea how that commit could cause this behavior?

**Comment by sonninnos** [comment] 2024-01-21 00:45
Not really since `CMD_EVENT_MENU_SAVE_CURRENT_CONFIG` was moved to happen even later, but apparently not late enough. Previously the config was saved multiple times, so I guess on the next run the remaps were already cleared to default before the last save attempt .

That simple finding from bslenul seems reasonable, as in move it after the remapping stuff. Surely it won't cause more damage. Perhaps makes sense to even do it after `config_unload_override();`, but do test first. Saving is blocked with overrides active anyway.

**Comment by bslenul** [comment] 2024-01-21 12:01
Thanks for the answer! Messed a bit with the change with remaps and overrides, seems fine AFAICT. However now even if you DON'T have a remap file the analog to digital option will not save globally either, do we want that?

Sure the remap stuff should be saved in remap files, however that option is also "duplicated" in `Settings > Input > RetroPad Binds > Port N Controls` so the user might be confused about why it's not saving globally when changing it from there while not using remap file, forcing them to close the content first.

Or am I overthinking this? :p

**Comment by sonninnos** [comment] 2024-01-21 13:27
Dang, it sure should get saved globally without remaps..

**Comment by bslenul** [comment] 2024-01-22 11:43
What about a flag that remembers if any remap file was active? Something like this:
```diff
diff --git a/input/input_driver.c b/input/input_driver.c
index 3e44dab937..6970cffe9a 100644
--- a/input/input_driver.c
+++ b/input/input_driver.c
@@ -6032,6 +6032,7 @@ void input_remapping_restore_global_config(bool clear_cache)
    for (i = 0; i < MAX_USERS; i++)
    {
       if ((input_st->flags & INP_FLAG_OLD_ANALOG_DPAD_MODE_SET)
+          && (input_st->flags & INP_FLAG_REMAP_FILE_WAS_ACTIVE)
           && (settings->uints.input_analog_dpad_mode[i] !=
                input_st->old_analog_dpad_mode[i]))
          configuration_set_uint(settings,
@@ -6050,7 +6051,8 @@ end:
    if (clear_cache)
       input_st->flags &= ~(INP_FLAG_OLD_ANALOG_DPAD_MODE_SET
                          | INP_FLAG_OLD_LIBRETRO_DEVICE_SET
-                         | INP_FLAG_REMAPPING_CACHE_ACTIVE);
+                         | INP_FLAG_REMAPPING_CACHE_ACTIVE
+                         | INP_FLAG_REMAP_FILE_WAS_ACTIVE);
 }
 
 void input_remapping_update_port_map(void)
diff --git a/input/input_driver.h b/input/input_driver.h
index 6fa75a3b35..ba996b1521 100644
--- a/input/input_driver.h
+++ b/input/input_driver.h
@@ -157,7 +157,8 @@ enum input_driver_state_flags
    INP_FLAG_OLD_LIBRETRO_DEVICE_SET  = (1 << 8),
    INP_FLAG_REMAPPING_CACHE_ACTIVE   = (1 << 9),
    INP_FLAG_DEFERRED_WAIT_KEYS       = (1 << 10),
-   INP_FLAG_WAIT_INPUT_RELEASE       = (1 << 11)
+   INP_FLAG_WAIT_INPUT_RELEASE       = (1 << 11),
+   INP_FLAG_REMAP_FILE_WAS_ACTIVE    = (1 << 12)
 };
 
 #ifdef HAVE_BSV_MOVIE
diff --git a/menu/cbs/menu_cbs_ok.c b/menu/cbs/menu_cbs_ok.c
index 2cbad23471..ac76b71d87 100644
--- a/menu/cbs/menu_cbs_ok.c
+++ b/menu/cbs/menu_cbs_ok.c
@@ -3610,6 +3610,7 @@ static int generic_action_ok_remap_file_operation(const char *path,
    bool has_content                      = !string_is_empty(rarch_path_basename);
    settings_t *settings                  = config_get_ptr();
    const char *directory_input_remapping = settings->paths.directory_input_remapping;
+   input_driver_state_t *input_st        = input_state_get_ptr();
 
    content_dir_name[0] = '\0';
    remap_file_path[0]  = '\0';
@@ -3700,15 +3701,24 @@ static int generic_action_ok_remap_file_operation(const char *path,
          {
             case ACTION_OK_REMAP_FILE_REMOVE_CORE:
                if (flags & RUNLOOP_FLAG_REMAPS_CORE_ACTIVE)
+               {
+                  input_st->flags &= ~INP_FLAG_REMAP_FILE_WAS_ACTIVE;
                   input_remapping_deinit(false);
+               }
                break;
             case ACTION_OK_REMAP_FILE_REMOVE_GAME:
                if (flags & RUNLOOP_FLAG_REMAPS_GAME_ACTIVE)
+               {
+                  input_st->flags &= ~INP_FLAG_REMAP_FILE_WAS_ACTIVE;
                   input_remapping_deinit(false);
+               }
                break;
             case ACTION_OK_REMAP_FILE_REMOVE_CONTENT_DIR:
                if (flags & RUNLOOP_FLAG_REMAPS_CONTENT_DIR_ACTIVE)
+               {
+                  input_st->flags &= ~INP_FLAG_REMAP_FILE_WAS_ACTIVE;
                   input_remapping_deinit(false);
+               }
                break;
          }
 
diff --git a/retroarch.c b/retroarch.c
index 413eb025a4..e24262f712 100644
--- a/retroarch.c
+++ b/retroarch.c
@@ -7698,6 +7698,7 @@ bool retroarch_ctl(enum rarch_ctl_state state, void *data)
 {
    struct rarch_state     *p_rarch = &rarch_st;
    runloop_state_t     *runloop_st = runloop_state_get_ptr();
+   input_driver_state_t *input_st  = input_state_get_ptr();
 
    switch(state)
    {
@@ -7839,16 +7840,19 @@ bool retroarch_ctl(enum rarch_ctl_state state, void *data)
          runloop_st->flags &= ~(RUNLOOP_FLAG_REMAPS_CONTENT_DIR_ACTIVE
                               | RUNLOOP_FLAG_REMAPS_GAME_ACTIVE);
          runloop_st->flags |=   RUNLOOP_FLAG_REMAPS_CORE_ACTIVE;
+         input_st->flags   |= INP_FLAG_REMAP_FILE_WAS_ACTIVE;
          break;
       case RARCH_CTL_SET_REMAPS_GAME_ACTIVE:
          runloop_st->flags &= ~(RUNLOOP_FLAG_REMAPS_CORE_ACTIVE
                               | RUNLOOP_FLAG_REMAPS_CONTENT_DIR_ACTIVE);
          runloop_st->flags |=   RUNLOOP_FLAG_REMAPS_GAME_ACTIVE;
+         input_st->flags   |= INP_FLAG_REMAP_FILE_WAS_ACTIVE;
          break;
       case RARCH_CTL_SET_REMAPS_CONTENT_DIR_ACTIVE:
          runloop_st->flags &= ~(RUNLOOP_FLAG_REMAPS_CORE_ACTIVE
                               | RUNLOOP_FLAG_REMAPS_GAME_ACTIVE);
          runloop_st->flags |=   RUNLOOP_FLAG_REMAPS_CONTENT_DIR_ACTIVE;
+         input_st->flags   |= INP_FLAG_REMAP_FILE_WAS_ACTIVE;
          break;
 #endif
       case RARCH_CTL_GET_PERFCNT:
@@ -8156,15 +8160,6 @@ bool retroarch_main_quit(void)
    }
    if (!(runloop_st->flags & RUNLOOP_FLAG_SHUTDOWN_INITIATED))
    {
-      /* Save configs before quitting
-       * as for UWP depending on `OnSuspending` is not important as we can call it directly here
-       * specifically we need to get width,height which requires UI thread and it will not be available on exit
-       */
-#if defined(HAVE_DYNAMIC)
-      if (config_save_on_exit)
-         command_event(CMD_EVENT_MENU_SAVE_CURRENT_CONFIG, NULL);
-#endif
-
       if (settings->bools.savestate_auto_save &&
           runloop_st->current_core_type != CORE_TYPE_DUMMY)
          command_event_save_auto_state();
@@ -8193,6 +8188,16 @@ bool retroarch_main_quit(void)
          config_unload_override();
       }
 #endif
+
+      /* Save configs before quitting
+       * as for UWP depending on `OnSuspending` is not important as we can call it directly here
+       * specifically we need to get width,height which requires UI thread and it will not be available on exit
+       */
+#if defined(HAVE_DYNAMIC)
+      if (config_save_on_exit)
+         command_event(CMD_EVENT_MENU_SAVE_CURRENT_CONFIG, NULL);
+#endif
+
 #if defined(HAVE_CG) || defined(HAVE_GLSL) || defined(HAVE_SLANG) || defined(HAVE_HLSL)
       runloop_st->runtime_shader_preset_path[0] = '\0';
 #endif
```
So if a remap file exists the flag `INP_FLAG_REMAP_FILE_WAS_ACTIVE` is set (so it remembers it even after the remap files flags are cleared) and will return analog to digital to its previous value, if no remap file was used (or "Delete xxx Remap File" was clicked) then we keep the current analog to digital value.

But, as usual, I'm still pretty noob at this and idk if there's a better way of handling this :p

**Comment by bslenul** [comment] 2024-02-01 13:13
I was rethinking about this, what about a second parameter for `input_remapping_restore_global_config()`? Like `bool restore_analog_dpad_mode` for example:
```diff
diff --git a/input/input_driver.c b/input/input_driver.c
index d112eb9049..74d9e74bb8 100644
--- a/input/input_driver.c
+++ b/input/input_driver.c
@@ -6062,7 +6062,7 @@ void input_remapping_cache_global_config(void)
                     | INP_FLAG_OLD_LIBRETRO_DEVICE_SET;
 }
 
-void input_remapping_restore_global_config(bool clear_cache)
+void input_remapping_restore_global_config(bool clear_cache, bool restore_analog_dpad_mode)
 {
    unsigned i;
    settings_t *settings           = config_get_ptr();
@@ -6073,7 +6073,8 @@ void input_remapping_restore_global_config(bool clear_cache)
 
    for (i = 0; i < MAX_USERS; i++)
    {
-      if ((input_st->flags & INP_FLAG_OLD_ANALOG_DPAD_MODE_SET)
+      if (   (input_st->flags & INP_FLAG_OLD_ANALOG_DPAD_MODE_SET)
+          &&  restore_analog_dpad_mode
           && (settings->uints.input_analog_dpad_mode[i] !=
                input_st->old_analog_dpad_mode[i]))
          configuration_set_uint(settings,
@@ -6195,7 +6196,7 @@ void input_remapping_set_defaults(bool clear_cache)
     * the last core init
     * > Prevents remap changes from 'bleeding through'
     *   into the main config file */
-   input_remapping_restore_global_config(clear_cache);
+   input_remapping_restore_global_config(clear_cache, true);
 }
 
 void input_driver_collect_system_input(input_driver_state_t *input_st,
diff --git a/input/input_remapping.h b/input/input_remapping.h
index 4dfb43bd49..57736e356c 100644
--- a/input/input_remapping.h
+++ b/input/input_remapping.h
@@ -58,11 +58,16 @@ void input_remapping_cache_global_config(void);
  * init if INP_FLAG_REMAPPING_CACHE_ACTIVE is set.
  * Must be called on core deinitialization. 
  * 
- * @param clear_cache  If true, function becomes a NOOP until the next time
- *                     `input_remapping_cache_global_config()` is called, and 
- *                     INP_FLAG_REMAPPING_CACHE_ACTIVE is set.
+ * @param clear_cache               If true, function becomes a NOOP until the next time
+ *                                  `input_remapping_cache_global_config()` is called, and
+ *                                  INP_FLAG_REMAPPING_CACHE_ACTIVE is set.
+ * @param restore_analog_dpad_mode  Treat 'Analog to Digital Type' like a regular setting,
+ *                                  meaning this should be false when we're not using any
+ *                                  remap file so its value is saved globally on close/quit,
+ *                                  and it should be true when we're using a remap or if
+ *                                  we're resetting settings, to restore its global value.
  */
-void input_remapping_restore_global_config(bool clear_cache);
+void input_remapping_restore_global_config(bool clear_cache, bool restore_analog_dpad_mode);
 
 /**
  * Must be called whenever `settings->uints.input_remap_ports` is modified.
diff --git a/retroarch.c b/retroarch.c
index 413eb025a4..0087d445de 100644
--- a/retroarch.c
+++ b/retroarch.c
@@ -3667,7 +3667,7 @@ bool command_event(enum event_command cmd, void *data)
                input_remapping_set_defaults(true);
             }
             else
-               input_remapping_restore_global_config(true);
+               input_remapping_restore_global_config(true, false);
 
 #ifdef HAVE_CONFIGFILE
             if (runloop_st->flags & RUNLOOP_FLAG_OVERRIDES_ACTIVE)
@@ -7579,7 +7579,7 @@ bool retroarch_main_init(int argc, char *argv[])
             input_remapping_set_defaults(true);
          }
          else
-            input_remapping_restore_global_config(true);
+            input_remapping_restore_global_config(true, false);
 
 #ifdef HAVE_CONFIGFILE
          /* Reload the original config */
@@ -8156,15 +8156,6 @@ bool retroarch_main_quit(void)
    }
    if (!(runloop_st->flags & RUNLOOP_FLAG_SHUTDOWN_INITIATED))
    {
-      /* Save configs before quitting
-       * as for UWP depending on `OnSuspending` is not important as we can call it directly here
-       * specifically we need to get width,height which requires UI thread and it will not be available on exit
-       */
-#if defined(HAVE_DYNAMIC)
-      if (config_save_on_exit)
-         command_event(CMD_EVENT_MENU_SAVE_CURRENT_CONFIG, NULL);
-#endif
-
       if (settings->bools.savestate_auto_save &&
           runloop_st->current_core_type != CORE_TYPE_DUMMY)
          command_event_save_auto_state();
@@ -8184,7 +8175,7 @@ bool retroarch_main_quit(void)
          input_remapping_set_defaults(true);
       }
       else
-         input_remapping_restore_global_config(true);
+         input_remapping_restore_global_config(true, false);
 
 #ifdef HAVE_CONFIGFILE
       if (runloop_st->flags & RUNLOOP_FLAG_OVERRIDES_ACTIVE)
@@ -8193,6 +8184,16 @@ bool retroarch_main_quit(void)
          config_unload_override();
       }
 #endif
+
+      /* Save configs before quitting
+       * as for UWP depending on `OnSuspending` is not important as we can call it directly here
+       * specifically we need to get width,height which requires UI thread and it will not be available on exit
+       */
+#if defined(HAVE_DYNAMIC)
+      if (config_save_on_exit)
+         command_event(CMD_EVENT_MENU_SAVE_CURRENT_CONFIG, NULL);
+#endif
+
 #if defined(HAVE_CG) || defined(HAVE_GLSL) || defined(HAVE_SLANG) || defined(HAVE_HLSL)
       runloop_st->runtime_shader_preset_path[0] = '\0';
 #endif
diff --git a/runloop.c b/runloop.c
index 5b59d614fb..5282cd03ec 100644
--- a/runloop.c
+++ b/runloop.c
@@ -4085,7 +4085,7 @@ void runloop_event_deinit_core(void)
       input_remapping_set_defaults(true);
    }
    else
-      input_remapping_restore_global_config(true);
+      input_remapping_restore_global_config(true, false);
 
    RARCH_LOG("[Core]: Unloading core symbols..\n");
    uninit_libretro_symbols(&runloop_st->current_core);
```
It passes "false" when there's no remap file, so the setting is saved globally and it only passes "true" when `input_remapping_set_defaults()` is called, in which case we restore the global value.

I can't really think of anything else, I tried creating a flag but there's so many things to check that I always end up finding a case where it doesn't work as expected -_-

**Comment by sonninnos** [comment] 2024-02-01 21:34
Seems reasonable and simple enough.

**Comment by bslenul** [comment] 2024-02-01 23:51
Awesome thank you, I will make a PR then, do you mind if I ping you as reviewer again? 😳

**Closed** 2024-02-02 20:53 UTC

**Comment by kokoko3k** [comment] 2024-02-05 11:18
Thank you very much for your efforts!
