### ISSUE TITLE
AppImage crashes with Vulkan - Flatpak works with Vulkan

### ISSUE THREAD

**Issue by jbmoss1982** [libretro/RetroArch#14709] opened 2022-12-07 20:50 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch AppImage crashes when Vulkan is the configured video driver.
Flatpak version does not crash when Vulkan is the configured video driver on the same system using the same retroarch.cfg.

### Expected behavior

RetroArch AppImage starts and runs when configured to utilize the Vulkan video driver.

### Actual behavior

RetroArch crashes on launch.

### Steps to reproduce the bug

1. Download a Linux x86_64 RetroArch AppImage
2. Execute AppImage
3. Set Video Driver to Vulkan and save configuration
4. Exit RetroArch AppImage
5.  Verify retroarch.cfg contains value video_driver = "vulkan"
6. Attempt to execute RetroArch AppImage again

### Bisect Results

As far as I can tell this issue has been present since the first AppImage was released.

### Version/Commit

- RetroArch: This issue is present in every available AppImage (Qt and non-Qt) from version 1.9.1 to the current nightly.

### Environment information

- OS: SteamOS 3.3.2
- Hardware: SteamDeck 512GB
[AppImage Log retroarch__2022_12_07__15_46_11.log](https://github.com/libretro/RetroArch/files/10179897/retroarch__2022_12_07__15_46_11.log)
[Flatpak Log retroarch__2022_12_07__15_46_16.log](https://github.com/libretro/RetroArch/files/10179900/retroarch__2022_12_07__15_46_16.log)
[retroarch.cfg.zip](https://github.com/libretro/RetroArch/files/10179908/retroarch.cfg.zip)

**Comment by mantralunar** [comment] 2023-01-08 19:03
Also experiencing this on Steam Deck

**Comment by gouchi** [comment] 2023-01-09 13:46
I can't reproduce the issue using [latest nightly](https://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z) with Nvidia gpu with or without your [retroarch.cfg.zip](https://github.com/libretro/RetroArch/files/10179908/retroarch.cfg.zip)

**Comment by jbmoss1982** [comment] 2023-01-09 14:31
Just tested the latest x86_64 nightlies released 9JAN2023. No change in behavior on SteamDeck using the same retroarch.cfg. GL vs Vulkan RetroArch logs for AppImage attached for QT/non-QT.


[GL_2023-01-09_RetroArch-Linux-x86_64_QT_retroarch__2023_01_09__09_19_33.log](https://github.com/libretro/RetroArch/files/10373941/GL_2023-01-09_RetroArch-Linux-x86_64_QT_retroarch__2023_01_09__09_19_33.log)
[VULKAN_2023-01-09_RetroArch-Linux-x86_64_QT_retroarch__2023_01_09__09_23_59.log](https://github.com/libretro/RetroArch/files/10373943/VULKAN_2023-01-09_RetroArch-Linux-x86_64_QT_retroarch__2023_01_09__09_23_59.log)

[GL_2023-01-09_RetroArch-Linux-x86_64_retroarch__2023_01_09__09_20_01.log](https://github.com/libretro/RetroArch/files/10373942/GL_2023-01-09_RetroArch-Linux-x86_64_retroarch__2023_01_09__09_20_01.log)
[VULKAN_2023-01-09_RetroArch-Linux-x86_64_retroarch__2023_01_09__09_24_22.log](https://github.com/libretro/RetroArch/files/10373944/VULKAN_2023-01-09_RetroArch-Linux-x86_64_retroarch__2023_01_09__09_24_22.log)

**Comment by gouchi** [comment] 2023-01-12 13:35
@hizzlekizzle Do you reproduce the issue with the Appimage ?

Thank you.

**Comment by hizzlekizzle** [comment] 2023-01-14 22:10
Works fine here with the latest nightly. I didn't mess with any other settings, just downloaded it, changed to vulkan, quit, verified that video_driver = "vulkan" in the cfg and then started it back up. No problems with intel IGP.

**Comment by gouchi** [comment] 2023-10-30 14:20
@jbmoss1982 If it is ok for you, please close this issue. Thank you.

**Closed** 2023-10-30 18:31 UTC
