### ISSUE TITLE
Wii U, If Retroachievements enabled, RetroArch stutters for many seconds

### ISSUE THREAD

**Issue by MysticFlipFlop** [libretro/RetroArch#14543] opened 2022-10-22 05:34 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

This is on nightly release post-1.12.0. I start any core and it stutters for many seconds. More than a minute if the game has many achievements. I realized this doesn´t happen on stable release 1.10.3

### Expected behavior

Game starting with no stuttering when Retroachievements enabled

### Actual behavior

Game starts with stuttering when Retroachievements enabled

### Steps to reproduce the bug

1. Enable Retroachievements
2. Start any game that has achievement support

### Bisect Results

Every stable and nightly release after 1.10.3

### Version/Commit
RetroArch: Git Version: 622cc61671
Build Date: Oct 22 2022
Compiler: GCC (6.3.0) 32-bit

### Environment information

- OS: Wii U Tiramisu
- Compiler: [In case you are running local builds]

**Comment by dekgear** [comment] 2022-10-23 05:20
I think this issue is caused because it attempts to download the cheevos badges image files every time a game with achievements starts up.

On 1.10.3 and older versions, the cheevos and badges folders on the thumbnails directory had to be manually created as Retroarch on Wii U had issues creating new directories/folders. When the folder was set up correctly, it only stuttered the first time a game with achievements was set up, as the badges are getting downloaded; afterwards the stutter stops when opening the game again. Without that folder, the game would stutter every time and the cheevos badges would never get downloaded

1.12.0 fixed the issue with creating new directories, and I can confirm the cheevos/badges folders generate properly on the thumbnails directory. The badges images themselves also get downloaded properly. However, it seems it now always attempts to download the cheevos badges even if they are already downloaded, so it stutters every time.

**Comment by MysticFlipFlop** [comment] 2022-12-14 19:58
fixed on 1.14.0 stable

**Comment by Jamiras** [comment] 2022-12-14 20:09
> However, it seems it now always attempts to download the cheevos badges even if they are already downloaded, so it stutters every time.

Changes in 1.11.0 exposed a bug in the way the badge cache path was constructed, causing it to not find the previously downloaded badges. It was fixed in #14712. Glad to hear things are working now.

**Comment by LibretroAdmin** [comment] 2022-12-14 22:18
Great to hear this is resolved now.

**Closed by LibretroAdmin** 2022-12-14 22:18 UTC
