### ISSUE TITLE
[3DS] Vertical games rotate the top screen the wrong way

### ISSUE THREAD

**Issue by Tinister** [libretro/RetroArch#13018] opened 2021-09-19 20:30 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

This is easiest seen with the Beetle Cygne core for WonderSwan, since with that core you can press the select button to rotate the screen.

This has also been reported with Final Burn cores:  https://www.reddit.com/r/RetroArch/comments/pm62zt/fba_and_fb_neo_on_new_3ds_top_screen_display/

Screenshots from WonderSwan, before and after pressing select:
![landscape](https://user-images.githubusercontent.com/12524695/133941879-ada59409-2259-47d5-ad4b-fd46d630580f.png) ![portrait](https://user-images.githubusercontent.com/12524695/133941936-d02a4eff-73ba-46ea-80f1-1183d9c3a119.png)

### Expected behavior

Vertical screen is right side up.

### Actual behavior

Vertical screen is upside down.

### Steps to reproduce the bug

1. Open up content for the Beetle Cygne core for WonderSwan.
2. Press the select button.

### Bisect Results

No idea.

### Version/Commit
You can find this information under Information/System Information

- RetroArch 1.9.9, Build Date Sep 5 2021

### Environment information

New Nintendo 3DS XL with system update 11.15.0-47U with custom firmware installed (Luma3DS v10.2.1)

**Comment by MrHuu** [comment] 2021-10-02 15:58
It seems hardware rotation isn't exposed by the frontend. The core falls back on software rotation which does not seem to work properly in this case.

You can use the frontends ability to rotate the screen, found in settings:
```Settings / Video / Output / Video Rotation```

**Comment by Tinister** [comment] 2021-10-02 18:01
I don't seem to have that setting (I'm on 1.9.10 now):

![settings](https://user-images.githubusercontent.com/12524695/135727252-ecae8802-1dfa-445a-bdf6-dbdf6c36e226.png)

`Video -> ctr` isn't it.

**Comment by MrHuu** [comment] 2021-10-02 18:31
That's odd.
Also using the latest build, the option is there for me:
![20211002_201941](https://user-images.githubusercontent.com/561623/135727789-980037f6-ca27-431d-8baa-e2baf6a8d4ec.jpg)
 
Not sure why it's not on your end.
I did enable ```show advanced settings```, maybe the option is hidden by default.

**Comment by Tinister** [comment] 2021-10-02 19:44
`Show advanced settings` was the secret sauce.  Thank you!

The video rotation setting doesn't persist after pressing select, but that's "fine" -- just re-open the settings to fix the rotation again.  Also, I'd imagine if it did persist then landscape view would get mirrored.

**Comment by vaguerant** [comment] 2021-11-27 14:21
I'm a bit late, but I don't think the problem is the 3DS not exposing rotation, it's that the implementation of rotation on 3DS isn't working correctly. Until this is fixed on the RetroArch side, there is a better solution than manually rotating. Go into Settings > Core and turn Allow Rotation off.

This isn't as severe as it sounds, it just prevents cores from using RetroArch's rotation features. Cores that support rotation internally like Beetle WonderSwan, all or most of the arcade cores, etc. will simply fall back on their internal rotation rather than using the RetroArch-side feature. As an end-user, the difference is invisible; you can now rotate with Select as designed.

**Closed** 2021-12-14 12:43 UTC
