### ISSUE TITLE
Trying to download cores from the RA core updater always fails in linux.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#6378] opened 2018-03-12 00:08 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The above probably happens because the 'normal' core directory in installed packages is not writable. This is pretty much 'only' relevant because some cores get into the 'core updater' but not the ppa/packages.

### Expected behavior

Before downloading, it should check if the dir it's trying to write to is writable. If not, download to "$XDG_CONFIG_HOME/cores". When *loading* a core from the menu, check for cores both in the default dir and the "$XDG_CONFIG_HOME/cores" dir and handle duplicates somehow (one wins or date check or something).

Although, it's viable to argue that this is a packaging problem and the only thing that's needed is to update the ppa builds to add missing cores (openlara, cavestory, dcss, flashback, citra-canary, etc). On this case, i'd suggest *disabling* the core downloader on startup if the directory it's expecting to write is not writable.

### Actual behavior

People who prefer to have sane packaging practices get screwed over, but what else is new.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment] 2018-03-21 16:46
This is more or less a duplicate of https://github.com/libretro/RetroArch/issues/3237.

**Comment by orbea** [comment] 2018-10-08 18:54
I'm going to close this as a duplicate.

**Closed by orbea** 2018-10-08 18:54 UTC
Labels: invalid: duplicate
