### ISSUE TITLE
Mouse input bug

### ISSUE THREAD

**Issue by Ghostlamer** [libretro/RetroArch#3989] opened 2016-11-13 10:52 UTC
libretro-dosbox (or Retroarch input) have a mouse bug (tested on 4 games), when i use mouse grab toogle or fullscreen, sometimes mouse rests on the invisible wall, but if you move it in the opposite direction several times, then it disappears, in some games this is almost not observed (kyrandia), in some games it constantly appears ((space quest 1 vga, space quest 4, space quest 5) - the easiest way to find this bug, the opening game settings panel)).
Sometimes it is really annoying that you just can not move the ingame mouse left and right because of some invisible wall.
I thought it was only libretro-dosbox  bug, but on forum Tatsuya79 said http://libretro.com/forums/showthread.php?t=7032&p=50623&viewfull=1#post50623 that it happens to with Mame or TyrQuake, so maybe that's a Retroarch input bug.
My os: Windows 10 x64, screen resolution: 2560x1440.

**Comment by gnutechs** [comment] 2017-02-16 23:13
This bug still occurs on 1.4.1 stable.
Video showing the bug: [https://vid.me/UzUr](url)

**Comment by gudlyf** [comment] 2017-02-22 15:28
I believe this is a dupe of #3408. It appears that RetroArch is reading cursor position to determine placement in-game, and since your cursor is hitting the left side of the screen and stopping (where you cannot see it), the cursor in-games stops.

**Comment by orbea** [comment] 2018-12-27 01:12
This seems to be a duplicate of a fixed issue so I am going to close this, please let us know if this is still a problem for anyone.

**Closed by orbea** 2018-12-27 01:12 UTC
