### ISSUE TITLE
[Cheevos] Segfault when detecting rom using Generic (filename) method

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#6448] opened 2018-03-24 02:59 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch crashes when a certain rom is loaded and is using "Generic (filename)" to look for achievements.

### Expected behavior

should fail gracefully regardless or errors without crashing retroarch.

### Actual behavior

when cheevos tries to detect a rom using **Generic (filename)** method, RetroArch crashes. At least one game i found that for some reasons is being detected this way. the 1943 (BETA) version for nes.

exact filename, NoIntro verified: "**1943 - The Battle of Midway (Japan) (Beta).nes**"
tested using FCEUmm, QuickNES
```
[INFO] [CHEEVOS]: got game id 0.
[INFO] [CHEEVOS]: testing Generic (plain content).
[INFO] [CHEEVOS]: getting game id for hash 982dbeeedf440832a1355722cd22af46
[INFO] [CHEEVOS]: got game id 0.
[INFO] [CHEEVOS]: testing Generic (filename).
Segmentation fault (core dumped)
```
**UPDATE:**
**This seems to affect games that probably do no have cheevos or if game ID is 0 since VS. games are also crashing but other that have zero achievements but has game ID (like Salamander(PR is awaiting merge to support this mapper in quicknes atm incase rom does not load at all in quicknes) do not crash.**

### Steps to reproduce the bug

1. With retroarchievement configured, load the specified rom.
2. it should soon crash while cheevos detection is going on

### Bisect Results

1st bad commit : https://github.com/libretro/RetroArch/commit/d2d8f00b29eef7b9b828f90c76833734a8fca98d

backtrace: https://hastebin.com/ukadicoduh.go

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.2 / 4d1b4f9

### Environment information

- OS: Arch Linux
- Compiler: gcc version 7.3.1 20180312 (GCC)

**Comment by meleu** [comment] 2018-06-04 13:33
@retro-wertz I'm unable to reproduce. Is it already fixed?

**Comment by orbea** [comment] 2018-12-24 05:38
@retro-wertz Can you please confirm if this issue is still current or not?

**Comment by retro-wertz** [comment] 2018-12-24 06:09
cheevos log has been removed a few months ago now  so i dont know what cheevos detects it anymore. but so far at least for the game title tested above, it does not cause crash so this can probably be closed.

**Comment by orbea** [comment] 2018-12-24 06:15
Okay, I am going to close this then and if its ever a problem again in the future it can be reopened or a new issue made, thanks for the quick reply!

**Closed by orbea** 2018-12-24 06:15 UTC
Labels: bug: major, cheevos, followup: needs info or confirmation
