### ISSUE TITLE
Bad font rendering in Manjaro Linux

### ISSUE THREAD

**Issue by orderorder** [libretro/RetroArch#14705] opened 2022-12-06 21:18 UTC
Bad font rendering with any graphic font except "rgui" 

Manjaro 22.0.0 - Mesa 22.2.4-1 - AMD R7 240 - CPU: AMD A10-7850K

![screenshot](https://user-images.githubusercontent.com/7293829/206025058-3e9ce6fa-bd72-450e-aebf-2f6e571789b6.png)
RetroArch 1.13.0

**Comment by orderorder** [comment] 2022-12-07 13:58
> This usually means your driver doesn't have sufficient OpenGL capabilities. Are you using the SDL or GL1 drivers in RetroArch, by chance?

I try with  video_driver = "glcore" in retroarch.cfg and it works with "gl" or "gl1" dont render the fonts

**Comment by spiralcules** [comment] 2023-02-04 20:55
mantap

**Comment by LibretroAdmin** [comment] 2023-02-04 21:07
Can you guys tell me what font rendering backend is being used here?

You could try switching between FreeType and STB Font.

To compile with FreeType:
./configure --enable-freetype --disable-stb_font
make

To compile with STB Font:
./configure --enable-stb_font --disable-freetype
make

Try seeing if any of the two will render properly on your system.

Also let us know your GPU and video driver version if possible.

**Comment by orderorder** [comment] 2023-02-24 15:25
> Can you guys tell me what font rendering backend is being used here?
> 
> You could try switching between FreeType and STB Font.
> 
> To compile with FreeType: ./configure --enable-freetype --disable-stb_font make
> 
> To compile with STB Font: ./configure --enable-stb_font --disable-freetype make
> 
> Try seeing if any of the two will render properly on your system.
> 
> Also let us know your GPU and video driver version if possible.

No luck, same behaviour. 

Manjaro 22.0.4 - Mesa 22.3.5-1 - AMD R7 240 - CPU: AMD A10-7850

**Comment by S0yKaf** [comment] 2023-06-08 17:14
any update on this? seems like it's an issue with mesa and radeonsi. 

6.3.5-arch1-1
mesa 23.1.1-1
[AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280]

**Comment by S0yKaf** [comment] 2023-06-08 21:24
Ok, so it's been confirmed to be an issue with mesa. if you're having the same problem, I've added a patch on the mesa issue that you can use to build mesa-git with that will fix the problem.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/9176#note_1949560

@LibretroAdmin This issue can probably be closed now since mesa is confirmed to be the culprit.

**Comment by viachaslavic** [comment] 2023-10-10 13:37
@orderorder, this bug should already be fixed since [Mesa 23.1.3 ](https://docs.mesa3d.org/relnotes/23.1.3.html). Can you confirm this?

**Comment by orderorder** [comment] 2023-10-13 21:12
> @orderorder, this bug should already be fixed since [Mesa 23.1.3 ](https://docs.mesa3d.org/relnotes/23.1.3.html). Can you confirm this?

Sorry for the delay. I am now using Endeavour OS with MESA 23.2.1 and it works properly

**Comment by gouchi** [comment] 2023-10-14 18:54
@orderorder so please close this issue then ;)

**Closed** 2023-10-15 12:12 UTC
