### ISSUE TITLE
(WIMP) Left Click Action?

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#7112] opened 2018-08-23 12:19 UTC
In the Playlists browser 'All Playlists' is selected by default and if I left click on any of the other playlists e.g. 'Nintendo - Game Boy' or 'History' there is no response - all non-hidden game titles continue to be displayed.

Surely the expected behaviour is that clicking on a playlist would display only the games in that playlist. Am I missing something here? I am using the retroarch-git AUR package on Archlinux.

**Comment by bparker06** [comment] 2018-08-23 12:35
It should change the center display to only show that playlist's contents, it does for me. Can you try updating RA? "All Playlists" is also not the default anymore.

**Comment by RobLoach** [comment] 2018-08-23 14:32
Going to close this one for now. If the issue persists after updating, feel free to re-open it. Thanks!

**Comment by pepedopolous** [comment] 2018-08-23 15:02
I've rebuilt and reinstalled and deleted the old .config files. Now when I turn on the Desktop interface it shows the History list. The problem with the playlists persists however. If I click on any other playlist, the middle panel doesn't change, it still shows the History list.

**Comment by pepedopolous** [comment] 2018-08-24 21:04
Hi, please can this Issue be reopened? It is present on both my Archlinux boxes, using the latest builds of the AUR package retroarch-git.  It happens even if I completely delete all of the retroarch config folder and start from scratch.

**Comment by RobLoach** [comment] 2018-08-26 01:30
Sounds good with me! Thanks a lot. 👍 

I'll assign them over.

**Comment by pepedopolous** [comment] 2018-08-28 21:11
Here's a video of the issue: https://youtu.be/nHk95ou33Yw

**Comment by retro-wertz** [comment] 2018-08-29 04:58
to make this issue abit more clear, this happens when running on KDE, regardless of which distro.

**Comment by bparker06** [comment] 2018-08-29 16:14
Can you paste a log? Have you tried this in a different DE? What about adding/dropping new items into the playlist? Does that work?

**Comment by pepedopolous** [comment] 2018-08-29 17:00
https://pastebin.com/UBGQeZzJ

**Comment by pepedopolous** [comment] 2018-08-29 17:04
When I drag a rom from Dolphin (file manager) to the playlist a modal dialogue appears. When I click to confirm, the rom isn't added to the playlist.

**Comment by pepedopolous** [comment] 2018-08-29 20:40
Hello again. I can confirm that the issue happens under KDE but not GNOME.

**Comment by retro-wertz** [comment] 2018-08-30 10:51
if it helps (guess my post above was not clear enough) i have experienced this issue months ago. This issue happens when you are using KDE, regardless of what distribution you are using (tested on live install of debian/ubuntu,suse,fedora,arch,mandriva, some other independent distros... etc as long as its KDE(at least on >= 5.12  this issue persist). switching to another desktop environment do no have the issue. video should show what the problem is on the Playlist tab, nothing is changed in the main window whatever list you click. Changing to Browse tab listing on main window works fine, but when you go back to Playlist tab, you are stuck with whatever was the last items displayed.

**Comment by bparker06** [comment] 2018-09-04 22:15
I did some testing and this appears to be a KDE "bug".

First reported to KDE bug tracker in 2014: https://bugs.kde.org/show_bug.cgi?id=337491

Then to Qt in 2015: https://bugreports.qt.io/browse/QTBUG-47696

This causes checks like this to fail:
https://github.com/libretro/RetroArch/blob/master/ui/drivers/qt/ui_qt_window.cpp#L2524

Where it checks if the current tab is "Playlists", but Qt is returning "&Playlists" instead, apparently due to a KDE platform theme plugin injecting the & sign (presumably for keyboard navigation purposes) in the tab title.

**Comment by pepedopolous** [comment] 2018-10-25 16:00
This workaround works for me. Add: -

```
[Development]
AutoCheckAccelerators=false
```

to ~/.config/kdeglobals.

From https://github.com/clementine-player/Clementine/issues/5931#issuecomment-353175247

**Comment by bparker06** [comment] 2019-01-03 17:14
Closing this since it is an unrelated upstream issue.

**Closed by bparker06** 2019-01-03 17:14 UTC
Labels: bug: wimp, bug: windowing systems, de - kde, invalid: upstream issue
