### ISSUE TITLE
[Windows] Filepath contain unicode will open failed from history playlist

### ISSUE THREAD

**Issue by LetCodeGo** [libretro/RetroArch#12624] opened 2021-07-08 01:07 UTC
{
      "path": "D:\\Roms\\GBA\\恶魔???- 月之轮回[施珂昱](简)(JP)(64Mb).gba",
      "label": "恶魔城 - 月之轮回[施珂昱](简)(JP)(64Mb)",
      "core_path": "C:\\Users\\zhang\\AppData\\Roaming\\RetroArch\\cores\\mgba_libretro.dll",
      "core_name": "Nintendo - Game Boy Advance (mGBA)",
      "crc32": "DETECT",
      "db_name": "GBA.lpl"
}
Open the content_history.lpl will find the path is garbled, but the label is correct.
RetroArch version is 1.9.6.

**Comment by toshixm** [comment] 2021-07-08 01:51
@LetCodeGo I think it is probably the same problem as #12103.
I have sent PR #12459 to fix it, but it has not been merged yet.
Could you try to build with this fix applied if you can?

**Comment by LetCodeGo** [comment] 2021-07-08 02:28
Indeed the same problem as #12103.
Sorry, I don't know how to build it with fix applied.

**Comment by toshixm** [comment] 2021-07-09 02:00
PR #12459 had been merged yesterday.
Could you confirm using the latest version of nightly build or next stable release?
And if the problem is solved, please close the issue.

**Comment by LetCodeGo** [comment] 2021-07-09 04:22
> PR #12459 had been merged yesterday.
> Could you confirm using the latest version of nightly build or next stable release?
> And if the problem is solved, please close the issue.

Is this https://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z

**Comment by LetCodeGo** [comment] 2021-07-09 04:52
I test with this https://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
and the issue is solved.
another issue is when open the game, the file name will appear in the middle screen with bold font. the file name is garbled.
this occured before this fix.
I will test more and close this issue, and open a new issue with above issue.

**Closed** 2021-07-09 08:29 UTC

**Comment by LetCodeGo** [comment] 2021-07-09 08:34
Issue solved.
Test version https://buildbot.libretro.com/nightly/windows/x86_64/2021-07-09_RetroArch.7z
