### ISSUE TITLE
RFE: create a option on the core updater to update all installed cores.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#8048] opened 2019-01-20 08:36 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Don't know if this can be made to only download if needed without further work, but i do know it's annoying to update the cores i already have one at a time.

### Expected behavior

A button/option on the top of the core download section that updates all of those that are already installed. Maybe a indicator for which already exist on the GUIs too.

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment] 2019-01-20 14:31
Duplicate of issue https://github.com/libretro/RetroArch/issues/1957.

**Closed by orbea** 2019-01-20 14:31 UTC
