### ISSUE TITLE
Favourites playlist doesn't show thumbnails

### ISSUE THREAD

**Issue by kade-robertson** [libretro/RetroArch#5477] opened 2017-09-26 03:11 UTC
## Description

When browsing the "Favourites" playlist, no thumbnails show up for the playlist items. These same items in their respective system playlists show the thumbnails as expected.

### Expected behavior

Thumbnails should always be displayed in the "Favourites" playlist.

### Actual behavior

Thumbnails do not display whatsoever.

### Steps to reproduce the bug

1. Start a game
2. Add it to the Favourites playlist using the Quick menu
3. Close the content and quit RetroArch
4. Re-open RetroArch

### Bisect Results

This has been happening since I set up RetroArch a few days ago.

Here's a gist of the log file that is created when I follow the above steps: https://gist.github.com/kade-robertson/9a6d35a88fe493efa0996db534c7e0d0

### Version/Commit

- RetroArch: 1.6.7 (a235c0b)

### Environment information

- OS: Windows 10 Home 64-bit
- Compiler: MinGW (6.3.0) 64-bit (this was pre-compiled directly from your website).

**Comment by RobLoach** [comment] 2017-09-26 04:15
Duplicate of https://github.com/libretro/RetroArch/issues/5411

**Comment by RobLoach** [comment] 2018-11-06 16:50
^

**Closed by RobLoach** 2018-11-06 16:50 UTC
