### ISSUE TITLE
Controller input not recognized on macOS 13 Ventura

### ISSUE THREAD

**Issue by TylerLoch** [libretro/RetroArch#14268] opened 2022-08-02 02:29 UTC
## Description

External controller (Bluetooth and USB tested) input is no longer recognized within RetroArch on development builds of macOS.

### Expected behavior

Upon connecting a controller, a status message about the controller appears within RetroArch. The controller can be selected in the Input config section, configured and used.

### Actual behavior

Upon connecting a controller, a status message about the controller appears within RetroArch. The controller can be selected in the Input config section, but cannot be configured or used. Inputs are not detected.

### Steps to reproduce the bug

1. Update to macOS Ventura. Tested on Beta 3 and Beta 4
2. Run a recent build of RetroArch. Tested latest Nightlies.
3. Connect external controller
4. Attempt to use controller.

### Bisect Results

Issue appears in versions of RetroArch starting with 1.9.8, which coincided with a major change in input management on macOS builds:
https://www.libretro.com/index.php/retroarch-1-9-8-released/
1.9.7 and below are not affected. Running in Rosetta does not seem to make a difference.

### Environment information

- OS: macOS Ventura Beta 4, M1 MacBook Pro

**Comment by LibretroAdmin** [comment] 2022-08-02 06:09
PRs welcome.

**Comment by EmeraldLoc** [comment] 2022-09-10 20:31
Can confirm this bug also happened on beta 2, it seems to be an issue with the new gamepad system. Launching retro arch via steam may or may not fix it, as steam input works fine.

**Comment by LibretroAdmin** [comment] 2022-09-11 08:47
@gblues has fixed an issue now that occured only on the latest version of macOS for DualShock3 -

https://github.com/libretro/RetroArch/commit/cdd39a63644e1a772c19c9aa6fdb0af21ddc00c5

Any other pads that remain non-working that used to work before on older macOS versions? Please report back.

**Comment by EmeraldLoc** [comment] 2022-09-11 19:48
I will confirm that the Nintendo pro controller also works

**Comment by LibretroAdmin** [comment] 2022-09-11 20:01
Switch pro controller or wiiu?

**Comment by TylerLoch** [comment] 2022-09-12 02:35
Both my HAC-042 Bluetooth SNES Controller and USB iBuffalo SNES Controller are now working as expected, though the oldest available nightly (8/30/2022) works as well, which may indicate the core issue was instead fixed by a later build of Ventura.

**Comment by EmeraldLoc** [comment] 2022-09-12 15:30
Switch controller works

**Comment by LibretroAdmin** [comment] 2022-10-04 22:35
@TylerLoch So can the issue be closed now? 1.11.1 works ?

**Comment by TylerLoch** [comment] 2022-10-05 02:05
Yes.

**Comment by LibretroAdmin** [comment] 2022-10-26 00:50
Confirmed that controller input still works on the final public Ventura release (both a DualShock 3 and DualSense work), so closing this.

**Closed by LibretroAdmin** 2022-10-26 00:50 UTC
Labels: platform: osx, prs welcome, input, input: hid

**Comment by shalfey4** [comment] 2023-01-19 22:39
I can confirm that the problem is still remains I'm using
- MacOS 13.1 Ventura
-  with switch Pro controller. 
- RetroArch version 1.14.0
When controller connected popup window appears that controller been connected, but there's no input detection.

**Comment by fooness** [comment] 2023-02-25 20:04
I can confirm that the problem still remains. Issue #13237 is probably related.

**Comment by LibretroAdmin** [comment] 2023-02-25 20:58
> I can confirm that the problem still remains. Issue #13237 is probably related.

What issue? Please be specific as to what it is you are referring to as an 'issue'.

If it is about Switch Pro controller not working with MFi, we can confirm that. DualShock4 and DualSense/DS5 pads do work through MFi though.

**Comment by Traace** [comment] 2023-05-20 22:39
Hi,
not sure if this fits here but...

I have a controller that is using dinput. When choosing „hid“ as controller driver in Retroarch the controller itself gets detected, but the buttons are not working (while attempting to remap). The .app has all permissions it needs to access the controller. The controller gets detected when testing in firefox browser, dolphin emulator or steam. All buttons work there, too. 

As a workaround I tried to use the „mfi“ driver but it doesn’t detect the controller at all.

Some Info about my Controller / System:
Controller Vendor ID: 0x3285
Controller Product ID: 0x0c03
Brand / Modell: Nacon GC100
Tested with latest Nightly Build from yesterday
MacOS: Ventura 13.4
SoC: M1 Ultra

Anything I can do on my side to assist fixing the issue?

**Comment by rereprep** [comment] 2023-05-30 20:55
Steam official controller doesn't work on retroarch steam version neither on hid nor on mfi setting. Steam controller works fine on steam interface.

Environment information

OS: macOS Ventura Beta 4, M1 MacBook Air

**Comment by shalfey4** [comment] 2023-10-22 20:27
> I can confirm that the problem is still remains I'm using
> 
> * MacOS 13.1 Ventura
> * with switch Pro controller.
> * RetroArch version 1.14.0
>   When controller connected popup window appears that controller been connected, but there's no input detection.

I tried it almost 1 year after. And controller support is still not functioning. I'm using MacOS 14.0 (23A344)

**Comment by Kimon91** [comment] 2023-12-24 15:59
> Hi, not sure if this fits here but...
> 
> I have a controller that is using dinput. When choosing „hid“ as controller driver in Retroarch the controller itself gets detected, but the buttons are not working (while attempting to remap). The .app has all permissions it needs to access the controller. The controller gets detected when testing in firefox browser, dolphin emulator or steam. All buttons work there, too.
> 
> As a workaround I tried to use the „mfi“ driver but it doesn’t detect the controller at all.
> 
> Some Info about my Controller / System: Controller Vendor ID: 0x3285 Controller Product ID: 0x0c03 Brand / Modell: Nacon GC100 MacOS: Ventura 13.4 SoC: M1 Ultra Retroarch Build: Latest Nightly
> 
> Anything I can do on my side to assist fixing the issue?

Hey, did you have any progress with that? I'm facing the same issue/

Logitech Dual Action 
Vendor: 046d
product: c216
OS 12.6.6 Monterey
