### ISSUE TITLE
Advanced Settings and Saving Crashes

### ISSUE THREAD

**Issue by tmsullivan333** [libretro/RetroArch#5095] opened 2017-06-22 23:41 UTC
## Description

When Show  Advanced Settings is turned on and then Saving setting is opened RetroArch Crashes

### Expected behavior

Saving Menu Opens up as normal

### Actual behavior

RetroArch Crashes

### Steps to reproduce the bug

1. User Interface > Show Advanced Settings > On
2. Enter Saving Settings

### Bisect Results

I noticed it on the nightly build for 6/21/17 and currently running the 6/22/17 build. Tested other builds still available and it appears to have started on 6/19/17.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [e7d623f] Build Date: Jun 22 2017

### Environment information

- OS: Windows 7 64bit

**Comment by bparker06** [comment] 2017-06-22 23:44
duplicate of #5091

**Closed by bparker06** 2017-06-22 23:44 UTC
