### ISSUE TITLE
[Feature Request] PS3/4 style Cheevo unlock messages? 

### ISSUE THREAD

**Issue by CyanPrime** [libretro/RetroArch#5022] opened 2017-06-04 13:46 UTC
Can we get PS3/4 style messages for Cheevos?

Currently they're yellow from the function "runloop_msg_queue_push" as seen here.

```
static void cheevos_test_cheevo_set(const cheevoset_t *set)
{
   settings_t *settings = config_get_ptr();
   cheevo_t *cheevo    = NULL;
   const cheevo_t *end = set->cheevos + set->count;
   int mode, valid;

   if (settings->bools.cheevos_hardcore_mode_enable)
      mode = CHEEVOS_ACTIVE_HARDCORE;
   else
      mode = CHEEVOS_ACTIVE_SOFTCORE;

   for (cheevo = set->cheevos; cheevo < end; cheevo++)
   {
      if (cheevo->active & mode)
      {
         valid = cheevos_test_cheevo(cheevo);

         if (valid && !cheevo->last)
         {
            char url[256];
            url[0] = '\0';

            cheevo->active &= ~mode;

            if (mode == CHEEVOS_ACTIVE_HARDCORE)
               cheevo->active &= ~CHEEVOS_ACTIVE_SOFTCORE;

            RARCH_LOG("CHEEVOS awarding cheevo %u: %s (%s).\n",
                  cheevo->id, cheevo->title, cheevo->description);

            runloop_msg_queue_push(cheevo->title, 0, 3 * 60, false);
            runloop_msg_queue_push(cheevo->description, 0, 5 * 60, false);

            cheevos_make_unlock_url(cheevo, url, sizeof(url));
            task_push_http_transfer(url, true, NULL, cheevos_unlocked, cheevo);
         }

         cheevo->last = valid;
      }
   }
}
```

Is there a way to write a UI Plugin that could change how "runloop_msg_queue_push" looks when it's displayed? If not, is there a way to make the messages more PS3/4 like? This could match the XMB's style.

Personally I'd prefer it to display the Cheevo Badge and Title more then the Title and Description.

**Comment by saftle** [comment] 2017-06-04 16:06
Duplicate of https://github.com/libretro/RetroArch/issues/3946?

**Comment by meleu** [comment] 2017-07-04 08:08
Yes, it's duplicated. I think this here can be closed.

**Closed** 2017-07-10 00:32 UTC
