### ISSUE TITLE
Box arts don't appear on Retroarch Windows 10 32-bit (in XMB)

### ISSUE THREAD

**Issue by FrostMage10** [libretro/RetroArch#12626] opened 2021-07-08 10:20 UTC
## Description
Box arts don't appear in Retroarch XMB but do appear in Ozone. But box arts appear when they when select is pressed and disappear once again on exiting select menu

### Expected behavior
Box arts to appear in the lower right hand corner 

### Actual behavior
Box arts don't appear. But they appear when select is pressed and disappear again when select menu is exitter

### Steps to reproduce the bug
1. Add games via scanning
2. Download Box arts
3. The box arts wont appear in 32bit Windows 10
4. Pressing select/rshift will make them appear but they will disappear on exiting 

### Version/Commit
-RetroArch: 1.9.6
-Supposedly also not working since 1.9.0 build...informed to me by bslenul#5766 in Retroarch discord server

### Environment information
- OS: Windows 10/32bit
- Compiler: .exe

### Image
![No Boxarts](https://user-images.githubusercontent.com/87124158/124905018-38f47280-e003-11eb-8a91-8f8441879266.png)
![Boxart but only with select](https://user-images.githubusercontent.com/87124158/124905008-3560eb80-e003-11eb-9ead-4170aaf503c7.png)

**Comment by bslenul** [comment] 2021-07-08 15:18
So I did some bisect for this, looks like thumbnails started to disappear with 2dc9616509fd0b8764158ea0e87b7ef11d8f366d , even when pressing Select to trigger the "No Information Available" popup they don't appear.

Then with 004d100ed8eb1ad75e6fdb8305c875c5dfce2721 thumbnails were still missing but they started to appear when pressing Select, however the feature included in that commit (fullscreen thumbnails) didn't work on the Windows 32bit version, and it's still not working on that version to this day, pressing Start/Space bar doesn't do anything.

Hopefully this will help finding the cause, also idk if this is a Windows 32bit exclusive bug or what but it doesn't happen on RA 32bit on my Android phone.

**Comment by jdgleaver** [comment] 2021-07-12 12:42
The root cause of this bug was incredibly strange and disturbing...

I believe it should be fixed by this:  #12644

I can only test on Linux, however - could someone please confirm that it solves the issue on Windows?

**Comment by bslenul** [comment] 2021-07-12 13:03
![image](https://user-images.githubusercontent.com/33353403/125290471-a1ec2b00-e320-11eb-86ec-a5d576c5e193.png)
![image](https://user-images.githubusercontent.com/33353403/125290515-ae708380-e320-11eb-8a10-fc7ac5dc6120.png)
![image](https://user-images.githubusercontent.com/33353403/125291600-df9d8380-e321-11eb-940c-c3bdfd6f43ea.png)

I'm on a 64bit machine but I built it for 32bit, seems to be working like a charm! 👍 Unfortunately I can't test on a real 32bit machine, but since I was able to reproduce OP original issues I guess it should be fine?

**Comment by jdgleaver** [comment] 2021-07-12 13:18
Thanks @bslenul! Yes, that should be all the confirmation we need :)

> edit: There's even a super smooth scrolling on items now! Before while scrolling it was just "jumping" from an item to another, now it's super smooth!

Yeah - the bug meant is was detecting a menu scale change on every frame. So it was doing a 'context reset' on every frame, which means recalculating dimensions, cancelling animations, reloading all images, etc. (so a lot of functionality was broken - and the performance hit was intense!)

**Comment by bslenul** [comment] 2021-07-12 13:29
So not only it will look better, but it will also perform better, that's awesome! Excellent work as usual 👍

**Closed** 2021-07-12 14:49 UTC
