### ISSUE TITLE
[Linux] Long loading times if Xbox One Controller is connected via bluetooth

### ISSUE THREAD

**Issue by iGom** [libretro/RetroArch#10408] opened 2020-04-06 02:43 UTC
## Description

Retroarch takes a long time, as well as games or thumbnails to load if Xbox One S Controller is connceted via bleutooth on Linux (enhanced retransmission mode within Bluetooth protocol needs to be disabled for Xbox1pad to work)

### Expected behavior

Normal loading times

### Actual behavior

Long loading times, thumbnails don't even load, I also noticed menu doesn't show battery charge level or shows 0% next to clock time)

### Steps to reproduce the bug

1. Disable the aforementioned Bluetooth mode using commend `$ sudo sh -c 'echo 1 > /sys/module/bluetooth/parameters/disable_ertm'`
2. Connect Xbox One S Controller via Bluetooth to laptop
3. Launch Retroarch and wait, then launch any core/game

### Version/Commit

- RetroArch: Stable 1.8.5 installed via PPA

### Environment information

- OS: Ubuntu Focal Fossa 20.04 (Lubuntu distro) 
Linux 5.4.0-22-generic x86_64

[http://dpaste.com/08264DR](url)

**Comment by iGom** [comment] 2020-04-06 03:07
I reproduced it with other bluetooth controllers and the problem does not occur

**Comment by prurigro** [comment] 2020-04-15 05:12
It does occur for me with an 8bitdo controller in xbox bluetooth mode.

**Comment by Sanaki** [comment] 2020-04-15 06:33
Same here with the 8bitdo SN30 Pro+ in xinput mode on x86_64 Linux.

**Comment by goodjaerb** [comment] 2020-04-16 01:47
I just ran into this issue today with my Xbox One S bluetooth controller. I know it use to work just fine. I thought retroarch was just frozen but after reading the information here I waited a minute or so and sure enough the emulator started. But did anyone else have this issue: the controller detected as "Xbox Wireless Controller" which is slightly off, it should be "Xbox One S Controller" or something like that more specific. The autoconfig wasn't quite right as it should be I believe because it wasn't detected properly.

Beside that (possibly separate issue?) if I plug the Xbox One S controller in with USB it detects fine and the autoconfig loads but it plain doesn't work. No response from any buttons.

**Comment by otonoton** [comment] 2020-04-24 15:02
Same issue here with 8bitdo SN30 Pro on Ubuntu 18.04. If the gamepad is connected before RA starts, it takes somewhere around 30 seconds to start up, and the same delay happens again every time content is loaded or closed. GDB seemed to suggest there was some kind of hang happening in a udev function but I didn't write it down. The same pad on my raspberry pi does not have this issue. Also if I wait until the game is loaded before turning on the pad, then there is no delay... but then closing content will have a delay if I don't turn off the pad first.

**Comment by Sanaki** [comment] 2020-05-13 13:16
Just got an 8bitdo m30, same issue present. I'm now thinking this is due to the attempt to check and display controller battery. I managed to get this error once when it hung trying to end the process by turning off the controller (to get it to finish closing).
`Failed to open /sys/class/power_supply/hid-e4:17:d8:58:86:7f-battery/capacity: No such file or directory`
Upon attempting to cat that file myself, the terminal hung up for about ten seconds before returning `cat: '/sys/class/power_supply/hid-e4:17:d8:58:86:7f-battery/capacity': No data available`

**Comment by goodjaerb** [comment] 2020-05-13 14:20
@Sanaki I had the same idea, but you can disable the battery display and it still happens. Unless there are still checks happening int he background. I believe those "failed to opens" ceased when I disabled the battery display but the bluetooth lag remained. It's also strange that when I posted before, my M30's worked fine, but now they behave just as the xbox controller. It seems tied to the bluetooth adapter as I can unplug it while it's "lagging" and I believe the core immediately resumes. Then I can plug it in and it works fine. I would have to do more tests.

I've considered making a second issue because the autoconfig's for my bluetooth devices appear all out of whack but I don't know if it is related to this or not.

**Comment by Sanaki** [comment] 2020-05-13 14:30
Yeah, it's still running the check in the background. I'm fairly confident this is the issue. I could try just replacing it with a spoof file and rebuilding to verify. As for the autoconfig, I just learned the hard way that the m30 in particular screws up the button layout if you update from 1.10 to 1.13 or 1.14. I'm going to downgrade mine later.

**Comment by gouchi** [comment] 2020-05-13 20:59
You may start [here](https://github.com/libretro/RetroArch/blob/master/frontend/drivers/platform_unix.c#L1139) for power state checking.

**Comment by Sanaki** [comment] 2020-05-16 18:40
Changing joypad driver from udev to linuxraw remedies this issue. Not quite sure what that means for how to fix it while still using udev though.

**Comment by joshuaseltzer** [comment] 2020-05-19 23:01
This issue seems very similar and related to a long-time issue I've been dealing with on MacOS (#3660).  About a year ago, I attempted to set up a development environment to debug this but never was able to figure it out unfortunately.

The symptoms I face are almost identical to what people are experiencing here on Linux.  Personally I'm using a Dualshock 3 via Bluetooth on MacOS Mojave 10.14.6.  It all began when upgrading to macOS Sierra years ago.

**Comment by Mangus78** [comment] 2020-05-28 08:42
I've noticed that turning OFF "show battery level" under settings>user interface>views, resolved the issue and now there are no more lag or dalay doing whatsoever. So it seems to be definitely a battery check issue.
Ubuntu 20.04/retroarch 1.8.8

**Comment by joshuaseltzer** [comment] 2020-05-28 11:08
@Mangus78 I was hopeful that this would fix the controller lag issue on macOS, but it didn't change anything.

I timed it on macOS, and it appears that the lag/hang is for 15 seconds.  It seems as though this issue is unrelated on Mac (I believe it's a rumble-related bug, not battery level).

**Comment by goodjaerb** [comment] 2020-05-28 14:00
@Mangus78 I'll have to try again on 1.8.8. Turning that feature off before did not resolve anything for me. Same OS.

**Comment by Sanaki** [comment] 2020-05-28 22:02
There was an update today for the SF30 Pro+ involving battery. While it didn't fix the problem at all, the description has made me think the freeze from udev attempting to read the battery is related to some special method involved in the xbox game bar battery reporting that goes against the standard Bluetooth battery spec.

**Comment by denilsonsa** [comment] 2020-08-06 08:14
I can confirm Sanaki findings. I'm using Raspberry Pi 4 running Gentoo arm64.

Using `strace -f -o strace.log retroarch`, I can see retroarch opening that path about **four times during startup**. And that path takes about 10 seconds to return any data, which means at least **40 extra seconds waiting for retroarch to load**.

Not only the startup gets slower, but **loading thumbnail images** (inside playlists) **also gets slower/delayed** while my 8BitDo Bluetooth controller is connected in X-input mode (turn on the controller by holding X+Start). Switching the controller to Android/Dinput mode (turning it on by holding B+Start) (and re-pairing it) solves the issue, because there will be no `power_supply` path in `/sys/` anymore.

Regardless of the bluetooth controller, RetroArch is still reading the `power_supply/*battery/*` path from my Wireless Logitech USB keyboard (it has a dongle connected through USB). I don't know why RetroArch wants to read from it.

---

Suggestions:

1. RetroArch could stop reading such data.
2. RetroArch should try reading that data in non-blocking mode. Of course this is easier said than done, as it means converting a simple synchronous call into async code. However, the benefit to the end-user is enormous.

---

Other people are also being affected by this issue. On a quick search, I found a few reddit posts:

* https://old.reddit.com/r/RetroPie/comments/95x509/slow_loading_times/ea0eiwi/
* https://old.reddit.com/r/RetroPie/comments/9kbqds/extremely_long_load_times_when_using_8bitdo/
* https://old.reddit.com/r/RetroPie/comments/d057i5/8bitdo_sn30_pro_slow_starting_emulators/

---

Some investigation:

```
cd /sys/devices/platform/soc/fe201000.serial/tty/ttyAMA0/hci0/hci0:11/*/power_supply/hid-*-battery
for a in capacity model_name  online  present scope status type uevent ; do time grep -H '' $a ; done
```

* `capacity` took 5.2 seconds (not used by RetroArch)
* `status` took 5.2 seconds (not used by RetroArch)
* `uevent` took 10.2 seconds (read multiple times by RetroArch)

**Comment by MrZammler** [comment] 2020-08-06 08:21
Hi, I'm also affected by this bug. I'm on Gentoo on x86_64, and it seems that by using the xpadneo driver there's no more blocking while using retroarch. (The same driver also enables rumble in Steam for the SN30+ Pro). There's an ebuild for the driver in vortex overlay.

**Comment by Sanaki** [comment] 2020-08-06 09:43
Tested xpadneo out. While it does resolve the issue, it has some of its own issues, such as forcing the Nintendo button layout for 8bitdo controllers and failing to expose the guide button as a button.

**Comment by RBertoCases** [comment] 2021-01-21 20:28
SN30 Pro+ user here. I tried using dinput mode on the controller. It works but didn't care for the button layout changes. So tried a wired connection in xinput mode and can confirm that resolves the issue on my end.

Tested on Pop!_OS 20.10 x86_64, Retroarch 1.9.0

**Comment by gitowiec** [comment] 2021-02-06 00:35
> xpadneo driver

How can I use and configure the xpadneo driver with RetroArch? Please elaborate

**Comment by Sanaki** [comment] 2021-02-06 00:46
You install the driver. It automatically handles xinput controllers over bluetooth. That's it. Though I need to look into some changes, I'm not sure how you're supposed to fix it forcing Nintendo layout on 8bitdo controllers now, which is irritating enough to make me never want to use it.
https://github.com/atar-axis/xpadneo/

**Comment by gitowiec** [comment] 2021-02-06 01:11
@Sanaki thank you, I just choose 2 (no trigger rumble) to pass anything else than 32. Can I pass 0 to disable everything? Zero 2 does not have rumble, and I don't know what other 1,4,8 options mean. Or should I choose 16?

**Comment by Sanaki** [comment] 2021-02-06 01:15
You should be able to just pass 0 if need be.

**Comment by chinarut** [comment] 2021-02-19 10:39
ah - see I'm not alone here.  Experiencing this issue on Ubuntu 20.04.2 LTS w an 8Bitdo Lite controller.

I did not have this issue a few weeks ago and the only major change I see is an update to 20.04.2.

**Comment by AlexFolland** [comment] 2021-03-23 00:08
This seems to be a duplicate of #8510.  However, this has more information, so that one should probably be closed instead.

That being said, I am experiencing this right now with the latest git build using an 8Bitdo SN30 Pro.  Here are some facts.

- I'm running Manjaro 21.0 stable with XFCE and using the `retroarch-git` AUR package.
- The gamepad works, but the only problem is a long delay on a black screen every time I start RetroArch, close content, or start content.
- I'm using the input driver in RetroArch called `x`.
- I've timed the black screen delay multiple times with a stopwatch and it always lasts 25 seconds.
- With the gamepad not connected at all, there's no delay starting RetroArch.  It starts instantly, like in the next frame after I click the launcher in my XFCE panel.
- There is no delay with a PS4 gamepad connected instead.  This is only happening with the 8bitdo SN30 Pro.
- The 8bitdo SN30 Pro is connected using the "Windows" connection mode, which requires pairing it after starting it with Start+Y.
- While this is happening, RetroArch's CPU and GPU usage is insignificant.
- I am able and willing to gather any requested logs for this.

**Comment by nadenislamarre** [comment] 2021-04-22 15:41
if needed, i fixed it today on batocera.linux (https://github.com/batocera-linux/batocera.linux/commit/ce894a8e7730f5c0a67a507e50489ffb6614ca01)
(at least, i applied a workaround to disable battery at linux level)
because of the battery long (and incorrect) answer from the firmware, udev takes long time to applies rules (and then declare the pad as a joystick). 8bitdo should give me a firmware dev contact to work on the subject.
depending on the pad and configuration, retroarch reads the battery information too at boot and it takes long too, but it is not the ra fault.

**Comment by joshuaseltzer** [comment] 2021-04-22 15:49
@nadenislamarre this is great. I’m not super familiar with this code base, but it looks like all of the patches are specific to Linux-based builds. I might try to apply this patch to the macOS version, but then I’d also need to setup an environment to build a release.

**Comment by nadenislamarre** [comment] 2021-04-22 15:56
this is the linux hid driver. you cannot apply on mac os x. and i guess you've not the code for that driver open on osx.
this is to prevent linux to get battery information about the pad.

**Comment by joshuaseltzer** [comment] 2021-04-22 17:57
@nadenislamarre yeah I was hoping a similar patch could be applied to the controller logic/code on macOS since it experiences the same exact lockups.

**Comment by nadenislamarre** [comment] 2021-04-22 18:02
yes, because it is a firmware issue i think, it is not related to linux nor mac os x i think. i will see if i can do something to help to fix at firmware level. i"m currently trying to get a contact.

**Comment by obrie** [comment] 2021-04-25 00:25
Can this be enabled through the `usbhid.quirks` kernel option?  e.g. In the RPi's /boot/config.txt, I was thinking something along the lines of:

```
usbhid.quirks=0x045e:0x02e0:0x40
```

Happy to test, but wanted to see if you knew off-hand.

**Comment by gouchi** [comment] 2021-06-01 14:01
Can you make a test with this [patch](https://patch-diff.githubusercontent.com/raw/libretro/RetroArch/pull/12469.patch) if it is improving the situation ?

Thank you.

**Comment by tomgar** [comment] 2021-07-22 22:39
@obrie I guess the usbhid quirks option is for usb connections and not bluetooth ones which is the one having the issue at hand.

@nadenislamarre did someone from 8bitdo contact you about this? Thanks!

**Comment by nadenislamarre** [comment] 2021-07-23 05:55
not technical peopl

**Comment by gouchi** [comment] 2021-07-23 11:53
So you are still having the issue in RA 1.9.6 ?  (The [patch](https://patch-diff.githubusercontent.com/raw/libretro/RetroArch/pull/12469.patch) is included)

**Comment by Sanaki** [comment] 2021-07-23 12:36
I actually forgot about testing this, sorry about that. Seems I can't properly validate this, since the above `cat` commands actually return instantly now. I'm not sure when this changed or why, I assume it was a kernel update that did so. Hopefully someone else can chime in.

**Comment by tomgar** [comment] 2021-07-23 16:15
@gouchi just checked with RA 1.9.6 and yes, the issue is still there.

**Comment by gouchi** [comment] 2021-09-06 21:41
@tomgar Are you still getting this issue with current stable RA 1.9.9 ?

**Comment by tomgar** [comment] 2021-09-06 22:35
@gouchi I can confirm that the issue is gone for Linux's udev input driver starting from RA 1.9.8.

**Comment by joshuaseltzer** [comment] 2021-09-06 23:48
> Are you still getting this issue with current stable RA 1.9.9 ?

Working great for me on both 1.9.8 and 1.9.9 on macOS Mojave 10.14.6 and a DualShock 3 (Bluetooth).

**Comment by AlexFolland** [comment] 2021-09-07 01:50
A DualShock 3 gamepad is not an Xbox One gamepad.

**Comment by gouchi** [comment] 2021-09-07 11:47
@tomgar Thank you for the feedback.

@iGom Please close this issue.

**Comment by gouchi** [comment] 2022-09-06 15:54
@LibretroAdmin I think this issue can be close because of [tomgar's feedback](https://github.com/libretro/RetroArch/issues/10408#issuecomment-913875376). Thank you.

**Closed** 2022-09-06 19:24 UTC
Labels: platform: linux, bug: input, bluetooth, xbox one controller
