### ISSUE TITLE
udev input driver fails silently when permission denied

### ISSUE THREAD

**Issue by ewtoombs** [libretro/RetroArch#9976] opened 2020-01-09 20:32 UTC
### To reproduce

0. Start as a regular user without permission to access devices nodes or whatever.
1. Config > Drivers > Input > udev
2. Restart
3. Try navigating with the keyboard.

### Expected behaviour

Everything explodes with an error saying, "Retroarch has no access to any inputs: read failed on /dev/input/whatever! permission denied!"

### Actual behaviour

The interface loads and everything looks fine, only the controls aren't working.

### Versions
```
$ pacman -Qi retroarch xorg-server | egrep 'Name|Version'
Name            : retroarch
Version         : 1.8.1-1
Name            : xorg-server
Version         : 1.20.6-3
$ uname -s -r -v -m -o
Linux 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux
```

**Comment by gouchi** [comment] 2021-09-01 10:47
Hi,

Please close this issue as it is duplicate of #5033.

Thank you.

**Closed** 2021-09-10 17:23 UTC
