### ISSUE TITLE
Retroarch 1.4 and 1.4.1 not working on Intel HD Graphics and Intel HD Graphics 3000

### ISSUE THREAD

**Issue by grakist** [libretro/RetroArch#4738] opened 2017-03-09 13:12 UTC
Retroarch 1.4.0+ crashes on some notebooks with Intel HD Graphics.
Message: Retroarch stopped working...

I tried multiple versions. 1.4.0, 1.4.1 and the nightlies. They all crash. Retroarch 1.3.6 works without problems.

I tried multiple laptops and multiple RetroArch versions and multiple versions of the Graphics driver.

The problems seems to be the Intel HD Graphics and Intel HD Graphics 3000 on Retroarch 1.4.0 and higher.

Below I list the systems on which it doesn't run. Furter down the list I list the systems on which it does work.

CRASH:
HP 250
Retroarch 1.4.1 64 bits
intel hd graphics
driver: intel, 12/12/12, 9.17.10.2932
DEV_0106&SUBSYS_1854103C
windows 10, 64 bits, version 1607, build 14393.693

CRASH:
HP 250
Retroarch 1.4.1 64 bits
intel hd graphics
driver: intel, 27/05/15, 9.17.10.4229
DEV_0106&SUBSYS_1854103C
windows 10, 64 bits, version 1607, build 14393.693

CRASH:
HP 250
Retroarch nightly 07/03/2017 64 bits
intel hd graphics
driver: intel, 27/05/15, 9.17.10.4229
DEV_0106&SUBSYS_1854103C
windows 10, 64 bits, version 1607, build 14393.693

CRASH:
HP 250
Retroarch 1.4.0 64 bits
intel hd graphics
driver: intel, 27/05/15, 9.17.10.4229
DEV_0106&SUBSYS_1854103C
windows 10, 64 bits, version 1607, build 14393.693

CRASH:
HP Elitebook 8460P
Retroarch 1.4.1 32 bits
Intel HD Graphics 3000
DEV_0126&SUBSYS_161C103C
driver: intel, 27/05/15, version 9.17.10.4229
Windows 10, 32 bits, version 1607, build 14393.693

NO PROBLEMS:
HP 250
Retroarch 1.3.6 64 bits
intel hd graphics
driver: intel, 27/05/15, 9.17.10.4229
DEV_0106&SUBSYS_1854103C
windows 10, 64 bits, version 1607, build 14393.693

NO PROBLEMS:
dell latitude E6430
Retroarch 1.4.1 64 bits
intel hd graphics 4000
driver: intel, 10/07/15, 10.18.10.4252
DEV_0166&SUBSYS_05341028
windows 10, 64 bits, version 1511, build 10586.0

NO PROBLEMS:
dell latitude E6430
Retroarch 1.4.1 64 bits
intel hd graphics 4000
driver: intel, 04/04/16, 10.18.10.4425
DEV_0166&SUBSYS_05341028
windows 10, 64 bits, version 1607, build 14393.693

NO PROBLEMS:
HP 17-x030nd
Retroarch 1.4.1 64 bits
Intel HD Graphics 520
driver: intel, 24/10/16, version 21.20.16.4542
DEV_1916&SUBSYS_8207103C
Windwos 10, 64 bits, version 1607, build 14393.693

**Comment by bparker06** [comment] 2017-03-09 13:40
Duplicate of #4580. It appears to be an HD3000 driver bug specific to Windows 10. Windows 7 is not effected.

**Comment by bparker06** [comment] 2017-03-09 13:57
Other applications are having similar issues too: https://bugreports.qt.io/browse/QTBUG-42240

**Closed** 2017-03-14 17:21 UTC
Labels: invalid: duplicate
