### ISSUE TITLE
[Android] Problems with analog sticks in ARCHOS Gamepad

### ISSUE THREAD

**Issue by Quickgold74** [libretro/RetroArch#2473] opened 2015-11-26 20:01 UTC
I know that this issue is old and it has already been reported in the forums here: http://goo.gl/u5U4Yi and here: http://goo.gl/4r3Cn1 , well, this issue affects both models Archos Gamepad 1 and 2, you can setup all buttons and d-pad but not the analog sticks (both works fine under other android emulators), d-pad and buttons are recognized like joy_key and analog sticks are recognized like joystick (RA only takes the joy_key)

**Comment by Quickgold74** [comment] 2015-12-09 05:57
Hi, with the last nightly both analog sticks in my ARCHOS GAMEPAD works fine, thanks guys keep the nice job!

**Comment by fr500** [comment] 2015-12-09 06:10
Uhhh the fix isn't merged yet

**Comment by Quickgold74** [comment] 2015-12-09 06:14
it works for me I can set the analogs left and right, works fine with the RA menu too

**Comment by Quickgold74** [comment] 2015-12-10 01:26
Thanks and keep the nice job!, it works fine in both models, there is a little input lag in Archos Gamepad 1 using the analog for example in core FBA with a demanding game (in ARCHOS gamepad 2 all works smooth)

**Comment by fr500** [comment] 2015-12-10 01:29
btw, in the current nightlies it should print ARCHOS Gamepad instead of joystick or joy_key, can you verify?

**Closed** 2015-12-10 01:29 UTC
Labels: bug

**Comment by Quickgold74** [comment] 2015-12-10 01:35
Yes the message in the screen is "Archos Gamepad configured in port 0"

**Comment by fr500** [comment] 2015-12-10 01:44
cool, thanks, I guess the back button still doesn't work as intended (it's not part of the controller) I could make it part of the controller too if you can give me the name of the device.

**Comment by Quickgold74** [comment] 2015-12-10 02:01
Well you can assign menu toggle to the back button (4) and it works for me now ...in some applications or other emulators they indentify the device with the name of .....Back......

**Comment by fr500** [comment] 2015-12-10 02:10
I didn't mean that, when you press back the yellow letters should show up again and show a device name, what-s the name?

**Comment by Quickgold74** [comment] 2015-12-10 02:15
it says..... Virtual (0/0) not configured

**Comment by fr500** [comment] 2015-12-10 02:24
thanks, I'll try to make it part of the same device so it doesn't keep rebinding controllers back and forth.
Can you make me a favor, can you write down the bindings you have for the archos gamepad so I can bundle an autoconf?

Also another question, the first time you hit a button you get a message right, after that, when you touch the analogs, do you get the message again?

**Comment by Quickgold74** [comment] 2015-12-10 02:31
When you press the joy_key buttons you get the message the first time, after that, you don't see the message when you touch the analog, the same thing happend when your touch the analog for first time, you don't see the message when you press the buttons.

**Comment by Quickgold74** [comment] 2015-12-10 02:43
The file under the autoconfig folder with the name of Archos_Gamepad.cfg it doesn't works anymore the new file should rename like ARCHOS GamePad.cfg (User 1 Save Autoconfig make the file with that name) now the binds:

input_driver = "android"
input_device = "ARCHOS GamePad"
input_b_btn = "96"
input_y_btn = "99"
input_select_btn = "109"
input_start_btn = "108"
input_up_btn = "19"
input_down_btn = "20"
input_left_btn = "21"
input_right_btn = "22"
input_a_btn = "97"
input_x_btn = "100"
input_l_btn = "102"
input_r_btn = "103"
input_l2_btn = "104"
input_r2_btn = "105"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"

**Comment by fr500** [comment] 2015-12-10 03:09
thanks so everything is working as intended

**Comment by Quickgold74** [comment] 2015-12-10 05:40
Thanks to you and RA team!
