### ISSUE TITLE
Windows 10 64bit - Crash on Fullscreen

### ISSUE THREAD

**Issue by cirolaferrara** [libretro/RetroArch#4899] opened 2017-05-10 18:08 UTC
Windows 10 68bit - Crash on Fullscreen

1. Hardware: Beelink Z83-II Mini PC x5-Z8350 Intel Atom
2. Software: Windows 10 64bit, DirectX 9

This is the log: https://pastebin.com/YuYdAXq4

**Comment by retro-wertz** [comment] 2017-05-10 23:53
start by trying to update video drivers to official windows 10 supported
ones. Intel HD 4000 has probably a newer one than the one you have

https://downloadcenter.intel.com/download/25977/Intel-Graphics-Driver-for-Windows-10-and-Windows-7-8-1-15-33-?product=81499

**Comment by cirolaferrara** [comment] 2017-05-11 09:37
After update drivers at URL https://downloadcenter.intel.com/download/25176/Intel-HD-Graphics-Production-Driver-for-Windows-10-64-bit-N-Series- (Processor Graphics: Intel HD Graphics 400 and not 4000), problem persists.

Now I have win64_154001.exe driver

This is the log: https://pastebin.com/AN4qx0CS

**Comment by retro-wertz** [comment] 2017-05-11 12:09
i see lots of glsl warning, somebody else should be able to tell how RA
enumerates gl stuff, especially on win10..

try using d3d for retroarch video drivers if it does something different..

**Comment by cirolaferrara** [comment] 2017-05-11 14:13
With d3d I have black screen

**Comment by bparker06** [comment] 2017-05-11 14:41
Possible duplicate of #4839

**Closed** 2017-05-11 21:50 UTC
