### ISSUE TITLE
The menu text  is Garbled on japanese.

### ISSUE THREAD

**Issue by asm256** [libretro/RetroArch#4761] opened 2017-03-17 00:30 UTC
## Description

The menu text for japanese is garbled.

It seemes...
rc encoding: CP932
windres expeted encoding: utf-8

### Expected behavior

![image](https://cloud.githubusercontent.com/assets/660363/24023781/e037108e-0af1-11e7-949b-3cd1e3d2aea0.png)
(I used Resource Hacker)

### Actual behavior

![01c01ed50234d58f3377830ca63feca6](https://cloud.githubusercontent.com/assets/660363/24023582/904508de-0af0-11e7-8d45-40a23af9df42.png)

### Steps to reproduce the bug

Start with Japanese environment windows 7.

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  1.5.0 git:137f8df0570aa351ee724ebe3edd62499fc1f423
### Environment information

- OS: Windows7
- I got it from https://buildbot.libretro.com/stable/1.5.0/windows/x86_64/

**Comment by bparker06** [comment] 2017-03-17 02:16
Hi @asm256,

CP932 is actually the correct encoding as RetroArch is not technically a Unicode app on Windows, so I cannot accept the pull request. We maintain compatibility with very old versions of Windows that don't have proper Unicode support, and the issue you're seeing is not a utf8 problem but an unresolved bug we've noticed with msys2/mingw builds made by our buildbot. You'll notice that if you compile RetroArch yourself, it works fine. Also the alternative MSVC builds we have available do not exhibit this problem.

Could you try either compiling yourself with msys2/mingw or using the MSVC build?

**Comment by bparker06** [comment] 2017-09-15 18:34
duplicate of #4536

**Closed by bparker06** 2017-09-15 18:34 UTC
