### ISSUE TITLE
[Android]Request: Change default directory for save/savestate

### ISSUE THREAD

**Issue by Raijinili** [libretro/RetroArch#1328] opened 2015-01-08 23:38 UTC
The current default is in the app's folder, which, as far as I know, is inaccessible to a normal (non-root) user, as well as being deleted when the app is deleted. This can cause issues if such a user enables the use of the custom folder without changing the custom folder.

Additionally, the current PCSX with a BIOS always uses the specified folder instead of the ROM's folder, despite the settings. So this will stop cores from accidentally writing to a user-inaccessible folder.

**Comment by Raijinili** [comment] 2015-01-09 17:07
Seems like the default folder for saving configs is also in the app's folder, so saving configs in the green menus will result in configs that can't be loaded? I can't seem to get at the saved configs from within RetroArch, since it starts looking for them in / and can't get to its data folder from there. Maybe I'm severely misunderstanding something.

**Comment by micechal** [comment] 2015-01-10 08:16
You can manually change the save file / save state directory and that works fine, so I don't think it's much of an issue.
I can confirm the second one though. Without root, one can not list the contents of `/data/` directory, which makes it impossible to load previously saved configurations.
The path used for storing these can still be changed though, so it definitely is usable with non-default settings.

**Comment by Raijinili** [comment] 2015-01-10 12:11
Default is harmful to nonroot user (unless I misunderstand Android): if you don't know that you have to change your default, you will lose your saves upon changing the folder, or upgrading OS. You also can't back up saves. And if you try to set the folder, you can't change it back to the original, so 

It is surprising, and is irreversible (for nonroot) once you learn about it. Isn't that enough reason to call it an issue?

**Comment by Qard** [comment] 2015-01-14 05:17
It seems that, on first run, it looks in the ROM path for state/save files. Upon editing any configs in the GUI, it changes to the /data/... path. If I try to change it, it just resets back to the data directory. :(

**Comment by eadmaster** [comment] 2015-07-14 20:54
I've just installed the latest v1.2 from the Play store and i'm getting the behavior described (here)[https://github.com/libretro/RetroArch/issues/1656].
Actually i don't mind about the default paths, but why resetting the paths when the Android UI is started?

**Comment by Raijinili** [comment] 2015-07-15 08:06
Are you asking why it happens or what's it good for? It is not good, and
the issue you reference points out that the Android UI will be removed
(invalidating its bugs), and how to deal with the change in folders.

As for why, if I remember correctly, the Android UI loads its own config
when launching RetroArch, and it doesn't ever read back RetroArch's config.
So for the settings that the Android UI has, it pretty much thinks it owns
them.

**Comment by fr500** [comment] 2015-07-15 13:51
That's not true anymore the Android ui doesn't do anything to the settings.

Most of these issues are fixed now Andrea.  Just make sure you quit
retroarch cleanly

**Comment by eadmaster** [comment] 2015-07-15 15:03
Basically i would like to have the savepath set as the "content dir".
I've found i can set this in the RGUI by pressing Start after selecting savepath in the Directory settings menu. It actually works, but when i exit RA and start it again the savepath goes back to its default value.
In the Android GUI i can only set a custom path, not the content dir.

**Comment by fr500** [comment] 2015-07-15 15:08
That is not like that anymore.  First,  there is no Android settings.  Second the default is now content dir unless RA can't write to the internal SD AND to the folder returned. By getExternalFiles for some reason.  Only in that case it defaults to the app dir.

**Comment by fr500** [comment] 2015-10-09 19:23
Should be fixed by now

**Closed** 2015-10-09 19:23 UTC

**Comment by Aeroxia** [comment] 2017-01-02 02:08
I just lost hours due to this "non-issue". There's no way I should have known I had to change the default directories for saves/states, and there's no way to root my phone without wiping it clean apparently (Galaxy S7). I simply cannot access my savestates, and it didn't save the saves on exit, so there's nothing I can do but start over from hours ago.

Calling this a non-issue is legitimately angering.

**Comment by fr500** [comment] 2017-01-02 03:48
The default is not the internal APP dir, it's the rom folder so what you way about root makes no sense whatsoever.
Only if RA can't write to the internal user storage it defaults to the internal dir. 
Basically if RA can save settings it can save states as long as they are in the internal SD.

**Comment by Aeroxia** [comment] 2017-01-02 06:18
The game defaulted to the content database directory (or changed somehow by normal usage), which is internal, and I can save states but not load them. It fails to load, I cannot access them even to just copy them out by file explorers or adb or anything else it seems. And I know it's there now, because I did a convoluted thing with adb backup and extracted it, and got the savestates, but they didn't work on my desktop version.

**Comment by fr500** [comment] 2017-01-02 08:08
Content Database or content dir?

**Comment by Aeroxia** [comment] 2017-01-02 10:38
Sorry, it ate the \<>. It said \<Content dir>, and the only thing I could find with that word was content database directory. I don't know how to put it back, so I set it to content database (/data/user/0/com.retroarch/database/rdb) after the fact and made things extra confusing for myself. (But this was after I had issues with failing loading state.)
