### ISSUE TITLE
N64 Cores not working at all in web player

### ISSUE THREAD

**Issue by NovaKatsu** [libretro/RetroArch#8387] opened 2019-03-01 16:55 UTC
Mupen64 and Glupe64 dont work at all. They dont even load up... please help. o-O

**Comment by orbea** [comment] 2019-03-01 17:11
There is an issue template for a reason....

**Comment by NovaKatsu** [comment] 2019-03-01 17:16
right, sorry.

**Comment by orbea** [comment] 2019-03-02 00:55
I guess I will close this as a duplicate of the newer https://github.com/libretro/RetroArch/issues/8392.

**Closed by orbea** 2019-03-02 00:55 UTC
Labels: followup: needs info or confirmation, platform: emscripten
