### ISSUE TITLE
Thumbnails wont match/display if the symbol "&" is present in title

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8724] opened 2019-05-08 14:34 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Thumbnails wont match if rom includes a "&"

### Expected behavior
Media to match the same as it does with any other title. 

### Actual behavior
All media matches properly, apart from anything including a "&" in the name/label

### Steps to reproduce the bug
1. create a playlist
2. ensure media is named 1:1 with the rom(s) including titles with a "&" aka "Adventures of Batman & Robin, The (USA)" and placed in the proper Named_Boxarts folder
3. Open RA, and scroll down the associated playlist, noting every game with a & does not display its thumbnail.

### Bisect Results
unfortunately i couldnt say, I just began scraping proper media and creating my playlists manually

### Version/Commit

- RetroArch: 1.76/ad7da9736a

### Environment information

- OS:  Windows 10

**Comment by klepp0906** [comment] 2019-05-08 15:11
just to update
I tried on 1.77 -same behavior.
also right clicked and downloaded the thumbnail manually through RA's scraper.  It picked up with the same name, including the & symbol - yet worked.  

so it has something to do with that symbol tied to manual playlist creation.  Hopefully that helps.

**Comment by orbea** [comment] 2019-05-08 15:52
I'm going to close this as a duplicate of issue https://github.com/libretro/RetroArch/issues/8700. Please continue this discussion there and read the already existing discussion for more details on this issue, thanks!

**Comment by klepp0906** [comment] 2019-05-08 15:52
aaaaand looks like this is a known limitation which is documented and i didnt pick up on it.  So sorry for that!  Changing & to _ is necessary but only in the image file itself. 

hopefully I dont run up against too many playlists with games including &, alotta renaming :P

**Closed by orbea** 2019-05-08 15:52 UTC
Labels: invalid: duplicate
