### ISSUE TITLE
[Android] Add .nomedia file in thumbnails directory

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#13849] opened 2022-04-15 20:11 UTC
Android lists all images from the thumbnails directory as media.

![3oa6d0srzmt81](https://user-images.githubusercontent.com/25086/163627310-7e761c7d-38d8-4646-a601-b2d955fdd6d0.jpg)

Reported by foxferreira64 over at https://www.reddit.com/r/RetroArch/comments/u41qrj/hi_is_there_any_way_for_boxarts_to_not_show_on/i4tnbrc/?context=3

### Expected behavior

Thumbnails shouldn't be considered media in Android

### Actual behavior

Thumbnails are listed in media of android

### Steps to reproduce the bug

1. Run Android build
2. Download thumbnails
3. Load up the photos app
4. See that thumbnails are indexed

### Suggested Fix

On the Android build, when writing to the thumbnails directory, add an empty `.nomedia` file in the thumbnails root directory.

### Version/Commit

- RetroArch: 1.10.3

### Environment information

- OS: Android
- Compiler: -

**Comment by Jamiras** [comment] 2023-01-07 01:09
duplicate of #12067?

**Closed** 2023-01-07 08:00 UTC
Labels: platform: android, thumbnails

**Comment by LibretroAdmin** [comment] 2023-01-07 09:59
Was this fixed?

**Comment by hizzlekizzle** [comment] 2023-01-07 14:49
not fixed, just a dupe of an existing issue.
