### ISSUE TITLE
Controllers Not Reusing Ports

### ISSUE THREAD

**Issue by DanilaPenzin** [libretro/RetroArch#12561] opened 2021-06-23 11:08 UTC
Device: Lenovo TB3-710I
Controller: Ritmix GP-030BTN
Device config name: Amazon Fire Game Controller.cfg
Version Retroarch Git: 81075aa 

When I am using this controller via Bluetooth to the Lenovo, if it disconnects for any reason while RetroArch is running then reconnects, it's added as a second port instead of reconnecting to port 1. This leaves RetroArch in an unusable state requiring a force close and relaunch since the controller in port 1 is dead and no way to reconnect it.

**Comment by Arjan219** [comment] 2021-06-23 15:30
Device: Linux Mint 20 (Ulyana)
Controller: Wireless XBox 360 controller
RetroArch: v1.7.3 b2ceb50
Compiler: GCC (9.2.1) 64-bitBuilt: Feb 11 2020

This happens for me too.
I can navigate the main menu fine, but the moment i load content the controller reconnects from port #0 to port #1, making it unusable.
A workaround i found is to remove the controller's battery, put it back in, and turn it back on: RetroArch then correctly connects it to port #0. The problem then no longer occurs until i load some other content.

**Comment by markwkidd** [comment] 2021-06-24 02:17
Please post logs showing the entire period including when the controller binds to the next port. This is a guide to logs: https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by markwkidd** [comment] 2021-06-26 20:02
This may be the same issue: https://github.com/libretro/RetroArch/issues/9296

**Comment by ComradeEcho** [comment] 2021-07-25 22:56
Hello, I'm having the same issue on my system as well.

[INFO] CPU Model Name: Apple M1 (Mac Mini)
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jul 19 2021
[INFO] Version: 1.9.6
[INFO] Git: GIT_VERSION
Controller: Microsoft Wireless Controller (xbox series x) - Bluetooth

Unfortunately while my logs are set to Debug, they still don't seem verbose enough to get much information out of them.

What I do notice however is that this appears to be caused by the application often not detecting that a controller has been *disconnected*, so when the controller reconnects, RetroArch appears to think you just plugged in an *additional* controller.

macOS *does* show the controller as "Not Connected" in the system bluetooth settings after the controller has been shut off - so it doesn't appear to be an issue with the Operating System thinking the controller is still connected.

[retroarch__2021_07_25__17_42_34.log](https://github.com/libretro/RetroArch/files/6874671/retroarch__2021_07_25__17_42_34.log)

**Comment by ComradeEcho** [comment] 2021-07-25 23:54
https://github.com/libretro/RetroArch/issues/11294

**Comment by ComradeEcho** [comment] 2021-07-26 00:20
I'm not sure if this is helpful - but the macOS console is showing a  message from the retroarch process when my controller is powered off - but retroarch doesn't see/respond to the controller disconnecting

`HIDAnalytics Unregister Send event com.apple.hid.queueUsage`

![Screen Shot 2021-07-25 at 7 17 09 PM](https://user-images.githubusercontent.com/4523694/126918236-f63b4804-ad2b-4ea6-8558-1f1ee5a2fa6e.png)

**Comment by ComradeEcho** [comment] 2021-07-26 00:46
Another thing I'm seeing in the console logs is that when a controller is connected I get a `AddInstanceForFactory` and `Created instance of plugin for factory` message, and when I disconnect the controller I get a `RemoveInstanceForFactory` message regardless of whether or not RetroArch removes the controller from the port.

It seems like on some level, RetroArch is *seeing* the controller disconnecting, but it's not very reliably not acting on it.
![Screen Shot 2021-07-25 at 7 37 32 PM](https://user-images.githubusercontent.com/4523694/126918990-7e2a7d6b-e33a-48d3-a0f6-fa912d2ab82b.png)

**Comment by ComradeEcho** [comment] 2021-08-04 05:24
I think I have mostly fixed this issue, however it has resulted in another major issue being exposed in the pad_matching functionality.
The pad matching code appears to be overwriting the structure that holds the controller's reference handle.
For example in `hidpad_ps4_init()` the code passes along a  `iohidmanager_hid_adapter` in `void* data` but it gets dereferenced as a `pad_controller` structure resulting in data corruption.

I don't know if the wrong data is getting passed into this function, or if the function is doing the wrong thing *with* that data. https://github.com/libretro/RetroArch/blob/49632bbde9630bf9de95fcb9c06e5b1371fe2432/input/connect/connect_ps4.c#L130-L147

Here's the work I have done to get the port-reusing mostly fixed.. but I really need help figuring out these issues within the pad-matching to continue this

https://github.com/ComradeEcho/RetroArch/commit/7b87ab6e1173d3f7e70de59a231d6513289f10e7

**Comment by markwkidd** [comment] 2021-08-04 15:41
I think it would be useful to have your patch as a PR. That way folks can easily post code review and other comments directly with your code. Would you be willing to make a PR?

**Comment by twinaphex** [comment] 2021-08-07 23:59
@ComradeEcho tells me this is fixed now, closing.

**Closed by twinaphex** 2021-08-07 23:59 UTC
