### ISSUE TITLE
Black screen with retroarch 1.4.0

### ISSUE THREAD

**Issue by scorpiusmilo** [libretro/RetroArch#4456] opened 2017-01-19 18:23 UTC
Blackscreen when I load a game ( zip,bin or iso... ) with many and all Retroarch core

I make test and I select "d3d" drivers in video settings, after that all work fine. 

When I use Retroarch 1.3.6 I not have this issue with "gl" drivers ( same core, same rom or iso ) 

My pc run: Win10 Core I7 860 8Go ram and HD4850 videocard, Ati not release Windows10 Drivers for this card it's "Windows Driver"

**Comment by bparker06** [comment] 2017-01-20 22:15
Romjacket had the same issue, also on an ATI card (4650HD), and was able to narrow down the issue to a commit by @loganmc10:

https://github.com/libretro/RetroArch/commit/1d69baca8297287f14430d0b994abe72e15e96f3

Your GPU driver may have a bug with the ARB_texture_storage extension that causes it to crash, or maybe one of the formats we're using isn't compatible, but it seems to be an ATI/AMD-specific issue as we cannot reproduce it with nvidia or intel devices.

**Comment by loganmc10** [comment] 2017-01-21 00:09
Ya this seems to potentially be some kind of Windows 10 + ATI bug with ARB_,texture_,storage.

@scorpiusmilo are you able to update your graphics drivers and retest?

**Comment by loganmc10** [comment] 2017-01-21 00:26
@bparker06 @twinaphex if this does turn out to be an ATI issue I would suggest checking GL_RENDERER inside the GL_CAPS_TEX_STORAGE check in gl_capabilities.c and disable GL_CAPS_TEX_STORAGE for ATI cards

**Comment by scorpiusmilo** [comment] 2017-01-21 15:51
** @loganmc10 ** 
I, and thanks for the answer

My graphic drivers are udapted, there are no Windows10 updated drivers for HD4xxx on the ATI site 
Hd4xxx drivers are legacy drivers and stop at windows 8.1 
I tried to install Windows 8.1Catalyst but no success 

Maybe it's time to update my graphic card :( or stay with 1.3.6 RetroArch version

**Comment by loganmc10** [comment] 2017-01-21 15:55
@scorpiusmilo can you try the latest nightly of RetroArch? @twinaphex pushed a commit that should hopefully fix this issue for ATI cards

**Comment by twinaphex** [comment] 2017-01-21 16:05
Well, it just disables glTexStorage2D for any ATI GPU, but I guess this will do as long as we don't know how to fix the actual cause.

And yeah, try to see if it can get you past the black screen now.

**Comment by loganmc10** [comment] 2017-01-21 16:44
It likely boils down to a driver bug, since I guess ATI hasn't released official Win 10 drivers. That code has been tested on Nvidia (Windows Linux and Android), Intel (Windows and Linux), and mobile drivers like Adreno and Mali

**Comment by twinaphex** [comment] 2017-01-22 00:59
@romjacket Says it works for him now, so closing it. To OP - if this still persists with the latest sources for any reason, reopen this again.

**Closed by twinaphex** 2017-01-22 00:59 UTC
