### ISSUE TITLE
beetle-pc engine core is not even attempting to softpatch roms

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5129] opened 2017-06-29 05:15 UTC
unlike other 'small rom' cores this one is not attempting to softpatch, for no reason as far as i can tell because .pce roms are less than 1 mb.

**Comment by retro-wertz** [comment] 2017-06-29 06:51
wrong section. and yes, pce does not do softpatching.

**Comment by hizzlekizzle** [comment] 2017-06-30 01:11
I think the issue is that the same core also handles PCE-CD and needs direct file access.

**Comment by i30817** [comment] 2017-06-30 01:28
I've been thinking about it after reporting and i think the 'issue' might be something more surprising. PCE and PC98 (and dosbox) games are computer games, and as such expect to be able to write to game files. What happens if you softpatch, then the game writes something and then you reset the game is at best that the changes get ignored next run, at worst, you've caused the patch file to not apply.

There is a external solution i'm pursuing now, a FUSE copy on write mount. I'm going to do a little tray utility with yad (linux only) that mounts a redirect that can be used for when games try to write to harddisk files, that would solve this ips issue too. Well, i'm just mentioning for if you ever want to enable softpatch on these cores. I think thats the best way.

**Comment by i30817** [comment] 2017-06-30 07:52
Just for fun [here is my solution](https://gist.github.com/i30817/3fbb5abcb0937ad57b1f956977505492) to computer cores clobbering their ROMs. it will only ever run on linux though.

**Comment by fr500** [comment] 2017-07-10 00:12
This is about RetroArch, not a core issue tracker. Closing.
Feel free to reopen on the proper repo or libretro meta

**Closed** 2017-07-10 00:11 UTC
