### ISSUE TITLE
[Switch] Black screen freeze when being offline while RetroAchievements are enabled

### ISSUE THREAD

**Issue by lordelan** [libretro/RetroArch#8072] opened 2019-01-23 09:01 UTC
It seems that the RetroAchievements feature tries to connect to http://retroachievements.org/ when enabled and prevents RetroArch from proceeding loading the selected content if the Switch is offline.

Steps:

1. Enable RetroAchievements and log in to an account so it is set up.
2. Load a content and a core. The order doesn't matter.
3. As soon as the content/game should start, either one of the following two things happen:
4. a) if the Switch is online, the content/game launches with no issues
4. b) if the Switch is offline, it stays at the black screen without any notification

While the black screen is displayed, RetroArch isn't responding (menu can't be entered with - and +).
It can however be left with the home button to the Switch's main menu so it's not a complete console freeze.

Setup:
• Firmware 6.2.0
• Atmosphère 0.8.2
• RetroArch 1.7.5 stable
• Snes9x core

**Comment by natinusala** [comment] 2019-01-23 10:18
Can you follow this guide and give us logs of that black screen issue?

https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-with-nintendo-switch

**Comment by orbea** [comment] 2019-01-23 14:49
Maybe a duplicate of issue https://github.com/libretro/RetroArch/issues/6084.

**Comment by orbea** [comment] 2019-02-02 14:19
I'm going to close this in favor of issue https://github.com/libretro/RetroArch/issues/6084 since its probably the same.

**Closed by orbea** 2019-02-02 14:19 UTC
