### ISSUE TITLE
Intergated file browser bug

### ISSUE THREAD

**Issue by Betonar** [libretro/RetroArch#8243] opened 2019-02-10 08:52 UTC
## Description

https://youtu.be/q-UVTQpiBxE

Notice its required to select drive twice

### Expected behavior

Choose the drive just once

### Steps to reproduce the bug

1. First lunch of RA 1.7.6. Win 10 64b on Win 1064, clean instal
2. Go to set up directories
3. Notice drive has to be selected twice

### Bisect Results

Out of scope of my ablities

### Version/Commit

Git version 9750719074

**Comment by orbea** [comment] 2019-02-10 15:33
This is a problem with the drop down list and a duplicate of issue https://github.com/libretro/RetroArch/issues/7528.

You can avoid this by not using the drop down menu for now...

**Closed by orbea** 2019-02-10 15:33 UTC
