### ISSUE TITLE
[Feature Request] Integer Zoom Function.

### ISSUE THREAD

**Issue by whatwwkd4496** [libretro/RetroArch#5008] opened 2017-06-01 15:11 UTC
please add separate integer zoom function to guarantee screen fill, example 320x240 source image on a 1600x900 monitor will be multiplied 5x to 1600x1200, so only 1600x900 image will be visible, a clean 16x9 ratio from 4x3 source to display scanlines evenly. and a 256x224 source on a 1600x900 monitor will be multiplied to 7x rather than 6x because 256x6=1536=underscan and 256x7=1792=overscan, so the goal is to fill screen and display scanlines evenly. basicly an automatic integer pan scan that prefers overscan.

**Comment by dankcushions** [comment] 2017-06-01 15:23
Can we have an example of a game + core? I think most systems that have ignorable overscan will have option in the core options (eg https://github.com/libretro/nestopia/blob/master/libretro/libretro.cpp#L362), and some others respect the Retroarch `video_crop_overscan` option: https://github.com/libretro/RetroArch/blob/1a251de6be2c418b1deda205cd31bc1420455073/retroarch.cfg#L228

i think using these options plus the integer scale option should achieve what you want. anything that gets cropped beyond that is probably stuff you wouldn't want hid.

that said i did make script for retropie to try and intelligently calculate resolutions for use with scanline shaders: see https://github.com/dankcushions/crt-pi-configs - when making this script i thought it would be useful to add video modes to Retroarch 'integer scale on X' and 'integer scale on Y' but never got around to it, so i just did the calculation in my script :)

**Comment by whatwwkd4496** [comment] 2017-06-01 17:52
but the point is not to manually set for each core and game but a single general video option to zoom-in in integer factor to fill screen width. screen width devided by input width example: 1920/320=6, or 1366/256=5,335975 will be count as 6 not 5 to make sure no screen width wasted. it's like a switch to chose between normal or zoomed.

**Comment by whatwwkd4496** [comment] 2017-06-01 18:37
i'm sorry i wasn't straight forward before, what i mean is retroarch is currently fitting image to screen by height, what i want is an option to switch between fit by height or width, as for now a 240p on a 1080p with integer scale on will scale to 960p, if there's an option to switch fit by width a 320 width on a 1920 screen will fill the entire screen, so if this option enabled i can switch between normal and zoomed instantly

**Comment by hizzlekizzle** [comment] 2017-06-01 21:34
I believe what he's asking for is, instead of the current behavior, which always rounds down to the nearest integer (that is, similar to floor(x,y)), he wants it to always round up (so, floor(x,y) + 1.0 or round(x,y+0.5)). On a 1080p screen, this would be 5x integer instead of 4x, which the remaining image being cut off by the monitor edges.

**Comment by whatwwkd4496** [comment] 2017-06-01 21:59
yes, but i'm not asking default behaviour to be replaced just given another option to scale input width to screen width integer wise, cropping up and bottom, by a single switch.

**Comment by whatwwkd4496** [comment] 2017-06-01 22:25
i believe generally this is called pan scan and current behaviour is called pillarboxing/letterboxing. can you please add pan scan option?

**Comment by hizzlekizzle** [comment] 2017-06-01 23:53
Oh, you want the width to fill up the screen? That's gonna cut off a *lot* from the top and bottom.

**Comment by whatwwkd4496** [comment] 2017-06-01 23:55
yes, i would like it as an optional feature.

**Comment by orbea** [comment] 2019-01-04 03:39
Duplicate of issue https://github.com/libretro/RetroArch/issues/4158.

**Closed by orbea** 2019-01-04 03:39 UTC
Labels: feature request, invalid: duplicate
