### ISSUE TITLE
[Feature Request] Support for JPG thumbnails to save up space

### ISSUE THREAD

**Issue by Starman99x** [libretro/RetroArch#15144] opened 2023-03-30 00:43 UTC
RetroArch strictly limits us to PNG format only, which when importing high resolution boxart from elsewhere, will require converting them first to PNG format, and thus, inflate their file size to big numbers, that's not justified because there's nothing to be gained from the process except a couple of extra megabytes.

**Comment by gouchi** [comment] 2023-03-30 09:10
Duplicate of #15121 which is duplicate of https://github.com/libretro/RetroArch/issues/12832 which is duplicate of https://github.com/libretro/RetroArch/issues/12236.

So you should close this issue.

Thank you.

P.S = Before opening a new issue, you should try to search for existing ones ;)

**Closed** 2023-07-18 20:30 UTC
