### ISSUE TITLE
(Menu) Cannot select French Translation

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#7150] opened 2018-08-29 06:48 UTC
Hello,
I downloaded the last Retroarch git and I can no more choose french translation, is it a know issue?
Thank you for your help.

**Comment by Tatsuya79** [comment] 2018-08-29 08:28
Looks like Français became Italien.

**Comment by RobLoach** [comment] 2018-08-29 16:29
It appears for me...

![screenshot at 2018-08-29 12-27-54](https://user-images.githubusercontent.com/25086/44801448-1705f080-ab87-11e8-9a3c-bf2be50756c6.png)

**Comment by Tatsuya79** [comment] 2018-08-29 16:53
I'm on win7 x64 current git.
The title of the options are wrong too.

<a href='https://postimages.org/' target='_blank'><img src='https://s15.postimg.cc/b0wfatocr/RA_french_bug.png' border='0' alt='RA_french_bug'/></a><br /><a href='https://postimages.org/fr/'>image hebergeur</a><br />

**Comment by legluondunet** [comment] 2018-08-29 17:50
As you can see and if you understand a little french, this translation is totally wrong, not at the good place.

![capture d ecran de 2018-08-29 19-46-33](https://user-images.githubusercontent.com/325405/44805416-6b7b9100-abc4-11e8-9e7e-e868f68abb74.png)
![Uploading Capture d’écran de 2018-08-29 19-47-16.png…]()

I have this bug for I updated my github Retroarch version.
Did you change a parameter in the config file?

**Comment by Tatsuya79** [comment] 2018-08-29 19:44
fixed with https://github.com/libretro/RetroArch/commit/9d43f7f03625c834f8f1d13fa618c1fa0975728e

**Comment by RobLoach** [comment] 2018-08-29 19:49
Confirmed without Qt too....

![screenshot at 2018-08-29 15-48-52](https://user-images.githubusercontent.com/25086/44811631-14b18f80-aba3-11e8-8aa0-a572f2cf41d5.png)

**Closed by RobLoach** 2018-08-29 19:49 UTC
Labels: bug: ui, bug: wimp
