### ISSUE TITLE
Most translations are broken in RetroArch x86_64

### ISSUE THREAD

**Issue by 6lackmag3** [libretro/RetroArch#11750] opened 2020-12-24 16:06 UTC
Hello. 
RetroArch x86_64, todays build (2020-12-24 18:24).
Half of translations (Japanese, Greek, Korean, Russian, Arabic etc) show ???????? instead of text strings.
Updating assets, changing menu driver wont help.

**Comment by cynodesmus** [comment] 2020-12-27 11:02
> Half of translations (Japanese, Greek, Korean, Russian, Arabic etc) show ???????? instead of text strings.
> Updating assets, changing menu driver wont help.

Faced the same problem in a freshly installed RetroPie on Raspberry Pi.
When trying to use the Russian locale, we get the following:
![IMG_20201227_145503_2](https://user-images.githubusercontent.com/16974509/103169346-24fdd600-4854-11eb-8774-d746a08bc0a8.jpg)

**Comment by 6lackmag3** [comment] 2020-12-27 15:38
@cynodesmus RGUI never supported Russian along with some other non-latin languages.

**Comment by cynodesmus** [comment] 2020-12-27 19:01
@6lackmag3 I do not require RGUI to display Russian. The problem is that if you select ru_RU.UTF-8 UTF-8 as the main one in the console, then in RGUI all menu items disappear, despite the fact that English was selected there. When you move through the menu items, punctuation marks run through the bottom of the screen in the scrolling line, the text itself is not visible.
The language selection menu looks like this - part of the text is there, the other part is not:

![IMG_20201227_224025_2](https://user-images.githubusercontent.com/16974509/103177626-9f9b1580-4895-11eb-9d16-84ba54d1215b.jpg)

I have 2 devices, one with a Raspbian Stretch and the other with a freshly installed Raspberry Pi OS (Buster).
On a device with Raspbian Stretch and an old version of Retroarch - all menu items were displayed. After the Retroarch update, almost all items in the menu are not displayed.
I'm trying to figure out what the problem is. Thought we had similar problems.

**Comment by twinaphex** [comment] 2020-12-27 19:14
We are currently in the process of moving to a new server, and there are still several incomplete things in the Windows version. Give us a bit of time while we scramblw to iron out the chinks in the armor.

**Closed** 2021-01-15 23:36 UTC
