### ISSUE TITLE
External controller not working correctly on RG351M

### ISSUE THREAD

**Issue by sergimes** [libretro/RetroArch#13281] opened 2021-11-24 16:40 UTC
## Description

When using Retroarch with Lakka 3.6 on the RG351 external controllers get recognaized, but the mappings to the buttons are not working, although analog input is being mapped correctly. When I go to input settings and try to map d-pad up, then I press d-pad up on the controller but nothing happens, as if it was not being registered. I'm using an F310 as external controller with a usb to type-c adapter, also tried with a Gamesir G3s and the problem is the same. I also tried using 351Elec that uses a frontend on top of retroarch and I have the same isssue, althought the controller is fully working on the ES frontend.

### Expected behavior

When pluging external controller either the controller should work right away or it should be possible to map all the controlls.

### Actual behavior

When pluggin external controller only analog input is being recognaized, buttons such as d-pad up or A don't seem to register.

### Steps to reproduce the bug

1. Plug external controller
2. Go to Settings->Input->Controller 2
3. Try to map D-pad up on the controller

### Bisect Results

I don't rember this working any time, and I first encoutered this problem 5 months ago more or less.

### Version/Commit
- Build Date: Nov 13 2021
- RetroArch: [fca72f67d1]

### Environment information

- OS: Lakka 3.6
- Compiler: GCC (9.4.0) 32-bit

**Comment by aldebaran27** [comment] 2022-04-17 23:04
I have this same problem on an RG351V running the stable 351Elec/AmberElec  from November 2021 - any progress or resolution?

**Comment by aldebaran27** [comment] 2022-07-01 11:46
I know the issue - in "input/input_driver.h" there is a define for only one controller:
#elif defined(HAVE_ODROIDGO2)
#define DEFAULT_MAX_PADS 1

Changing this to a higher number fixes the problem. The reason it is broken is because in "input/drivers_joypad/udev_joypad.c" in the "udev_joypad_button" function there is this line:
   if (port >= DEFAULT_MAX_PADS)
      return 0;

This also impacts the D-pad hat, but not the analog joysticks and triggers (this is why those would work - I think it is an oversight that there is not a similar check for them).

**Comment by sergimes** [comment] 2022-07-01 12:02
Oh nice that you found the issue, did you make a pull request to solve It?

**Comment by aldebaran27** [comment] 2022-07-01 12:10
Yes, I just submitted it.

**Comment by Keltron3030** [comment] 2022-07-17 02:28
Has anyone confirmed if the fix worked in the nightly?

**Comment by aldebaran27** [comment] 2022-08-01 22:30
No, because I cannot find a nightly aarch64 build other than for Android -
do you know where the aarch64 nightly build for Linux is located?

**Comment by Keltron3030** [comment] 2022-08-01 23:03
Unfortunately no, I couldn't find it either.

**Comment by LibretroAdmin** [comment] 2022-09-03 11:29
Going to assume this issue is now fixed.

**Closed by LibretroAdmin** 2022-09-03 11:29 UTC

**Comment by Keltron3030** [comment] 2022-10-14 01:21
This issue has indeed been fixed. Thanks again @aldebaran27 🙂
