### ISSUE TITLE
Menu does something strange selecting "Input User X binds"

### ISSUE THREAD

**Issue by mibofra** [libretro/RetroArch#2600] opened 2015-12-27 00:02 UTC
Two machines. One with Intel atom x86_64 bit with Ubuntu 15.04 and one an armhf device with ubuntu 16.04. The x86 one is working with the latest linux 4.4-rc6 lowlatency and the armhf device is a cubieboard 4 with an allwinner a80 on linux 3.4-sunxi, and ubuntu 16.04 dev branch. The lastest version of retroarch in the ppa testing repository (when writing it's the package with version 1.2.2+r283~22~ubuntu15.10.1) on both machines. If I want to map a controller manually, going under setting → input; when I select the menu entry "Input User 1 Binds" (but the same with 2, and 3 etc.), the menu response it's strange, on both machines. See the gif at http://imgur.com/xjTz80D . Tried with other menu drivers too, with the same result.

**Comment by mibofra** [comment] 2015-12-29 22:45
It seems that if you make changes under settings → user (like select another language, insert a username or both), the menu has a glitch (the menu entries will disappear but reappear after an input from mouse, keyboard, controller), and after the settings → input → input user binds menus stop working as described above.

**Comment by fr500** [comment] 2016-02-24 16:39
Closing, reopen if the issue is still there

**Closed by fr500** 2016-02-24 16:39 UTC
Labels: minor bug, unconfirmed

**Comment by mibofra** [comment] 2016-02-27 00:12
The issue is still here, retroarch 1.2.2+r283~22~ubuntu15.10.1 (latest ubuntu ppa package version I've tried now).

**Comment by fr500** [comment] 2016-02-27 00:56
that's several months old

**Comment by mibofra** [comment] 2016-02-27 07:05
I've seen there is the 1.3 into the ppa. I'll try to update retroarch (I do an apt-get update & apt-get upgrade every day, ubuntu xenial; and still it doesn't fetch the 1.3 version automatically). At least I'll try to compile it from repository and after I'm going to try again. Thanks for the advice, I've missed that there was the 1.3 version (even if I've to see the x86_64 machine where maybe for obscure reasons there is the 1.3 version).

**Comment by mibofra** [comment] 2016-02-27 12:17
spf@spf-cubieboard:~$ dpkg -l | grep retroarch
ii  retroarch                                            1.3.0+r305~32~ubuntu16.04.1                  armhf        Simple frontend for the libretro library 

The issue is still here.

**Comment by twinaphex** [comment] 2016-02-27 12:25
And that one is old too.

Honestly, start building from source.

**Comment by mibofra** [comment] 2016-02-27 12:30
https://launchpad.net/~libretro/+archive/ubuntu/testing/+sourcepub/6099029/+listing-archive-extra This version was packaged two days ago. Really is it still too old? Yes at this point I'm going to build from source.

**Comment by mibofra** [comment] 2016-02-28 00:25
I've tried with the latest source code from https://github.com/libretro/RetroArch/, compiled it but still the same issue. Anyway I'm going to get a new piece of hw next week (a more powerful x86_64 machine), so I'm going to try also there.

**Comment by mibofra** [comment] 2016-03-16 21:34
I'm on a new machine x86_64. Intel i7-4750HQ CPU @ 2.00GHz and 8GB of ram. Fresh installation of ubuntu 15.10 x86_64, fresh installation of retroarch (tried both from repo and compiled from the master trunk). Still the same issue. If you want a recording I can provide it.
