### ISSUE TITLE
"Onscreen Notifications" setting ignored

### ISSUE THREAD

**Issue by Bezier89** [libretro/RetroArch#8855] opened 2019-05-27 00:10 UTC
## Description

As of RetroArch 1.7.7, the "Onscreen Notifications" setting ignored. In RetroArch 1.7.6 turning it off would prevent notifications from being printed to the screen.

### Expected behavior

"Onscreen Notifications" setting is honored.

### Actual behavior

"Onscreen Notifications" setting is treated as if it's always on.

### Steps to reproduce the bug

1. Set "Onscreen Notifications" to off.
2. Do something that triggers a notification (e.g. loading a save state or connecting a controller).
3. Note the notification printed in the bottom-left corner of the screen.

### Version/Commit

- RetroArch: 1.7.7 (52dd39f)

### Environment information

- OS: Windows 10

**Comment by bparker06** [comment] 2019-05-27 13:41
This is by design because all the OSD settings currently only apply to the old notifications system, which was recently replaced with the menu widgets system. If you turn off "Menu Widgets" in Settings -> User Interface and then restart RA, the old settings will work again.

**Comment by Bezier89** [comment] 2019-05-27 15:43
Thanks @bparker06, that worked. Although I wonder if the "Onscreen Notifications" settings should be removed now since it effectively doesn't do anything? Or are there still messages that go through the old system?

**Comment by orbea** [comment] 2019-06-02 17:25
Closing as duplicate of issue https://github.com/libretro/RetroArch/issues/8714.

**Closed by orbea** 2019-06-02 17:25 UTC
Labels: invalid: duplicate, menu: widgets
