### ISSUE TITLE
The Wii U port clips audio

### ISSUE THREAD

**Issue by LIJI32** [libretro/RetroArch#6252] opened 2018-02-08 09:30 UTC
It appears that the Wii U port of RetroArch clips audio. This mostly affects SameBoy ([Issue 29](https://github.com/LIJI32/SameBoy/issues/29)) when high-pass filtering is off, because clipping audio with a DC offset effectively reduces its volume (or even completely mute it). This can also affect other cores while they play relatively loud audio, or any other core that might also play audio with a DC offset.

**Comment by fr500** [comment] 2018-02-09 03:20
Related:
https://github.com/LIJI32/SameBoy/issues/29

**Comment by aliaspider** [comment] 2018-02-11 18:01
https://github.com/libretro/RetroArch/blob/master/audio/drivers/wiiu_audio.c#L87
volume is set too high here which is probably the cause for clipping.
try setting this to 0x8000 to see if it helps.

**Comment by twinaphex** [comment] 2018-07-11 08:54
@fr500 @hunterk Can anybody manually compile and test this change first before we push this?

Alternatively, I could push the change to master, then you guys could test a nightly and see if it is better that way.

**Comment by aliaspider** [comment] 2018-07-11 09:14
yeah just push the change, I tested it last time.

**Comment by twinaphex** [comment] 2018-07-11 09:21
OK, let me push that.

**Comment by twinaphex** [comment] 2018-10-17 16:39
I am going to assume this issue is fixed now? @LIJI32 let me know if there are still issues, i'd be glad to reopen the issue or start a new one.

**Closed by twinaphex** 2018-10-17 16:39 UTC
Labels: bug: major, platform: wiiu

**Comment by LIJI32** [comment] 2018-10-17 16:42
I don't have a homebrew enabled Wii U so I never got the chance to test it, I noticed the bug to the SameBoy bug report, but I think this should have fixed the problem. I'll revert the hack meant to bypass this bug in SameBoy and see if anyone complains.
