### ISSUE TITLE
Retroarch Nightly crashes when Google Chrome/Chromium is started on Ubuntu

### ISSUE THREAD

**Issue by DarkSpartan7** [libretro/RetroArch#3931] opened 2016-11-04 09:41 UTC
Hi, i want to point out a bug in retroarch. In ubuntu, when you open retroarch, run a core and THEN open google chrome/chromium, retroarch would crash. But it doesnt seem to crash when retroarch is minimised
[out-2.ogv.zip](https://github.com/libretro/RetroArch/files/572096/out-2.ogv.zip)

**Comment by fr500** [comment] 2016-11-04 16:29
Without even a backtrace we can't do anything about this. And it could well be chrome's fault not ours.
Did you bug them?

**Comment by DarkSpartan7** [comment] 2016-11-04 16:37
lol i just found it and sorry for not uploading a vid. I'm new to github. Anyways, here's the pic:
![screenshot_2016-11-04_22-33-13](https://cloud.githubusercontent.com/assets/23255069/20013953/4cc00fec-a2df-11e6-996a-6baa25bd72f7.png)

**Comment by fr500** [comment] 2016-11-04 16:42
You should bug them instead.
It's chrome causing another app to crash not the other way around. It could be 100000 things not related to retroarch.

Closing until you can get some information

**Closed by fr500** 2016-11-04 16:42 UTC

**Comment by DarkSpartan7** [comment] 2016-11-04 16:43
Uploaded a Vid on how i replicated the bug, did you see that video?

**Comment by twinaphex** [comment] 2016-11-04 16:48
Can't reproduce what you're saying on Arch Linux. I start up RetroArch with a core loaded, I play a game, then I load google-chrome-stable, and it boots up properly.

Honestly, this is a needle-in-a-haystack issue you're pointing out, nearly impossible to gather what is at fault or what the actual cause is, or which program is at fault.

**Comment by Alcaro** [comment] 2016-11-04 16:49
We need to see the inner workings of the program, not just the output. We need a stack trace, we can't do anything with just that video.

If it's only Chrome and nothing else, my guess is faulty hardware. Judging by the Chrome startup time, your computer is ancient.

**Comment by hizzlekizzle** [comment] 2016-11-04 16:52
I use Ubuntu at home and can try to reproduce. I don't have any problems launching RetroArch while Chrome is running, so I'm assuming the issue is only when RetroArch is already running and then Chrome is launched?

**Comment by DarkSpartan7** [comment] 2016-11-04 16:56
Maybe Alcaro is right, Faulty hardware. my computer was brought in maybe 2010. I'm running Linux Mint 18 which is based on Ubuntu 16.04 LTS and my DE is  Xfce (my ram is 1gb)
