### ISSUE TITLE
[Switch] Save states options keep hidden

### ISSUE THREAD

**Issue by askotx** [libretro/RetroArch#14250] opened 2022-07-29 20:11 UTC
# Description
Save states options are hidden and not showing anymore, were working fine

Version 1.10.3 ~
No retroachievements are enabled

Same like here:
https://www.reddit.com/r/RetroArch/comments/tz3dye/cant_find_save_state_option_while_using_ra_on/

### Expected behavior

Show save states on quick menu

### Actual behavior

Save states are hidden on quick menu

### Steps to reproduce the bug

1. Make a save state from any core, in my case was mgba
2. Suddenly save state options were gone

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Nintendo Switch 14.1.1

**Comment by evbo** [comment] 2022-07-31 00:52
I am also impacted by this. I do not remember ever making a save state, but on Xubuntu 22 I installed retroarch 1.10.3 and left all configuration default other than changing the directories to `~/games/retroarch` instead of `~/.config/retroarch`

I will try running `retroarch -v` to see if there are any logs in verbose mode and will update this comment hopefully tomorrow if there's any additional information I can provide. But otherwise, there are no logs or errors produced that I noticed.

**Comment by evbo** [comment] 2022-07-31 13:57
@askotx can you check your `retroarch/cores` directory to confirm `*.info` files are present for each core you use?

That was the reason for mine not working ;)

They are downloaded here: https://buildbot.libretro.com/assets/frontend/info.zip

**Comment by askotx** [comment] 2022-08-01 00:45
Yes, info file is there in:  /retroarch/info/mgba_libretro.info

**Comment by lampadablu** [comment] 2022-10-02 23:15
I had the same problem and I solved by set the "Save configuration on exit" to ON and restarted Retroarch.
It happens only on switch.

**Comment by Instandhaltung** [comment] 2022-11-14 05:22
I have the same problem on Switch. It seems the problem is temporarily resolved if I delete and reinstall a random core. Very weird

**Comment by FabiV7** [comment] 2022-12-27 11:48
Got the same issue, switch firmware 15.0.1
Can't save anything

**Comment by m4xw** [comment] 2023-01-20 22:59
Resolved in #14875

**Comment by m4xw** [comment] 2023-01-20 22:59
> I had the same problem and I solved by set the "Save configuration on exit" to ON and restarted Retroarch. It happens only on switch.

That bug was also fixed while at it

**Closed by m4xw** 2023-01-20 22:59 UTC
Labels: platform: switch
