### ISSUE TITLE
Cannot install without superuser permissions

### ISSUE THREAD

**Issue by dleslie** [libretro/RetroArch#4074] opened 2016-11-26 18:23 UTC
HEAD at 8b29fb42932cab8e65e8054b204ce90261bc0977

Build steps from a fresh checkout up to the point of failure:

```
./configure --prefix=$HOME/local
make 
make install
```

Relevant failure:

```
rm -f obj-unix/git_version.o
mkdir -p /home/dleslie/local/bin 2>/dev/null || /bin/true
mkdir -p /etc 2>/dev/null || /bin/true
mkdir -p /home/dleslie/local/share/applications 2>/dev/null || /bin/true
mkdir -p /home/dleslie/local/share/man/man6 2>/dev/null || /bin/true
mkdir -p /home/dleslie/local/share/pixmaps 2>/dev/null || /bin/true
install -m755 retroarch /home/dleslie/local/bin 
install -m755 tools/cg2glsl.py /home/dleslie/local/bin/retroarch-cg2glsl
install -m644 retroarch.cfg /etc/retroarch.cfg
install: cannot create regular file '/etc/retroarch.cfg': Permission denied
Makefile:176: recipe for target 'install' failed
make: *** [install] Error 1
```

Suggestion: retroarch.cfg should reside in `$PREFIX/etc`

**Comment by lasers** [comment] 2016-11-26 20:08
https://github.com/libretro/RetroArch/wiki/Compilation-guide-(Linux)

```
./configure --prefix=$HOME/local
make
make DESTDIR=~/local install
```
... works for me with `install -m644 retroarch.cfg ~/local/etc/retroarch.cfg`.

You can use that as a workaround. This might be changed later. Not up to me. Thanks. :-)

**Comment by dleslie** [comment] 2016-11-26 21:50
Hmm, as a user I would expect that `PREFIX` would define what `DESTDIR` would be, as it goes with all autotools-based builds, in general.

I'll give the workaround a shot.

**Comment by dleslie** [comment] 2016-11-26 21:51
Yah, that installed it.

**Comment by lasers** [comment] 2016-11-30 22:03
@twinaphex What do you want to do with this?

**Comment by orbea** [comment] 2017-10-22 02:40
@fr500 This is not a bug, this is intended behavior. If a user does not have root permissions they should set the `PREFIX` or `DESTDIR` to a directory they have write permissions or they should skip `make install` and run RetroArch from the src directory. Can you close this issue?

**Closed** 2017-10-22 03:21 UTC
Labels: bug: minor, platform: linux

**Comment by orbea** [comment] 2017-10-22 04:43
I've submitted a PR to try to make this a little better, but the underlying explanation is the same.
https://github.com/libretro/RetroArch/pull/5577

**Comment by dleslie** [comment] 2017-10-23 02:53
In the bug report it shows that prefix was being set to a location that was writable by the user. Later comments stated that DESTDIR needed to be set as well.

Does it need both set, or has it been fixed so that only prefix need be set?

**Comment by orbea** [comment] 2017-10-23 11:37
If PREFIX is not set to `/usr*` it will use `PREFIX/etc` instead of `etc` now so only PREFIX is needed assuming that is a writable location. If you are installing to `/usr*` you probably have root permissions and it will install to `/etc` which is the FHS standard.
