### ISSUE TITLE
SDL2 driver can't see USB Gamepad, even though sdl-jstest sees it

### ISSUE THREAD

**Issue by GeoffreyPlitt** [libretro/RetroArch#1296] opened 2014-12-19 05:58 UTC
Hi,

I'm running Ubuntu Linux (trusty 64), running retroarch 1.0.0.3, and trying get it working with a USB gamepad (http://www.amazon.com/Retro-Nintendo-Controller-Not-Machine-Specific/dp/B0034ZOAO0).

Running jstest-gtk, I can see all axis and buttons working fine, I did deep testing in this way to prove that the hardware and USB device drivers are working fine. I believe (though I'm not sure) that jstest-gtk uses linux raw device mode.

The only driver in retroarch that seems to be able to see my device is linux raw, so that's what I'm using (is it weird that sdl2 doesn't see it?). Anyway, I go to do "Bind All" and the first binding ("B") works fine, and then the second binding ("Y") does not, it seems to hang. Pressing Y tons of times does nothing, but then pressing some other button (L or R) can unfreeze it.

Are these symptoms familiar to anyone?

**Comment by neilmunday** [comment] 2015-01-06 22:11
If it helps, I have seen the same issue when using the Linux raw driver rather than SDL2 with RetroArch 1.0.0.3-beta. For me, I see it under Arch Linux on the Raspberry Pi. The Linux jstest utility works fine.

**Comment by neilmunday** [comment] 2015-01-06 23:54
Update: If I check out commit 569de131a05eb443178132d927aca1058d14ce6b my joysticks work fine with SDL (1.2) and linuxraw.

The question is, is this a bug?

**Comment by heuripedes** [comment] 2015-01-17 14:37
Sounds like an issue with your udev/evdev configuration. RetroArch's linuxraw and jstest use Linux's old "Joystick" API (`/dev/input/jsX`). Modern SDL uses the evdev API (`/dev/input/eventX`) and in many distros/systems the user is unable to read/write to them. Try adding your user to the `input` group or changing `/dev/input/eventX` permissions to 666 (see http://wiki.libretro.com/index.php?title=RetroArch#Input_drivers_in_Linux_without_Xorg for more information).

**Comment by neilmunday** [comment] 2015-01-17 19:35
I should add that I am configuring RetroArch with the --disable-udev option.

**Comment by heuripedes** [comment] 2015-01-17 20:21
I've just tried `--disable-udev` and both SDL drivers worked fine so I take your system doesn't run udev at all and SDL was compiled without udev/evdev support. If that's not the case, I've adapted a shell script from https://github.com/ValveSoftware/steam-for-linux/issues/1894#issuecomment-50716691 to run RetroArch with a proper `SDL_JOYSTICK_DEVICE` value:

```bash
# Finds joystick devices so we can coerce Steam's old SDL library into using them
function enum_joysticks {
  local joyprop=ID_INPUT_JOYSTICK=1
  for f in /dev/input/*; do
    if [ ! -c $f ]; then
      continue
    elif udevadm info --query=property --name=$f | grep --quiet $joyprop; then
      echo $f
    fi
  done
}

# Uses the first arg as a separator to join the remaining args
function join {
  local IFS="$1"
  shift
  echo "$*"
}

env SDL_JOYSTICK_DEVICE=$(join : $(enum_joysticks)) ./retroarch $*
```

**Comment by neilmunday** [comment] 2015-01-19 19:48
Thanks for the info. Arch Linux definitely has udev/evdev support. What is odd, is that with the latest RetroArch source if I tell the retroarch-joystick utility to use the linuxraw driver, it doesn't detect button presses correctly (as per the original poster's experience). This is regardless of the udev/evdev support surely and why does https://github.com/libretro/RetroArch/commit/569de131a05eb443178132d927aca1058d14ce6b work then?

**Comment by heuripedes** [comment] 2015-01-21 00:48
I couldn't replicate the SDL issue but I pushed a fix for the linuxraw joypad driver, could you try it out?

**Comment by neilmunday** [comment] 2015-01-21 22:52
Hi. If I try to configure the latest commit using the configure line (SDL 1.2) and make command:

./configure --prefix="/home/pi/install" --disable-udev --disable-ffmpeg --disable-netplay --disable-pulse --disable-x11 --enable-sdl
make GLOBAL_CONFIG_DIR="/home/pi/install/etc" V=1

The make fails with:

/usr/bin/gcc -O3 -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -I./libretro-sdk/include -I./deps/7zip -Wall -O3 -ffast-math -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./decompress/7zip/ -g -I. -std=gnu99 -D_GNU_SOURCE -Wno-unused-result -Wno-unused-variable -DHAVE_CONFIG_H -DRARCH_INTERNAL -DHAVE_OVERLAY -DGLOBAL_CONFIG_DIR='"/home/pi/install/etc"' -DHAVE_FBO -DHAVE_DYLIB -DHAVE_GIT_VERSION -DGIT_VERSION=eb25b91 -DHAVE_COMMAND -DHAVE_STDIN_CMD -I/usr/include/alsa -DHAVE_MENU -DHAVE_RGUI -DHAVE_GLUI -DHAVE_XMB -DHAVE_LAKKA -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -DHAVE_THREADS  -DHAVE_OPENGL -DHAVE_GLSL  -I/usr/include/libdrm -I/usr/include/libdrm -I/usr/include/libdrm  -DHAVE_OPENGLES -DHAVE_OPENGLES2 -DHAVE_GLSL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL   -DHAVE_7ZIP -DHAVE_ZLIB -DHAVE_COMPRESSION -DHAVE_ZLIB_DEFLATE -MMD -c -o obj-unix/gfx/drivers/sdl_gfx.o gfx/drivers/sdl_gfx.c
gfx/drivers/sdl_gfx.c: In function 'sdl_gfx_frame':
gfx/drivers/sdl_gfx.c:354:4: warning: implicit declaration of function 'RARCH_PERFORMANCE_INIT' [-Wimplicit-function-declaration]
    RARCH_PERFORMANCE_INIT(sdl_scale);
    ^
gfx/drivers/sdl_gfx.c:354:27: error: 'sdl_scale' undeclared (first use in this function)
    RARCH_PERFORMANCE_INIT(sdl_scale);
                           ^
gfx/drivers/sdl_gfx.c:354:27: note: each undeclared identifier is reported only once for each function it appears in
gfx/drivers/sdl_gfx.c:355:4: warning: implicit declaration of function 'RARCH_PERFORMANCE_START' [-Wimplicit-function-declaration]
    RARCH_PERFORMANCE_START(sdl_scale);
    ^
gfx/drivers/sdl_gfx.c:357:4: warning: implicit declaration of function 'RARCH_PERFORMANCE_STOP' [-Wimplicit-function-declaration]
    RARCH_PERFORMANCE_STOP(sdl_scale);
    ^
Makefile:96: recipe for target 'obj-unix/gfx/drivers/sdl_gfx.o' failed
make: *** [obj-unix/gfx/drivers/sdl_gfx.o] Error 1

This appears to be caused by the "sdl_scale" scale function not being found.

**Comment by neilmunday** [comment] 2015-01-21 23:13
If I use SDL 2, then it compiles and installs fine. Also retroarch-joystick now works with the linuxraw driver so that's fixed at least ;-)

**Comment by twinaphex** [comment] 2015-01-21 23:26
neilmunday: Try again with this commit - https://github.com/libretro/RetroArch/commit/f1eee5554f47666ce1c934bae67e8d306246880a

**Comment by neilmunday** [comment] 2015-01-23 19:56
twinalphex: that did the trick - thanks!

heuripedes: thanks for fixing the linuxraw issue

I the latter also solves GeoffreyPlitt original issue, as he was also trying to use the linuxraw driver so perhaps this issue can be closed?

**Closed** 2015-02-01 20:49 UTC
