### ISSUE TITLE
RPI4: 1.7.9 fails to compile

### ISSUE THREAD

**Issue by darksaviorx** [libretro/RetroArch#9583] opened 2019-10-10 06:47 UTC
https://pastebin.com/HEFMfj27
I'm using retropie with raspbian lite on my pi4 to compile. 1.7.8-1.7.8.4 have compiled fine.
``` CC gfx/common/sdl2_common.c
gfx/common/sdl2_common.c: In function ‘sdl2_set_handles’:
gfx/common/sdl2_common.c:70:55: error: ‘union <anonymous>’ has no member named ‘wl’
          video_driver_display_set((uintptr_t)info.info.wl.display);
                                                       ^
gfx/common/sdl2_common.c:71:54: error: ‘union <anonymous>’ has no member named ‘wl’
          video_driver_window_set((uintptr_t)info.info.wl.surface);
                                                      ^
make: *** [Makefile:213: obj-unix/release/gfx/common/sdl2_common.o] Error 1```

**Comment by cmitu** [comment] 2019-10-12 05:35
This seems to be a dependency issue - if your SDL2 library was compiled without Wayland support and you've requested Wayland video in the `configure` script, this won't work.
SDL2 sets `SDL_VIDEO_DRIVER_WAYLAND` when compiled with Wayland support, so maybe that should be checked in `sdl2_common.c` when `HAVE_WAYLAND` is requested.

**Comment by orbea** [comment] 2019-10-15 16:12
@cmitu Confirmed and fixed, thanks. https://github.com/libretro/RetroArch/pull/9597

**Closed** 2019-10-15 17:28 UTC
