### ISSUE TITLE
RetroAchievements can't connect on Mac Nightly (Metal), working on Mac Nightly (Non-Metal).

### ISSUE THREAD

**Issue by emperordahc** [libretro/RetroArch#16023] opened 2023-12-20 16:35 UTC
## Description

Current builds of Mac Nightly (Metal) cannot connect to RetroAchievements. The current Mac Nightly (Non-Metal) can connect, and Mac Stable (Metal) can connect.

### Expected behavior

When a game starts, a notification should appear that RetroAchievements has been logged in.

### Actual behavior

When a game starts, two notifications appear:

"RetroAchievements login failed: No response"

"RetroAchievements game load failed: No response"

### Steps to reproduce the bug

To reproduce:

1. Install the Mac Nightly (Metal) build from https://www.retroarch.com/?page=platforms
2. Start RetroArch.
3. Start a game.
4. See failure messages.

If I install the Nightly (Non-Metal) build, RetroAchievements immediately works.

If I install the Stable (Metal) build (Version: 1.16.0, Build Date: Oct 2, 2023), RetroAchievements immediately works.

### Bisect Results

I do not know when this started happening; I just switched over to Metal to get better video quality several days ago, and noticed the issue then.

### Version/Commit

RetroArch Version: 1.16.0, Build Date: Dec 20, 2023
Nightly (Metal) fails, Nightly (Non-metal) works.

### Environment information

- OS: Mac 14.2
- Compiler: (Using https://www.retroarch.com/?page=platforms versions.)

**Comment by warmenhoven** [comment] 2023-12-20 17:35
It works for me, and there's not actually a difference wrt achievements between the two builds. I know their servers have been a little less stable the last few days; maybe it's just bad timing/luck? When I tried just now my token had expired, and I had to re-login to get it working again. Can you try logging out and back in again to see if it fixes it for you?

**Comment by emperordahc** [comment] 2023-12-20 18:06
I've tried this 20x - 30x for days, always with the same results, so it can't be timing. I swap back and forth between Nightly (Metal) and Nightly (Non-Metal) versions, same CFG file or fresh CFG file, one fails and one works.

I have deleted the entire cheevos section in the CFG, deleted just the token in CFG, retyped the password cleanly in the CFG file, deleted the entire CFG file to do a clean boot, etc., always the same results. I've made sure the Nightly (Metal) version can use "Refresh Netplay Host List" menu item to make sure networking isn't blocked on that version, etc.

Nightly (Metal) build always fails for me. All other versions run fine.

**Comment by warmenhoven** [comment] 2023-12-20 19:30
Ok, just grabbed the latest nightly off the website and it's still working for me. Can you capture and attach a log?

**Comment by emperordahc** [comment] 2023-12-21 02:12
Log for Nightly (Metal):
https://gist.github.com/emperordahc/0601173ee6df893c2e9b1e857ed10127

Log for Nightly (Non-Metal):
https://gist.github.com/emperordahc/9540cc2f2e71b1f5a190a9d54ba24efb

I started up the Metal version, started a game, it failed. Immediately installed the Nightly (Non-Metal), made no changes to the same CFG file, started the same game, logged in.

Appreciate the help!

**Comment by Jamiras** [comment] 2023-12-21 02:34
The "No response" log indicates that the callbacks here:
https://github.com/libretro/RetroArch/blob/f4f43d9501876697d7c6e88fa8759921025f5923/cheevos/cheevos_client.c#L337-L350

Were called with a `body` that is null or empty, suggesting either `http_data` or `http_data->data` was null or `http_data->data` was pointing to an empty string.

Both logs indicate an attempt to connect to the same server:
```
[INFO] [RCHEEVOS]: Using host: https://retroachievements.org
```

Is there some different set of flags being used in the Metal build that could affect the HTTP layer?

**Comment by warmenhoven** [comment] 2023-12-21 03:20
No, they both should be using `-DHAVE_SSL`. There's not really that much different between the two builds other than some additional graphics/audio/input drivers, unless if you want to start getting really paranoid: they're build with different versions of Xcode, and the non-Metal build targets x86 only while the Metal build is universal. You could try running the Metal build in Rosetta and see if it works any better.

**Comment by emperordahc** [comment] 2023-12-21 05:09
> You could try running the Metal build in Rosetta and see if it works any better.

My Mac is Intel; I can't run Rosetta to test.

**Comment by warmenhoven** [comment] 2023-12-21 15:21
That's good, one less variable.

I still can't reproduce this. I have seen a few times where logging in and fetching the achievements is relatively slow but in absolute terms it's still reasonable, somewhere around 5 seconds per request.

Since you can reproduce it reliably, and have a known working version, the easiest way to track down what changed is git bisect. If building it yourself isn't something you're up for, I'm happy to send you builds, though comments in GitHub aren't a great way of doing that. Feel free to reach out to me through email, eric@warmenhoven.org, or on Discord.

**Comment by warmenhoven** [comment] 2023-12-22 05:01
For those following along, it is a result of moving to the new Xcode version (from 12.2 to 14.0.1) and there are compiler flags that can be changed to fix the problem and now we're going to be working on figuring out which ones specifically, and hopefully why.

**Closed** 2023-12-23 09:22 UTC
