### ISSUE TITLE
Unable to save current config

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#3605] opened 2016-09-17 10:12 UTC
This issue keeps coming up even though I've started with a clean config file many times.

I like to disable the option to save config on exit and then save the config manually. This way if I make a change I don't like it's gone when I restart retroarch.

However, eventually when I try to save the current config nothing happens, no OSD message is displayed. To workaround I have to save a new config, move it and rename it to retroarch.cfg.

**Comment by fr500** [comment] 2016-09-17 16:07
Hmmm are you using overrides?

**Comment by pepedopolous** [comment] 2016-09-17 16:09
Yes.

**Comment by fr500** [comment] 2016-09-17 16:16
when overrides are active you can't save the current config, it is by design so it doesn't get mixed up.
Save the core or game override instead or close content

**Comment by pepedopolous** [comment] 2016-09-17 16:25
OK, that makes sense but what about when I start Retroarch?No core is loaded and therefore no override is active. In this situation I still can't save changes to the main retroarch.cfg

**Comment by fr500** [comment] 2016-09-17 16:31
I just tried on my end and I can't repro on the latest nightly

**Comment by pepedopolous** [comment] 2016-09-17 16:38
It doesn't happen from a clean config, but something happens and then I can't save anymore. This has happened to me many times perhaps since before 1.3.6. I use Archlinux and the AUR package retroarch-git.

**Comment by fr500** [comment] 2016-09-21 19:22
I really can't reproduce this..

**Comment by pepedopolous** [comment] 2016-09-21 19:31
Should I post my retroarch.cfg?

**Comment by fr500** [comment] 2016-09-22 04:35
Sure... I dunno if it'll make a difference, I can't reproduce.
The way I usually debug these issues is:

- open the config
- sort settings alphabetically
- remove a huge chunk of the config
- test, if it fails revert to the original sorted state, if it succeds now, then the infringing setting is in the chunk
- repeat with another chunk

Try finding if any particular setting causes the problem, I know it's a pain in the butt but it has to be done.

**Comment by Galious** [comment] 2016-09-24 14:07
I experience the same issue, here is how I reproduce it on a clean install.
I am on Windows 10 x64 (no anniversary update installed yet).
1 - download 17/07/2016 "RetroArch.7z" package for Windows, it is v1.3.6 (either x86 or x86_64, it makes no difference)
2 - unzip and run retroarch
3 - in the menu, click on "Save current config" : the config file is overwritten, this part is OK
4 - in the menu, switch "Settings" > "Configuration" > "Save configuration on exit" to off
5 - click again on "Main menu" > "Save current config" : nothing happens, the config file is not overwritten, this is the issue.

**Comment by joolswills** [comment] 2016-09-24 14:30
I can reproduce it too. Quick look at the code and I can see it checks for this when saving 

Eg patching like this resolves it

```
diff --git a/command.c b/command.c
index 021cd91..ec34bfa 100644
--- a/command.c
+++ b/command.c
@@ -1578,7 +1578,7 @@ void command_event_save_current_config(int override_type)
    {
       settings_t *settings = config_get_ptr();
 
-      if (settings->config_save_on_exit && !path_is_config_empty())
+      if (!path_is_config_empty())
       {
          bool ret                = false;
          const char *config_path = path_get_config();
```

this might effect other things - just to demonstrate - I shouldn't think this flag should be checked in this function anyway - it would make more sense to check if calling this function on exit or not.

**Comment by joolswills** [comment] 2016-09-24 15:11
Something like this perhaps

```
diff --git a/command.c b/command.c
index 021cd91..ec34bfa 100644
--- a/command.c
+++ b/command.c
@@ -1578,7 +1578,7 @@ void command_event_save_current_config(int override_type)
    {
       settings_t *settings = config_get_ptr();
 
-      if (settings->config_save_on_exit && !path_is_config_empty())
+      if (!path_is_config_empty())
       {
          bool ret                = false;
          const char *config_path = path_get_config();
diff --git a/frontend/frontend.c b/frontend/frontend.c
index 13df9a5..f26f606 100644
--- a/frontend/frontend.c
+++ b/frontend/frontend.c
@@ -27,6 +27,7 @@
 #endif
 
 #include "frontend.h"
+#include "configuration.h"
 #include "../ui/ui_companion_driver.h"
 #include "../tasks/tasks_internal.h"
 
@@ -45,7 +46,10 @@
  **/
 void main_exit(void *args)
 {
-   command_event(CMD_EVENT_MENU_SAVE_CURRENT_CONFIG, NULL);
+   settings_t *settings = config_get_ptr();
+
+   if (settings->config_save_on_exit)
+      command_event(CMD_EVENT_MENU_SAVE_CURRENT_CONFIG, NULL);
 
 #ifdef HAVE_MENU
    /* Do not want menu context to live any more. */
```

**Comment by twinaphex** [comment] 2016-09-24 15:15
@joolswills I'll commit something similar to your patch.

**Comment by twinaphex** [comment] 2016-09-24 15:18
See if this fixes the issue for you -

https://github.com/libretro/RetroArch/commit/9637e4ee29c3888015aba307ceb5f202d534d11f

**Comment by pepedopolous** [comment] 2016-09-24 16:19
Hi, the issue seems fixed now (on just-compiled AUR retroarch-git).

Thanks!

**Comment by twinaphex** [comment] 2016-09-25 01:27
@joolswills If you can confirm it's fixed now too, we can close this.

**Closed** 2016-09-28 04:43 UTC
Labels: unconfirmed

**Comment by Ez3chiel** [comment] 2020-05-12 01:31
Hello,
I'm new to retroarch and even though my skills at programming are limited, I managed to install it on a JXD Mini retro arcade instead of the built-in firmware.

I have the same issue as described here (#3605), and it seems you fixed it.
Can one of you please explain how I can replace the faulty files/file parts?
