### ISSUE TITLE
Can't add games from recently played tab to favorites.

### ISSUE THREAD

**Issue by CaptainCoward** [libretro/RetroArch#5807] opened 2017-11-27 14:54 UTC
## Description

Adding content from the "recently played" playlist to the "favorites" doesn't work. 

### Expected behavior

Game getting added to Favorites

### Actual behavior

It says "has been added to favorites" but won't show up in favorites playlist

### Steps to reproduce the bug

Just try to add content from the recently played playlist to favorites.

### Version/Commit
Windows 10 x64
1.6.9 f0becad9d

**Comment by hyarsan** [comment] 2017-11-27 16:00
Yeah, the same happens with the other playlists too.

**Comment by orbea** [comment] 2017-11-27 20:20
Can you bisect this? When you were asked to use the issue template, that didn't include removing necessary sections...

**Comment by orbea** [comment] 2017-11-27 20:21
Can you bisect this?

**Comment by Ryunam** [comment] 2017-12-03 09:50
I can confirm this too. The "Add to Favorites" option under each individual entry (both for Playlists and History) is not producing any effect.

**Comment by alfrix** [comment] 2017-12-03 13:58
@Orbea This seems because the option needs a core loaded to actually write that core to the favorites playlist, that option should not try to add a core, because it's not guaranteed that the loaded core is correct, load a core and you can add to favorites anything with the current core.
The playlist option should add DETECT and be done with it.

**Comment by RobLoach** [comment] 2017-12-07 15:07
Added the following to `~/.config/retroarch/content_favorites.lpl`...

```
~/.config/retroarch/downloads/Floppy Bird.chailove
Floppy Bird
DETECT
DETECT


```

When you go to run the game, it says "No cores available". May need to detect what core could be used when adding?
https://github.com/libretro/RetroArch/blob/master/command.c#L2317-L2342

**Comment by alfrix** [comment] 2017-12-07 15:24
@RobLoach  it works for me, but the sintax should be:
```
~/.config/retroarch/downloads/Floppy Bird.chailove
Floppy Bird
DETECT
DETECT
DETECT
DETECT
```
As in:

```
File
Name
Core
Core Name
CRC
Playlist Name
```

**Comment by gouchi** [comment] 2017-12-11 21:10
I confirm that the core needs to be loaded so that you can add it to the favorite tab.

**Comment by slacknk** [comment] 2019-02-01 00:01
Don't add in linux distro: slackware64-14.2

- RetroArch-1.7.5  (build from [_SBo](https://slackbuilds.org/repository/14.2/games/RetroArch/))

**Comment by orbea** [comment] 2019-02-01 02:33
Closing in favor of the more specific issue https://github.com/libretro/RetroArch/issues/6909.

**Closed by orbea** 2019-02-01 02:33 UTC
Labels: bug: minor
