### ISSUE TITLE
[iOS 9+] Cores don't load

### ISSUE THREAD

**Issue by Jesskas** [libretro/RetroArch#2214] opened 2015-10-05 02:08 UTC
Having previously made an issue; I'm using xCode on OS X 10.11 with an iPad Air 2 with iOS 9.0.2.

I have successfully managed to build the most recent commit with 57 cores that were successfully processed (including snes9x, pcsx_rearmed, and a few others). 

- Online Updater -> Core Updater -> [Core Name].zip ; selecting these cores one-by-one appears to work with "Download complete: [Core Name].zip" at the bottom of the screen. However:
- Selecting these individual cores that completed under "Load Core" in the main menu seems to do nothing; the bottom of the screen remains saying "1.2.2 - No Core".
- Loading a file auto-detecting the core seems to completely crash the application. Wasn't debugging; couldn't figure out why this occurred.

However, I can't debug that; when running a debugger on the application, the "Load Core" option gives an empty list. Going to Online Updater -> Core Updater to download the core doesn't completely work the way it did earlier; and gets stuck (i.e., it's been saying "Download progress: 90%" for a single core for about 10 minutes now where originally it would've finished in <1 minute.)

When initially running/debugging things, selecting a Core in "Load Core" gives an output: "notify_list_pushed: old size should not be larger" each time.

I apologize, I just don't know how far along this iOS port is. :p I apologize if it sounds presumptuous or demanding

**Comment by fr500** [comment] 2015-10-05 03:16
I think you have to sign the dylibs

**Comment by Jesskas** [comment] 2015-10-05 03:46
Tested that with two dylibs:
codesign -fs "[iPhone Developer ID thing]" ./iOS/modules/\snes9x_libretro_ios.dylib
codesign -fs "[iPhone Developer ID thing]" ./iOS/modules/\pcsx_rearmed_libretro_ios.dylib

the dylibs being in apple/iOS/modules

Deleted current build, built again with those two dylibs supposedly cosigned, through xCode; no change. Still remains "1.2.2 - No Core" at bottom.

**Comment by twinaphex** [comment] 2015-10-05 04:02
Cores would have to be recompiled with min-version=8.0. With the change to iOS9, requirements got bumped again and it is now no longer possible to target cores with a minimum version of iOS 5.0.

I don't really like this forced deprecation and I don't like Apple making these kinds of ill-advised changes that cripple backwards compatibility, but it is something that we will have to deal with from now on I guess.

Let me see if I can update the cores in the following days so that minimum version becomes iOS 8.0. I really did not like to do this but this company just does not care about backwards compatibility and is in fact toxic towards it.

**Comment by Jesskas** [comment] 2015-10-05 04:32
Actually, I used the cores pre-compiled and distributed from this page: http://libretro.com/forums/showthread.php?t=4002 which appear to do just that, and ended up with the result in my last post.

**Comment by vincentsaluzzo** [comment] 2015-10-05 20:58
I enchant the same issue. I think that me which do not use the app correctly but after reading @Jesskas I understand the problem isn't only from my side.

For my self, i'm trying RetroArch on my iPhone 6S, compiled with Xcode7 for iOS9 and it seems not compatible.

Even if y follow thread posted by @Jesskas, I can't load any code:

1 - It will not be displayed/accessible in the "Load Cores" menu list
2 - I could download core from buildbot with download section but there's nothing happen when tap on the downloaded core.

**Comment by twinaphex** [comment] 2015-10-05 21:06
I cannot test on iOS 9. I refuse to upgrade to it until a jailbreak is out and until I know that it has the usual features I care about, like self-recompiling code support.

**Comment by Jesskas** [comment] 2015-10-06 01:58
Bleh, having a lot of trouble downgrading, as if Apple forbade that from occurring even with recurring factory resets. Well, great.

What is a PR? I'll hope to end up helping in some regard.

And I hate to ask, but in case this is beyond my capacity, are there any other open source emulators for iOS that have a PSX emulator? :p

**Comment by hizzlekizzle** [comment] 2015-10-06 02:09
PR=pull request. It's how you submit patches on github.

I don't think there are any other PSX emus for iOS at the moment.

**Comment by Jesskas** [comment] 2015-10-06 04:16
Yeah, turns out Apple is no longer signing all iOS versions that aren't 9.0.1 or 9.0.2 anymore, which apparently makes downgrading of any support completely impossible. Darn, I knew upgrading a few days ago was the worst idea ever.

Yeah, I'll start investigating it as time allows, I guess.

**Comment by vincentsaluzzo** [comment] 2015-10-06 21:03
@Jesskas Yes, Apple have stop to sign iOS8 & 9.0.0 last week.
If you found another emulator for PSX or N64, and ran in iOS9 environment, could you inform us ?

**Comment by Jesskas** [comment] 2015-10-06 21:07
Planning on it, nothing yet.

**Comment by twinaphex** [comment] 2015-10-06 21:35
@vincentsaluzzo I must remind you that Github issues are meant for technical development issues related to the sourcecode/project you are commenting on.

It is NOT meant for idle enduser talk on which PSX/N64 emulator you could rather use instead just because you are too impatient and/or too unwilling to cooperate to contribute to the project at hand that already exists. If this is how people approached opensource from the beginning, then no prioject would ever progress.

I am really getting highly annoyed to see this recurring thing popping up in mobile oriented marketplaces where people take from opensource, but they do not give anything back and their only concern is just 'using it' to further their own business while doing nothing to give back to the source, I am not saying you are one of those guys but those comments you made just now sure does not give away the indication you plan to do anythigg to contribute. In such a case, please do not use Github to make issues, thanks. Why do you guys think things are unfinished? Its because exactly NOBODY in either Android or iOS marketplaces want to do a damn thing to contribute, everybody only wants to use it and then make money off our backs. It is a disgusting practice, and I for one am rather getting fed up of it.

**Comment by twinaphex** [comment] 2015-10-06 22:01
Also, this is not a forum. Keep talk related to the issue at hand or I'm just going to close it, thanks.

**Comment by duskgao** [comment] 2015-10-18 05:38
I have same bug with most MAME/MESS/UME cores in android port RA nightly build for a long time...

android 4.4.4

**Comment by Jesskas** [comment] 2015-10-26 01:07
Seems to be fixed following this:
http://libretro.com/forums/showthread.php?t=4201&page=12

**Closed** 2015-10-26 01:08 UTC
Labels: bug
