### ISSUE TITLE
Retroarch Android Online Updater works only via mobile data

### ISSUE THREAD

**Issue by hericstrada** [libretro/RetroArch#4503] opened 2017-01-25 08:44 UTC
Hi,  tried to run Core Updater, Assets updater via WiFi in 3 different networks,  but it fails. Only works via mobile data. Find a reddit post of people with the same issue. Android 5.1 Asus Zenfone GO.

**Comment by hericstrada** [comment] 2017-01-25 11:05
https://www.reddit.com/r/RetroArch/comments/4w9698/retroarch_core_updater_not_working/

**Comment by fr500** [comment] 2017-01-25 15:23
It works fine for me on wifi on numerous wifi networks.

**Comment by hericstrada** [comment] 2017-01-25 16:15
@fr500 , thanks for the reply. Would you kindly confirms if those lines in my retroarch.cfg are correct?

core_updater_buildbot_assets_url = "http://buildbot.libretro.com/assets/"
core_updater_buildbot_url = "http://buildbot.libretro.com/nightly/android/latest/armeabi-v7a/"

**Comment by hericstrada** [comment] 2017-01-25 16:16
I can access those links via the same network on a PC.

**Comment by bparker06** [comment] 2017-01-25 16:17
Can you access those links from an android web browser on your wifi network?

**Comment by hericstrada** [comment] 2017-01-25 16:18
I'll confirm, and post back tonight, i'm not in the wifi network anymore.

**Comment by hericstrada** [comment] 2017-01-25 21:44
Tested both links.  Opens in android web navigator. Tested a download and it works aswell.  Tested again in retroarch, tries to download the index,  but fails.

**Comment by fr500** [comment] 2017-01-25 21:54
maybe your wifi has proxy via wpad or something, or even manual. We don't have proxy support though.

**Comment by hericstrada** [comment] 2017-01-26 01:18
Ive messed a bit in my router after your tip,  unfortunately nothing about proxy was configured... Well,  if there is nothing to do with Retroarch Ill close the issue,  but its sad since im without mobile data this month.. Lol

**Comment by hericstrada** [comment] 2017-01-26 01:41
I suppose there is no way to inject those cores in some folder for retroarch via pc,  right? Not rooted.

**Comment by hericstrada** [comment] 2017-01-26 14:37
Just for register.  Tested on a 4th wifi in a cafeteria.  Same issue.

**Comment by hericstrada** [comment] 2017-01-27 02:35
Found the workaround.  Ive disabled the IPV6 protocol in my router and everything worked like a charm.  Any idea why this happens?

**Comment by fr500** [comment] 2017-01-27 04:30
Well... I guess it either doesn't work with ipv6 which would be a RA problem or our server doesn't have an ipv6 address and records which is more likely.

**Comment by bparker06** [comment] 2017-01-27 05:43
buildbot.libretro.com does have AAAA records, but it's possible @hericstrada's equipment thinks it supports v6 when it doesn't and then fails to reach the server that way. That or maybe the v6 connectivity on the server end isn't working or has a problem reaching him.

**Comment by jarredholman** [comment] 2017-02-18 13:03
This is still a problem. I spent ages trying to figure out why it couldn't download anything until I found this. Disabled IPv6 on my router and then it worked fine.

If the AAAA records aren't correct they should be fixed or deleted... or should RetroArch be modified to prioritize ipv4 over ipv6 if the domain resolves both?

**Comment by fr500** [comment] 2017-02-18 17:40
> > set query=AAAA
> > buildbot.libretro.com
> Server:  fw.home
> Address:  192.168.1.1
> 
> Non-authoritative answer:
> Name:    buildbot.libretro.com
> Addresses:  2400:cb00:2048:1::681c:1453
>           2400:cb00:2048:1::681c:1553

The records are correct

**Comment by jarredholman** [comment] 2017-02-19 11:41
I have ipv6 disabled now so I can't check, but is the webserver responding on those ipv6 addresses? When I tried it before it didn't seem to be.

**Comment by pkugler** [comment] 2017-02-22 18:42
I can confirm this issue. No downloads possible via RetroArch (on FireTV), although all files are accessible from my PC on the same network. After disabling IPv6 on the FireTV everything works like a charm.

**Comment by nickie66** [comment] 2017-09-12 16:48
several month later, still confirming the issue, freshly installed retroarch on my android phone, and no way to download cores, the download only goes to a few percent , and then "task failed" 

this thread made me try using 3g data (very bad reception here so last resort) and it did actually work 

it's the only thing ever to fail downloading on any of my devices so i don't feel that my router should be the cause

**Comment by BlueMax** [comment] 2017-09-12 20:19
Here's a network log. Looks like the socket is closed prematurely by the server [FIN, ACK] so the http request is invalid. Maybe the servers flood protection kicks in due to those push retransmits.

      5 0.073677       192.168.2.2         162.243.173.131       TCP      74     35747 → 80 [SYN] Seq=0 Win=65535 Len=0 MSS=1460 SACK_PERM=1 TSval=1037462 TSecr=0 WS=64
      6 0.173281       162.243.173.131       192.168.2.2         TCP      74     80 → 35747 [SYN, ACK] Seq=0 Ack=1 Win=28960 Len=0 MSS=1452 SACK_PERM=1 TSval=3472047126 TSecr=1037462 WS=256
      7 0.175155       192.168.2.2         162.243.173.131       TCP      66     35747 → 80 [ACK] Seq=1 Ack=1 Win=87616 Len=0 TSval=1037493 TSecr=3472047126
      8 0.175405       192.168.2.2         162.243.173.131       TCP      69     35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1037493 TSecr=3472047126 [TCP segment of a reassembled PDU]
      9 0.495544       192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1037586 TSecr=3472047126
     10 1.115921       192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1037772 TSecr=3472047126
     11 2.360508       192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1038145 TSecr=3472047126
     12 4.843578       192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1038890 TSecr=3472047126
     15 9.809084       192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1040380 TSecr=3472047126
     16 19.742779      192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1043360 TSecr=3472047126
     19 39.643727      192.168.2.2         162.243.173.131       TCP      69     [TCP Retransmission] 35747 → 80 [PSH, ACK] Seq=1 Ack=1 Win=87616 Len=3 TSval=1049328 TSecr=3472047126
     27 60.277117      162.243.173.131       192.168.2.2         TCP      66     80 → 35747 [FIN, ACK] Seq=1 Ack=1 Win=29184 Len=0 TSval=3472062152 TSecr=1037493
     28 60.339024      192.168.2.2         162.243.173.131       TCP      66     35747 → 80 [ACK] Seq=4 Ack=2 Win=87616 Len=0 TSval=1055540 TSecr=3472062152
     29 60.339256      192.168.2.2         162.243.173.131       HTTP     175    GET /assets/frontend/info.zip HTTP/1.1 
     30 60.437360      162.243.173.131       192.168.2.2         TCP      54     80 → 35747 [RST] Seq=2 Win=0 Len=0

**Comment by WHK102** [comment] 2019-08-26 05:08
Same problem on the core updater:
> Downloading index Task Failed

Under Samsung Galaxy S6. No lucks when reset settings to default and restart application.

**Comment by twinaphex** [comment] 2019-08-26 05:19
Yeah we know. We are currently working on it.

**Comment by twinaphex** [comment] 2019-08-26 07:53
Should be fixed now.

**Closed** 2022-09-04 19:10 UTC
Labels: followup: needs info or confirmation, bug: networking
