### ISSUE TITLE
[PLAYLISTS] Add an option to scan unknown roms

### ISSUE THREAD

**Issue by andiandi13** [libretro/RetroArch#8624] opened 2019-04-22 20:17 UTC
[ISSUE UPDATED] The other one was blocked

Many many, users complains about RetroArch not adding files to their playlists because the CRC doesn't match the original dump.

It can be because of a translation patch, an SRAM patch, and so on...

So I suggest a very simple solution :

Just add an option in playlist menu that could be named '_Ignore CRC while scanning roms_' or '_Add unknown roms to playlists_', whatever.

The thing is that it'll replace that line

`"crc32": XXXXXXXX | crc"`

By

`DETECT`

In order to easily display all roms on playlists, with a label **taken from rom filenames**, so that roms with a good labels would display thumbnails, and roms with another label (like T-eng 100% etc...) would not display cover (it's not a big deal).

RetroArch playlists are painful to use because of those unique CRC32, and it would be wonderful to simplify it in that way !

For now, I'm creating my Playlists with _RetroArch Playlists Manager_ on Windows, to add my SRAM patched GBA roms, as well as all my non-detected translated roms.

Thanks for reading, I really hope to see that option.

### Version

- RetroArch: 1.7.6

### Environment information

- OS: Windows, Android, Switch

**Comment by i30817** [comment] 2019-04-22 21:11
I should apologize. I misread the previous issue and thought it was about 'disabling CRCs' when i already knew the CRCs weren't used anymore and was pissed about it. To be constructive i suggest using 'Add unknown roms to playlists' for this reason.

However, i'm not sure it's that easy to make a 'match' of a rom to a image/data with a filename. They're not unique not only because of hacks but because dumping groups (from where the name comes from) can have the same name for the same release of the same game on a different console. This is kind of unintuitive, but i'd expect this to happen a bunch on redump for instance.

**Comment by andiandi13** [comment] 2019-04-22 21:51
> They're not unique not only because of hacks but because dumping groups (from where the name comes from) can have the same name for the same release of the same game on a different console. This is kind of unintuitive, but i'd expect this to happen a bunch on redump for instance.

What about the header ?
When I check roms header I see the name and other infos.

e.g. if the header is FINAL FANTASY TACTICS and the extension is .gba, then it must recognize it has FF tactics gameboy advance and match the thumbnail and the title in the db.

It's funny how easy it is to create manual playlists on a PC, but seems to be very hard to do it directly on RetroArch :/

**Comment by i30817** [comment] 2019-04-22 22:02
> What about the header ?
For roms, they habitually can be easily be recognized by the extension so parsing that is 'fixed' to a implementation (well there are complications on consoles like the N64 that liked to byteswap words, but you generally can trust the extension).


For cd consoles however, cd-images have a proliferation of formats and meta-formats.

You generally can trust the dumping groups to use the same format (but not hacks, for technical reasons). However, the RA code doesn't actually try to read the 'bytes' as they are if the cd image was mounted; because a multiplatform mulltiformat cd image mounter is hard work. Instead it does some heuristics, tries to find the track that has the 'magic bytes' identifying the platform (this sometimes doesn't start at track one) and then attempt reading those bytes to match.

This fails if the cd image is some format the magic bytes didn't expect sometimes. For example, most psx cues point to MODE2/2352 (a bin). However they might as easily point to a MODE2/2048 (a iso). These files not only have different block sizes but also different 'headers' (so the magic is wrong).

**Comment by fr500** [comment] 2019-04-23 01:51
@andiandi13 sorry but your request makes little sense.
If it can't identify the content, the resulting playlist will be nothing more than a list of files.

If you want a list like that may as well just browse to the folder.

**Comment by andiandi13** [comment] 2019-04-23 02:54
> If you want a list like that may as well just browse to the folder.

lol

More seriously. Here is an example of a playlist that I want RetroArch to make :

```
1.C:\retroarch\roms\Zelda (USA).gba" 
2. Zelda (USA)
3. DETECT
4. DETECT
5. DETECT
6. Nintendo - Nintendo Gameboy Advance.lpl
```

Let's take the problem line by line :

1. Can RetroArch list all files in a folder to a playlist, rather based on a know extension, or not ? YES
2. Can RetroArch copy the filename to the title ? YES
3. 4. 5. Can RetroArch write DETECT ? YES
6. Can RetroArch match a console with a file do determine what files go in what playlist and name those playlists ? I don't know and I think that's the main issue.


Here are some ideas :

- All the content scanned from a folder well named (RetroArch's folders, like thumbnails and playlists), will go to the playlists named after that same folder. Example : if I scan a folder named "**Nintendo - Nintendo 64"**, all the files inside that folder would be listed on a playlist named 'Nintendo - Nintendo 64.lpl', even if there are .gba .bin. .md or .iso inside that folder.
_Users should managed their own folder well._
Alternatively, a detection file could be placed into a folder, whatever it's name, to help RetroArch determine in which playlists would go the roms inside. e.g. in the folder /RetroArch/roms/MySNESroms, we just copy a file named "**Nintendo - Super Nintendo Entertainment System.whatever**" inside, and RetroArch would detect that "whatever" extension and put all the files into that folder in a Super Nintendo playlist.

- That new option will let users choose which extensions to manage, and RetroArch will guess which extension go in which playlist (gba in gba, md in megadrive/genesis, gb in gameboy etc..)
Extensions that are shared with different system would be ignored (bin, iso...), or users would manually associate an extension with a console (e.g. bin = Genesis, ISO = PSP...).

- Same as above (console detected by my extea), but for shared extensions, RetroArch would check the filename and go trough the database to match the rom name with a console. e.g. **Final Fantasy Crisis Core.ISO** or **Crisis Core.ISO** or **Final Fantasy Crisis.ISO** would match that game in the PSP rdb, and that ISO would go inside a PSP playlist instead of nowhere or in a Dreamcast or Saturn playlist by mistake.



I think the first option seems pretty easy and feasible...

**Comment by i30817** [comment] 2019-04-23 05:46
I honestly agree with that idea that the user should be able to start a 'dumb' scan on a folder and the resulting files should either be assumed (per directory name) or chosen to go a console playlist manually (per GUI) Users that are organized already place their games per platform on the filesystem.

But i think the RA team would rather find and fix the reason why some games aren't scanning correctly on the automatic scanner, *shrug*.

**Comment by andiandi13** [comment] 2019-04-23 14:03
Yeah as soon as we have the choice of scan type, it's OK.

Let's wait what the devs will think about it :)

**Comment by hizzlekizzle** [comment] 2019-04-23 16:46
Simple directory listing seems to be what most people want out of the playlists, but they also want boxart/thumbnails, and that's where the problem comes in. That is, hooking things up when we have no way of knowing what's what. We can do fuzzy matching, but then we have to add a bunch of stuff (menus, etc.) to correct false positives.

**Comment by andiandi13** [comment] 2019-04-23 17:25
@hizzlekizzle As I said, you just have to rename your rom the same name as the thumbnail

**Comment by i30817** [comment] 2019-04-23 18:18
Naively I also don't understand 'why' it would require new GUI screes. If the cd images get classified correctly as 'for a console' and the filename is correct. Find that during the new scan mode, store the entry on the playlist, when loading images find what playlist the entry comes from, and the name, pass to the database the tuple.

In practice, the bugs on that heuristic(s) that find out the cd image platform need to be fixed, and if you want the maximum benefit (more games scanned) fixing those bugs would also help for the other mode (serial scanner), though that would require more code I suspect.

If it's a fast function it could also streamline some parts of the interface (like the 'which core do you want to open this cd with' when you try to load a game from the filebrowser).

**Comment by i30817** [comment] 2019-04-23 18:38
edit: accidentally deleted a post, but tl;dr: if using a the tuple (console-type, rom filename) the false negatives could be controlled to the minimum if the users are smart enough to name things the same as the dump sets; and i don't really see why that would require new GUI. You can make users select the first manually ofc, but you already need those heuristics to even start scanning serials because each console has a different type of header structure.

**Comment by Ferk** [comment] 2019-04-25 16:05
> Just add an option in playlist menu that could be named 'Ignore CRC while scanning roms' or 'Add unknown roms to playlists', whatever.

I don't understand in which way such an option would require having `DETECT` in the playlist in place of the crc.

If such an option (adding unknown roms) was added I would expect that the scanning process would generate the crc from the file and save that crc into the playlist, not `DETECT`. Maybe the only thing you would gain is some speed in the scanning, but speed wasn't the problem you were talking about to begin with.

In my opinion, what would help in the scanning would be to it make so when the playlist scanner finds a file with a particular extension (say... ".retroentry" for example) read the content of the file and add it as a playlist entry file.

Then  you could place a "mycustomgame.retroentry" file next to your custom game and store it always together so whenever you scan the folder with your games the entry will be added to the playlist, instead of having to recreate the playlists every single time in every new device you install retroarch on.

Kodi already does something similar with the ".nfo" files, it will read the local metadata stored on disk and add the movies and shows using it.

**Comment by andiandi13** [comment] 2019-04-25 17:47
It's kinda like what I suggested in my third post (first idea).

If RetroArch see a file named "Sega - Game Gear.retroentry" (to keep your nomenclature) in a folder, then it will add all the content of that folder to a playlist named Sega - Game Gear.lpl, whatever roms are in the folder.

Or.... Just based on the extension.

It's really easy

**Comment by Ferk** [comment] 2019-04-25 17:56
Making it based on extensions would complicate things.
It's not a good thing to let the scanner try to be too smart, because then you risk it doing dumb things. Not every ISO/EXE/BIN file is game content, and not every game content is just one file.

I think it's better to keep things simple but flexible. Just allowing the users to have playlists within their content folders that contain paths relative to the location of the playlists and that get included when they are scanned would be more than enough to make me happy.

This would also decouple the scanning process. You could scan your content folder with a third party tool from your computer and then copy the resulting  along with your content into your Switch or whatever device you want to run it from.

**Comment by andiandi13** [comment] 2019-04-25 18:35
Yes of course, there is an obvious issue with many extensions, the idea of a small "detection" file is good imo

**Comment by i30817** [comment] 2019-04-25 18:59
> Making it based on extensions would complicate things.
> It's not a good thing to let the scanner try to be too smart, because then you risk it doing dumb things. Not every ISO/EXE/BIN file is game content, and not every game content is just one file.
> 
The scanner is 'already' too smart. What you're complaining about here already occurs and must occur to scan for serials.

**Comment by Ferk** [comment] 2019-04-26 07:16
That's unfortunate, but if the scanner is already imprecise for CD images that's more or a reason to allow the use of additional methods that allow users to override the behavior of scanning, like distributing playlist files within the content folders.

That way regardless of what the scanner is normally doing, the user has a way to define what does it want to get added, and at the same time it would be an approach that would be ok for 10 years old hardware too, since you could skip the scanning of folders that have pregenerated playlists to include.

**Comment by i30817** [comment] 2019-04-26 08:41
A new file in the game folder is a terrible solution to the problem of pointing RA to the game version. I'd seriously stop using RA if that was the only method, because it's already fucking terrible when it happens for scummvm because the RA scanner is sufficiently simple it can't emulate the scummvm parsing algorithm.

**Comment by andiandi13** [comment] 2019-04-26 08:56
Why do you talk about hundreds of files ?

I'm talking about one file per console/per folder.

In your Game Boy folder, named **Nintendo - Game Boy**, you put a **Nintendo - Game Boy.d detect** file. 

In your Sony - PlayStation folder, you put a **Sony Playstation.detect** file, and so on.

All the files into each folder will go to a playlist named after the .detect file, whatever if it's .GB, .ISO, .TXT, .JPG etc...

RetroArch could come with a pre-created "games" folder, containing many folders inside it, named after each consoles,  with all the .detect files inside. Then you'll just have to put your roms at their place.

Is that painful ? Is that complicated ?

**Comment by i30817** [comment] 2019-04-26 08:57
Ok that's actually a ok idea, sorry for misunderstanding. I was immediately reminded of the scummvm scanning strategy, which is horrible.

**Comment by andiandi13** [comment] 2019-04-26 09:00
Yes, it would have been terrible to create a file per game. That method seems pretty feasible for the devs though

**Comment by i30817** [comment] 2019-04-26 09:02
Most people already organize their games in 'platform subtrees'. In fact there is confusing code in the scanner that is supposed to take advantage of this by either 'remembering' which database file the last game was found or based on the name of the scanned subtree being the same as the name of the playlist (can't recall what convention the code had).

**Comment by andiandi13** [comment] 2019-04-26 09:11
Hmm I see...
I wish I could have done a PR. For now I'm going to wait for a response of a member

**Comment by fr500** [comment] 2019-04-26 12:40
I don't like the create files idea at all.

**Comment by i30817** [comment] 2019-04-26 13:59
Why's that? Sounds like a good way to  avoid the 'we have to create a GUI' and the 'the scan is letting false positives / false negatives pass' to the people that are organized enough.

**Comment by andiandi13** [comment] 2019-04-26 17:57
@fr500 What then ?

I never told that this new feature would replace the current scan at all !

It's adding an extra options, an _advanced_ feature, for _advanced_ users, that _know_ what they are doing.

RetroArch could even generate _automatically_ a file in each console folder, if those folder are located in a certain path. e.g. /retroarch/games

So if I create a new folder named "Sega - Master System Mark III" in /retroarch/games (for example), RetroArch will create a "Sega - Master System - Mark III.whatever" file, to put all the games in that folder on a Master System playlist.

I know I repeat the same things a lot, but it seems so obvious and simple...

**Comment by andiandi13** [comment] 2019-04-29 12:36
@bparker06 @twinaphex What do you think of that idea ?

**Comment by i30817** [comment] 2019-04-29 13:46
I'm going to mention (again) i dislike 'false CRCs' in playlists - even if they already occur today with serial scanning.

'False CRC' equals 'useless, misleading, cause of bugs CRC'.

**Comment by andiandi13** [comment] 2019-04-29 14:13
@i30817 You're right. I just checked my manually created Playlists with DETECT, and RetroArch did manage to associate true CRC with rom information of the database, and nothing for patched roms.

So it's better to set the CRC line on DETECT (I edited my post above).

**Comment by hizzlekizzle** [comment] 2019-04-29 14:16
Something fr500 and I discussed on discord the other day is: keeping the existing CRC calculation, try to match thumbnails on name alone, and adding a flag (maybe a child node in the JSON playlists and an icon/character beside the name) to show that a file is "unverified" if it doesn't match the databases.

Would that be acceptable?

**Comment by andiandi13** [comment] 2019-04-29 14:24
> try to match thumbnails on name alone

Do you mean filename or title name extracted from the CRC while scanning ?

The idea of verified/unverified files is good.

But I guess you attempt to add unknown roms into playlists ? Did you discussed about that ?

**Comment by RobLoach** [comment] 2019-04-29 16:05
Possible duplicate of [#2033 Alternative Scanning Method](https://github.com/libretro/RetroArch/issues/2033).

**Comment by i30817** [comment] 2019-04-29 18:05
> Something fr500 and I discussed on discord the other day is: keeping the existing CRC calculation, try to match thumbnails on name alone, and adding a flag (maybe a child node in the JSON playlists and an icon/character beside the name) to show that a file is "unverified" if it doesn't match the databases.

fine by me, but at the cost of being pedantic again, name match has the problem this bug discussed of same named games on different platforms and needs a further subkey (platform).

**Comment by andiandi13** [comment] 2019-04-30 18:01
@RobLoach Thanks, I didn't saw it. However, I suggest a specific solution to solve the issue.

Also, the issue goes back to 2015 and there is no new scanning method despite the $15 bounty.

Is there a specific bounty value to be sure that the issue will be solved?

**Comment by Ferk** [comment] 2019-04-30 19:31
> keeping the existing CRC calculation, try to match thumbnails on name alone, and adding a flag (maybe a child node in the JSON playlists and an icon/character beside the name) to show that a file is "unverified" if it doesn't match the databases.

What determines if a file is added or excluded?
I imagine now you would have people complain on false positives and extra entries in their playlists.
I wouldn't want to run a blind scanner across my folders of custom wads for the prboom core, for example. Not every wad is a game, much like not every CD image is, or every bin/exe from Dosbox.

I think trying to get the perfect scanner that works automagically even for unlisted content is a lost battle.
Just let those of us who don't mind managing our own playlist to have at least a reusable way to maintain it.

**Comment by i30817** [comment] 2019-04-30 20:14
> > keeping the existing CRC calculation, try to match thumbnails on name alone, and adding a flag (maybe a child node in the JSON playlists and an icon/character beside the name) to show that a file is "unverified" if it doesn't match the databases.
> 
> What determines if a file is added or excluded?
> I imagine now you would have people complain on false positives and extra entries in their playlists.
> I wouldn't want to run a blind scanner across my folders of custom wads for the prboom core, for example. Not every wad is a game, much like not every CD image is, or every bat/exe file in Dosbox.

This can be easily and reliably done with just a bit of convention. Organized people already place their games by platform, so a standard dir name or a 'id file' that makes the scanner treat all subsequent files that can be for that 'platform' as targets is more than enough. Better even than the normal scanner because it won't depend on a very failible parsing and could accept 'weird' cd image files which the cores accept but RA has no conception of how to parse. For instance there are some games on the ps2 (for a hypothetical example ofc) that are isos instead of dvds).


> I think trying to get the perfect scanner that works automagically even for unlisted content and across different types of cores is a lost battle.

Just so. That's why this idea doesn't even try to use the part that screws up: the parsing for platform attribution and consequent parsing of serial.

I myself would rather *also* have a hard checksum method as a option, but you can read that on my last post.

**Comment by Ferk** [comment] 2019-04-30 20:35
> a standard dir name or a 'id file' that makes the scanner treat all subsequent files that can be for that 'platform' as targets

How do you exclude subsequent files within that folder that are not meant to be targets?
To illustrate it there's the example from https://github.com/libretro/libretro-prboom/issues/72, there are 3 files:
* original.wad
* original.deh
* orig15.wad

The actual game is `original.wad`,  while `orig15.wad` is an optional file that provides some extra stuff but it's not possible to load `orig15.wad` by itself (although you can set your configuration after loading `original.wad` to load `orig15.wad`).

A blind scanner could easily assume that orig15.wad is a game, since it's the wad extension and it cannot really know since they are just look like custom wads.

**Comment by i30817** [comment] 2019-04-30 20:41
To that i ask: is that situation any better right now? 

Single points of entry are usually maintained and when they aren't RA tends to support the 'cmd file' hack. In that case, i'd expect RA to simply support 'cmd' file for the doom engine and force users to put in 'only accepts .cmd' on their detect files and create them (just like it does when you want to load multiple floppies in x68k).

**Comment by Ferk** [comment] 2019-04-30 21:16
So far the PrBoom core does not use 'cmd' files. Wouldn't that bring the same problem as the '.scummvm' files that you criticised?

Right now I tackled the problem by allowing people to distribute a .cfg file along with the content so it's used as the default settings when the wad is loaded ([PR is still open](https://github.com/libretro/libretro-prboom/pull/79), but people seem ok with the solution). Within the configuration you can set additional wads to load, so you still open the wad itself (not the cfg or any cmd) and the cfg file next to the wad will indicate which other wads to load.

**Comment by i30817** [comment] 2019-04-30 21:25
> So far the PrBoom core does not use 'cmd' files. Wouldn't that bring the same problem as the '.scummvm' files that you criticised?
> 
> Right now I tackled the problem by allowing people to distribute a .cfg file along with the content so it's used as the default PrBoom settings when the wad is loaded ([PR is still open](https://github.com/libretro/libretro-prboom/pull/79), but people seem ok with the solution). Within the configuration you can set additional wads to load, so you still open the wad itself (not the cfg or any cmd) and the cfg file next to the wad will indicate which other wads to load.

Far less. It's a question of degree: you made the point that there is a 'exception', and the proposed scheme is supposed to be 'general'. So i proposed a way to deal with the exception. Cores that require multiple files that are not already in zip are either:

cd console cores with multiple cd games - like the ps1 - which require the user creating a m3u file - of [which i already have a solution for myself](https://gist.github.com/7dccadc56bfa63f344032c957d8d6cf9) and [proposed incorporating the same solution into RA](https://github.com/libretro/RetroArch/issues/6410) (it just depends on dumping group naming convention).

Cores which habitually require .cmd files or equivalent are basically x68k and scummvm and there the situation is deplorable because it's *every single game*.

**Comment by i30817** [comment] 2019-05-01 17:41
Thinking about it, this idea is orthogonal to the the scan type. 

Idea provides: A way to whitelist formats for directory branches and say which console they belong to.

serial scan -> needs to figure out the console of the game to place on a playlist and 'understand' fileformat the game is in to parse the serial. With this only needs to 'understand' a fileformat to parse the serial.

CRC scan -> needs to figure out the console of the game to place on a playlist and 'understand' the fileformat enough to know which file to checksum (in the case of divided files)

filename scan -> needs to understand the console of the game to place on a playlist and to have less false positives.

I think i'll open a request to have this as a optional 'hidden' alternative to depending on fileformat heuristics to figure out which playlist the game goes to.

**Comment by andiandi13** [comment] 2019-05-01 19:42
Why bothering with such advanced solutions ?

A path, a folder with a good name, and that's all

**Comment by i30817** [comment] 2019-05-01 20:09
Files give a opportunity to give the user control over whitelisting, which folders do not. I agree simpler is good, but this was too good of a opportunity to pass by.

**Comment by RobLoach** [comment] 2019-05-02 04:18
> @andiandi13  Also, the issue goes back to 2015 and there is no new scanning method despite the $15 bounty.

There is the Qt interface which you can use to build custom playlists, but it would be great to have it directly in the RetroArch menu. Here's a video demonstrating the Qt interface https://www.youtube.com/watch?v=hfuioGjCItw

> Is there a specific bounty value to be sure that the issue will be solved?

It varies depending on motivation and skill for people implementing. There have been bounties that got to ~$150 and were done, and there were bounties that were $0 and were done.

**Comment by andiandi13** [comment] 2019-05-02 04:26
> There is the Qt interface which you can use to build custom playlists, but it would be great to have it directly in the RetroArch menu. Here's a video demonstrating the Qt interface https://www.youtube.com/watch?v=hfuioGjCItw

Thanks, but actually I tested it once, and find that RetroArch Playlist Manager is faster to create quick playlists with just a drag and drop.

> It varies depending on motivation and skill for people implementing. There have been bounties that got to ~$150 and were done, and there were bounties that were $0 and were done.

I see... But honestly with what I suggest, despite not being a developer, it seems so easy to implement. 

Scanning folders, recognizing paths amd names, and creating .lpl files according to the content of each folder linked to a console.

**Comment by bparker06** [comment] 2019-05-22 18:27
While it may be possible with an "ignore CRC" or such option to add cartridge-based games into the right playlist (based on file extension<->core info/database mappings), this is a lot more difficult for CD systems because we don't have detection methods for all kinds of images and systems.

**Comment by andiandi13** [comment] 2019-05-22 18:31
@bparker06 : Again, it doesn't have to be that complicated.

- Retroarch would keep it's CRC-based scan

- A new option would be added into playlist menu

- That option is just a folder-based scan

So, for CDs (PSX, PSP, GC...), You'd just have to create the appropriate folder, or Retroarch would create them as soon as the option is activated, and you put your .ISO files in the appropriate folders.

I don't know what easiest can I suggest

**Comment by bparker06** [comment] 2019-05-22 18:44
Not everyone wants to make folders.

Where is the playlist name going to come from? 

How do you know what database to associate each entry with?

Thumbnails aren't going to work.

Playlist asset icons won't work.

Database metadata won't work.

What's the point now? Might as well just use Load Content.

I promise it's not actually easy to make even the majority of users happy.

**Comment by andiandi13** [comment] 2019-05-22 19:03
You obviously didn't read my previous posts.

> Not everyone wants to make folders.

No one is forced to use that new option + Retroarch can create them for us

> Where is the playlist name going to come from?

From the fact that file are inside folders named like playlists. e.g. Game Gear ROMs have to be put in a folder named "Sega - Game Gear" (which is in a certain path, that could be changed in Directories options e.g. "retroarch/roms" or just "/")

> How do you know what database to associate each entry with?

I never say that CRC32 would not work ! ROMs would still be scanned : known ROMs would have their informations from the database, and unknown ROMs, not.

> Thumbnails aren't going to work.

Yes they are, as soon as your ROMs are well named (like the thumbnails), and put in the food folder, thumbnails could be associated.

> Playlist asset icons won't work.

They would work

> Database metadata won't work.

CRC32

**Comment by bparker06** [comment] 2019-05-22 20:21
I meant that people aren't going to want to have specifically named files and folders in order for all the features/effects of the scanner and databases to work, whether or not the CRC/serial/etc. is checked. And that creates problems.

**Comment by andiandi13** [comment] 2019-05-22 20:42
If people don't want that, they just have to download clean ROMs with clean CRC and they're good.

What I suggest here is an _extra_ option, an _advanced_ option, why not an _hidden_ option.

Others CRC problems can be dealed with in other issues. 

But that feature would satisfy everybody making their Playlist manually on Windows/Mac/Linux, and I know they are numerous.

It's a hundred times easier for them, for us, than going through another device, managing Playlist, copying them to the target device. It's so painful, especially when you take new ROMs quite often.

**Comment by i30817** [comment] 2019-05-22 20:58
> I meant that people aren't going to want to have specifically named files and folders in order for all the features/effects of the scanner and databases to work, whether or not the CRC/serial/etc. is checked. And that creates problems.

This idea (both his and mine) is supplementary to the agnostic scanner that exists today and that allows zero customization. Frankly the main problem i have with the scanner is that it *doesn't* allow any adjustment in a sane manner.

Don't get me wrong, i'm the first one to criticize things like 'scummvm files' for the scummvm core, and i'm the first one to wish the scanner was more specialized in that case and was able to pick up the game folders without that 'help' which causes much much more work for the users. However, even on this example, imagine that tomorrow the scanner gained the ability to recognize scummvm compatible game folders. Would it be enabled? No, precisely because it would slow down the general scanner and the user doesn't have a way to configure it, except even more work per 'game'.

So yes, i support a 'hidden' way to configure the scanner that won't bother people that don't care, and i support a more complex version than just renaming directories (the file algorithm i opened in https://github.com/libretro/RetroArch/issues/8672 ) because it allows more and better control.

**Comment by diegopau** [comment] 2019-08-06 08:38
I am very new to RetroArch and have little knowledge about the internal works of it. I am using Retroarch in a Playstation Classic (Retroboot). I think I can be considered the "regular user" so I wanted to share my experience with this issue:

When I first tried Retroarch I moved my collection of Mega Drive roms to a "megadrive" folder and then I used the Scan Folder functionality inside Retroarch. Honestly I expected this to just work since all the roms are either .gen, .md, .smd or a zip file with the rom in any of those formats and all I wanted is have them on a playlist that can be quickly accessed. After scanning them I found out that around half of the games where there, the other half not. 
My reaction to this was to take a look to the folder structure and try to match the folder names of thumbnails, playlists, roms folder. This time i was really convinced I understood what the problem was, I even renamed a few name files to match the thumbnail names. I thought: if all the folders have the same name, Retroarch will already know that these are Mega Drive files because I am matching the name "Sega - Mega Drive - Genesis" everywhere, and the thumbnails have same name as the files... this has to work.

After another scan the problem was still there. I could see some thumbnails now, but big part of the roms were not there. Those roms come from different sources across time, some are hacks and translations, all or at least most worked always with different emulators.
I then found out about how Retroarch is trying to match every single file to a database and if it doesn't the game it is not added. It was a disappointment, I tried to see the database file but it doesn't seem to be in plain text. I gave up. My father was also struggling with the same thing when adding his ZX Spectrum games, some that he programmed himself decades ago.
Yes you an always manually load a game and add it to favorites, but it is not the same, what we love about Retroarch is precisely that feeling of having your full collection there, tidy, with playlists and thumbnails, and right now it is only possible with lots of manual editing to manually build playlists to basically bypass Retroach's way of doing things.

Another problem I see with not having an option of building playlists bypassing the database matching is that it really takes a huge amount of time in some cases, and if you have a big collection and you just added one new game it seems like it would try to match it all again, sometimes that means hours of leaving there the Playstation Classic working on it. For some people like me we wish to just add the games in a basis of 1 entry per file or 1 entry per subfolder, and skip completely any match against a database. Then the thumbnails just have to match the filename, which is much easier to understand for the average user in my opinion than trying to understand what specific ROM you have to get (if you can) so it is accepted or to manually edit playlists (I actually tried and I wasn't successful with that).

I just wanted to share my point of view as a new user. Maybe many of the things I comment here or suggest comes from too much ignorance about how it should work and they are just not possible. Thank you for reading. And big thanks for Retroarch!

**Comment by Mte90** [comment] 2019-10-18 21:05
I am just an user that every month discover a new homebrew game, load on retroarch, do a scan but is not found.
After a month that I not play with retroarch I don't remember the game name and I have to look in the folders in the ui to launch it.

It is very disappointing to not have an option to add in the playlist a game that is not in the database by folders.
I can accept also a prompt to ask for a confirm but is very annoying to use another computer for this task...

**Comment by wafflesinmybauble** [comment] 2019-12-18 12:22
I don't mean to rez bump this, but just as a heads up to anyone, make sure that your scan path doesn't include any escape characters at the beginning of a folder name, such as an underscore. For example "_NoFiller"

**Comment by i30817** [comment] 2019-12-20 12:49
How the hell is underscore considered a 'escape' character (do you mean it's ignored by the scanner?)

**Comment by RobLoach** [comment] 2020-01-26 19:53
This discussion has diverged a long way from its original intent. The Manual Scan is I. Now, I suggest you use that for odd cases like what are discussed.

**Closed by RobLoach** 2020-01-26 19:53 UTC
Labels: bug: scanner

**Comment by borrelnoten** [comment] 2021-02-16 20:09
I don't know why this topic is closed. I can't put my atari ST roms in a playlist. I tried to scan manualy but still no luck. They are not original games but hacked menu from crack scene (compressed  multiple games onto a disc decompression when loading a game).
I want to have a list of my Atari discs so that I can play them without having ot select them manualy (loading the entire directory with roms every time I select one).

Same goes for the amiga discs (HDR extention) which are not picked up for some reason. The manual scan does not work. Also I have tried to make the LPL file manualy and that works! But not for long because after selecting and playing a disc on the list, the list is upaded and is empty after returning from the emulated game to the retroarch menu / playlist.

I really would love to see Atari ST and Amiga discs in the playlist because they are truely historic value for me.
I do not understand why that is so difficult because it is simply a simple file list without extention. I do not care about auto detection at all. Also, why not just accept the manual crafted playlist? Why distroy it after selecting an item in it?  I love retroarch but the playlist thing is really not logical for me.

**Comment by RobLoach** [comment] 2021-02-16 21:07
> I do not understand why that is so difficult because it is simply a simple file list without extention. I do not care about auto detection at all.

Unfortunately it's not that simple. How do we know what system it's for? There are lots of cores, all with different use cases, and platforms. A file without an extension could be associated with virtually any of them. There has been a lot of clean up in the scanner to add support for these platforms.

> Also, why not just accept the manual crafted playlist? Why distroy it after selecting an item in it?

There is noone saying that manual crafted playlists are a bad thing. If a manual scan is destroying the existing playlist, this sounds like a new issue. Feel free to create one detailing re-produce steps and what you expect to happen.
