### ISSUE TITLE
Patching on the fly crashes RA

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3679] opened 2016-09-28 05:56 UTC
Happens with IPS and BPS, didn't have any UPS patches handy to test.
@bparker06 sounds related to the content loading changes, just pinging you in case you think it's related

> `cont(gdb)
> Continuing.
> [Thread 15160.0x2b8c exited with code 0]
> [Thread 15160.0x2e74 exited with code 0]
> [New Thread 15160.0x3bc0]
> [Thread 15160.0x1150 exited with code 0]
> [Thread 15160.0x3e10 exited with code 0]
> [New Thread 15160.0x9c4]
> 
> Thread 1 received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 15160.0x1b60]
> 0x00000000004176ec in encoding_crc32 (crc=<optimized out>, crc@entry=0,
>     buf=0x18c9c041 <error: Cannot access memory at address 0x18c9c041>,
>     len=<optimized out>) at libretro-common/encodings/encoding_crc32.c:86
> warning: Source file is more recent than executable.
> 86            crc = crc32_table[(crc ^ (*buf++)) & 0xff] ^ (crc >> 8);
> (gdb) bt
> # 0  0x00000000004176ec in encoding_crc32 (crc=<optimized out>, crc@entry=0,
> 
> ```
> buf=0x18c9c041 <error: Cannot access memory at address 0x18c9c041>,
> len=<optimized out>) at libretro-common/encodings/encoding_crc32.c:86
> ```
> # 1  0x0000000000414bb3 in load_content_into_memory (length=0x3cc4f88,
> 
> ```
> buf=0xffdc4a8,
> path=0x64d57d0 "C:\\Windows\\Temp\\Hyper Metroid (USA) (Hack).sfc", i=0)
> at tasks/task_content.c:342
> ```
> # 2  load_content (special=0x0, content=0xfedc660, info=0xffdc4a0,
> 
> ```
> temporary_content=0xfedc440) at tasks/task_content.c:528
> ```
> # 3  content_file_init (temporary_content=0xfedc440)
> 
> ```
> at tasks/task_content.c:731
> ```
> # 4  content_init () at tasks/task_content.c:808
> # 5  0x0000000000409dec in event_init_content () at command.c:1313
> # 6  command_event_init_core (data=0x7ac1a4 <current_core_type>)
> 
> ```
> at command.c:1379
> ```
> # 7  command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT,
> 
> ```
> data=data@entry=0x7ac1a4 <current_core_type>) at command.c:2239
> ```
> # 8  0x0000000000404a41 in retroarch_main_init (argc=0, argv=0x3cc6850,
> 
> ```
> argv@entry=0x3cc6750) at retroarch.c:1039
> ```
> # 9  0x0000000000413f14 in content_load (info=0x3cc9840)
> 
> ```
> at tasks/task_content.c:279
> ```
> # 10 task_load_content (content_info=content_info@entry=0x3cc98d0,
> 
> ```
> launched_from_menu=launched_from_menu@entry=false,
> mode=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU)
> at tasks/task_content.c:897
> ```
> # 11 0x0000000000414d8f in command_event_cmd_exec (
> 
> ```
> mode=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU,
> data=0x64e08e0 "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Hyper Metroid (USA) (Hack).zip")
> at tasks/task_content.c:1012
> ```
> # 12 task_push_content_load_default (
> 
> ```
> core_path=core_path@entry=0x3cc99e0 "D:\\PortableData\\GameData\\Emulators\\RetroArch\\libretro\\snes9x_libretro.dll",
> fullpath=0x64e08e0 "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Hyper Metroid (USA) (Hack).zip", content_info=content_info@entry=0x3cca9e0,
> type=type@entry=CORE_TYPE_PLAIN,
> mode=mode@entry=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU,
> cb=cb@entry=0x0, user_data=user_data@entry=0x0)
> at tasks/task_content.c:1149
> ```
> # 13 0x0000000000499ae0 in generic_action_ok_file_load (
> 
> ```
> content_enum_idx=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU,
> action_type=CORE_TYPE_PLAIN, fullpath=<optimized out>,
> corepath=0x3cc99e0 "D:\\PortableData\\GameData\\Emulators\\RetroArch\\libretro\\snes9x_libretro.dll") at menu/cbs/menu_cbs_ok.c:810
> ```
> # 14 action_ok_playlist_entry_collection (path=<optimized out>,
> 
> ```
> label=<optimized out>, type=<optimized out>, idx=<optimized out>,
> entry_idx=0) at menu/cbs/menu_cbs_ok.c:1032
> ```
> # 15 0x000000000049403a in menu_entry_action (entry=entry@entry=0x3ccbb10,
> 
> ```
> i=<optimized out>, action=action@entry=MENU_ACTION_OK)
> at menu/widgets/menu_entry.c:384
> ```
> # 16 0x00000000004b6dc4 in generic_menu_iterate (data=0xff3e670,
> 
> ```
> userdata=<optimized out>, action=MENU_ACTION_OK)
> at menu/drivers/menu_generic.c:244
> ```
> # 17 0x000000000047efc6 in menu_driver_ctl (
> 
> ```
> state=state@entry=RARCH_MENU_CTL_ITERATE, data=data@entry=0x3ccfcc0)
> at menu/menu_driver.c:886
> ```
> # 18 0x0000000000411c47 in runloop_iterate_menu (sleep_ms=0x3ccfde0,
> 
> ```
> action=MENU_ACTION_OK) at runloop.c:1146
> ```
> # 19 runloop_iterate (sleep_ms=sleep_ms@entry=0x3ccfde0) at runloop.c:1303
> # 20 0x00000000004016c0 in rarch_main (argc=<optimized out>,
> 
> ```
> argv=<optimized out>, data=0x0) at frontend/frontend.c:128
> ```
> # 21 0x0000000000651928 in WinMain ()
> # 22 0x00000000004013ed in __tmainCRTStartup ()
> 
> ```
> at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
> ```
> # 23 0x000000000040152b in mainCRTStartup ()
> 
> ```
> at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:212
> ```
> 
> (gdb)
> `
> `cont(gdb)
> Continuing.
> [Thread 15160.0x2b8c exited with code 0]
> [Thread 15160.0x2e74 exited with code 0]
> [New Thread 15160.0x3bc0]
> [Thread 15160.0x1150 exited with code 0]
> [Thread 15160.0x3e10 exited with code 0]
> [New Thread 15160.0x9c4]
> 
> Thread 1 received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 15160.0x1b60]
> 0x00000000004176ec in encoding_crc32 (crc=<optimized out>, crc@entry=0,
>     buf=0x18c9c041 <error: Cannot access memory at address 0x18c9c041>,
>     len=<optimized out>) at libretro-common/encodings/encoding_crc32.c:86
> warning: Source file is more recent than executable.
> 86            crc = crc32_table[(crc ^ (*buf++)) & 0xff] ^ (crc >> 8);
> (gdb) bt
> # 0  0x00000000004176ec in encoding_crc32 (crc=<optimized out>, crc@entry=0,
> 
> ```
> buf=0x18c9c041 <error: Cannot access memory at address 0x18c9c041>,
> len=<optimized out>) at libretro-common/encodings/encoding_crc32.c:86
> ```
> # 1  0x0000000000414bb3 in load_content_into_memory (length=0x3cc4f88,
> 
> ```
> buf=0xffdc4a8,
> path=0x64d57d0 "C:\\Windows\\Temp\\Hyper Metroid (USA) (Hack).sfc", i=0)
> at tasks/task_content.c:342
> ```
> # 2  load_content (special=0x0, content=0xfedc660, info=0xffdc4a0,
> 
> ```
> temporary_content=0xfedc440) at tasks/task_content.c:528
> ```
> # 3  content_file_init (temporary_content=0xfedc440)
> 
> ```
> at tasks/task_content.c:731
> ```
> # 4  content_init () at tasks/task_content.c:808
> # 5  0x0000000000409dec in event_init_content () at command.c:1313
> # 6  command_event_init_core (data=0x7ac1a4 <current_core_type>)
> 
> ```
> at command.c:1379
> ```
> # 7  command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT,
> 
> ```
> data=data@entry=0x7ac1a4 <current_core_type>) at command.c:2239
> ```
> # 8  0x0000000000404a41 in retroarch_main_init (argc=0, argv=0x3cc6850,
> 
> ```
> argv@entry=0x3cc6750) at retroarch.c:1039
> ```
> # 9  0x0000000000413f14 in content_load (info=0x3cc9840)
> 
> ```
> at tasks/task_content.c:279
> ```
> # 10 task_load_content (content_info=content_info@entry=0x3cc98d0,
> 
> ```
> launched_from_menu=launched_from_menu@entry=false,
> mode=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU)
> at tasks/task_content.c:897
> ```
> # 11 0x0000000000414d8f in command_event_cmd_exec (
> 
> ```
> mode=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU,
> data=0x64e08e0 "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Hyper Metroid (USA) (Hack).zip")
> at tasks/task_content.c:1012
> ```
> # 12 task_push_content_load_default (
> 
> ```
> core_path=core_path@entry=0x3cc99e0 "D:\\PortableData\\GameData\\Emulators\\RetroArch\\libretro\\snes9x_libretro.dll",
> fullpath=0x64e08e0 "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Hyper Metroid (USA) (Hack).zip", content_info=content_info@entry=0x3cca9e0,
> type=type@entry=CORE_TYPE_PLAIN,
> mode=mode@entry=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU,
> cb=cb@entry=0x0, user_data=user_data@entry=0x0)
> at tasks/task_content.c:1149
> ```
> # 13 0x0000000000499ae0 in generic_action_ok_file_load (
> 
> ```
> content_enum_idx=CONTENT_MODE_LOAD_CONTENT_FROM_PLAYLIST_FROM_MENU,
> action_type=CORE_TYPE_PLAIN, fullpath=<optimized out>,
> corepath=0x3cc99e0 "D:\\PortableData\\GameData\\Emulators\\RetroArch\\libretro\\snes9x_libretro.dll") at menu/cbs/menu_cbs_ok.c:810
> ```
> # 14 action_ok_playlist_entry_collection (path=<optimized out>,
> 
> ```
> label=<optimized out>, type=<optimized out>, idx=<optimized out>,
> entry_idx=0) at menu/cbs/menu_cbs_ok.c:1032
> ```
> # 15 0x000000000049403a in menu_entry_action (entry=entry@entry=0x3ccbb10,
> 
> ```
> i=<optimized out>, action=action@entry=MENU_ACTION_OK)
> at menu/widgets/menu_entry.c:384
> ```
> # 16 0x00000000004b6dc4 in generic_menu_iterate (data=0xff3e670,
> 
> ```
> userdata=<optimized out>, action=MENU_ACTION_OK)
> at menu/drivers/menu_generic.c:244
> ```
> # 17 0x000000000047efc6 in menu_driver_ctl (
> 
> ```
> state=state@entry=RARCH_MENU_CTL_ITERATE, data=data@entry=0x3ccfcc0)
> at menu/menu_driver.c:886
> ```
> # 18 0x0000000000411c47 in runloop_iterate_menu (sleep_ms=0x3ccfde0,
> 
> ```
> action=MENU_ACTION_OK) at runloop.c:1146
> ```
> # 19 runloop_iterate (sleep_ms=sleep_ms@entry=0x3ccfde0) at runloop.c:1303
> # 20 0x00000000004016c0 in rarch_main (argc=<optimized out>,
> 
> ```
> argv=<optimized out>, data=0x0) at frontend/frontend.c:128
> ```
> # 21 0x0000000000651928 in WinMain ()
> # 22 0x00000000004013ed in __tmainCRTStartup ()
> 
> ```
> at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
> ```
> # 23 0x000000000040152b in mainCRTStartup ()
> 
> ```
> at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:212
> ```
> 
> (gdb)
> `

**Comment by fr500** [comment] 2016-09-28 05:57
Tagging as major bug, all crashes are major.

**Comment by fr500** [comment] 2016-09-28 06:00
Tried with non-zipped content too:

> Thread 1 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 15656.0x3af8]
0x00000000004176ec in encoding_crc32 (crc=<optimized out>, crc@entry=0,
    buf=0x1947e041 <error: Cannot access memory at address 0x1947e041>,
    len=<optimized out>) at libretro-common/encodings/encoding_crc32.c:86
warning: Source file is more recent than executable.
86            crc = crc32_table[(crc ^ (*buf++)) & 0xff] ^ (crc >> 8);
(gdb) bt
#0  0x00000000004176ec in encoding_crc32 (crc=<optimized out>, crc@entry=0,
    buf=0x1947e041 <error: Cannot access memory at address 0x1947e041>,
    len=<optimized out>) at libretro-common/encodings/encoding_crc32.c:86
#1  0x0000000000414bb3 in load_content_into_memory (length=0x3cc7018,
    buf=0x11dd7818,
    path=0x650fec0 "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Mega Man X3 - Zero Project (Hack).sfc", i=0) at tasks/task_content.c:342
#2  load_content (special=0x0, content=0x11de26d0, info=0x11dd7810,
    temporary_content=0x11de2010) at tasks/task_content.c:528
#3  content_file_init (temporary_content=0x11de2010)
    at tasks/task_content.c:731
#4  content_init () at tasks/task_content.c:808
#5  0x0000000000409dec in event_init_content () at command.c:1313
#6  command_event_init_core (data=0x7ac1a4 <current_core_type>)
    at command.c:1379
#7  command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT,
    data=data@entry=0x7ac1a4 <current_core_type>) at command.c:2239
#8  0x0000000000404a41 in retroarch_main_init (argc=0, argv=0x3cc88e0,
    argv@entry=0x3cc87e0) at retroarch.c:1039
#9  0x0000000000413f14 in content_load (info=0x3cc87d8)
    at tasks/task_content.c:279
#10 task_load_content (content_info=content_info@entry=0x3ccba00,
    launched_from_menu=launched_from_menu@entry=true,
    mode=CONTENT_MODE_LOAD_CONTENT_WITH_NEW_CORE_FROM_MENU)
    at tasks/task_content.c:897
#11 0x0000000000414f48 in task_push_content_load_default (
    core_path=0x3ccbb10 "D:\\PortableData\\GameData\\Emulators\\RetroArch\\libretro\\snes9x_libretro.dll",
    fullpath=fullpath@entry=0x812920 <detect_content_path> "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Mega Man X3 - Zero Project (Hack).sfc",
    content_info=content_info@entry=0x3ccba00,
    type=type@entry=CORE_TYPE_FFMPEG,
    mode=mode@entry=CONTENT_MODE_LOAD_CONTENT_WITH_NEW_CORE_FROM_MENU,
    cb=cb@entry=0x0, user_data=user_data@entry=0x0)
    at tasks/task_content.c:1240
#12 0x00000000004966b9 in generic_action_ok_file_load (
    content_enum_idx=CONTENT_MODE_LOAD_CONTENT_WITH_NEW_CORE_FROM_MENU,
    action_type=CORE_TYPE_FFMPEG,
    fullpath=0x812920 <detect_content_path> "..\\..\\EmulatorData\\Games\\Console\\Super Nintendo Entertainment System\\Hacks & Translations\\Hacks\\Mega Man X3 - Zero Project (Hack).sfc", corepath=<optimized out>)
    at menu/cbs/menu_cbs_ok.c:810
#13 action_ok_file_load_detect_core (path=<optimized out>,
    label=<optimized out>, type=<optimized out>, idx=<optimized out>,
    entry_idx=0) at menu/cbs/menu_cbs_ok.c:1878
#14 0x000000000049403a in menu_entry_action (entry=entry@entry=0x3ccbb10,
    i=<optimized out>, action=action@entry=MENU_ACTION_OK)
    at menu/widgets/menu_entry.c:384
#15 0x00000000004b6dc4 in generic_menu_iterate (data=0x11d5e670,
    userdata=<optimized out>, action=MENU_ACTION_OK)
    at menu/drivers/menu_generic.c:244
#16 0x000000000047efc6 in menu_driver_ctl (
    state=state@entry=RARCH_MENU_CTL_ITERATE, data=data@entry=0x3ccfcc0)
    at menu/menu_driver.c:886
#17 0x0000000000411c47 in runloop_iterate_menu (sleep_ms=0x3ccfde0,
    action=MENU_ACTION_OK) at runloop.c:1146
#18 runloop_iterate (sleep_ms=sleep_ms@entry=0x3ccfde0) at runloop.c:1303
#19 0x00000000004016c0 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:128
#20 0x0000000000651928 in WinMain ()
#21 0x00000000004013ed in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:334
#22 0x000000000040152b in mainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:212

**Comment by twinaphex** [comment] 2016-09-29 17:37
This should be fixed now, please test again.

**Comment by bparker06** [comment] 2016-09-30 00:58
Works for me now.

**Comment by fr500** [comment] 2016-10-13 23:46
It no longer crashes, but it doesn't patch

**Comment by fr500** [comment] 2016-10-13 23:47
Hmmm
it does patch with SNES9X, fails to patch with BSNES

**Comment by GeneralFailer** [comment] 2016-12-09 16:04
Works with bsnes, crashes with "Fatal error received in (IPS)." with Nestopia for me.

**Comment by retro-wertz** [comment] 2016-12-09 16:11
mapper 23 roms, right?

**Comment by GeneralFailer** [comment] 2016-12-09 16:18
Yeah.

**Comment by orbea** [comment] 2018-12-24 18:19
@fr500 and @LaserMoai Is this still an issue?

**Comment by fr500** [comment] 2018-12-24 18:54
it's patching fine in my experience

**Comment by LaserMoai** [comment] 2018-12-24 19:40
Yeah, patching works now.

**Comment by orbea** [comment] 2018-12-24 19:51
Thanks for the feedback! I'm going to close this issue now until someone else can reproduce these problems.

**Closed by orbea** 2018-12-24 19:51 UTC
Labels: bug: major
