### ISSUE TITLE
Shader presets loaded but gui not refreshing

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4626] opened 2017-02-13 06:17 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When loading a game/core that has a saved shader preset the shader is loaded correctly, the effect is applied, as expected, etc. BUT the shader isn't loaded on the GUI, so the menu is empty or has whatever other shader that was loaded before.

### Expected behavior

Going to the menu would show the actual shaders loaded

### Actual behavior

It shows whatever shader was loaded before manually or more likely in

### Steps to reproduce the bug

1. Load a game, select a shader and save it as game preset
2. Close the game, load another game and select a different shader
3. Go back to the first game, the shader is loaded as it should but on the menu you'll see the shader from the second game

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Windows 10 x64
- Compiler: [In case you are running local builds]

**Comment by AlexFolland** [comment] 2017-02-13 14:55
Confirmed here too.  I've followed the reproduction steps and reproduced this bug.

**Comment by Tatsuya79** [comment] 2017-03-23 17:17
Bisect points to:
https://github.com/libretro/RetroArch/commit/899601e7bbd8e08304f1287dc6c8f5f80c3bbe88

**Comment by fr500** [comment] 2017-03-23 17:20
Hey @twinaphex this change causes this issue, not sure what to do about it though

**Comment by twinaphex** [comment] 2017-03-23 18:15
See if this fixes things -

https://github.com/libretro/RetroArch/commit/541c1b34e172095e328ce98c6f9567485f884748

**Comment by Tatsuya79** [comment] 2017-03-23 21:55
That's working now.
Great work.

**Comment by orbea** [comment] 2018-12-26 01:37
This seems to be fixed so I am going to close this issue.

**Closed by orbea** 2018-12-26 01:37 UTC
Labels: bug: major
