### ISSUE TITLE
[ps2] Quicknes No sound when load another rom file

### ISSUE THREAD

**Issue by tomudo** [libretro/RetroArch#9254] opened 2019-08-06 15:16 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
I'm not sure it is really quicknes core bug because quicknes core on PC has no problem like this.
It has sound while running rom file( .nes) on first time. Load next rom file ("Load conten" from GUI) has no sound.

### Expected behavior
Load next rom has sound.

### Actual behavior

Video is normal but no sound

### Steps to reproduce the bug

1. Load Content and select rom (.nes) file 
2. Bring up menu and load another rom file

### Bisect Results
no sound on 2nd rom file
### Version/Commit
You can find this information under Information/System Information

- RetroArch:  PS2 quicknes build on 2019-08-05 15:06 download from http://buildbot.libretro.com/nightly/playstation/ps2/

### Environment information

- OS: PS2 system with free mcboot

**Comment by LibretroAdmin** [comment] 2022-09-03 05:09
@fjtrujy Does this bug still happen or has it been fixed by now?

**Comment by fjtrujy** [comment] 2022-09-03 08:20
This no longer reproducible because the core is reloaded every time a rom is loaded.
You can close it

**Closed** 2022-09-03 10:38 UTC
Labels: platform: ps2, core bugs - not retroarch bugs
