### ISSUE TITLE
Issues with outputting in exclusive fullscreen to a secondary monitor in Windows

### ISSUE THREAD

**Issue by GPDP2** [libretro/RetroArch#2699] opened 2016-02-05 06:21 UTC
In recent builds, whenever I set RetroArch to output to a secondary monitor in exclusive fullscreen, if the existing desktop resolution said monitor is set to differs from the resolution I'm telling RetroArch to output at (say, if the desktop is set to 1024x768 and I tell RetroArch to output at 640x480), RetroArch will appear windowed at first. To get it to display in exclusive fullscreen on the secondary monitor properly, I have to do one of two things: either toggle fullscreen off, then back on (i.e. press F twice), or make sure the desktop resolution is already set to the resolution I want RetroArch to output before I run the program. Outputting to the primary monitor, for whatever reason, is perfectly fine, and does not suffer from this problem.

Thankfully, I mentioned this problem elsewhere, and a kind anonymous person ran a git bisect, and located the commit that causes this:

https://github.com/libretro/RetroArch/commit/8327302d6b92dd11467e6a1facabfa557ede6a43

Sure enough, a build right before that commit does not have this issue.

**Comment by fr500** [comment] 2016-02-24 16:27
@twinaphex @GPDP2  referenced this commit https://github.com/libretro/RetroArch/commit/8327302d6b92dd11467e6a1facabfa557ede6a43

**Comment by Monroe88** [comment] 2016-02-26 05:02
This issue seems to affect the WGL context driver only and not the D3D9 driver. 

The WGL driver also seems to longer fail when trying to set an undefined resolution mode, it just renders it on top of the screen instead of exiting immediately, unlike the D3D driver.

This is a screenshot of what happens:

https://a.pomf.cat/lvavve.png

Reverting the referenced commit restores the correct WGL non-windowed fullscreen behavior, though that causes the video mode setting code to be duplicated.

**Comment by Themaister** [comment] 2016-03-29 13:42
I think I found what might be going wrong, there is one very subtle bug in win32_set_style that could cause GetMonitorInfo to not work properly, which should be the cause for this problem:

https://github.com/libretro/RetroArch/pull/2825/commits/87a5fd2e44984a236ceb92ec530b23e6626d1e4b

**Comment by Themaister** [comment] 2016-03-29 13:54
It is merged now, so might work.

**Comment by Monroe88** [comment] 2016-03-30 00:47
Fullscreen on secondary monitor is working fine now, it goes straight to fullscreen like it's supposed to.

**Comment by fr500** [comment] 2016-03-30 01:00
it seems to flicker less times at startup/shutdown too!

**Closed** 2016-03-30 09:28 UTC
Labels: minor bug, unconfirmed
