### ISSUE TITLE
I have a feature request 

### ISSUE THREAD

**Issue by Yeetboi6364** [libretro/RetroArch#14277] opened 2022-08-03 17:45 UTC
I would like if retroarch automatically pauses the game when your controller dies

**Comment by bslenul** [comment] 2022-08-03 18:56
Duplicate of #13307 and #13016 but I agree, that would be a great addition.

**Comment by sonninnos** [comment] 2022-08-04 16:57
And the issue should be at least somewhat readable in the title..

**Comment by hizzlekizzle** [comment] 2022-08-04 18:14
We should probably just pick one of these tickets and then close the others.

**Closed** 2022-08-04 19:10 UTC

**Comment by Yeetboi6364** [comment] 2022-08-05 02:59
Sorry guys didn't know someone already requested this
