### ISSUE TITLE
OK and cancel are swapped for the second controller when a remote control is detected

### ISSUE THREAD

**Issue by Oibaf66** [libretro/RetroArch#5671] opened 2017-11-13 13:10 UTC
## Description

OK and cancel are swapped for the second controller when the "all users control menu" option is on and when the second controller is a remote control.

### Expected behavior

OK and cancel should behave the same for the first and second controller

### Environment information

- OS: Andoid

**Comment by bparker06** [comment] 2017-11-13 23:18
Is it possible your gamepad config's concept of what the A and B buttons are on your two controllers are just different?

**Comment by bparker06** [comment] 2017-11-14 15:30
I just tried this myself and was unable to reproduce the issue. Can you try on the latest nightly?

**Comment by Oibaf66** [comment] 2017-11-16 08:38
I tried the nightly build of 15 November but the autoconfig seems broken. Also other functions are broken (i.e. core loading, list of the cores).

**Comment by twinaphex** [comment] 2017-11-16 10:33
Having no such issues with the F-Droid nightlies on Shield Tablet.

**Comment by Oibaf66** [comment] 2017-11-22 08:35
The issue regards the use of a remote control and a Joystick for the Android  O.S.

**Comment by Oibaf66** [comment] 2017-11-23 18:58
I checked that with two joysticks the autoconfig works properly.
The issues affects only the case of a joystick and a remote controller.
I noticed that in all the config files of remote controllers the OK and cancel are reversed. This is likely due to the fact that with Android OS, OK and cancel are swapped by default.

**Comment by Oibaf66** [comment] 2017-11-23 20:07
Here it is the reason of the issue.

When a remote control is detected as first controller, the OK and cancel are swapped for all the controllers.


**task_autodetect.c**

if (string_is_equal_fast(device_type, "remote", 6))
   {
      static bool remote_is_bound        = false;

      snprintf(msg, sizeof(msg), "%s configured.",
            (string_is_empty(display_name) &&
             !string_is_empty(params->name)) ? params->name : (!string_is_empty(display_name) ? display_name : "N/A"));

      if(!remote_is_bound)
      {
         task_free_title(task);
         task_set_title(task, strdup(msg));
      }
      remote_is_bound = true;
      if (params->idx == 0)
         **input_autoconfigure_swap_override = true;**
   }

**menu_event.c** 

 bool input_swap_override                = input_autoconfigure_get_swap_override();
   unsigned menu_ok_btn                    = (!input_swap_override && 
      settings->bools.input_menu_swap_ok_cancel_buttons) ?
      RETRO_DEVICE_ID_JOYPAD_B : RETRO_DEVICE_ID_JOYPAD_A;
   unsigned menu_cancel_btn                = (!input_swap_override && 
      settings->bools.input_menu_swap_ok_cancel_buttons) ?
      RETRO_DEVICE_ID_JOYPAD_A : RETRO_DEVICE_ID_JOYPAD_B;

**Comment by fr500** [comment] 2017-12-26 19:07
well yeah the swap ok cancel stuff is unique (not implemented on a per-port basis)
so it will swap for everything

**Comment by orbea** [comment] 2018-12-31 01:02
I'm inclined to think this is not a bug and is working as intended, if you swap the okay and cancel buttons you should expect them to be swapped.

I'm going to close this, but if you feel strongly about this a feature request to make it configurable for each gamepad too might be considered by someone with the right skill set.

**Closed by orbea** 2018-12-31 01:02 UTC
