### ISSUE TITLE
[regression] RA closes in the second load, if first core was mame git

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2602] opened 2015-12-27 02:39 UTC
RA is closing in the second load of any core, when you first use the mame git.

Started at c0a1a6a

**Comment by bootsector** [comment] 2016-01-05 08:36
Confirmed! The bad part is that exit code seems to be left at zero, making my retrobox setup to think that I've chosen "Quit RetroArch" so it would shutdown. :-(

**Comment by sergiobenrocha2** [comment] 2016-01-15 02:30
Happening with mame 0.157 and mame2014 too.

**Comment by bootsector** [comment] 2016-01-19 14:33
Is it fixed on 1.3 stable release?

**Comment by sergiobenrocha2** [comment] 2016-01-19 15:57
Nope.

**Comment by twinaphex** [comment] 2016-01-19 15:59
Yes, it happens with any core that can 'shutdown' itself, another example is Prboom.

Unfortunately I don't know yet why it happens but we better make it a priority for 1.3.1.

**Comment by Kivutar** [comment] 2016-01-19 16:03
Oh I see

So I reference this issue https://github.com/libretro/libretro-prboom/issues/15
And this one too https://github.com/libretro/Lakka/issues/268

**Comment by twinaphex** [comment] 2016-01-19 16:05
Yes, it's the same issue.

**Comment by bootsector** [comment] 2016-01-19 22:05
For now I've commented out line # 685 from dynamic.c:

      case RETRO_ENVIRONMENT_SHUTDOWN:
         RARCH_LOG("Environ SHUTDOWN.\n");
         //runloop_ctl(RUNLOOP_CTL_SET_SHUTDOWN,      NULL);
         runloop_ctl(RUNLOOP_CTL_SET_CORE_SHUTDOWN, NULL);
         break;

It seems to fix the problem and I will keep using it until you guys more fluent with RetroArch's runloop innards come up with the proper fix!

**Comment by Hypnotoad90** [comment] 2016-05-22 01:08
This problem remains an issue for me still.

**Comment by dankcushions** [comment] 2016-07-09 18:35
i get this in mame2010 also. it calls `RETRO_ENVIRONMENT_SHUTDOWN` and RA exits, as it is being asked to do: https://github.com/libretro/mame2010-libretro/blob/a4537c34e89dd0e1402ee1a79943104dbe47c90f/src/osd/retro/retromapper.c#L129

is it as simple as these mame cores calling `RETRO_ENVIRONMENT_SHUTDOWN` when they shouldn't? i don't see why mame should have the ability to exit everything - there's no 'exit' in the TAB menu for example. could we just comment this line out?

**Comment by bootsector** [comment] 2016-07-09 18:41
I'm using RA 1.3.0 with that line commented out and today I've noticed what could be a side effect of that "quick fix". If using playlists (I wasn't using them until today), whenever I start any game on any system, it doesn't start at the first time. I need to choose the Run command again in order to get the game started.

To summarize: we really need a proper fix for this issue!

**Comment by dankcushions** [comment] 2016-07-09 18:48
@bootsector do you mean your fix from before, or my fix from just now?

**Comment by bootsector** [comment] 2016-07-09 19:03
Oh, I didn't realize you have it fixed! For sure I was talking about my half assed solution! Going to try your fix now! Thanks!

**Comment by dankcushions** [comment] 2016-07-09 19:24
@bootsector i'm not sure i'd call it a fix :) but for sure if I comment out https://github.com/sselph/scraper/blob/66ede3dcd652d6a9702380336b8516955930330a/ds/ds.go#L19 then i can load a game in 2010, then load a game in (some other core), and no exits. 

(i've not tested this in mame-current, but i guess if you comment out https://github.com/libretro/mame/blob/master/src/osd/retro/libretro.cpp#L429 and rebuild it will also work?)

i guess the question is, should these cores ever be able to shut down the whole of RA? mame2010 at least doesn't have a 'quit' option in the TAB menu or whatever.

**Comment by orbea** [comment] 2018-12-24 18:12
@twinaphex or @sergiobenrocha2 Do you know if this is still a problem?

**Comment by twinaphex** [comment] 2019-01-14 04:09
I'll close it for now. If @sergiobenrocha2 can still reproduce it, he can re-open this.

**Closed by twinaphex** 2019-01-14 04:09 UTC
Labels: bug: major
