### ISSUE TITLE
Crash when entering menu with core override that loads different video driver setting (opengl -> vulkan)

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4588] opened 2017-02-07 21:16 UTC
## Description

If a core override is saved with "vulkan" as the video driver setting and that core is run from RA's menu that was loaded with "gl" as the video driver setting, entering the menu causes a crash.

### Expected behavior

no crash

### Actual behavior

crash

### Steps to reproduce the bug

1. Set video driver to "gl"
2. Load and run a core that has no core override
3. Enter menu
4. Change "video driver" setting to "vulkan"
5. Save core override from quick menu
6. Close RA
7. Run RA and check menu to verify "video driver" is set to "gl".  If not, set to "gl" and close RA then run RA again
8. Load and run the core you saved the core override for earlier
9. Try to enter menu

### Version/Commit
a2141e61f771ce7bf16f08097d4923c5d0202e59

### Environment information

- OS: Win7-64
- Compiler: mingw-w64-x86_64-gcc-6.3.0-1

### Stack trace

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004ff380 in gl_raster_font_render_line (font=0x1acd1190, msg=<optimized out>, msg_len=<optimized out>, scale=1, color=0x22ea90, pos_x=inf, pos_y=-nan(0x400000), text_align=0) at gfx/drivers_font/gl_raster_font.c:328
328              gl_raster_font_emit(0, 0, 1); /* Bottom-left */
(gdb) bt
#0  0x00000000004ff380 in gl_raster_font_render_line (font=0x1acd1190, msg=<optimized out>, msg_len=<optimized out>, scale=1, color=0x22ea90, pos_x=inf, pos_y=-nan(0x400000), text_align=0) at gfx/drivers_font/gl_raster_font.c:328
#1  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by AlexFolland** [comment] 2017-02-09 22:15
For me, this currently happens every time I run a game with Snes9x, since I wish to use Vulkan for it, but I wish to use OpenGL for other cores.  The only workaround currently is to run RA, switch video driver, close RA, open RA, and run the core.  This applies every time I want to run a core with with one video driver or the other video driver, currently.  Also, the problem is invisible until the user tries to open the menu, as that's when it crashes, which may be deep into gameplay or even when they go to quit.  It will cause them to lose all their progress if they don't have SRAM Autosave Interval enabled.

While I am not sure what is truly happening, I suspect RA is running the core with Vulkan, but forgetting to set the menu driver (in my case XMB) to run with Vulkan as well when it loads the core override, so it is trying to load an OpenGL context and that is causing the crash.  I know this is speculation and it usually doesn't help, but I'm hoping it might.  I think this might be the case because the stack trace says ```gl_raster_font_render_line``` ```at gfx/drivers_font/gl_raster_font.c:328```.

**Comment by hizzlekizzle** [comment] 2017-04-06 21:22
Closing this as a dupe of #4804 , since a solution to it would fix this as well

**Closed by hizzlekizzle** 2017-04-06 21:22 UTC
