### ISSUE TITLE
[Vita] No achievements setting?

### ISSUE THREAD

**Issue by erfg12** [libretro/RetroArch#4853] opened 2017-04-26 20:52 UTC
No achievements setting for Vita?

**Comment by fr500** [comment] 2017-04-28 23:27
There is no socket support on vita.
Next time, use the issue submission template.

**Comment by frangarcj** [comment] 2017-04-29 11:41
@fr500 there's socket support on vita

**Comment by frangarcj** [comment] 2017-04-29 11:43
Duplicate of #4752

**Closed by frangarcj** 2017-04-29 11:43 UTC
Labels: invalid: duplicate
