### ISSUE TITLE
Per game/core hotkey and input configuration doesn't work

### ISSUE THREAD

**Issue by boomercore** [libretro/RetroArch#10453] opened 2020-04-15 14:30 UTC
This is one of the few options that won't stick when you attempt to save/load a core/game configuration file.  Whenever I save or load the settings per game/core it just goes right back to the universal hotkey assignments. Could this be fixed in the future?   

There are some cores where RB being fast forward would work out great, but this wouldn't work as a universal setting as it wouldn't play well with PS1 cores.  Now that I think of it, this seems to be a problem with general input settings as I can't save/load lightgun binds from the general Retroarch/Input section either per game.  I always have to map the SuperScope while the game is loaded.

Thank you.

**Comment by fraf** [comment] 2020-04-15 19:13
Duplicate of issue #6641 !

**Closed** 2023-01-24 00:42 UTC
