### ISSUE TITLE
RetroArch will NOT "scan a directory" for MAME/FBA

### ISSUE THREAD

**Issue by Dochartaigh** [libretro/RetroArch#4459] opened 2017-01-20 00:58 UTC
Description:
Using "Scan Directory" on any FBA/MAME/etc. romset will not populate the menu with those ROMs.

Expected behavior:
I expect my clrmamePro verified ROMs (tried merged and non-merged romsets for 0.175 and 0.78) to show up in the menu underneath the MAME or FBA icon.

Actual behavior:
Nothing happens at all after scanning. Maybe 5-10 out of hundreds show up, but that's it.

Steps to reproduce the bug:
1. Load your MAME or FBA core of choice.
2. Go to the + and select "Scan Directory".
3. Select your directory where the matching (i.e. the correct romset for the core you selected in step one) romset ROMs are stored.
4. Select "Scan this Directory"
5. Once scanning is complete exit out to the main menu and notice only a few ROMs, or none at all, are listed under the appropriate MAME or FBA icon.

Bisect Results:
I've been trying this off and on for a full year (on all the recent 'stable' releases on RetroArch). I've tried it on a Windows 7 PC, Windows 10 PC, Mac running Yosemite, El Capitan, and Sierra, and a PS VIta and PSP (~10 computers/devices total)

Version/Commit
Neither "Version" or "Commit" are listed when I go into Information/System Information. 

RetroArch:
1.40

Environment information:
I've tried it on a Windows 7 PC, Windows 10 PC, Mac running Yosemite, El Capitan, and Sierra, and a PS VIta and PSP (~10 computers/devices total) - none will add more than a few ROMs to the menu.

Additional info:
These ROMs will load (with the correct core) if I select them individually - the problem is they simply will not be added to the menu under their system icon (unlike my NES/SNES/Sega Genesis, GBA, N64, etc. ROMs which all show up properly). Romsets are the most common type from archive-org and the like, and again, are verified with clrmamePro. I've been trying non-merged sets mainly, but this week I made merged sets for 0.78 and 0.175 and those do not work either. I've tried this on so many different computers and devices, running so many different OS's it's not even funny. I've made several different forum posts on several different forums and it seems like nobody can get this to work. Please let me know if there's anything I can do to test or provide more information and I will.

**Comment by fr500** [comment] 2017-01-20 02:54
DO you actually have a MAME or FBA core installed?

**Comment by bparker06** [comment] 2017-01-20 02:56
To my knowledge, MAME/FBA roms will only scan if the database contains a CRC that matches the file being scanned. For mame git, this doesn't exist. The only database RA has (that I know of) for mame that contains CRCs is mame2003 (v0.78): https://github.com/libretro/libretro-database/tree/master/dat

For that to also work, you'll at least need the mame2003 core, its info file and the rdb database for it.

If you have all that and still aren't seeing the majority of your roms, I would double check the dat listed above and make sure the crcs match what you have on your drive, perhaps your files were re-compressed or not really v0.78 something that might change the crc.

If you're finding files that do match and aren't being scanned, then that is something we can look into.

**Comment by Dochartaigh** [comment] 2017-01-20 03:12
mame2003 core is what I use 99% of the time with my 0.78 romset (only 6 roms I play don't work on that which I use FBA/0.175 for). The 0.78 romset is the full 'official reference set' most everybody uses and does come with mame.exe, and the 'MAME 078.dat' file (along with samples, utilities, and all that good stuff).

I've never heard of a rdb database before (and evidently neither have the members of all those forums I posted on trying to get to the bottom of this issue ;)

I take it there are extra steps requires to scan MAME which cores for systems like NES, SNES, Sega Genesis, and Playstation do not need? Can you please kindly link me to a tutorial showing me how to use these additional info file and rdb database and I will try it out?

**Comment by retro-wertz** [comment] 2017-01-20 03:34
retroarch's database(rdb) will only scan and successfully import fbalpha
2.97.39 romsets(well most of it with some issues with pgm romsets). its
mame database will scan only mame.78(mame2003) romsets but that seems not
crc accurate.

in order for rom romsets to match retroarch's database(and use the import
content to play in playlst), you should run your roms with torrentzip after
verifying working sets with clrmame.

you can also still manually play using load core>detect core method or just
use @markwkidd's playlist generator from the forums.

**Comment by Dochartaigh** [comment] 2017-01-20 03:49
retro-wertz, if I'm hearing your correctly, you've also experience that RetroArc's CRC's for mame2003 are incorrect just like I have?

I only have a mere 6 ROM's that don't work in 0.175 which I use FB Alpha for. When I install the "Arcade (FB Alpha)" core, and scan the directory with those 6, nothing is added just like mame2003. Now for 2.97.39, there is only ONE SINGLE source for that romset on the entire public internet (barring some super-secret private websites or whatnot). How do I know this? Because it literally took me a solid month to find that romset to download, and I've confirmed with not one but two moderators/master-genius-programmers of the RetroPie project that's the one they're using and basing their code off of. It's a merged set around 10GB. It's MD5 checksums also DO NOT match what RetroArch has listed on the above link under "FB Alpha - Arcade Games.dat"...


 for confirming that RA has the incorrect CRC's listed for Mame2003 - that's the only conclusion I could come to as well.

**Comment by markwkidd** [comment] 2017-01-20 03:56
@Dochartaigh This is simultaneously being discussed on the forum, although I don't know if you will find an immediate answer there: https://forums.libretro.com/t/romsets-for-mame2003-and-fba-should-be-non-merged-or-splitted/6608/15

For what it's worth I have no idea what I need to do to make my 0.78 ROMs scan correctly. In the end I found it easier to create a tool that will create the RetroArch playlist for me. The example setup in the instructions is even for processing MAME 0.78 ROMs: https://forums.libretro.com/t/ahk-playlist-buddy-playlist-and-thumbnail-generation-for-retroarch/8417

(BTW: I know of three public FB Alpha ROM sets online. One is Non-Merged and can be found the same way as the 0.78 Reference Set you mentioned. The second one is Split but only has arcade games, rather than the full set. The third set I'm not sure about but maybe it's the Merged one you describe. What a world!)

**Comment by Dochartaigh** [comment] 2017-01-20 04:11
Mark! I've been hearing a lot about your tool. I posted on that forum as well (ok, like 3 times actually I think...even making a separate topic specifically for this)... maybe 2? 3? days ago? Totally dead there - no response. No response on GBAtemp for a day or so either. Reddit - like 2 or 3 different subforums - silent (or, well, like lots on reddit just nothing that helps). Facebook, dead. Tried multiple chat rooms and ICQ and such and it's like the silence is deafening! I've been cross-linking posts even to try to get more attention to this!

I'm actually on a Mac so I'll have to try your tool at work on an ancient xeon that takes like 10 minutes to boot-up... I think that's the only option right now if RetroArch is using the wrong CRC/MD5's (no offense RetroArch, your heart is in the right place and you're software is still awesome! ...although I hate you of late lol. What got me started is how 43 PSX games took 7 HOURS TO SCAN on a PS Vita....7 hours, really? All 'official' ReDumps too....but at least those finally scanned, MAME scanning is totally bricked ;)

**Comment by markwkidd** [comment] 2017-01-20 04:17
Some AHK programs can be run on OS X via WINE. No one has tried to run the AHK Playlist Buddy that way though, so I don't know if it would work for you on your Mac. If you do try WINE please consider letting me know about your results: https://www.winehq.org/

**Comment by Dochartaigh** [comment] 2017-01-20 04:29
Wineskin and me have an unsettling history together. Kinda like the hangovers I get from drinking real wine ;) - just easier for me to boot up in bootcamp if I really have to - or use the PC at work is what I usually do (that's where I use clrmamePro as well). Thanks though!

**Comment by Dochartaigh** [comment] 2017-01-20 20:04
Can anyone give me the exact .LPL playlist filename that retroarch uses on a PS VITA? - I need the filenames for mame2003 and FB Alpha.

If I get those I think I can manually add a playlist to my PS Vita handheld and have all my arcade games show up under the correct icon.

Mark's tool worked on my PC and the playlist is correctly setup there - and this should easily translate over to my Mac as well (although I haven't done that yet).

**Comment by rsn8887** [comment] 2017-01-21 02:30
What's so hard about just torrentzipping your roms to make all this work?

**Comment by markwkidd** [comment] 2017-01-21 02:37
TorrentZip will not cause a non-merged MAME 0.78 ROM to be added to a playlist. (In fact I would guess that the OP's 0.78 ROMs were already processed by TZ.)

**Comment by Dochartaigh** [comment] 2017-01-21 04:57
That's correct Mark, I'm 99% sure the romsets I'm using were zipped with TZ as TZ comes in the utilities folder along with clrmamePro (all the complete romsets usually come with all the tools used to make them, verify them, and run the ROMs).

Now if TZ is used when I made my merged and split romsets (which I also tried to get RetroArch to recognize, and which likewise failed) from the original non-merged romset, I honestly don't know (never thought to check for that option while I was making them).

Regardless, RetroArch is awesome for automatically working with the most popular romsets for systems like NES, SNES, Sega Genesis, TG16, PSX, Game Boy, etc. etc. etc...just needs some work with mame/arcade.

**Comment by fr500** [comment] 2017-01-25 05:29
Seems this is not really a RetroArch bug.
RA can't have databases for  every rom version under the sun. Feel free to discuss this matter further.

**Closed** 2017-01-25 05:29 UTC

**Comment by Bonobomagno** [comment] 2017-03-02 23:36
This is not a bug, but a wanted features!
Why not just import last mame db?

**Comment by Gamer75** [comment] 2017-08-23 01:56
I know this OLD post but Gotta question about thumbnailed that I downloaded ! I had rename the folder MAME 2014 it show up all my icons but there is problems is that I have three others core which is 2000 2003 2010 I would like to link to one folder (10.9GB) instead duplicated folder for each year. So far RetroArch have been kind to me so I am new to frontend but I have use mame since 2000 standalone emulators I know what I am talking about !there way you make link MAME core and FB Alpha since I have been reading they are pretty much borrow from MAME boxart etc... folder! Everything is working great it been learning experience in last couple days! I customize icons from google image and reading alot on this Retro Arch Forum. I think my brain going fried due alot of reading Thanks Thomas

**Comment by LOCOxCHAPA** [comment] 2023-03-13 02:12
2023 and i have the same problem, any solution?
