### ISSUE TITLE
2 Similar Crashs when Selecting Overlay Preset or Video Filter.

### ISSUE THREAD

**Issue by CaptainCoward** [libretro/RetroArch#5402] opened 2017-09-04 18:43 UTC
## Description
Selecting any Overlay-Preset will crash/freeze retroarch
Same happens when selecting any "Filter" from the Video Settings

### Expected behavior

Not crashing

### Actual behavior

Retroarch will freeze

### Steps to reproduce the bug

Select any Filter on Settings>Video>Video Filter 
or
Select any KEYBOARD or GAMEPAD Overlay Preset from Settings>OnscreenDisplay>Onscreen Overlay 

### Version/Commit

1.6.7 Git a235c0b Windows (10)

### Environment information

- OS: Windows 10 (x64)

**Comment by fr500** [comment] 2017-09-06 02:57
I don't get the issue with overlay presets.

**Comment by CaptainCoward** [comment] 2017-09-07 17:25
Sorry i should have been more specific.
Borders and effects work fine. But choosing any keyboard or gamepad preset crashs retroarch on my end. I updated my original post.

**Comment by ToniAlvarez** [comment] 2017-09-15 20:55
I have the same issue. RetroArch crash when selecting gamepad psx overlay. Windows 10 64 bits.

**Comment by Oibaf66** [comment] 2017-12-02 18:23
Same issue for me. Windows 10 64 bits. Retroarch 1.6.7

**Comment by retro-wertz** [comment] 2017-12-02 18:26
but were already version 1.6.9 now, maybe try updating 1st and see if issue
still persists

**Comment by Oibaf66** [comment] 2017-12-02 20:22
With version 1.6.9 the issue is not present anymore. Tested with 32 and 64 bit versions.
The issue can be closed for me.

**Comment by orbea** [comment] 2018-12-31 23:14
I think these are fixed so I am going to close this, but please let us know if this is mistaken!

**Closed by orbea** 2018-12-31 23:14 UTC
