### ISSUE TITLE
Glorious Gaming Mouse Model D not working on Retroarch

### ISSUE THREAD

**Issue by 1985a** [libretro/RetroArch#15733] opened 2023-09-24 13:00 UTC
In retroarch the mouse does not work, If you press any buttons it does not respond to any kind of input. 
According to the log, it's been recognized as a keyboard and touch device.
I did test with other input driver and shows the same issue.
I'm on Archlinux and the GCC version is 13.2.1 and the Retroarch version is 1.16.0 or git 041ae30103

I drop the log file here.

[retroarch.log](https://github.com/libretro/RetroArch/files/12708539/retroarch.log)

**Comment by zoltanvb** [comment] 2023-10-02 04:45
It seems to be detected as second mouse. Can you try changing mouse index in Input / RetroPad Binds / Port 1 controls? And/or enabling Input / Menu Controls / All users control menu.

**Comment by 1985a** [comment] 2023-10-02 19:36
Really, sorry, my bad. I currently have 2 mouse devices connected to my PC. The thing is, one of them is off, nevertheless, its USB device keeps saying there is another mouse in my PC.
I just changed the index and now the mouse is working.

I don't know how can I let this happen to me
Wao, really sorry for my mistake and making this thread.

**Comment by zoltanvb** [comment] 2023-10-03 19:11
No worries, and thank you for submitting a clear issue report and a proper log!
You may close the issue, if the problem is resolved now.

**Closed** 2023-10-03 20:36 UTC
