### ISSUE TITLE
retroarch doesn't work for me in freebsd

### ISSUE THREAD

**Issue by zsoltszasz** [libretro/RetroArch#5655] opened 2017-11-05 18:28 UTC
Hi, 
I installed retroarch from ports but it does not work under my user account. Here is the output:

$ retroarch --menu --verbose
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 
Built: Nov 4 2017
RetroArch [INFO] :: Version: 1.3.6
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Looking for config in: "/home/zsolt/.config/retroarch/retroarch.cfg".
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: /home/zsolt/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
error: XDG_RUNTIME_DIR not set in the environment.
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Found GL context: x
RetroArch [INFO] :: Detecting screen resolution 1280x800.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 960, H = 720.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: X.Org, Renderer: AMD RV620 (DRM 2.29.0 / 12.0-CURRENT, LLVM 4.0.1).
RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 17.2.3.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => exists
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: GL: Using resolution 960x720
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
RetroArch [WARN] :: [SDL]: Failed to initialize haptic device support: SDL not built with haptic (force feedback) support
RetroArch [INFO] :: Found joypad driver: "sdl2".
RetroArch [INFO] :: Using font rendering backend: bitmap.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/home/zsolt/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: Saving config at path: "/home/zsolt/.config/retroarch/retroarch.cfg"
RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [INFO] :: Saved new config to "/home/zsolt/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: [X11]: Xinerama version: 1.1.
RetroArch [INFO] :: [X11]: Xinerama screens: 1.
RetroArch [INFO] :: [X11]: Saved monitor #0.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

I can see a black windows for a second then nothing. Do you guys can you tell me what to check?
Under root it segfaults. 

Best regards,

**Comment by orbea** [comment] 2017-11-05 20:25
Can you try 1.6.7 and and the master to see if its any better? 1.3.6 is kind of old at this point.

**Comment by zsoltszasz** [comment] 2017-11-06 07:08
The version I am using is the latest ported to freebsd: 
https://www.freshports.org/games/retroarch/
so, I think I can't.

**Comment by orbea** [comment] 2017-11-06 14:15
Yes you can.
```
git clone https://github.com/libretro/RetroArch/
cd RetroArch
./configure && gmake && ./retroarch
```

**Comment by ensra** [comment] 2017-11-06 15:54
The latest RetroArch runs really well on NetBSD, and most libretro cores too btw. There were some problems (iirc) with the X11 drivers, so we use SDL2 instead (--disable-x11 --enable-sdl2 --enable-opengl).

Source is here. You can use pkgsrc on FreeBSD too btw: https://github.com/NetBSD/pkgsrc-wip/tree/master/retroarch

**Comment by bparker06** [comment] 2017-11-06 17:16
@zsoltszasz Using orbea's instructions I can run the latest RetroArch on FreeBSD 11 just fine under X11 with AMD drivers (Nvidia should work too).

**Comment by orbea** [comment] 2017-11-06 17:18
@ensra Are these issues reported? It would be good to know that RetroArch works as well as it can on NetBSD.

**Comment by ensra** [comment] 2017-11-06 20:05
@orbea 

Honestly, after redoing some tests, I can't reproduce most of the problems I found a few versions ago. So, never mind...

The X11 problems I experienced seem to be the same as issue #3969 (besides the stuff about GLSL, which might be the OP of that issue getting confused).

We might have got confused when testing xvideo, since it has no support for the menu system (the unaccelerated SDL driver does), but honestly I have no idea anymore. The main point is that X11 works now.

[Thread Local Storage was disabled on NetBSD](https://github.com/NetBSD/pkgsrc-wip/blob/master/retroarch/Makefile#L35) because of an assertion failure in libpthread when RetroArch 1.5.0 exited. Was this knowingly fixed in RetroArch? Can the workaround be safely removed?

**Comment by zsoltszasz** [comment] 2017-11-06 20:29
@orbea 

Following your advice I received this error message on while running gmake:

...
LD retroarch
obj-unix/input/drivers/wayland_input.o: In function `input_wl_init':
/usr/home/zsolt/RetroArch/input/drivers/wayland_input.c:267: undefined reference to `rarch_key_map_linux'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:148: retroarch] Error 1

What I am doing wrong?

**Comment by ensra** [comment] 2017-11-06 20:45
@zsoltszasz Configure with --disable-wayland?

**Comment by zsoltszasz** [comment] 2017-11-07 06:14
ok, its working! Thank you guys!

**Closed** 2017-11-07 06:49 UTC

**Comment by orbea** [comment] 2017-11-07 13:36
@zsoltszasz It had that error even with the default configure flags? Do you have wayland installed? I can test building RetroArch on FreeBSD and did not have this issue, but of course the FreeBSD environment I have access to is non-graphical so I can't test running it.

**Comment by zsoltszasz** [comment] 2017-11-07 17:43
I received that error on default configure I think because I dont have wayland, xorg-minimal is what I use. I will get back to you which regards other issues, if I will encounter any of course. This test system which I use is not 100% stable which regards packages or dependencies, maybe the problem is only valid for my test system. 
Which regards sound what is the minimum requirement? I dont have alsa or pulse...

**Comment by orbea** [comment] 2017-11-07 21:17
That is strange, you should not receive that error even without wayland installed. Additionally neither bparker or I seem to be able to reproduce that when building on FreeBSD. On Linux, Windows and some other platforms you can download the cores from the buildbot, but no one has set this up for FreeBSD so you will have to compile them yourself. This can be quite easy, clone the repo for the core you want and use `gmake` to build it. You may have to use `gmake -f Makefile.libretro` or similar with some cores. The cores will be compiled as a `.so` file.

**Comment by zsoltszasz** [comment] 2017-11-27 15:59
I reinstalled Freebsd 12 and now I have a cleaner os. What I would like to achieve is to run retroarch without xorg. I setup kms. I also installed retroarch from ports and all the dependencies (its now updated at version 1.3.6_9). Sadly, its not starting at all - it segfaults. I attached a log file. Do you want to look at it? 

Kind regards, 
[error.txt](https://github.com/libretro/RetroArch/files/1506511/error.txt)

**Comment by orbea** [comment] 2017-11-27 16:08
Try a newer RetroArch version...

**Comment by zsoltszasz** [comment] 2017-11-27 19:18
Ok, I got the latest version from github as you described earlier in this post. I tried to compile it and I receive an error message. I attached a log here. I'm stuck now. What to do next?

[error2.txt](https://github.com/libretro/RetroArch/files/1507249/error2.txt)

**Comment by myfreeweb** [comment] 2018-04-10 20:35
Hi, if this is still relevant, you can find my update of the port [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227345). Hopefully soon it will be in official ports/packages.

**Comment by zsoltszasz** [comment] 2018-04-12 09:06
Nice, I will definitely check it out.
