### ISSUE TITLE
RA Wiiu broken controls, Gamepad is always controlling player 1

### ISSUE THREAD

**Issue by Hielkenator** [libretro/RetroArch#8111] opened 2019-01-28 07:49 UTC
Retroarch Always controls 2 players even when 1 user is selected.

### Expected behavior

Using a wiimote with classic controller to play player one in 2 player games for instance super mario allstars , super mario bros 3 cannot be played in one player with wiimote and classic controller attached.

[What is actually happening]
I cannot play above mentioned game. The game registered 2 inputs allthough theres one active in the ra gui. I want to be able to play as player one in sma super mario bros 3, I cannot start thsi game in 1 player mode. The game inherntly won't let me cause it thinks 2 players are connected, like on the original snes.

### Steps to reproduce the bug

1. disable all user inputs except player one
2. start super mario allstars  and select super mariobros 3.
3. try to select 1 player game

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
Build jan 1 2019, git version 556bcc1
PPC

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment] 2019-01-28 13:32
Seems to be a duplicate of issue https://github.com/libretro/RetroArch/issues/8111.

**Closed by orbea** 2019-01-28 13:32 UTC
