### ISSUE TITLE
Dolphinbar takes priority over xbox pads.

### ISSUE THREAD

**Issue by chris243** [libretro/RetroArch#3402] opened 2016-08-18 11:55 UTC
Any way to make it so player one is always xbox pad 1 and player 2 is xbox pad 2 etc?
I only use dolphinbar with dolphin so if I could disable it completely in retroarch I think that would solve my problem. Once I unplug the dolphin bar everything works as it should but since this is on a living room pc that my kids use(I use bigbox to launch everything) plugging and unplugging the dolphinbar is not really an option.

**Comment by markwkidd** [comment] 2016-08-18 13:18
I believe this is an issue that has come up in another context as well: https://github.com/libretro/RetroArch/issues/3337

**Comment by fr500** [comment] 2016-08-18 15:30
The problem is that windows doesn't provide a way to reorder pads. We use the driver exposed controller ids to assign pads to port 1 2 3 etc.

**Comment by markwkidd** [comment] 2016-08-18 15:32
Evidently a similar issue exists in Linux/Lakka. Is there any other resolution than https://github.com/libretro/RetroArch/issues/3337 ?

**Comment by fr500** [comment] 2016-08-18 15:35
I don't want #3337 to happen to be honest.
The best solution imho would be to map on button press instead of on enumeration, so, add all the controllers to a temporary "slot" and when a button press registers move them to port 1, the next one to port 2 and so on.

Interestingly enough, this is how it works on android but that's only because the pads aren't enumerated till a button is pressed.

**Comment by fr500** [comment] 2016-08-19 02:59
https://github.com/libretro/RetroArch/issues/2060

**Comment by Papermanzero** [comment] 2016-08-25 06:51
You can set the preferred controller in the windows settings under devices.
Just select one game controller and then the properties.

**Comment by fr500** [comment] 2016-09-22 05:10
Won't be fixed (ie, no priority for controllers) but it should still be addressed by https://github.com/libretro/RetroArch/issues/2060 once it happens

**Closed by fr500** 2016-09-22 05:10 UTC
Labels: won't fix
