### ISSUE TITLE
Suspended screen rapidly flashes different colors in RetroArch menu if core is using RGB1555 pixels 

### ISSUE THREAD

**Issue by bleakassassin** [libretro/RetroArch#9615] opened 2019-10-19 00:28 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

If you open the RetroArch menu while content running in a core using the RGB1555 color space is running, the paused content's image will rapidly flash various colors, creating a strobe-like effect. This can be dangerous to people who are susceptible to seizures.

I'm not well-versed in this subject, but I was asked to open an issue here instead of the core-specific "Issues" area. For reference: https://github.com/libretro/bsnes/issues/4

### Expected behavior

The paused content's image should strictly be dimmed.

### Actual behavior

The paused content's image flashes different colors rapidly.

### Steps to reproduce the bug

1. Load a core that uses the RGB1555 color space. (ex. the new bsnes core, aka "bsnes-hd")
2. Load content supported by that core.
3. When that content is displaying any kind of image that isn't strictly monochrome, open the RetroArch menu.

### Bisect Results

I'm not sure how often this has occurred. I've only noticed it in the new bsnes core, which has only been out since v1.7.8., and it's happened since I first tried it there.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.7.9

### Environment information

- OS: Windows 10 Home 64-Bit

**Comment by hizzlekizzle** [comment] 2019-10-19 17:57
BearOso suggested that this is likely caused by RetroArch converting the colors (properly?) but then doing it again on the next frame, making it flash funky colors. I don't think anyone has actually verified that this is what's happening definitively, but it seems both plausible and probably easy to correct.

**Comment by rz5** [comment] 2019-10-25 04:10
@bleakassassin - Should be fixed by #9629.

**Comment by hizzlekizzle** [comment] 2019-10-25 23:09
Since the fix is in, I'll close this. Reopen if it doesn't fix it.

**Closed by hizzlekizzle** 2019-10-25 23:09 UTC

**Comment by bleakassassin** [comment] 2019-11-06 01:38
Sorry for the late response. I can confirm that it's fixed. Thank you!
