### ISSUE TITLE
[udev] Mouse inputs are being processed even if retroarch window is not active.

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#5520] opened 2017-10-08 07:12 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Mouse inputs/movements are read in retroarch even if its not currently the active window.

### Expected behavior

Should stop getting inputs if its not active window, especially when running different applications in window mode.

### Actual behavior

It moves when you move mouse, it clicks when you click.

During a game mode(like cores which makes use of retro_device_pointer interface as lightgun/mouse) pointer keeps moving and reading mouse clicks.

In menu mode, you just need the active window over the retroarch window and ra will intercept movement and clicks..

### Steps to reproduce the bug

1. Prepare the system 1st. add yourselft to input group, restart. load retroarch. switch input to udev. restart retroarch. Make sure to set corrent Mouse Index(make sure mouse is indeed working in retroarch).
2. Now with things setup. run retroarch mouse should be able to navigate the menu.
3. Run another application, probably a browser or something that uses a mouse. make that application the current active window(but make retroarch's window viewable on screen. overlap you active window with retroarch and place the mouse pointer where portion of retroarch's window is suppose to be
4. Now move or click mouse in the active window(the pointer should be still within retroarchs window) and retroarch should react to inputs even if its not active.

4-extra - when running a gun game or core which uses retro_device_pointer like genesis_plus_gx or fceumm, crosshair should keep moving even if the pointer is not within retroarchs window.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 6a5ad56bc

### Environment information

- OS: Arch
- Compiler: 7.2.0 64bit

**Comment by casdevel** [comment] 2017-10-08 16:19
Changes at [https://github.com/casdevel/RetroArch/tree/fix-5520](https://github.com/casdevel/RetroArch/tree/fix-5520) should disable mouse input when window is not active.

Regarding '4-extra', I tested this with input debugger core and I couldn't reproduce that issue. Mouse input is available to the core even if the pointer is outside of the window. Let me know which game and  input device did you use and I'll try again.

**Comment by retro-wertz** [comment] 2017-10-08 18:50
genesis_plus_gx should be a good test since it uses retro_device_pointer for its light phaser - lethal enforcers(japan) for example, of course you cannot see crosshair moving since by default, emulation is paused when not an active window, need to disable dont run in background.

this behaviour does not happen compared to other drivers and to add the crosshair is now misaligned compared to where the pointer is in udev.

**Comment by casdevel** [comment] 2017-10-09 19:18
Correct me if I'm wrong, you expect that mouse movement is always enabled and the rest of the mouse input only when window is active?

Regarding misaligned crosshair, if you are referring to different positions of core crosshair/pointer and OS pointer, this is normal (since #5512). Core can have up to 16 independent pointers (when using udev input driver) while OS has only one. It's impossible to have multiple mice support and core pointer(s) which follow system pointer.

**Comment by orbea** [comment] 2018-12-31 16:17
@retro-wertz Correct me if I am wrong, but this was fixed a while ago? I can't reproduce it with the master at least.

**Comment by orbea** [comment] 2018-12-31 16:55
Okay, I can reproduce it now too...

If both programs are on the same window manager workspace while the windows are not overlapping this does not seem to happen.

However if I hover the mouse over `Load Core`, change to another workspace with another program running and then press the mouse without moving it it will press `Load Core` too.

This does not seem to happen with the `x` input driver.

**Comment by orbea** [comment] 2018-12-31 16:56
@casdevel Maybe you might have an idea how to resolve this?

**Comment by orbea** [comment] 2018-12-31 17:21
@retro-wertz Actually I spent enough time staring at this file failing to fix an unrelated issue that this was easy, can you please test it. :)

**Closed** 2019-01-06 00:56 UTC
Labels: bug: major, bug: udev, platform: linux
