### ISSUE TITLE
RetroArch crashing upon startup

### ISSUE THREAD

**Issue by XNOm3** [libretro/RetroArch#5139] opened 2017-07-02 03:39 UTC
Upon first downloading RetroArch, i have not been able to successfully start it once. It crashes upon startup, and appears to happen with any version i download.

My system information is as follows:
Dell Latitude D620 running 32-bit Windows 7 installation
Intel Core 2 Duo T5600
Intel 945GMA iGPU (Intel's drivers, not the ones windows installed, also appears to use OpenGL 1.4)
and 3GB of RAM

I've tried various fixes, including changing the video driver in the config file, trying MSVC builds, and the older 1.3.6 build, none of them have seemed to stop the issue (although changing the video driver to d3d did seem to delay it somewhat, although nothing appeared to change in that time frame)

Any help would be greatly appreciated.

**Comment by bparker06** [comment] 2017-07-02 12:36
Did you try the gdi video driver? That may be the only one that works for your system.

**Comment by orbea** [comment] 2019-01-01 21:58
Since this issue hasn't any responses in over a year I am going to close it, please respond if anyone can reproduce this still.

**Closed by orbea** 2019-01-01 21:58 UTC
