### ISSUE TITLE
Can't run Retroarch 1.3.6

### ISSUE THREAD

**Issue by FeRcHuLeS** [libretro/RetroArch#3818] opened 2016-10-17 19:11 UTC
Hi, when I try to enter retroarch 1.3.6 a message pops ups something related with _itoa_s & msvcrt.dll and retroarch can't run, I'm still using Windows xp sp3.

**Comment by fr500** [comment] 2016-10-17 19:34
We don't really have any mentions of _itoa_s on the code so I'm guessing it's a compiler problem.

**Comment by hizzlekizzle** [comment] 2016-10-17 19:41
See this thread from the forums: http://libretro.com/forums/showthread.php?t=6150

**Comment by FeRcHuLeS** [comment] 2016-10-17 19:57
Thank you @hizzlekizzle that patched and fixed the executable, but I can't find mednafen saturn core does this core needs high requirements? or is a 64-bits core? as I posted I'm still in Windows xp sp3 32-bits

**Comment by hizzlekizzle** [comment] 2016-10-18 00:37
Correct, 64-bit only. I'm not sure if it's going to be that way forever or if 32-bit support will be added later.

**Comment by SigmaVirus** [comment] 2016-10-19 10:43
I don't think adding 32-bit support at this stage would benefit anyone since many developers/projects have started dropping support for 32-bit altogether and besides it would only be counterproductive.

The best example of this is Dolphin which have dropped both 32-bit and DX9 support since long.

Come to think of it, I'm not even sure if I use any 32-applications today at all or even have any installed.

This is a personal statement but it's for the best to focus on 64-bit only, 32-bit isn't part of any future anymore and is a dead end.

The same goes for Windows XP which had it's End of extended support date expire on April 8, 2014 which were around two and a half years ago!!

So I'm sorry but it's dead, @FeRcHuLeS if possible try to upgrade to something newer, and most importantly 64-bit.

I'm sorry if I came out a little to harsh, but this is my sentiments about it.

**Comment by twinaphex** [comment] 2016-10-19 11:17
I still want to keep RetroArch as backwards compatible as possible regardless, having it still work on XP is inline with that.

**Comment by lasers** [comment] 2016-10-19 11:41
Questions about backward compatible / portability. How can I move my `~/.config/retroarch` somewhere else to like `~/RetroArch` without using `ln -s`? I see `--config PATH`... and for fun, I tried something like `RWD="$(mktemp -d /tmp/retroarch.XXX)" ; retroarch -c "$RWD/retroarch.cfg"` and it will still get everything from `~/.config/retroarch` for assets, history, playlists, games, etc (as intended).

It is something I was pondering about because there are no option like `--home=PATH` where you can point it at the whole folder (and not just cfg alone) for portability and to be able to spin up a fresh copy of RetroArch for testing.

**Comment by SigmaVirus** [comment] 2016-10-19 12:53
@twinaphex
Fair enough I suppose, it's your project and you are free to do whatever you want with it so no arguments there.

I lied however, I do have some 32-bit applications on my system.
pcsx2, ScummVM and some PC Games but that's about it.

**Comment by hizzlekizzle** [comment] 2016-10-19 15:51
@lasers 
There's no single option that will make it start looking in other directories, but you can change the paths in settings > directory to point wherever you want.

**Comment by jason-oliveira** [comment] 2016-12-01 22:15
issue is resolved; should be closed.

**Comment by fr500** [comment] 2016-12-01 23:30
Wait how was this fixed? we didn't change anything

**Comment by orbea** [comment] 2017-10-22 08:31
@FeRcHuLeS Does the latest nightly work? If so can you close this issue?

**Closed** 2018-10-15 05:00 UTC
