### ISSUE TITLE
Analog Remapping Breaks Controls

### ISSUE THREAD

**Issue by SeongGino** [libretro/RetroArch#9431] opened 2019-09-05 03:42 UTC
## Description

Under a selected core's Quick Settings -> Controls, remapping valid controller axis (Left/Right Analog X/Y -/+) to anything other than defaults results in the input not being recognized in-game, as if the control is unmapped. Setting the axis back to its default will allow it to function normally again (which means axis that are unmapped by default cannot be used period). The only exception is the usage of Analog to Digital, which can allow the assigned analog stick to serve as an emulated D-Pad, but nothing more.
This bug does not affect traditional buttons or triggers recognized as axis (i.e. Xinput device).

### Steps to reproduce the bug

1. Start any game or core: preferably, `aburner2` (After Burner 2) using the FB Neo core. In this example, observe the left stick functioning as player movement, and the right stick up/down serving as ship throttle with accurate analog functionality to each; your selected game or core may function differently, but the result is the same and the default controls function as intended.
2. Open the UI, and enter the Controls submenu under the default Quick Settings.
3. For any input binding under Left analog/Right analog axis, change the default mapping (if any exists) to a desired command.
4. Close the menu and resume play. Observe that using the axis binded to the new controls cease to function, as if they are unbinded; any controls not changed from their defaults continue to work.
5. Open the UI, enter the Controls submenu, and change the redefined analog axis mappings back to their defaults from before you changed them in Step 3.
6. Close the menu and resume play. Observe that the axis restored to their original bindings work as before they were rebinded in Step 3.

These steps can be reproduced with any core.

### Bisect Results

Prior to publishing issue, this has been observed only on Android using 1.7.8 Stable (`aarch64`, buildbot APK). Since then, a Windows build of 1.7.7 Stable (`windows/x86_64`, buildbot ZIP) has been tested, and the analog axis remapping functionality was working as intended (changing mappings works in-game), and the same can be said of using an Android build of 1.7.7 Stable (`aarch64`, buildbot APK). Updating this Windows build to 1.7.8 Stable (`windows/x86_64`, buildbot ZIP) and the latest Nightly (commit below, same build type as before) breaks the functionality into the results seen above. 

### Version/Commit

Working - RetroArch: [1.7.7/Stable (3853d89)]
Regressed - RetroArch: [1.7.8/Stable (b3a4410e00) & Nightly (7cca6ea394)]

### Environment information

- OS: Windows 10 1903 x64 & Android Pie (64-bit) [OxygenOS 9.2.11]

**Comment by i30817** [comment] 2019-09-05 09:07
This might be relevant:

retropad handles only certain parts of itself as 'analog' and will freak out if it's mapped to a non-analog key and the core that maps the original console controls to the retropad tries to assign a 'original' analog key to a non-analog (physical) key on the other side of the retropad.

This was a issue in dolphin before, where the dolphin core was assigning 'Z' (a button on the gamecube controller that has a analog 'half pressed' function) to the retropad R (configured as a analog trigger), which is a digital key with a keyboard 'controller' [caused input not to be seen in some games](https://github.com/libretro/dolphin/issues/69)). 

[It was solved in the core by making a core hack.](https://github.com/libretro/dolphin/pull/75/files#diff-07bb0e795096d4abf9b008b24c2c437bR32)

> 
>     // If the analog trigger is at 0 but the digital trigger is set, we assume there's no analog trigger.
>     // Otherwise the analog trigger value takes precedence over the digital one.

**Comment by bslenul** [comment] 2019-09-05 09:53
Hm weird, I tried with After Burner 2 by mapping "Vulcan" (the machinegun) to left stick right direction and "Missile" to left stick left direction and yeah really strange behavior:

* When resuming I only have 1 of the 2 actions working, for example only the vulcan works (left stick right direction).
* If I hold the left direction and tilt the **right** stick up or right it starts to work but now right direction doesnt work anymore.
* If I want right direction to work again, same process: hold right then tilt down or left on the **right** stick.
* Both actions also work fine if I use left/right on the **right** stick, but they are unbinded in Quick Menu > Controls (set to `---`).

That's using a DS4 controller if it matters. Looks like RA is somehow "mixing" left and right analogs inputs or something?

**Comment by bslenul** [comment] 2019-09-05 11:56
Just spent like 1-2hrs compiling and testing older commits, seems like the problem is somewhere in this one: a88b357 because it works fine with the previous commit (da1ff54).

**Comment by i30817** [comment] 2019-09-05 14:16
That can't be right, because that commit has nothing to do with input handling. I recommend trying to bisect again, the error is probably on a commit after, or as a result of a subproject being updated.

**Comment by bslenul** [comment] 2019-09-05 14:23
Sorry for the confusion, I'm probably not using the correct "terms", I'm pretty new with the GitHub stuff :p What I mean basically is that the problem happens in one of these commits I circled in red in this image:

![](https://cdn.discordapp.com/attachments/469974542299955210/619167512529076259/unknown.png)

I only tested the "Verified" commits, so if its not a88b357 then its between this one and da1ff54.

**Comment by i30817** [comment] 2019-09-05 14:27
Ah ok. Someone should come along soon and point out which one of those broke it (probably a643f9e). I'd test it, but i don't actually have a controller with analog to do that, so someone else wil.

**Comment by SeongGino** [comment] 2019-09-05 14:35
Someone's going to have to check a643f9e and 05187f1 then. I suspect the latter is the last working commit and the former will exhibit these issues.
Currently don't have a building environment for it so someone else will have to confirm.

**Comment by bslenul** [comment] 2019-09-05 14:48
Ok so I've tested the commits between the 2 verified ones I mentionned, seems like it's 3ff237e thats causing issues, the previous one (a643f9e) works fine.

**Comment by twinaphex** [comment] 2019-09-05 19:44
I believe this should fix it -

https://github.com/libretro/RetroArch/commit/dec30677d95880d1890f36b518fe6c59a2a1edc6

@bslenul said this works for him. Let me know if it works for you too @SeongGino. 

If so, I will release a v1.7.8 revision 3 later this week with this fix incorporated for all platforms.

**Comment by SeongGino** [comment] 2019-09-06 14:13
@twinaphex 
Sorry for the wait, the commit works now and remapping works as intended.
Android nightlies still seem to be stuck in August builds at the moment though.

**Comment by hizzlekizzle** [comment] 2019-09-06 14:40
Ok, I'm going to close it for now, but once the Android builds update, if the problem is still there, feel free to reopen.

**Closed by hizzlekizzle** 2019-09-06 14:40 UTC
