### ISSUE TITLE
Added Korean Language Font Broken in XMB UI / Android Device

### ISSUE THREAD

**Issue by hong620** [libretro/RetroArch#4765] opened 2017-03-18 05:51 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

XMB UI, Android 4.4, Samsung SHV-E210K, RetroArch 1.5.0
New korean language in 1.5.0 is output as broken font.
alost text are alomost broken and unable to read, so change language to english on 'in-App' is also imposible.

if something functions like Language Recorgnize is forced on when without tested build pushed on public,
it could be trouble to some non-english users.

![screenshot_2017-03-18-02-40-16](https://cloud.githubusercontent.com/assets/12625315/24069334/e9da5518-0be8-11e7-8fc8-2761975bd94d.png)

### Expected behavior

Output korean font correctly

### Actual behavior

Korean language is output as broken font like square □□□□

### Steps to reproduce the bug

1. setting the UI to XMBUI
2. setting the language to korean before the update RetroArch 1.5.0 or just edit the config
3. excute RetroArch 1.5.0

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.5.0/can't check because build number text is also broken]

### Environment information

- OS: Android 4.4.4 KTU84P.E210KKTUKNI3
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment] 2017-03-18 13:08
The current font included with RetroArch does not have support for Korean, so the workaround at the moment is to manually change the font to something that does.

**Comment by hong620** [comment] 2017-03-18 14:32
then temporary drop 'Font-Depended Language' and check next time could be enough?

**Comment by Kivutar** [comment] 2017-03-18 22:28
Are there tools to easily merge missing glyphs from one font to another?

**Comment by hong620** [comment] 2017-03-19 06:08
without Korean Lanuage on RetroArch's 'In-App keyboard' function, '완성형' Korean Font is fair enough for fix the problem,
but if you want to add Korean Lanuage to RetroArch's 'In-App keyboard' function, then you have to use '조합형' Korean Font and add some difficulty IME implementation.

so, Android's own IME Pull-in to RetroArch is Bad, but Helpedful in this case.
I think **Drop** the Complicated Language like Korean in RetroArch's Keyboard function and just Focus on Support on Menu UI / In-Game Message Text seems enough fine **by now**.

**Comment by bparker06** [comment] 2017-03-23 16:05
@hong620 Hangul glyphs were recently added to the built-in RetroArch font in commit libretro/retroarch-assets@22e2ad7. Can you update your assets and try again?

**Comment by hong620** [comment] 2017-03-24 01:15
@bparker06 

![screenshot_2017-03-24-10-13-03](https://cloud.githubusercontent.com/assets/12625315/24276499/92976106-107a-11e7-818e-7a84f9bc81b5.png)

seems works now.
also font looks good.

nothing other broken or crash now.
if got some problem, i'll report.

i think it's okay to close.

**Comment by hong620** [comment] 2017-04-01 04:24
@bparker06 

http://imgur.com/a/EYsG0
seems still broken text in 'Overlay System Message(Yellow one)'

**Comment by bparker06** [comment] 2017-04-01 05:28
I believe the OSD font is not the same as the main menu font. @Kivutar can you look into this?

**Comment by Kivutar** [comment] 2017-04-01 08:14
It's the expected behaviour. We don't always have a menu (HAVE_MENU=0) so the OSD has its own font setting. Users can point the OSD font to the menu font by themselves.

**Comment by hong620** [comment] 2017-04-02 13:21
sorry for miss click the closing,
then, how'bout using **english** OSD **message** on language(issuing on font)setting during fix this font things?

**Comment by losernator** [comment] 2017-04-19 07:24
I don't know how to edit the internal osd font. so I didn't do more about that.
(don't worry, same things happen with  other language like Japanese, Chinese)

You can change osd font from "setting>onscreen disply> osd message font".
That's the best way for now.

**Comment by bparker06** [comment] 2017-12-21 19:26
Korean font is working fine in the menu itself, but @Kivutar says the OSD not using the same font is by design, so I'm marking this as wontfix.

**Closed by bparker06** 2017-12-21 19:26 UTC
Labels: invalid: won't fix
