### ISSUE TITLE
(Bounty) Real CD/DVD read support

### ISSUE THREAD

**Issue by anothername99** [libretro/RetroArch#7245] opened 2018-09-18 13:19 UTC
This bounty is about adding real CD/DVD read support to libretro/RetroArch. This would allow a user to for example play a game disc that is in the user's real CD/DVD drive. To complete the bounty:

- Add support to RetroArch and the libretro API for reading the contents of a real CD or DVD
- Add CD/DVD read support to a core
- Design your implementation so that it will be relatively easy for future core developers to add the feature to new cores

Bountysource link: https://www.bountysource.com/issues/63527883-bounty-real-cd-dvd-read-support

**Comment by markwkidd** [comment] 2018-09-18 15:36
Thank you for getting the bounty rolling with a nice starting pot of $105!

**Comment by orbea** [comment] 2018-10-08 15:47
Short of music CDs and video DVDs what consoles would this be practical for? I know for some consoles there are not any readily available drives that can both read the discs and do so at a playable speed.

**Comment by twinaphex** [comment] 2018-10-08 17:20
@orbea It would be to make commercial products that are based entirely around being able to read the original game discs obsolete, when every RetroArch device can potentially do this. This is why I consider this so important - this right now leaves a gap in the market for some entrepreneur to fill, and with it would likely come some patents as well. It's important to nip that stuff in the bud as soon as possible.

**Comment by twinaphex** [comment] 2018-10-10 19:17
@anothername99 All good points. Let's just start with the low-hanging fruit first, reading of CD/DVD discs. We can expand the scope to writing or whatever in a future stage and in future bounties. First we need that foundation in place.

**Comment by Colossus90** [comment] 2018-11-30 14:40
Maybe you can contact some people at redump.
They know a lot about physical media on disc.
http://redump.org/

**Comment by mirh** [comment] 2018-11-30 22:11
> some platforms have their own quirks like the very same PS1 requiring additional subchannel data for libcrypt-protected games to work properly

Reading of subchannel *shouldn't* really be rocket science. 
Putting aside [buggy drives](https://github.com/PCSX2/pcsx2/issues/648#issuecomment-227250009) and [unholy consoles](https://pcgamingwiki.com/wiki/Emulation_talk:Wii), the reader should already do most of work (unlike, say, if you were to implement [mounting](https://github.com/sysprogs/WinCDEmu/issues/13))

> The lack of image format compatibility is a very real problem, and it's not feasible to implement those individually for each core.

That's pretty secondary tbh. There'll always be time for a converter later. 

> There needs to be an app to make disc images that is designed with emulators in mind

I'm not sure what'd be special about emulators, but for all intent and purposes imo: https://github.com/saramibreak/DiscImageCreator

> Having both the VFS API and the CD/DVD API will allow experiments on creating a generic game archival format

Wasn't retroarch already settled with CHD?

> the cores will always use it in favor of their native implementations. The latter will remain maintained for compatibility with legacy frontends, if there are any.

Mhh, why so?
Supporting reading original media seems pretty of a feature if you ask me. 
In fact, I could imagine, say, some ps1-clone replicating it faithfully these days.

**Comment by nayslayer** [comment] 2018-12-01 03:39
Thanks for your reply, @mirh. This is exactly the feedback I'm asking for :)

> Reading of subchannel shouldn't really be rocket science.
It isn't, but you can't expect users to get it right without assistance, and I'd rather have the tedious tasks automated instead. I've had my share of corrupt dumps already, thankyouverymuch.

> That's pretty secondary tbh.
Secondary, yes. Converting my images? Hell no, not unless there's a definite format that can be fed to any emulator. Image formats mostly differ in metadata, so it's not like they're that hard to support anyway. I only mentioned disc images so that they won't be blocked out by an ossified API.

> I'm not sure what'd be special about emulators [...]
This isn't relevant for now, but basically, the idea is to make a disc imager that will detect disc types by their content and pick imaging settings accordingly, preventing users from making corrupt dumps. The tool you've mentioned is good news, though it'll need to be packaged into a user-friendly, foolproof GUI to make it useful to average users.

> Wasn't retroarch already settled with CHD?
This is even less relevant for now, but the CHD isn't designed as a universal game format, it's primarily a HDD image format. For a format to become useful to collectors it'll need much more than that: content ids, metadata, reproducibility, error correction codes, compression size-speed tradeoffs, multiple partition support, etc. It's good as prior art, but it's unwieldy and easy to mess up, e.g. by specifying incorrect sector sizes.

> Supporting reading original media seems pretty of a feature if you ask me.
Sorry, I meant the emulators' support for image file formats. I edited the original post to clarify that. Basically, I want cores to be oblivious of whether the data is backed by a read device or an image file, it's as simple as that.

**Comment by mirh** [comment] 2018-12-01 12:09
> foolproof GUI to make it useful to average users.

https://github.com/reignstumble/DICUI

> but the CHD isn't designed as a universal game format, it's primarily a HDD image format. For a format to become useful to collectors it'll need much more than that

I'm not sure why a "hdd format" would support CDDA.. And I'm not sure if MAME guys would like to be told they are not true collectors /s

To the best of my knowledge [bin/cue](https://blog.thirdechelon.org/2018/10/retroarch-convert-playstation-1-bin-cue-to-chd/) (what redump uses atm) and CHD are completely interchangeable. 
And, I mean, CHD is already used successfully in PS1 cores, isn't it?

... Then I'm not claiming any particular expertise myself in this field, but maybe it's just you are left in what the state of [affairs](https://github.com/libretro/beetle-saturn-libretro/issues/31#issuecomment-319596660) was [years](https://forums.bannister.org/ubbthreads.php?ubb=showflat&Number=106272&page=1) ago?

**Comment by anothername99** [comment] 2018-12-01 16:14
Very good to see someone taking on this, and you bring up some good points. Here are some things I would like to add:

1. As the original purpose was to use this feature with PC emulation (but this goal is paused because we don't have a good and up-to-date PC emulator core yet), I would very much like it if your implementation allows for detecting disc type and how to read it even when the core is already running. Imagine you want to, say, rip a disc with Imgburn, in Windows XP, in a PC emulator core, in RetroArch. The user will expect Imgburn and the DVD drive to "just work". Discs will be put in and out during runtime and Imgburn will control how the disc is read.

2. While the goal for this bounty is read support, I intend to also follow this bounty up with a bounty for write support. It would be a very good thing if your design is open to be extended by someone who wants to implement write support in the future, so that they don't have to rewrite everything from scratch.

3. I agree that it would be a very good thing if the disc image support can be unified somehow. I noticed this the other day when I was testing Kronos. My whole Saturn set is CHD because I use that with Beetle Saturn, and suddenly I had to spend time converting games back to cue/bin.

4. Most consoles have games that require disc swapping. At the same time, some consoles don't respond very well if you arbitrarily open the disc tray. The Dreamcast for example will outright take the player back to the BIOS menu when it happens. It would be a good thing if the core can detect when the game actually wants a disc swap, and have RetroArch respond appropriately. So by default, opening the tray while playing a Dreamcast game, emulation should be paused and the emulated system should ideally not be informed at all of what happened. But, if the game wants the player to switch discs, then the emulated system *should* be informed of the tray status just as if it's a real drive. With PC emulation on the other hand, opening the disc tray should never trigger an emulation pause, because PC software is designed to be able to handle this.

5. As for bad CD/DVD drives not reading PS1 discs properly, this isn't a big priority for me and I think that validating the disc against a game database would be a very complicated approach. You would need a complete database of every single game and every single translation or hack that is out there. This would be a never-ending project just like the scanner that RetroArch has.

6. Another idea though would be to have a database of CD/DVD drives that are known to work well with this type of disc, and if the user has a bad or unknown CD/DVD drive, display a warning. This would effectively do the same thing with a dramatically smaller scope. If there are any holes in the database, the user can just choose to ignore the warning.

7. I do also think that it would be very useful to have a way of automatically detecting which system the disc is for. Every proper PS1 disc for example has a game ID starting with SLUS, SCUS, SLES, SCES, SLPS or SLPM. You don't need to know which exact game is in the drive to know that it's a PS1 disc.

**Comment by markwkidd** [comment] 2018-12-01 16:18
CHD format for optical discs does seem to be gaining ground as a de facto standard over the last year or two now that it uses a lossless audio codec. Certainly I have seen CHD support spread quite a bit throughout the libretro cores over that time period.

**Comment by Colossus90** [comment] 2018-12-01 17:51
“As for bad CD/DVD drives not reading PS1 discs properly, this isn't a big priority for me and I think that validating the disc against a game database would be a very complicated approach. You would need a complete database of every single game and every single translation or hack that is out there. This would be a never-ending project just like the scanner that RetroArch has.”


The redump site is creating such a database, all the hashes to confirm a correct dump. Which is why I think it would be interesting to work with the people of redump. They also have a lot of tools available. I have some contacts there.

**Comment by barbudreadmon** [comment] 2018-12-02 18:40
While this idea is nice, keep in mind that some systems had non-standard optical media, or peculiar ways to read them.

**Comment by anothername99** [comment] 2018-12-03 12:41
Another thought that just came to my mind is, what are the specific problems with reading PS1 discs? If the main issue is subchannels, then Redump is actually collecting those: http://redump.org/downloads/

So an idea is to put all the SBI files in a database. Then, when a PS1 game is in the CD/DVD drive, look for the game ID and then use a matching SBI file to "patch" the disc in memory.

**Comment by markwkidd** [comment] 2019-03-17 13:38
My understanding is that this PR just added the ability for the PS2 port of RetroArch to read CDs. The library: https://github.com/libretro/RetroArch/pull/8482

The "libcdvd" library seems to be PS2 specific but I wanted to make sure that the author of that patch @fjtrujy is aware of this bounty. Could it be that the PS2 implementation is a useful step towards a more generalized API for reading CDs and DVDs in RetroArch?

**Comment by markwkidd** [comment] 2019-03-17 13:39
## This bounty stands at $155 as of today.

**Comment by fjtrujy** [comment] 2019-03-17 13:58
Thanks @markwkidd for notifying me about this bounty.

**Comment by chuwchu** [comment] 2019-03-18 09:33
@anothername99 maybe the platform should be specified, like at least linux 64bits or windows 64bits.

**Comment by markwkidd** [comment] 2019-03-18 15:14
Madnafen evidently uses libcdio: http://www.gnu.org/software/libcdio/

**Comment by anothername99** [comment] 2019-03-19 18:51
Either Windows or Linux is fine. But if you can only do one OS, it is preferable that there is room for someone to pick up the code and add support for another OS in the future.

**Comment by markwkidd** [comment] 2019-03-22 01:15
Bounty is up to $265 thanks to a $100 contribution from libretro organization bounty funds!

**Comment by twinaphex** [comment] 2019-07-02 20:16
While there is still work to be done, I believe we should reward @bparker06 already under the condition that we will continue the work and further improve compatibility with existing drives.
We do need more eyeballs in this endeavor though. But I'll close it with the full faith and confidence that this will be delivered on.

**Closed by twinaphex** 2019-07-02 20:16 UTC
Labels: bounty

**Comment by anothername99** [comment] 2019-07-03 11:54
I will test this today. Was a possible expansion (for burning discs) taken into account with this implementation? Either way, thank you @bparker06 and I don't mind rewarding already.

**Comment by SpaceAgeHero** [comment] 2020-03-31 15:21
DVD is not yet supported, right? Would be useful for PS2 / Play!
