### ISSUE TITLE
Xbox guide button exits when input_exit_emulator = "nul"

### ISSUE THREAD

**Issue by SystemDisc** [libretro/RetroArch#4881] opened 2017-05-05 16:40 UTC
## Description

Xbox guide button exits when `input_exit_emulator = "nul"`, `input_exit_emulator_btn = "nul"`, and `input_exit_emulator_axis = "nul"`

### Expected behavior

I expect no buttons to exit RetroArch when `input_exit_emulator = "nul"`, `input_exit_emulator_btn = "nul"`, and `input_exit_emulator_axis = "nul"`

### Actual behavior

RetroArch exits when I press the Guide button (Xbox button) on my Xbox One controller when I set `input_exit_emulator = "nul"`.

### Steps to reproduce the bug

1. Fresh config (download RetroArch, launch RetroArch, close RetroArch - you will have a fresh install/config)
2. Set `input_exit_emulator = "nul"` without changing anything else (this means all the other `input_exit_emulator_*` options are `"nul"`)
3. Launch RetroArch and press guide button on an Xbox One controller
4. RetroArch closes immediately (maybe crashes?)

NOTE: On Windows 10, to make sure the Guide button works, you may need to follow the steps in this link to disable Windows 10 Game DVR. Windows 10 Game DVR prevents software from receiving the guide button input: https://steamcommunity.com/discussions/forum/1/496881136907901669/?ctp=5

## *** Very Important ***

If `input_exit_emulator = "escape"`, `input_exit_emulator_btn = "nul"`, and `input_exit_emulator_axis = "nul"`, the Xbox One controller guide button **DOES NOT** cause RetroArch to exit/crash, so it seems the affected configuration option is `input_exit_emulator`.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: <img src="https://i.imgur.com/R2GY3fy.png">

### Environment information

- OS: Windows 10 Pro 64-bit v1703 build 15063.250

**Comment by Awakened0** [comment] 2017-05-06 01:19
input_exit_emulator = "nul" only nulls out the key. If you set input_exit_emulator_btn = "nul" in your config it should null out the button exit too.

**Comment by SystemDisc** [comment] 2017-05-06 01:21
`input_exit_emulator_btn` isn't in the config file and the Xbox guide button does not exit RetroArch when `input_exit_emulator` is set to the default value of `"escape"`

**Comment by Awakened0** [comment] 2017-05-06 02:42
Add it to your config. If a line isn't in your config, it uses the default, which must be guide button for some reason. Input lines that don't end in _btn or _axis only set what the keyboard does. _btn ones are controller buttons, while _axis are controller analog axis' (stick directions and triggers).

**Comment by SystemDisc** [comment] 2017-05-06 16:00
That doesn't make sense. It's not in my config when I set `input_exit_emulator = "nul"` and it's not in my config when `input_exit_emulator = "escape"`, but the guide button only exits when `input_exit_emulator` is not `"nul"`

**Comment by Awakened0** [comment] 2017-05-06 18:45
What happens when you have both:

```
input_exit_emulator = "nul"
input_exit_emulator_btn = "nul"
```

in your config?

**Comment by SystemDisc** [comment] 2017-05-07 18:40
Look, I gave a set of steps to reproduce the issue. This would of course have `input_exit_emulator_btn = "nul"` and `input_exit_emulator_axis = "nul"` by default.

I'm telling you, if you do nothing other than install RetroArch, launch and close RetroArch to setup the default cfg file, set `input_exit_emulator` to `"nul"` (`input_exit_emulator_btn` will already be `"nul"`), launch RetroArch, and press the Xbox One guide button RetroArch will close immediately (maybe it's a crash?).

**Comment by SystemDisc** [comment] 2017-05-07 18:54
I've updated the OP with more detailed information. Hopefully, this will allow you to stop assuming I did something wrong and recognize this as an actual bug.

**Comment by fr500** [comment] 2017-05-07 18:56
@Awakened0 is just trying to help you get to the bottom of it. 
He's a user just like you trying to help.

**Comment by SystemDisc** [comment] 2017-05-07 18:58
I understand. Hopefully, there is enough information here now to reproduce the bug consistently and for the devs to track down the issue.

**Comment by Awakened0** [comment] 2017-05-07 19:08
Yeah, I just wanted to rule out any possible config issues first. It does indeed sound like a bug. Normally, the guide button should default to menu, so it's odd it changes to exit when you null out the exit key. It might be worth disabling `input_autodetect_enable` to see if the behavior changes. Though if you are configuring your inputs manually through the config file, you might already have it set to false.

**Comment by SystemDisc** [comment] 2017-05-07 19:09
I'll try that.

**Comment by SystemDisc** [comment] 2017-05-07 19:11
Also, as a note to devs which may be able to track this down, but may not have Windows 10 + an Xbox One controller + Game DVR completely disabled, feel free to let me know what you need me to do to debug this. I have *some* experience programming in C, but not enough to figure it out on my own - and definitely not enough experience with RetroArch.

**Comment by Awakened0** [comment] 2017-05-07 19:25
I tested adding all three exit inputs to my config and couldn't reproduce the exit/crash when hitting my guide button (Xbox Elite, wired). It did stop my exit key from closing RA and I tested with `input_menu_toggle_btn = "10"` to make sure I was getting guide button inputs working in RA. I was using the latest nightly from the buildbot and I'm on Win10 Anniversary. To get the guide button working, I disabled the Game DVR overlay shortcut, then disabled Game DVR entirely. Here's my full config: https://pastebin.com/hT5XZRfD

I tested removing the menu toggle from my config too and that just made the guide button do nothing.

**Comment by SystemDisc** [comment] 2017-05-07 23:47
Did you try deleting the config file and starting over fresh?

The only other differences are that I'm using Windows 10 Creator's Update, a wireless Xbox One controller with the wireless adapter from Microsoft, and the latest stable RetroArch.

I'll download the latest nightly and see if I still have the issue.

**Comment by SystemDisc** [comment] 2017-05-08 00:28
I set up a screen recorder and went through the steps I took to replicate the bug. I was able to replicate the bug 100% of the time when I made the original post. However, I was unable to replicate the bug this time around. After messing around for awhile, I thought maybe it was an issue with Steam overlay, so I launched it through Steam, but still couldn't replicate the bug. This is really mind-boggling because it was so easy to replicate before.

Anyway, here's the video of my attempt to replicate the issue, though it will probably be of zero help. If I'm able to consistently replicate the bug again in the future, I'll make another post. For now, this issue can be closed.

[![Unable to replicate RetroArch bug (issue #4881) ](https://i.imgur.com/gxGw6Tg.png)](https://youtu.be/qlUAEVmb6R8)

**Comment by Awakened0** [comment] 2017-05-08 00:41
I didn't try with a fresh config, but the first time I launched RA after adding the exit key nul lines, my backspace and enter keys stopped doing anything in the interface. The arrow keys worked, but holding them down wouldn't keep scrolling through menu entries like they usually do. This persisted when I commented out the exit key nul lines. I've never had that happen before. What got them working again was when I pressed a button on my controller. After that, even after restarting RA and uncommenting the nul lines my keyboard inputs continued to work like normal.

So maybe the guide button closing thing is one of those strange, frustrating issues that crop up for seemingly no reason and disappear the same way :P

**Comment by SystemDisc** [comment] 2017-05-08 00:47
Yeah, it must be. I really wish I could figure out what combination of things causes this bug. For now, I'm just happy not to be affected by it, since I prefer not to have any keys bound to close RetroArch.

**Comment by SystemDisc** [comment] 2017-05-08 22:28
I was able to reproduce the bug, but only while launching it through Steam. I'm guessing RetroArch is crashing, and I'm guessing it has something to do with an incompatibility with Steam Overlay. It's weird that setting `input_exit_emulator` to `"nul"` causes the crash, and having `input_exit_emulator` set to `"escape"` prevents the crash.

[![Replicating RetroArch bug (issue #4881)](https://i.imgur.com/ZipOW10.png)](https://youtu.be/OLFz4p-rG6Y)

**Comment by SystemDisc** [comment] 2017-05-08 22:51
Correction: It is not a bug with Steam overlay. You can reproduce the bug by setting `input_exit_emulator` to `"nul"` and launching RetroArch as an administrator.

**Comment by SystemDisc** [comment] 2017-05-08 23:39
@Awakened0, I'd be interested to find out if you can reproduce this bug by launching RetroArch as an administrator.

**Comment by Awakened0** [comment] 2017-05-09 00:24
Yep, I was able to reproduce it when right clicking retroarch.exe and running as admin.

**Comment by SystemDisc** [comment] 2017-05-11 05:43
@meepingsnesroms Is there any way I can add the appropriate labels to this issue?

**Comment by NelsonRosenberg** [comment] 2017-11-14 00:29
I was having the exact same problem and I do think it's not something with the exit emulator option, but rather a something with a "fallback to default" on any hotkey. I have almost all my hotkeys to "nul" and when I press the guide button first it exit the emulator, which I fixed by assigning it to escape, now when I press guide it pauses, changes shaders, opens the system tray and activates slow motion, all at once because all those functionalities have nul hotkeys.

**Comment by sonninnos** [comment] 2022-11-12 20:48
This is no longer a problem.

**Closed** 2022-11-13 16:59 UTC
