### ISSUE TITLE
Shader Core presets are not being applied automatically

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#3504] opened 2016-09-04 16:14 UTC
I'm currently experiencing an issue with the latest nightly not applying shader core presets upon starting any relevant core / game.

The shader preset is correctly saved on disk: if you access Quick Menu -> Shader options, the Menu detects the corresponding shader preset exactly like it was previously saved by the user, but you have to click on Apply Shader to make it output the desired result. It's not being applied automatically upon startup.

**Comment by fr500** [comment] 2016-09-04 16:17
It is working fine for me

**Comment by Axiphel** [comment] 2016-09-04 17:06
Working fine for me too.

**Comment by andreycout** [comment] 2016-09-06 11:42
Have you recently moved your Retroarch install to a different path? I've had this happen to me before  when I moved Retroarch.

**Comment by dojima** [comment] 2018-08-29 23:07
I had this exact same issue.  Game presets were being loaded but not applied correctly.  I had to manually go into the menu and click apply settings to make any game preset work automatically, but after a lot of trial and error, I think I've discovered a workaround.

When selecting 'Save Game Preset' from Shaders section of the Quick Menu, Retroarch seems to save a shader preset under 'retroarch\shaders\presets\[core]\[game filename].[shader extension]'.  This is also the file that is correctly loaded, but not applied, when launching a game with the same filename.  It's not a major issue to go into the menu and manually apply the shader settings, but if you use a game configuration override file in 'retroarch\config\[core]\[game filename].cfg', you can make preset created with 'Save Game Preset' load and apply automatically using the line

`video_shader = ":\shaders\presets\[core]\[game filename].[shader extension]"`

This seems to be the only way I'm able to get the settings to load and apply automatically.

I'm not sure if this is the intended functionality or if it's some kind of a bug, but if it is intended, it's highly unintuitive.  One would expect that a game preset is loaded and applied automatically when launching a game.  Instead, 'Save Game Preset' seems to save the preset and load it automatically when launching a game, but it does not apply it.  Strange.

**Comment by fr500** [comment] 2018-08-29 23:49
It's not intended it should work right away.
Not sure when it broke (or if it actually did since I haven't been able to
confirm)

**Comment by LazyBumHorse** [comment] 2019-06-24 20:26
This can probably be closed.

What Ryunam and dojima describe could have multiple reasons like
 - having multiple shader presets of same name with differing types (fixed by #8910)
 - inconsistencies between shader loading in a video driver's `init()` vs `set_shader()` (if that still happens I need to know the video driver) 

The part about the `video_shader` setting working while presets do not sounds like something that has been fixed for quite a while.

What andreycout mentions is caused by shader presets using absolute paths, which was changed to relative in nightly (#8933) - though the presets need to be re-saved first.

**Comment by hizzlekizzle** [comment] 2019-06-25 00:21
Ok, I'll go ahead and close this and if @Ryunam and/or @dojima are still experiencing the issue, we can reopen it.

**Closed by hizzlekizzle** 2019-06-25 00:21 UTC
Labels: followup: needs info or confirmation

**Comment by Ryunam** [comment] 2019-06-25 08:02
I can confirm that I have not been experiencing this anymore, so it seems fine to close it! Thank you as usual for your work.

**Comment by LazyBumHorse** [comment] 2019-06-25 11:41
@Ryunam No, _you_ are breathta-
I mean thank _you_ for testing!
