### ISSUE TITLE
Fullscreen command line switch does not appear to do anything

### ISSUE THREAD

**Issue by 7oxicshadow** [libretro/RetroArch#3831] opened 2016-10-19 20:03 UTC
The help file says that either -f or --fullscreen on the command line will override the config file setting and will force the application to open in fullscreen.

This does not appear to work on Linux (Fedora 24). The application always opens in the mode specified in the cfg file. (built from latest GIT 19 OCT 2016)

Is it only supported on certain video types (i.e SDL etc...)?

**Comment by sergiobenrocha2** [comment] 2016-10-21 00:06
I can confirm too

**Comment by lasers** [comment] 2016-10-21 02:04
Confirmed.

**Comment by 7oxicshadow** [comment] 2016-10-22 12:25
Ok so this was fun to track down.

The order appears to be the following in code:
parse command line
set override bool
set default config (using override bool)
load config

The default config forces settings->video.fullscreen to true by checking the override flag.

When load config is called it parses the config file in a for loop at line 1793 (configuration.c). This undoes the work done by set default config (using the override flag) and gets the data from the config file.

I think the main problem is actually the "if" command at line 1800 (configuration.c). It uses inverted logic to fetch the video_fullscreen state from the config file (which it has already done in the for loop above.) making it a pointless check.

Changing it to the following fixes the problem and it uses the command line correctly:

   if (rarch_ctl(RARCH_CTL_IS_FORCE_FULLSCREEN, NULL))
	   settings->video.fullscreen               = true;

Note: when closing retroarch it updates the config file to always be fullscreen. I think this is as intended but might be worth considering not saving the state of fullscreen if it was called with a commandline override.

**Comment by orbea** [comment] 2016-10-23 02:07
Strangely enough I can't reproduce this on Slackware64-current.

**Comment by 7oxicshadow** [comment] 2016-10-23 09:32
That is odd as I suspect that this problem will exist on all os including windows assuming they all use the same code.

Can you confirm that you did the following steps:

open retroarch (without paramaters)
set windowed mode
save settings
exit retroarch
open retroarch again (without parameters) to prove that it opens in window mode
close retroarch
open retroarch using either -f or --fullscreen.

It should have no effect and open in window mode.

**Comment by undeadindustries** [comment] 2019-02-10 15:39
Confirmed that this is still a bug in Windows. Running 1.7.6.

**Comment by orbea** [comment] 2019-02-10 15:43
@7oxicshadow Sorry, I missed this reply two years ago...I tried your reproduction steps now and still can't reproduce it...

Maybe its because I'm using x11 and not wayland or w/e windows uses?

**Comment by 7oxicshadow** [comment] 2019-02-10 16:06
This bug is quite old now and the configuration.c file has seen a lot of changes in the last 2+ years.

This is no longer an issue on Linux anymore. I have just done a clean source build to confirm it. Using both -f and --fullscreen results in the correct mode being used.

I am afraid that I no longer have a windows environment to test in so I cannot validate the problem @undeadindustries has recently reported

**Comment by orbea** [comment] 2019-02-10 16:12
@7oxicshadow Thanks for the quick confirmation that its fixed for you too now.

@fr500 Can you reproduce this on windows?

**Comment by fr500** [comment] 2019-02-10 16:18
fullscreen switch works fine in windows

**Comment by undeadindustries** [comment] 2019-02-10 16:59
I tried it today in 1.7.6 and it didn't work. Just --fullscreen right?

**Comment by 7oxicshadow** [comment] 2019-02-10 16:59
you can also try -f aswell

**Comment by fr500** [comment] 2019-02-10 19:55
I tried -f too and it's working properly with a clean config

**Comment by undeadindustries** [comment] 2019-02-10 21:34
Sorry, this is working. It was an issues with Launchbox.

**Comment by orbea** [comment] 2019-02-11 00:06
Okay, thanks for clearing that up! Given everyone seems to agree this works now I'm going to close this issue. :)

**Closed by orbea** 2019-02-11 00:06 UTC
Labels: commandline, followup: needs info or confirmation, platform: windows
