### ISSUE TITLE
[Feature Request] Add title property in playlist item

### ISSUE THREAD

**Issue by loqusion** [libretro/RetroArch#15730] opened 2023-09-24 02:24 UTC
## Problem

Currently, automatic thumbnail downloading seems to depend on the `items[*].label` property in the playlist files. This means that renaming the playlist item (i.e. changing `label`) will remove the association between the item and its thumbnails (unless you manually rename the thumbnail files, which is undesirable).

## Solution

There should be a way to rename the title of a playlist item while preserving its thumbnail association.

---

### Version

```
RetroArch: Frontend for libretro -- v1.15.0 -- 6616b807ed --
Compiler: GCC (13.2.1) 64-bit Built: Sep 13 2023
```

**Comment by sonninnos** [comment] 2023-09-24 06:25
Duplicate of https://github.com/libretro/RetroArch/issues/10093

**Closed** 2023-09-24 06:39 UTC
