### ISSUE TITLE
Doesn't detect softpatches

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#3710] opened 2016-10-02 17:39 UTC
Test case:

Sega Genesis No-Intro romset (with zipped roms).

After creating playlist for this,
I manually added IPS patch (english translation) for Langrisser II (v1.2) to archive with this rom.

Filenames:
Langrisser II (Japan) (v1.2).zip - archive filename
Langrisser II (Japan) (v1.2).md - rom filename
Langrisser II (Japan) (v1.2).ips - patch filename

And this rom isn't patched on Genesis Plus GX and Picodrive either when I try to launch it from GUI.

**Comment by Alcaro** [comment] 2016-10-02 17:46
Dupe of #3702

**Comment by twinaphex** [comment] 2016-10-02 17:47
@Alcaro wrong.

This is a need_fullpath 'true' core.

**Comment by Alcaro** [comment] 2016-10-02 17:50
3702 is about Desmume, which [needs fullpath](https://github.com/libretro/desmume/blob/master/desmume/src/libretro/libretro.cpp#L148).

This issue is about Genplus, which [needs fullpath](https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro.c#L1629), and Picodrive, which [needs fullpath](https://github.com/libretro/picodrive/blob/master/platform/libretro/libretro.c#L530).

Therefore, same issue.

**Closed by Alcaro** 2016-10-02 17:50 UTC
