### ISSUE TITLE
(Linux) Online Updater doesn't install cores when using PPA

### ISSUE THREAD

**Issue by simbalion** [libretro/RetroArch#6919] opened 2018-06-24 23:06 UTC
## Description
When downloading cores, the log says it can't write. It doesn't say where it's trying to write to, but I assume it's a permissions error.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
RetroArch: Frontend for libretro -- v1.3.6Compiler: GCC (6.2.0) 64-bitBuilt: Aug 24 2016

Installed using apt-get

### Environment information

- OS: Debian stable

**Comment by i30817** [comment] 2018-06-25 11:04
If the downloader is trying to place the cores in the system retroarch core place, it won't be able to write because these cores are managed by apt-get/aptitude and require root to modify. 

This is normal, unfortunately Retroarch doesn't have a 'overlay' system for adding cores to the path. Even if you change the core download location in the options - i think you can do this, then you have to copy them with sudo to the system directory (or maybe there is a option to set the core directory, in which case you could do the reverse).

It's a limitation of retroarch/the debian and ubuntu package.

**Comment by anothername99** [comment] 2018-06-25 14:02
It would make the most sense to make the online updater work out of the box by making ~/config/retroarch/cores the default core directory, even if it interferes with the distros' core packages. There aren't any "stable" releases of cores, so there's really no advantage of installing a core through the distro's package manager over using RetroArch's online updater.

**Comment by i30817** [comment] 2018-06-25 14:05
I think the reason they don't do that is that they want a way to use both, since debian for instance wouldn't like that sort of thing (the *requirement* of a external download so software packaged by them works). The symlink overlay idea i posted above should satisfy both sides, if correctly done, it's just that no one has done it. Or they're waiting for the VFS for a more elegant solution...

**Comment by i30817** [comment] 2018-06-25 14:16
There is also the point that distro software management is much superior as a distribution method even for retroarch. Package holds, distributed downloads that don't cost RA anything, conflicts for free (well, if the debian/control is correct) etc.

**Comment by RobLoach** [comment] 2018-07-02 18:48
There was some talk about allowing multiple core directories, but then it got complicated. Lakka gets around it by using a unified filesystem.

Recommend doing what was suggested above, and change the core directory to `./config/retroarch/cores`. The PPA stable will stick with the default, as in that space, it's expected that you install the cores using the PPA.

**Comment by orbea** [comment] 2018-07-12 02:41
More or less a duplicate of issue https://github.com/libretro/RetroArch/issues/3237.

**Comment by hizzlekizzle** [comment] 2018-07-12 14:13
@anothername99 Sorry, I didn't see this when it was originally posted, but to be considered a valid/safe debian package, the install scripts *cannot* write to or create files/directories in user directories. It's a big no-no.

The way packages typically handle this sort of thing is to write them to a root-level directory and then copy the files down to the individual user directory on launch (or else have a launcher script that does this and then launches the actual program afterward).

Currently, your options are 1.) use your package manager (apt/synaptic) to manage your cores and leave the core downloader hidden. 2.) stop using your package manager for cores and go to settings > directory to change your 'core' directory to something user-writeable (usually ~/.config/retroarch/cores) and make the core downloader visible in settings > user interface > views.

**Comment by orbea** [comment] 2018-12-21 00:37
I'm going to close this as a duplicate of https://github.com/libretro/RetroArch/issues/3237.

**Closed by orbea** 2018-12-21 00:37 UTC
Labels: bug: minor, platform: linux
