### ISSUE TITLE
"Scan this directory" includes rom in subfolder

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#4129] opened 2016-12-02 17:18 UTC
Hello.

How can I exclude roms in subfolders from scanning "scan this directory"?

I'm in trouble because a huge amount of prototype rom etc. saved in a subfolders has been added to the playlist.

I'm using Nightly version, and in previous versions, I think that only rom of "this directory" was being scanned.

**Comment by hizzlekizzle** [comment] 2016-12-02 19:06
Recursive scanning is hardcoded right now. It may be configurable in a menu at some point but that's in the future.

**Comment by RobLoach** [comment] 2016-12-03 15:08
As HizzleKizzleNizzle mentioend, recursive scanning was added. Suggest either...

1. Closing this issue as recursive scanning is by design
2. Reframing this issue as a new feature to be able to disable recursive scanning in the config

**Comment by twinaphex** [comment] 2016-12-15 11:33
Following RobLoach's advice, closing this.

**Closed by twinaphex** 2016-12-15 11:33 UTC
