### ISSUE TITLE
Retroarch crashes when menu key-combo pressed in Mupen64 core. - Impossible to save games.

### ISSUE THREAD

**Issue by smidley** [libretro/RetroArch#3095] opened 2016-06-10 16:38 UTC
When running an N64 game, if I try to press the key combo to bring up the Retroarch menu, retroarch crashes immediately.  This makes it impossible to save an N64 game since the roms need to exit cleanly in order to write the save data for in-game saves, and you never get the chance to perform a save state.

Using Nvidia Shield TV.  Stable branch of Retroarch from play store.  Launching games with Gamesome 2.0.

I only experience this behavior with the Mupen64 core.  I believe it's due to this being a GL core and there is some issue with rendering the Retroarch menu from this core.  This issue has also been reported to the Gamesome dev just in case it's their problem.

**Comment by smidley** [comment] 2016-06-11 00:22
Confirmed that this only happens when launching games through Gamesome.

**Comment by alondero** [comment] 2016-07-26 22:16
I'm getting this same issue - again only when launching this from Launchbox.

**Comment by fr500** [comment] 2016-09-22 05:36
@alondero does it happen if you press F1 too?

**Comment by dankcushions** [comment] 2016-09-22 07:13
99% sure this is a dupe of https://github.com/libretro/RetroArch/issues/2655

**Comment by alondero** [comment] 2016-09-22 07:53
I'll test on the latest nightly again later but switching to rgui has solved my issue for now

**Comment by alondero** [comment] 2016-09-22 19:09
@dankcushions I agree - testing the latest nightly it freezes, until you press menu again (both on a gamepad as well as hitting F1) just like described in #3095. At least it doesn't crash any more!

**Comment by fr500** [comment] 2016-09-22 19:15
We have this problem on android too. I think it may be a case of things
running out of order.
Maybe the menu context isn't initialized when it runs via CLI.

**Comment by Ketsueki2b** [comment] 2016-11-16 18:18
Hi,

is there any news about this issue?

I'm using the Mupen64 core by Retroarch on my Android TV Box and I just can't go back on the core's menu when I launch a game from the Gamesome Frontend.

Thanks.

**Comment by twinaphex** [comment] 2016-11-16 18:19
We don't provide support for Gamesome or any other external launcher app. You're on your own.

This issue could potentially be fixed but honestly it's low-priority, there is far more important stuff and external launcher apps is not one of the most immediate things.

**Comment by fr500** [comment] 2016-11-16 18:22
@Ketsueki2b for us the priority is RetroArch, we don't use external launchers or anything like that so yeah it's no priority for us.

**Comment by twinaphex** [comment] 2016-11-16 18:22
If anybody has a fix though, feel free to send a pull request.

**Comment by Ketsueki2b** [comment] 2016-11-16 18:36
Yeah I understand that's an "additionnal layer" I'm currently using and you can't be responsible for this.

If I find some workaround I'll put it on this topic.

Thanks.

**Comment by elwooha6** [comment] 2017-03-01 14:24
I am having similar issues, when I try to make a save state with mupen64plus core retroarch just crashes. I have tried both with and without "launcher" programs.
Running retroarch 1.4.1 on 64-bit Windows 10, this also happens on the 3-1-17 Nightly as well.

**Comment by orbea** [comment] 2018-12-16 19:11
I agree with @dankcushions and @alondero that this is probably a duplicate of issue https://github.com/libretro/RetroArch/issues/2655. I am going to close this one, please continue further discussion in the other issue.

**Closed by orbea** 2018-12-16 19:11 UTC
Labels: followup: needs info or confirmation
