### ISSUE TITLE
Android: glui/materialui doesn't recognize button press

### ISSUE THREAD

**Issue by rrooij** [libretro/RetroArch#3128] opened 2016-06-19 11:52 UTC
The following occurs on Android with the Galaxy S Plus (i9001) and RetroArch version 1.3.4:

The RetroArch application starts correctly, it extracts the assets and the menu appears.

However, in the menu it's impossible to press anything, as glui seems to think that it is a gesture instead of a button press. This makes it impossible to select menu entries and start a game. This never happened with the older versions of the RetroArch Android menu, which had a black background.

I've already tried the latest nightly version too, but unfortunately it didn't solve the problem.

The specs of the phone:

Android: 5.1.1 (Cyanogenmod 12.1, to be specific:`[GT-I9001][ROM][ION][5.1.1][LMY49F] CyanogenMod 12.1 by ADC-Team` )
Model: Galaxy S Plus (i9001)

A video that shows the problem: https://0x0.st/TVn.mp4

Some entries in logcat that appear when running retroarch and that might be interesting:

```

W/Adreno-ES20( 3995): <__load_uniform_float:825>: GL_INVALID_OPERATION
```
Full log with logcat:

https://gist.github.com/rrooij/b13e8865fedb92d3c86876564940710a

I've discovered things that can help in debugging:

When disabling input_overlay_hide on menu I can control the menu. However, every button pressed on the gamepad gets in a loop. For instance, when pressing dpad-right, it's as if I'm pushing the dpad-right the whole time even if I just pressed it once. Pushing another button on the overlay cancels the previous loop but will start a new loop instead with that button. Pressing an unmapped button will cancel the previous loop and start a loop with no events attached (since the button isn't mapped). Touching the screen also cancels this input loop. Only the gamepad-specific buttons seem to loop. The change orientation button doesn't loop for instance. When I tried to run a game, the same problem with the input events seem to happen.

**Comment by rrooij** [comment] 2016-06-28 16:47
I found some people with similar problems on the RetorArch forums:

http://libretro.com/forums/archive/index.php?t-663.html

**Comment by fr500** [comment] 2016-06-28 17:09
duplicate of https://github.com/libretro/RetroArch/issues/3003
add your info there please

**Closed** 2016-06-28 17:08 UTC
