### ISSUE TITLE
Overrides didn't save input-changes to game.cfg

### ISSUE THREAD

**Issue by Oend** [libretro/RetroArch#9958] opened 2020-01-07 09:03 UTC
I created a overrides for crazy taxi (naomi)
then I F1>quick menu>backspace>main menu>input>change port 1 binds
then back to quick menu and save overrides for game
then exit RetroArch
then open RetroArch and open game
then saw input changes was't there
actually if I write input line to game cfg file and load game, it works, but after I save overrides, it gone again, looks like RetroArch doesn't save input changes to game cfg file

1.8.2 X64 last flycast 
Windows 7 SP1 X64

**Comment by bslenul** [comment] 2020-01-07 22:26
For per game rebinds use `Quick Menu > Controls` instead, then click `Save Remap Game File`.

**Comment by hizzlekizzle** [comment] 2020-01-08 00:42
Correct, that's working as intended. I'm going to close this for now but we can reopen it if anything changes.

**Closed by hizzlekizzle** 2020-01-08 00:42 UTC
Labels: invalid: won't fix, no issue template

**Comment by Oend** [comment] 2020-01-08 06:47
I knew that founction, but here are some difference: the "Quick Menu > Controls remap" only works for rebind game-inside button function to existing-keyboard-mapped-key for each player-input-setting, for example, I set L2 to keyboard-M for player 1, then I can go "Quick Menu > Controls remap" and rebind player 1 game function "fire" to "L2" while "fire" was "L1".
that means, if I want to set a two-players keyboard layout (on a single keyboard) for a special single game, and this game has 8 buttons for one player, then I must to set 16 buttons on keyboard, and layout must be side-by-side for keyboard.
that means, for example, wasd+ihjk for player 1, arrows+number pad for player 2.
but when I play other games for single player, I want to use arrows+wasdzxc.etc
but, you can't use "Quick Menu > Controls remap" to create the layout of arrows+wasdzxc.etc for player 1, because for player 1, it had set on wasd+ihjk in main-menu-input-port1, "Quick Menu > Controls remap" can only rebind game button function to these key for player1.
For current, I write game.cfg file manually for those special two-players-game to solve this probelm.
This is not a big problem, but if can, I wish RetroArch can write input-changes to game.cfg.

**Comment by Oend** [comment] 2020-01-08 06:51
@hizzlekizzle
Don't know how to reopen issue, so I use @ to......

**Comment by bslenul** [comment] 2020-01-09 10:54
Oh I see, yeah that's probably a bit tricky to set up because for some reason inputs/hotkeys reset to defaults when you try to make an override :/ Atm I'm not sure there's any other way than doing it manually like you're doing unfortunately.

Also, I don't think you can re-open an issue if you didn't close it yourself.
