### ISSUE TITLE
Core can't be loaded with wrong core info files

### ISSUE THREAD

**Issue by rrooij** [libretro/RetroArch#4821] opened 2017-04-13 17:23 UTC
## Description

Whenever the core info files are outdated or bad, paralleln64 can't run and mupen64plus will run instead. It also happens in the file browser, so it's not a playlist issue.

I'm not sure if this happens with wrong core info files on other systems too. That's why I filed this bug here and not in the paralleln64 repository.

### Expected behavior

paralleln64 running instead of mupen64plus

### Actual behavior

mupen64plus is opened instead of paralleln64

### Steps to reproduce the bug

1. Use outdated core info files (I used the standard ones in Debian Testing (Stretch)
2. Have mupen64plus core installed and paralleln64 from the core updater (not the Debian Repository), this has to be done so that the core info files and cores don't match
3. Load Core -> the `.so` of paralleln64 -> Load Content -> Load the game
4. Press F1
5. You'll see that the mupen64plus library loaded instead of the parallel core.

### Bisect Results

It started happening because my system is not fast enough for the GlideN64 plugin and I therefore wanted paralleln64 instead.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.5.0 c04573233

### Environment information

- OS: Debian Testing (Stretch) x64-64
- Compiler: GCC 6.3.0 64 bit

**Comment by sergiobenrocha2** [comment] 2017-04-15 08:32
Update the info files on your system (get the package from here: https://launchpad.net/~libretro/+archive/ubuntu/stable/+packages?field.name_filter=info&field.status_filter=published&field.series_filter=xenial)

It's not really an issue, mupen from the repo works with the info package from the same repo right?

**Comment by rrooij** [comment] 2017-04-15 08:56
@sergiobenrocha2 it was indeed solved by updating the core info files, but shouldn't RetroArch warn about them being outdated or something else to prevent this from happening?

**Comment by sergiobenrocha2** [comment] 2017-04-15 09:01
Maybe, info files are not automatically updated in most platforms. Sometimes when l update the cores on Android, I see a .so file without proper name or another weird thing in the Core Updater, then I remember I need to update the info files first

**Comment by orbea** [comment] 2017-04-21 05:34
Sounds like a packaging bug. I would suggest shipping the core info files with each individual core. This way you can ensure the info file is always up to date with the core.

**Comment by sergiobenrocha2** [comment] 2017-04-21 14:33
I would suggest shipping the core info files with each individual core.

No way, too much maintenance.

**Comment by fr500** [comment] 2017-04-21 14:44
It's certainly not a packaging bug.
It's actually impossible to load a core that doesn't have info atm

**Comment by orbea** [comment] 2017-04-22 01:23
The cores not shipping with the required info files is a packaging bug for ubuntu/debian. It should be easy to curl/wget the required info files when generating the source tarballs or cloning the git repos with a relatively simple script. I've done just this for Slackware and its works great.

The cores not working without info files at all is a related, but different RetroArch issue. That said I'm not sure it would be wroth fixing when you can just provide the info files or download them with the online updater. My understanding is at least some features rely on the info files being present.

**Comment by sergiobenrocha2** [comment] 2017-04-22 01:33
The cores not shipping with the required info files is a packaging bug for ubuntu/debian.

Dude, it's not a bug... debian/ubuntu/launchpad farm does not permit connecting to web while compiling. I'll not "fix" it. I can update the mupen/parallel cores there, and the info package too

**Comment by rrooij** [comment] 2017-04-22 09:05
It is not a packaging bug. The problem was that I had old core info files from the Debian Testing repository, compiled RetroArch myself and used the core updater to download mupen64plus_parallel without updating the core info files. I would expect the core to be loaded nevertheless, even if it has outdated core info. The Debian Testing core info files are correct and match the cores in their repository. However, they are of course outdated in comparison with the latest core info from the core updater.

The problem was on my end since I didn't update the core info files using the core updater. However, I would expect a core to run regardless of the info files.

**Comment by orbea** [comment] 2017-04-22 15:17
@sergiobenrocha2 SBo has the same restriction, that is why I curl them when generating the source tarballs before anyone actually builds the packages. Well I tried to explain the proper fix. I guess its not my responsibility if you don't want to implement it.

**Comment by fr500** [comment] 2017-04-22 18:30
Packaging bug or not
RA currently can't load content with cores that have no info files and that should be fixed.

To test:
Delete a core info file
Load Core
Load Content

The selected core won't be on the suggested cores list as "Current core"

**Comment by Nine-H** [comment] 2020-01-30 08:04
Is this related to parallel failing to load on the flatpak version, all I get is
```
[ERROR] Failed to open libretro core: "/home/me/.var/app/org.libretro.RetroArch/config/retroarch/cores/parallel_n64_libretro.so"
[ERROR] Error(s): libtinfo.so.5: cannot open shared object file: No such file or directory
```
but 
```
-rw-r--r--  1 me me 56404928 Jan 30 18:52 parallel_n64_libretro.so
```
and I just updated the core info through the updater.

**Comment by RobLoach** [comment] 2020-05-06 08:26
https://github.com/flathub/org.libretro.RetroArch/issues/81

**Closed by RobLoach** 2020-05-06 08:26 UTC
Labels: bug: minor
