### ISSUE TITLE
Linux: Netplay controls not working

### ISSUE THREAD

**Issue by alkaris2** [libretro/RetroArch#11996] opened 2021-02-06 17:09 UTC
## Description

Regression return of issue #9281 Linux : Netplay controls stop working on some cores?

Netplay controls stops working for analogue stick input for player, also after trying said solution from that issue of running retroarch with the following;

`./retroarch -d1:5 -d2:5 -d3:5 -d4:5 -L <core> <rom> `

while this DOES appear to give control back to the first client player, it ends up controlling the other client's game. I tested this out on my two machines, running same versions of RetroArch with same Core, which was ParaLLel N64 core, and the game tested with was Ocarina of Time Randomizer version 6.0, multiworld 2 player seed.

The result is this;

```mermaid
[ Host ]       -->> input <<--       [ Client ]
```
controller input becomes unidirectional, and controls both Host and Client games.

### Expected behavior

Expected result is Host starts game, Client joins, and each have their own working independant controls of the game to play over Netplay.

### Bisect Results

I was testing out Netplay to see how I could play Randomizer over Netplay using RetroArch, and to make sure that I've got everything I could setup correctly. Disabling NAT (since it's not needed and port mapping fails otherwise) disable upnp since it automatically opens the ports to use on the network.

- RetroArch: RetroArch 1.9.0-2 from AUR / Git version: 5e551dd92b

### Environment information

- OS: Manjaro Linux (w/ Cinnamon + KDE Plasma)
- Compiler: GCC 10.2 (64-bit)

**Comment by LibretroAdmin** [comment] 2022-08-02 16:29
@Cthulhu-throwaway is this still reproducable?

**Comment by Cthulhu-throwaway** [comment] 2022-08-02 21:42
Unsupported core. https://docs.libretro.com/guides/netplay-faq/#does-psx-n64-dreamcast-gamecube-wii-3ds-netplay-work

**Comment by Cthulhu-throwaway** [comment] 2022-08-17 06:19
@LibretroAdmin see above. Should be closed as "won't fix".

I think I've covered all open netplay issues (those that make any sense) from 2022 and 2021, anything older than that can be considered outdated, given how much I've refactored since late 2021.

**Closed** 2022-08-17 06:21 UTC
