### ISSUE TITLE
Choppy background animation

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#4753] opened 2017-03-14 00:49 UTC
When running retroarch background ribbon sometimes jitters as if not updated properly. Video: https://www.youtube.com/watch?v=4Fws3_pso-g

Steps to reproduce: 1. Run retroarch on it's default settings

### Version/Commit

Retroarch: 51581e1
Linux Kubuntu 16.10 x64, radeon driver, ati rx470 8gb, gl rendering

**Comment by bparker06** [comment] 2017-03-14 01:17
paging @hunterk

**Comment by ArcFutahito** [comment] 2017-03-14 09:54
Only ribbon (simplified) and ribbon seem to be affected with ribbon being less "jumpy". Bokeh and snow shader pipelines look good or it's not noticeable.

**Comment by orbea** [comment] 2019-01-01 02:43
The ribbon is fine here. Since the original user has since deleted their account and this has not had any activity since this issue was made I am going to close this. If anyone can reproduce problems with the ribbon with the current master please let us know!

**Closed by orbea** 2019-01-01 02:43 UTC
