### ISSUE TITLE
Can't install content or save config when installed through Chocolatey

### ISSUE THREAD

**Issue by Zeklandia** [libretro/RetroArch#6521] opened 2018-04-03 07:26 UTC
## Description
The core updater and core installer download but do not install cores. Config files also cannot be saved.

### Expected behavior
The core installer should be able to install cores

### Actual behavior
Cores download and then nothing happens. Attempting to save a config throws an error.

### Steps to reproduce the bug
1. `choco install retroarch`
2. `retroarch`
3. attempt to install core (or any other content), or save a new config file

### Bisect Results
This was my first time installing RetroArch on this machine. I would guess, that, because the default Chocolatey install directory is `C:\ProgramData\chocolatey\lib\`, the problem is with needing administrative permission to edit the install folder.

### Version/Commit
- RetroArch: 1.7.1/`6fc6bfbb24`

### Environment information
- OS: Windows 10 Pro 64-bit

**Comment by orbea** [comment] 2018-04-03 19:14
The obvious question is, what is chocolatey?

I suppose the issue is that `C:\ProgramData\chocolatey\lib\` requires admin permissions to write to and you're running RetroArch as a user? RetroArch unfortunately currently only supports one core directory and Linux distros run into the same issue.

If you want to work around this I suggest one of these two things.
1. Change the core and other related directories to somewhere you have permissions to download cores to.
2. Build the cores from source and install them to the desired location manually.

That said this is essentially a duplicate of issue https://github.com/libretro/RetroArch/issues/3237. I think solving that would be the correct long term solution.

**Comment by Zeklandia** [comment] 2018-04-03 19:35
This is [Chocolatey](https://chocolatey.org).

I see what you mean, but I think this is a different issue, because this is more of a problem with the Chocolatey packaging. If the package were set to install to a user-accessible folder instead, this would be fixed without having to implement a fix for #3237.

**Comment by gouchi** [comment] 2018-04-03 20:03
Please report the issue to the [package maintainer](https://chocolatey.org/packages/retroarch).

Thank you.

**Closed** 2018-04-03 20:14 UTC
Labels: invalid
