### ISSUE TITLE
Linux: udev input dangerous: replayed on terminal

### ISSUE THREAD

**Issue by T-X** [libretro/RetroArch#4252] opened 2016-12-16 00:13 UTC
I was at first very astonished when RetroArch seemed to restart itself after selecting to quit in the menu. And grew sceptical when another time the config had reset itself.

It seems that when starting RetroArch in a terminal on Linux, for instance via a plain "$ ./retroarch", once RetroArch exits any keyboard input previously done is still executed on the terminal.

So the RetroArch config reset was basically triggered by me browsing through the RetroArch menu and resulted in replaying that browsing in the bash history upon exit. Which in turn happened to be a "rm -r ~/.config/retroarch" I had issued earlier... I was very glad that it wasn't something like a "rm -r ../" or so...

My current ugly workaround is to run "$ exec ./retroarch" to be on the safe side for now. But RetroArch should definitely somehow avoid any input getting to the terminal at all.

(maybe, even though things are getting written to the framebuffer directly, I guess, spawn a new, focused window which eats any input instead of the terminal?)

**Comment by bparker06** [comment] 2016-12-16 15:38
I've never heard of this happening and I'm unable to reproduce it. Can you explain your exact setup in more detail? Like what udev devices you have, which Linux distro, what RetroArch commit etc. and see if we can narrow it down. Does this happen with the keyboard or with a gamepad? What about in fullscreen vs not? Do other input drivers behave similarly? What about on another machine/OS entirely?

**Comment by bparker06** [comment] 2016-12-16 16:39
I just realized you mentioned "things are getting written to the framebuffer", this suggests a separate problem that may be the cause of the issue. Can you post a verbose log output from RA? It's possible you're somehow using one of the non-X11 context drivers (EGL/KMS/DRM) while running under X11, and that could explain your keystrokes being seen twice.

**Comment by T-X** [comment] 2016-12-18 21:58
Sure, it's an Odroid W (so basically the same single core, ARMv6-based Broadcom SoC as on a Pi Zero or Pi One). I'm running a Debian Jessie based Raspbian on it. With X11 together with a lightdm and the tiling window manager Xmonad.

Here are two screenshots, both taken after RetroArch exits. The former one looks pretty ok-ish. The date command and ./retroarch command were executed manually. The only thing odd here is the Ansi escape sequence for the escape key: "^[%" shouldn't be there, I guess, but was added through me hitting escape to exit RetroArch.

![retroarch-ok](https://cloud.githubusercontent.com/assets/350145/21296791/cd7ab9b4-c573-11e6-88e6-040ed2752fef.png)

The second screenshot is more interesting: The second "date" command is one I've **never** typed in the shell. It automatically appeared upon exiting RetroArch. Notice how the RetroArch output now contains "^[[A^[[A", two times the Ansi escape sequence for the Up-key. This time, while having the RetroArch menu I not only just hit "Escape", but before doing that "Up, Up, Enter", too.

![retroarch-not-ok](https://cloud.githubusercontent.com/assets/350145/21296792/d7974e8a-c573-11e6-82bf-b496f001fc27.png)

I'm also attaching my retroarch configs here:

[retroarch.cfg.txt](https://github.com/libretro/RetroArch/files/659683/retroarch.cfg.txt)
[retroarch-core-options.cfg.txt](https://github.com/libretro/RetroArch/files/659684/retroarch-core-options.cfg.txt)

As well as the output of ./configure:

[configure.txt](https://github.com/libretro/RetroArch/files/659685/configure.txt)

Let me know if there is any additional information needed to reproduce the issue.

**Comment by bparker06** [comment] 2016-12-19 16:01
Ok, it looks like what's going on is that the "videocore" context driver is being used (which has precedence over X11), which only supports EGL, something that's not going to play nicely within X11. At this point I think you have 2 options. You can either switch to the console/VT and run RA from there, which should invoke EGL outside of X11 and run normally (not sure if X11 is allowed to be running at the same time though), or you could try compiling without Videocore support and see if it will then use the "x" context driver instead.

**Comment by T-X** [comment] 2016-12-20 00:31
You're right, on a tty1 for instance I cannot reproduce the issue!

Regarding Videocore support, what is the recommended way to deactivate it? (couldn't find the term "videocore" in "./configure --help") Also, would that have a noticeable impact on performance?

**Comment by orbea** [comment] 2017-10-22 02:41
@T-X Is this still an issue for you?

**Comment by orbea** [comment] 2018-12-27 06:03
Given the lack of replies or activity I am going to close this issue, please reply if this is still a problem.

**Closed by orbea** 2018-12-27 06:03 UTC
