### ISSUE TITLE
UI doesn't go back to the main menu after selecting a core

### ISSUE THREAD

**Issue by leiradel** [libretro/RetroArch#1791] opened 2015-06-14 16:44 UTC
Go to "Core Selection" and navigate to a core. When you select it, the UI will go back one folder instead of going back to the main menu.

MinGW64 build, no paths configured (i.e. the folder navigation begins at drive selection.)

**Comment by fr500** [comment] 2015-06-14 19:12
I don't get this issue, but, it doesn't go back to main menu when loading a game from Content History

**Comment by leiradel** [comment] 2015-06-14 19:39
Yes, I've seen the same thing in some other places.

**Comment by fr500** [comment] 2015-07-02 22:31
This is fixed already, now after loading content users are always left at the Quick Menu

**Comment by leiradel** [comment] 2015-07-03 00:58
The issue is when the user selects a core, not a content. I've just built RA 24236455c28af03946a9f77304e68e58d00425b3 and the user is left browsing the file system after selecting a core, please reopen.

**Comment by fr500** [comment] 2015-07-03 01:35
my bad sorry

**Comment by Kivutar** [comment] 2015-07-04 07:55
OK, maybe some are not able to reproduce this because they have their "core directory" set, so going back to the parent directory is equal to going back to the main menu.

@leiradel is your core directory set?

**Comment by twinaphex** [comment] 2015-07-08 06:35
This should be fixed by now.

In case OP can still reproduce this issue, then open it again.

**Closed** 2015-07-08 06:44 UTC
