### ISSUE TITLE
[GLUI] Scrolling beyond currently selected menu item causes all items to disappear

### ISSUE THREAD

**Issue by FrozenFish24** [libretro/RetroArch#1995] opened 2015-07-19 15:17 UTC
On my HTC Desire 320 running Android 4.4.2 scrolling in GLUI so that the currently selected menu item goes offscreen causes all the menu items to vanish. If running a game, the paused image behind the menu elements will also disappear. The bars at the top and bottom of the screen and their text are unaffected.

Here's a screenshot of the topmost menu with "Load Core" selected and the menu scrolled to the bottom:
![screenshot_2015-07-19-23-02-38](https://cloud.githubusercontent.com/assets/12547453/8766434/9c851418-2e6a-11e5-8bc3-6292427e832f.png)

**Comment by twinaphex** [comment] 2015-07-19 15:44
Can you tell us - if you can see it that is - what kind of DPI it reports in RetroArch?

You can view this by going to Information -> System Information. It should be shown somewhere there - should be called 'Display metric DPI'.

**Comment by FrozenFish24** [comment] 2015-07-19 15:50
It's reporting 240.00

**Comment by Kivutar** [comment] 2015-07-19 16:03
I noticed something close to this, use R on the main menu, when a specific entry gets selected, every entry will go away.

**Comment by heuripedes** [comment] 2015-07-20 00:24
Could you post the exact actions to reproduce this?

**Comment by FrozenFish24** [comment] 2015-07-20 07:06
Sure.

1. Make sure the onscreen overlay is disabled and you're navigating the GLUI menus by touch
2. Enter any menu that has more items than can fit on your screen e.g. Settings
3. Tap a menu item once so it becomes highlighted but do not enter it's submenu
4. Touch scroll to the point where the highlighted menu item leaves the screen at the top or bottom
5. All menu items should disappear

**Comment by heuripedes** [comment] 2015-07-20 14:07
Like this?
![https://i.imgur.com/nD7ckwr.gif](https://i.imgur.com/nD7ckwr.gif)

**Comment by thatcadguy** [comment] 2015-10-14 22:26
I can confirm this on the Samsung Galaxy Note II running both 1.2.2 and nightly. Basically any menu with more items than a screenful will have the items disappear when you scroll down. The trigger seems to be after the slider goes a certain amount of pixels rather than a percentage, but that's just a guess based on watching it.

I noticed that tapping where the items should be will make it re-appear, assuming you don't have an overlay up.

**Comment by heuripedes** [comment] 2015-11-02 15:56
@Kivutar and @twinaphex have pushed many improvements to GLUI, including one that is related to the reported GPUs, are you guys still able to reproduce the bug with the latest nightly build?

**Comment by thatcadguy** [comment] 2015-11-02 15:58
No, this is fixed as of yesterday

**Closed** 2015-11-02 16:02 UTC
Labels: bug
