### ISSUE TITLE
[Windows 10]startup failed

### ISSUE THREAD

**Issue by sean908** [libretro/RetroArch#11298] opened 2020-09-07 06:41 UTC
I've tried the 32/64bit zip version and 64bit installer version on my Win 10 PC, but all of them got no response after double click the icon.

So I deleted the retroarch.cfg file and did the full process again.

After double click the retroarch.exe, it will generate a .cfg file with the content

> config_save_on_exit = "true"

then I updated the .cfg file with the property I found on the Internet(My DX version is 12)
**video_driver = "d3d12"**

the exe still didn't work.

And then I output the log

> [INFO] RetroArch 1.9.0 (Git 6388872a54)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
[INFO] 容量:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Aug 11 2020
[INFO] Version: 1.9.0
[INFO] Git: 6388872a54
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Overrides]: 重定向游戏存档文件至 "G:\FreeGames\Simulators\RetroArch_x64_green\saves\.srm".
[INFO] [Overrides]: 正在重定向状态存储至 "G:\FreeGames\Simulators\RetroArch_x64_green\states\.state".
[INFO] libretro API 版本: 1
[INFO] 未按照 API 编译: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 960x720
[ERROR] [D3D12]: win32_set_video_mode failed.
[ERROR] [D3D12]: failed to init video driver.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] 收到严重错误于: "init_video()"

So what else can I try to make it work now?

**Comment by shinecurve** [comment] 2020-09-24 11:49
Experienced the same problem since version 1.8.9

retroarch 1.9.0 x64
win10 x64 2004 simp_chinese

**Comment by tommyonsn** [comment] 2020-10-16 22:52
same error v1.90
win10 x64 18363 simp_chinese
是不是简体中文的win10都不行啊？
我把debug的log删了之后这货干脆log都不给出了

**Comment by ajiesw** [comment] 2020-10-25 17:03
me too，task manager will flash once when run exe

**Comment by gouchi** [comment] 2020-10-29 20:06
I can't reproduce your issue using [latest nightly](http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z). I switched to simplified Chinese and launched RA.

![RA-chinese](https://user-images.githubusercontent.com/7869503/97626726-8fe48980-1a2a-11eb-8de3-7b06c6a21bf7.png)

**Comment by shinecurve** [comment] 2020-11-05 10:12
The latest nightly version does not have the problem of being unable to open, but the window title bar will have garbled characters, just like your screenshot.

**Comment by ajiesw** [comment] 2020-11-06 16:17
> I can't reproduce your issue using [latest nightly](http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z). I switched to simplified Chinese and launched RA.
> 
> ![RA-chinese](https://user-images.githubusercontent.com/7869503/97626726-8fe48980-1a2a-11eb-8de3-7b06c6a21bf7.png)
sorry,too late to reply.now I use 1.7.8version,it`s ok.but The latest version can`t open
![Snipaste_2020-11-07_00-09-22](https://user-images.githubusercontent.com/24909939/98388309-90fe6200-208d-11eb-9d67-605c55857cd2.png)
maybe u  can tell me how to update latest version in software

**Comment by gouchi** [comment] 2020-11-06 21:06
@ajiesw no problem. If you want to update to RetroArch nightly please download this [archive](https://buildbot.libretro.com/nightly/windows/x86_64/RetroArch_update.zip) and decompress it in RetroArch directory. If you have an issue launching the new version please decompress also this [archive](https://buildbot.libretro.com/nightly/windows/x86_64/redist.7z) in RetroArch directory.

You can also use this [software](https://stellarupdater.github.io) to update to nightly.

Lastly, if you want to use the latest stable release (1.9.0) please use this [archive](https://buildbot.libretro.com/stable/1.9.0/windows/x86_64/RetroArch.7z).

@shinecurve Please open another issue for the garbled window title bar.

@sean908 If it is ok for you, please close this issue.

**Comment by ajiesw** [comment] 2020-11-07 05:14
> @ajiesw no problem. If you want to update to RetroArch nightly please download this [archive](https://buildbot.libretro.com/nightly/windows/x86_64/RetroArch_update.zip) and decompress it in RetroArch directory. If you have an issue launching the new version please decompress also this [archive](https://buildbot.libretro.com/nightly/windows/x86_64/redist.7z) in RetroArch directory.
> 
> You can also use this [software](https://stellarupdater.github.io) to update to nightly.
> 
> Lastly, if you want to use the latest stable release (1.9.0) please use this [archive](https://buildbot.libretro.com/stable/1.9.0/windows/x86_64/RetroArch.7z).
> 
> @shinecurve Please open another issue for the garbled window title bar.
> 
> @sean908 If it is ok for you, please close this issue.

----
> thx,now I can play latest
![Snipaste_2020-11-07_13-13-10](https://user-images.githubusercontent.com/24909939/98432633-1e2bd000-20fb-11eb-8bbc-d86fe4f6a3e8.png)
> good,luck

**Comment by gouchi** [comment] 2021-06-06 14:20
@sean908 Is it possible to close this issue ? Thank you.

**Closed** 2022-09-03 12:25 UTC
