### ISSUE TITLE
cfg override propagates to retroarch.cfg

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#3481] opened 2016-08-31 15:39 UTC
It happens when using a core override with the internal ffmpeg core.

When a video ends you get back to retroarch GUI.
Pushing "escape" with "save config on exit" activated will save the override settings to your main retroarch.cfg.

It doesn't happen if you stop the video with quickmenu "close" or just push esc during viewing.

**Comment by fr500** [comment] 2016-08-31 15:47
Then I guess when the video stops RetroArch is doing something differently than "close content"
The issue is not on overrides themselves but on the runloop, no idea how the internal cores work in this regard 
Maybe @twinaphex has an idea.

**Comment by dankcushions** [comment] 2016-08-31 15:48
If i'm reading correctly, i also get this with rom overrides - see http://libretro.com/forums/showthread.php?t=3128&page=9&p=37803&viewfull=1#post37803

i haven't retested this in several months though!

**Comment by fr500** [comment] 2016-08-31 17:04
@dankcushions can you confirm? and give me exact steps to reproduce?
If it works fine on close content but not on exit then it means it's not calling config_unload_overrides on exit but from my testing it is doing so fine.

**Comment by bparker06** [comment] 2016-08-31 18:55
How old is the build you are using? There was a fix merged for issue #3432 on 8/20 that handles override saving and auto save-state correctly when pressing escape.

**Comment by Tatsuya79** [comment] 2016-08-31 19:03
I'm using a build I compiled earlier today for win x64.

**Comment by fr500** [comment] 2016-08-31 19:18
@bparker06 he is not complaining about config not saving. He's complaining about some settings carrying over to the global config.

**Comment by bparker06** [comment] 2016-08-31 19:32
Yep, I'm able to reproduce it here also, looking into it.

**Comment by dankcushions** [comment] 2016-08-31 20:09
here's how i can reproduce:

set your global cfg to have:
```
auto_overrides_enable = "true"
video_smooth = false
config_save_on_exit = true
```
load up gamename.zip to test smoothing is off.

then create a gamename.zip.cfg to have:
```
video_smooth = true
```
load up gamename.zip to test smoothing is on, then quit (i used start + select where select is my hotkey, and start is quit RA)

the setting now seems to be stored in the main cfg as true.

**Comment by fr500** [comment] 2016-08-31 20:11
did you try now? or is that from memory?

**Comment by dankcushions** [comment] 2016-08-31 20:26
@fr500 tried just then. going to rebuild RA and try again as my build is a couple of weeks old.

**Comment by fr500** [comment] 2016-08-31 20:27
Cool, let me know, you can now create the overrides from within the menu btw

**Comment by fr500** [comment] 2016-09-01 04:02
I tried with overrides and normal content operations (no ffmpeg since it crashes on nvidia) and I couldn't reproduce the other issues, overrides are not propagating if I exit with hotkey, quit on the menu, or close content and then quit from the menu

**Comment by Tatsuya79** [comment] 2016-09-01 07:06
I'm on nividia and got the crash too in gl, but vulkan is working now.
That's using it that I noticed this bug.

**Comment by dankcushions** [comment] 2016-09-02 15:19
@fr500 
> Cool, let me know, you can now create the overrides from within the menu btw

Nice! However I just tried this and not sure if it's working right for me. Loaded up robotron.zip in mame2003, changed quick menu > controls > device type to 'retropad w/ analog' & analog to digital type to 'left analog', and then saved game override.

The override seems to have saved in /config dir/MAME 2003/robotron.cfg and it's:
```
video_allow_rotate = "true"
video_force_aspect = "true"
xmb_show_settings = "true"
xmb_show_images = "true"
xmb_show_history = "true"
auto_shaders_enable = "true"
show_hidden_files = "true"
```
which is a bunch of stuff I didn't change. meanwhile, the two settings i did change are in my normal .cfg as per 'save on exit':
```
input_libretro_device_p1 = "5"
input_player1_analog_dpad_mode = "1"
```
Maybe I'm doing it wrong?

I also retested my previous issue of the override settings migrating into the main config and it's still happening. These are overrides I've manually made, though, and they're called 'gamename.ext.cfg' rather than 'gamename.cfg' like the auto ones, if that matters.

Eg, if you use shaders in your cfg, and if your normal cfg has 'save config on exit' turned on, stick this in one of your rom folders:
**gamename.ext.cfg**
```
video_shader_enable = "false"
```
then load up the game - shaders turned off. load up another game, also turned off. IMO it shouldn't save any settings you've overridden.

**Comment by fr500** [comment] 2016-09-02 16:24
@dankcushions 
I dunno aboyt those manual overrides, I don't expect it to play well with that. How are you loading them? --appendconfig?

Regarding the settings that don't work, input settings are the one thing that might be lacking because they haven't been moved to the new arrays.

And the ones that did copy... well those are new, just load RA and exit once and it won't copy those over.

**Comment by dankcushions** [comment] 2016-09-02 16:34
@fr500 
> I dunno aboyt those manual overrides, I don't expect it to play well with that. How are you loading them? --appendconfig?

you don't need to add them to the commandline RA just seems to pick them up if they're the same name as the game.ext and in the content dir. in fact i'm surprised this autoconfig stuff doesn't use the same system.

**Comment by fr500** [comment] 2016-09-02 16:44
Where do you put those ?

**Comment by dankcushions** [comment] 2016-09-02 16:50
In the same directory as the rom. Eg:
```
/roms/robotron.zip
/roms/robotron.zip.cfg
```

**Comment by fr500** [comment] 2016-09-02 16:51
Can you post a full log to see if it's the override system doing something
unexpected or another thing someone else might have implemented and never
documented?

**Comment by joolswills** [comment] 2016-09-02 17:09
@dankcushions those are added using  `--appendconfig` by the retropie runcommand launch script.

**Comment by dankcushions** [comment] 2016-09-02 17:13
@joolswills @fr500 whoops :( sorry i totally assumed they were a RA thing. I just found out the same thing. sorry for wasting your time!

**Comment by fr500** [comment] 2016-09-02 18:24
Oh, ok then. So I guess I only have to worry about what @Tatsuya79 reported

**Comment by fr500** [comment] 2016-09-09 15:58
Hmmm I don't get it.
Did the core crash to menu or did it crash retroarch?

**Comment by Tatsuya79** [comment] 2016-09-09 16:39
It crashed to the GUI (retroarch didn't crash).

Happened again when trying glupen64 core-> crash when trying to run with cg shader, override got into retroarch.cfg (this crashed retroarch this time)

**Comment by fr500** [comment] 2016-09-11 04:34
Shaders are being propagated to the CFG, that's separate, it's something that was changed on how presets are loaded (before the active preset always was retroarch.cgp|glslp, now it actually loads the shader and changes it which I hate)

**Comment by fr500** [comment] 2016-09-11 04:37
Ok confirmed this happens with FFmpeg when playback ends and whe the cores "fail to load" and go back to menu.
These cases are new and I certainly don't know how to handle them yet

**Closed** 2021-07-26 17:12 UTC
Labels: bug: minor, commandline
