### ISSUE TITLE
PS2 RetroArch cores for Stella2014  and GearColeco crash to PS2 menu in recent stable builds and breaks PS2 RetroArch

### ISSUE THREAD

**Issue by larryvgs** [libretro/RetroArch#16122] opened 2024-01-16 02:17 UTC
The last stable build for PS2 RetroArch that works with both the Stella2014 and Gearcoleco cores is the 1.13 build.
In every stable build since, (1.14, 1.15 and 1.16) if you try to load the core or launch an Atari 2600 or Colecovision game, PS2 RetroArch will crash to the PS2 menu, and will break PS2 RetroArch if you try to launch it again.  Deleting the retroarch.cfg file does not help, and PS2 RetroArch will then have to be re-installed to get it to work again.

**Comment by zoltanvb** [comment] 2024-01-16 19:53
Bisect points to https://github.com/libretro/RetroArch/commit/b207ddbe845baa54f922c8f8a63e63dbd3e5ccda . However, it is not possible/recommended to roll it back as this has fixed a number of other faults... I wonder why it causes problem with these cores.

**Comment by LibretroAdmin** [comment] 2024-01-16 21:40
@fjtrujy Do you have any ideas here?

**Comment by fjtrujy** [comment] 2024-01-17 17:51
I would need to try myself

**Comment by larryvgs** [comment] 2024-01-20 06:50
Archades Games had a video on YouTube "Retroarch Atari 2600 Emulation Setup Guide" from 2 years ago which peaked my interest in which the 1.9.1 version of PS2 RetroArch worked with Stella2014.  Then I came across another post searching where someone said the Gearcoleco core also did not work when he tried it.  I first tried different installs of FunTuna and OpenTuna which made no difference, before testing with the current nightly builds of PS2 RetroArch, before moving on to the latest stable versions and going back, before finally the 1.13 version (11-19-2022) worked with both.

**Comment by fjtrujy** [comment] 2024-01-20 09:47
All the changes done has been either in a RetroArch or  core, because the PS2 toolchain keeps the same.
I will try to debug it and find out why is it failing

**Comment by larryvgs** [comment] 2024-01-20 14:22
Did a lot more testing, and while the latest stable 1.16 PS2 RetroArch has no sound, the latest nightly build does have sound.
Nightly build (1-20-2024) still crashed on Stella2014 and Gearcoleco cores though.  But I think I narrowed down the problem.

Just for the hell of it, I replaced the Stella2014 and Gearcoleco cores from the 1.16 nightly build with the cores from the 1.13 build and it worked!  No more crashes.  So there's your temporary fix.  Something must be off with the versions of the Stella2014 and Gearcoleco cores after 1.13.  Everything else that I tested seems to be fine.  Tested GameBoy, Lynx, Genesis, Sega Master System, NES, SNES and Intellivision and I was able to get them all working with at least one of the cores provided.

**Comment by zoltanvb** [comment] 2024-01-21 07:03
Just a note: PS2 RetroArch is statically compiled, that is, the core file contains all of RetroArch code. So by using the core from 1.13, you are using RA 1.13.0. No sound issue was RetroArch problem and was fixed at #15827 .

I have tried to load all supplied cores on 1.14.0, and apart from the mentioned 2, following cores can be loaded no more, if it helps the investigation. I have not bisected these further, but these cores can also not be loaded on 1.16.0.
Arduboy
Gearboy
Retro8
Gearsystem
ECWolf

**Comment by Jamirus238** [comment] 2024-02-01 12:18
Are the Atari800 and Pico Drive cores confirmed to work fine? I remember I had problems with these (used on 1.14.0), the A8 one couldn't detect roms for some reason from mass where I started it from. I ended up transfering it to mc, but gameplay was very slow. 
The Pico Drive core worked for me, but save states where unusable as they led to freezing.

**Comment by andymcca** [comment] 2024-08-31 17:50
> All the changes done has been either in a RetroArch or core, because the PS2 toolchain keeps the same. I will try to debug it and find out why is it failing

Hey @fjtrujy , I sent you a message on Discord if you still use it?  Trying to fix lr-gpsp on PS2, would like to share info between us if possible? Thx

**Comment by fjtrujy** [comment] 2024-09-06 14:06
> Did a lot more testing, and while the latest stable 1.16 PS2 RetroArch has no sound, the latest nightly build does have sound. Nightly build (1-20-2024) still crashed on Stella2014 and Gearcoleco cores though. But I think I narrowed down the problem.
> 
> Just for the hell of it, I replaced the Stella2014 and Gearcoleco cores from the 1.16 nightly build with the cores from the 1.13 build and it worked! No more crashes. So there's your temporary fix. Something must be off with the versions of the Stella2014 and Gearcoleco cores after 1.13. Everything else that I tested seems to be fine. Tested GameBoy, Lynx, Genesis, Sega Master System, NES, SNES and Intellivision and I was able to get them all working with at least one of the cores provided.

I'm able to reproduce the stella2014 issue, black screen it is not loading. I don't know yet where is the issue, I would need to investigate it :(

**Comment by fjtrujy** [comment] 2024-09-06 22:40
I have found the issue for Stella2014.

I have it now working, in the following days/weeks will be fixed.
<img width="1076" alt="Screenshot 2024-09-07 at 00 37 22" src="https://github.com/user-attachments/assets/a6c953b8-99c9-448f-baee-8d82e45de378">

<img width="1076" alt="Screenshot 2024-09-07 at 00 38 12" src="https://github.com/user-attachments/assets/dd520a19-c3eb-40ed-8a32-699505a7bc96">

**Closed** 2024-09-06 22:45 UTC

**Comment by fjtrujy** [comment] 2024-09-08 17:25
@larryvgs the latest nightly has already the fix!
Enjoy it!

**Comment by zoltanvb** [comment] 2024-09-08 17:37
I can confirm other cores (mentioned above) can also be loaded now. Thank you!

**Comment by larryvgs** [comment] 2024-09-10 05:46
Excellent!  Finally found the time to try it and all the retro cores I tried including the Stella2014 (Atari 2600) and Gearcoleco (ColecoVision) cores now work in the latest nightly build.  Great job everyone!  Appreciate all your hard work.
larryvgs

    On Sunday, September 8, 2024 at 10:38:02 AM PDT, zoltanvb ***@***.***> wrote:  
 
 


I can confirm other cores (mentioned above) can also be loaded now. Thank you!
