### ISSUE TITLE
Window not composited on GNOME wayland (flatpak)

### ISSUE THREAD

**Issue by Nine-H** [libretro/RetroArch#6606] opened 2018-04-23 01:08 UTC
## Description

- Installed retroarch from flatpak on fedora27
- works fine in xorg
- no window border, can't drag or resize window in wayland
- running stable

```
[nine@x1-yoghurt ~]$ flatpak list
Ref                                             Options     
org.libretro.RetroArch/x86_64/stable            user,current
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6 user,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6      user,runtime
org.freedesktop.Platform/x86_64/1.6             user,runtime
````

### Expected behavior

- I expect the flatpak package to function normally in a wayland session

### Actual behavior

- I get a pseudo window that can't be interacted with from gnome
- clicking on the window (or app in fullscreen) goes "through" retroarch to the apps in the background

### Steps to reproduce the bug

1. start a wayland sesson
2. flatpak run org.libretro.Retroarch
3. click anything

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 6fc6bfb

### Environment information

- OS: fedora f27
- Compiler: GCC (6.2.0)64-bit

**Comment by hizzlekizzle** [comment] 2018-04-23 02:16
I believe this is a duplicate of https://github.com/libretro/RetroArch/issues/4778

**Comment by Nine-H** [comment] 2018-04-25 01:16
I think it's super, and the events go straight through the window. Could just be build flags for the flatpak because I understand there is wayland support.

**Comment by costrouc** [comment] 2018-05-07 15:59
I have the same issue Ubuntu 17.04 with wayland

**Comment by twinaphex** [comment] 2018-07-11 08:20
Is this still an ongoing issue? Is there anybody able to help with this issue? @Themaister You have any clues?

**Comment by Nine-H** [comment] 2018-07-11 11:56
current flatpak is working in fedora: no window controls, but you can move retroarch with the super key and it's added correctly to the window stack.

**Comment by Sunderland93** [comment] 2018-11-24 08:54
RetroArch does not support Client-Side Decorations, which GNOME (and Weston) needs. And GNOME developers is against SSD (Server-Side Decorations), which I plan to implement in RetroArch after #7607 is merged.

**Comment by orbea** [comment] 2018-12-21 21:04
@Sunderland93 Is this still an issue?

**Comment by Sunderland93** [comment] 2018-12-22 14:49
@orbea since GNOME (and Weston tough) is against SSD (Server Side Decorations), it will be permanent issue, because RetroArch doesn's support client-side window decorations (it's really hard to implement it). RetroArch already support xdg-decoration protocol - standard Wayland extension which supported by Sway (and other wlroots-based compositors), and will be implemented in KDE Plasma 5.15.

**Comment by orbea** [comment] 2018-12-22 15:02
Thanks for the update!

**Comment by ColinKinloch** [comment] 2022-01-25 15:10
This should be resolved as of [v1.10.0](https://github.com/libretro/RetroArch/tree/v1.10.0)

**Closed** 2022-09-03 03:36 UTC
Labels: bug: major, bug: wayland, platform: flatpak, de - gnome, window compositor
