### ISSUE TITLE
toggling between full screen and window looses apsect ratio

### ISSUE THREAD

**Issue by grant2258** [libretro/RetroArch#8373] opened 2019-02-26 16:29 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]
When toggling full screen on windows the aspect ratio 4:3 changes to 16:9 in full screen. Tested on many cores snes 9x mame2003 mame2010. you can get the sapect ratio back if you change core provided to something else then set it to core provided again.

- RetroArch: [version/commit]
RetroArch 1.7.6 (Git 0aa9df6acd)

### Environment information
windows 10 msys compile env.

**Comment by orbea** [comment] 2019-02-26 17:26
Can you please bisect this and see when it started?

**Comment by grant2258** [comment] 2019-02-26 19:35
checked into this more and its happening at v1.7.6 as well so it probably a know bug or long term one.

i tested the following video drivers
(gdi)  (loose aspect ratio)
gl (works properly)
d3d9 (doesnt work for me)
d3d910 (loose aspect ratio)
d3d911 (loose aspect ratio)
d3d12 (works properly)
sdl (works properly)

ill just change the video driver to one that works looks like them 3 need fixed though.

**Comment by twinaphex** [comment] 2019-02-26 19:50
Can you test vulkan too?

**Comment by grant2258** [comment] 2019-02-26 20:08
I cant test this on the laptop im on atm. 

Ill test on my desktop when i get in  a rx480 should support vulkan and the desktop is  on windows 10 64 bit as well. Ive never used it to be honest always usually use gl. 

This laptop just has a crap intel gfx card vulkan just segfaults when i try it that why i never posted that one.

**Comment by orbea** [comment] 2019-02-26 20:29
Would you mind trying older releases than `1.7.6`? It might be worth going back all the way to `1.3.6`.

**Comment by grant2258** [comment] 2019-02-26 20:35
ill test the 1.7.x series thats as far back as im willing to go with it. If any of them work ill let you know.

**Comment by orbea** [comment] 2019-02-26 20:42
You don't have to try every single release, for example, try `v1.7.0`, `v1.6.0`, `v1.5.0`, `v1.4.1` and `v1.3.6`. If one of them is good than narrow down between which two tags it started and bisect. Since it seems other people have not been able to reproduce this yet it would really help if you can help narrow it down.

**Comment by grant2258** [comment] 2019-02-26 21:08
well even going back to 1.7.0. the cores now just segfault dont unless there are downloads available with cores dot see how to go this far back

**Comment by orbea** [comment] 2019-02-26 21:23
That sounds like an issue in itself, maybe specific to one release? Cores should not depend on any specific RetroArch version. I would suggest testing with a core like snes9x that gets lots of testing.

**Comment by grant2258** [comment] 2019-02-26 21:29
that is the core i am using tested fba mame and snes9x. Doesnt libretro common changes cause issues?

**Comment by orbea** [comment] 2019-02-26 22:08
In theory it shouldn't and it doesn't seem to cause problems on linux, but I don't use windows. In the event of bad commits I would just try another tag and use `git bisect skip` when needed.

**Comment by grant2258** [comment] 2019-02-26 22:42
@twinaphex i tested this on the desktop machine i7 with a ati 480 windows10 results are the same. I just used the v1.7.6 as i dont have a msys env on this machine

(gdi) (loose aspect ratio)
d3d9 (not working)
d3d10 (loose aspect ratio)
d3d11 (loose aspect ratio)
vulkan (is working)

im just getting segfaults when compiling older versions of RA when using current cores on windows. I did delete the retroarch.cfg and and core options and history contents

**Comment by grant2258** [comment] 2019-02-26 23:01
feel free to close this if you like there are several issues from that other link

**Comment by fr500** [comment] 2019-02-26 23:03
@orbea many cores just won't work because VFS was introduced later.

**Comment by fr500** [comment] 2019-02-26 23:13
My own findings:
I'm testing this with a fixed window size of 1920x1080 in all cases

- GDI windowed is 16:9 even though it's set to core provided
![image](https://user-images.githubusercontent.com/1721040/53453055-290b0380-39f1-11e9-838f-2a1de55fbf2a.png)

Fullscreen is 16:9, and resetting to windowed stays in 16:9 so I feel like GDI is always stretched to viewport size.

-D3D9 windowed is correct
![image](https://user-images.githubusercontent.com/1721040/53453221-8606b980-39f1-11e9-9463-1a4e5c95d94e.png)

Switching to fullscreen results in a 16:9 stretched view. Oddly enough toggling the menu fixes the stretched viewport

![image](https://user-images.githubusercontent.com/1721040/53453306-b2bad100-39f1-11e9-8269-05adae99d65c.png)
![image](https://user-images.githubusercontent.com/1721040/53453327-c403dd80-39f1-11e9-95bc-342874a43112.png)

Another weird thing this menu toggle actions destroys and re-creates the context (each time you toggle menu the window is destroyed and re-created)

Toggling back to windowed is correct

-D3D10 windowed is correct
![image](https://user-images.githubusercontent.com/1721040/53453444-1cd37600-39f2-11e9-897e-807af13c101a.png)

Switching to fullscreen results in a stretched 16:9 viewport, toggling the menu doesn't fix it here
![image](https://user-images.githubusercontent.com/1721040/53453458-26f57480-39f2-11e9-8573-58d1b8418c42.png)
![image](https://user-images.githubusercontent.com/1721040/53453475-2f4daf80-39f2-11e9-8caa-3c74209cf949.png)

Switching back to windowed is still stretched
![image](https://user-images.githubusercontent.com/1721040/53453493-3aa0db00-39f2-11e9-8c62-e966c7260b76.png)

**Comment by orbea** [comment] 2019-02-26 23:23
> many cores just won't work because VFS was introduced later.

Could this be avoided by not using VFS? I can't say I have ever run into it.

**Comment by fr500** [comment] 2019-02-26 23:24
not really sure to be honest, simple cores like snes9x should still work

**Comment by fr500** [comment] 2019-02-26 23:24
GL, D3D12 and Vulkan work properly.

**Comment by orbea** [comment] 2019-02-26 23:27
> feel free to close this if you like there are several issues from that other link

Yes, seems to be a duplicate of issue https://github.com/libretro/RetroArch/issues/6150 so lets continue that there.

**Closed by orbea** 2019-02-26 23:27 UTC
Labels: platform: windows
