### ISSUE TITLE
Settings group set to "Select File (NULL)" when looking at setting description.

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#6200] opened 2018-01-30 02:02 UTC
![menubug](https://user-images.githubusercontent.com/1220805/35544236-3ad35224-051e-11e8-8f4f-51bcb6b1f55a.PNG)

The group should remain whatever it was before, this happens with all menu options and categorys and in the help dialogs by just loading one.

RetroArch 1/29/2018 nightly
Windows 10

**Comment by orbea** [comment] 2018-12-22 17:13
I can only reproduce this with rgui and glui, can you confirm this?

**Comment by meepingsnesroms** [comment] 2018-12-22 19:55
Yes I only tested rgui, It doesnt happen on xmb.

**Comment by orbea** [comment] 2019-02-11 16:45
@jdgleaver Any chance you might be able to help with this issue?

**Comment by jdgleaver** [comment] 2019-02-11 16:55
I'll have a go!

I'll try to find some time to look at the code tomorrow.

**Comment by jdgleaver** [comment] 2019-02-11 17:12
Actually, it looks like this should be quite simple. The other menu drivers aren't affected because they don't update the title while showing message boxes. For RGUI and GLUI, we probably just need to cache the current title each time the frame is rendered, and use this whenever a message box is active. Shouldn't be too much bother (famous last words...)

**Comment by orbea** [comment] 2019-02-11 17:23
Awesome, thanks a lot!

**Comment by hhromic** [comment] 2019-02-11 17:27
I've been seeing this too, good it's being worked on! :)

**Comment by jdgleaver** [comment] 2019-02-12 11:25
PR #8261 should fix the issue :slightly_smiling_face: 

(Turns out that it was mostly unrelated to message boxes - we were just reading the menu title text in the wrong place...)

**Comment by hhromic** [comment] 2019-02-12 11:48
Kudos @jdgleaver ! Now I need to wait for the next stable release :)
In RetroPie the practice is to build only from stable releases for safety :D

**Comment by jdgleaver** [comment] 2019-02-12 12:06
> Now I need to wait for the next stable release :)
In RetroPie the practice is to build only from stable releases for safety :D

Stable is good, but that's something of a pity - I imagine we'll be waiting months for the next point release!

Ah well, they say patience is a virtue... :wink:

**Comment by twinaphex** [comment] 2019-02-12 12:46
There will be a 1.7.7 soon. The 1.7.6 release had a couple of glaring issues.

**Comment by jdgleaver** [comment] 2019-02-12 12:56
That's great news!

(Guess I'd better hurry up and get on with my last few RGUI additions...)

**Comment by orbea** [comment] 2019-02-12 16:26
Fixed in https://github.com/libretro/RetroArch/pull/8261, thanks @jdgleaver!

**Closed by orbea** 2019-02-12 16:26 UTC
Labels: bug: major, bug: ui, menu : rgui, menu: materialui
