### ISSUE TITLE
Can't apply single SLANG shader not from preset  with GLCORE and create new preset

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#10965] opened 2020-07-05 02:29 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

1. Can't apply single SLANG shader not from preset  with GLCORE and create new preset

### Expected behavior

2. I should can easily create my own preset from RA interface

### Actual behavior

3. Custom presets falling back to stock when applies.

### Steps to reproduce the bug

1. Switch Video Driver to GLCORE
2. Restart Retroarch
3. Open any game.
4. Go to shaders.
5. Add 1 shader pass, set shader 0 to "fast-bilateral.slang", shader 0 filter as "nearest", shader 0 scale to 1x.
6. Apply changes.

```
[INFO] Saved shader preset to shaders\retroarch.slangp.
[INFO] [slang]: Compiling shader "C:\shaders\shaders_slang\denoisers\shaders\fast-bilateral.slang".
[ERROR] Failed to open shader file: "C:\shaders\shaders_slang\denoisers\shaders\fast-bilateral.slang".
[ERROR] Failed to compile shader: "C:\shaders\shaders_slang\denoisers\shaders\fast-bilateral.slang".
[ERROR] [GLCore]: Failed to create preset: "shaders\retroarch.slangp".
[ERROR] [GLCore]: Failed to create filter chain: "shaders\retroarch.slangp". Falling back to stock.
[INFO] [slang]: Building pass #0 (N/A)
```

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 9edd265bf4

### Environment information

- OS: Windows 8.1 Enterprise 64-bit
- Compiler: [In case you are running local builds]

**Comment by Tatsuya79** [comment] 2020-07-05 09:53
```
[INFO] [slang]: Compiling shader "E:\Emulateurs\RetroArch64\shaders\shaders_slang\crt\shaders\geom-deluxe\crt-geom-deluxe.slang".
[INFO] [slang]: Building pass #0 (ORIG_LINEARIZED)
[ERROR] [slang]: Non-semantic textures not supported yet.
[ERROR] [slang]: Failed to reflect SPIR-V. Resource usage is inconsistent with expectations.
[ERROR] [GLCore]: Failed to create preset: "E:\Emulateurs\RetroArch64\shaders\retroarch.slangp".
[ERROR] [GLCore]: Failed to create filter chain: "E:\Emulateurs\RetroArch64\shaders\retroarch.slangp". Falling back to stock.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [GLCore]: Not using frame history.
[INFO] [GLCore]: Not using framebuffer feedback.
```

Individual slang shaders lilke those in the misc folder seem to be loading fine.

**Comment by twinaphex** [comment] 2020-07-05 15:09
I don't see the problem here. Try the latest build. It seems to work fine.

Maybe explain EXACTLY the steps you are doing that don't work (and EXACTLY the steps, one by one, thoroughly)

**Comment by ofry** [comment] 2020-07-05 17:20
@twinaphex @Tatsuya79 I'm edited issue with exast error.

**Comment by twinaphex** [comment] 2020-07-05 18:35
Does this still happen with the latest source?

If so ,we need a bisect.

**Comment by Tatsuya79** [comment] 2020-07-05 21:19
I just tried setting a single pass with crt/shaders/crt-easymode-halation/crt-easymode-halation.glsl
using the gl driver.

It failed under qt but worked under glui.

then I tried setting a single pass with crt/shaders/crt-easymode-halation/crt-easymode-halation.slang
using the vulkan driver.
It failed in both menus.

**Comment by twinaphex** [comment] 2020-07-05 21:29
I cannot reproduce this.

We need a bisect done by somebody who can reproduce this.

**Comment by Tatsuya79** [comment] 2020-07-05 23:18
OK so that's expected from a pass within a chain which refers to a previous shader, you can not isolate it.
So they're no issue it seems.

**Comment by ofry** [comment] 2020-07-06 04:24
This bug I can't reproduce with fresh config, but I found new bug. Maybe it's related too.


 1.   Switch Video Driver to GLCORE
 2.  Restart Retroarch
 3.  Open any game.
4. Open desktop UI QT companion.
5. Go to shaders.
6. Set preset mdapt.slangp
7. Add one more shader pass, set it  to "fast-bilateral.slang".

Now you will get such error:

![Screenshot - 06_07](https://user-images.githubusercontent.com/11790863/86555656-a46fb400-bf59-11ea-9045-85b64a9541f1.jpg)

Could you reproduce this? Thanks.

**Comment by bslenul** [comment] 2020-07-06 13:08
Can reproduce with Desktop Menu, for some reason it puts the drive letter 2 times in path:
```
[INFO] [slang]: Compiling shader "D:\D:\programmes\RetroArch\shaders\shaders_slang\denoisers\shaders\fast-bilateral.slang".
[ERROR] Failed to open shader file: "D:\D:\programmes\RetroArch\shaders\shaders_slang\denoisers\shaders\fast-bilateral.slang".
[ERROR] Failed to compile shader: "D:\D:\programmes\RetroArch\shaders\shaders_slang\denoisers\shaders\fast-bilateral.slang".
```
No issue without the Desktop Menu however.

**Comment by bslenul** [comment] 2020-07-06 15:09
Bisect done, started happening with this commit: 4f9a3f6813f3d90199687718f6c8116902871d5e

**Comment by twinaphex** [comment] 2020-07-06 17:27
See if this fixes it -

https://github.com/libretro/RetroArch/commit/3ad0187012025bccf32a968c786358562c739489

**Comment by bslenul** [comment] 2020-07-06 18:51
Yup, looks like it fixed it!

**Comment by hizzlekizzle** [comment] 2020-07-06 19:26
Alright, I'll close this issue, then.

**Closed by hizzlekizzle** 2020-07-06 19:26 UTC
