### ISSUE TITLE
[Android] RA takes a long time to load Overlays

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2005] opened 2015-07-22 20:13 UTC
There's an unexpected behavior in the first seconds you open it, try press the d-pad down button [tested only with the overlay] 3 times and instead it's focused at Add Content, it will be at Information --> Core informations --> No core information available. The first down press takes you at Information option, instead Load Content. It happens with B button too.

Forgot to say, I'm testing with XMB.

S4 mini (GT-I9195), android 4.4.2.

**Comment by sergiobenrocha2** [comment] 2015-07-22 20:39
You have to wait 3~4 seconds after you open it to get the expected/normal behavior.

**Comment by micechal** [comment] 2015-07-23 13:07
Could it be because you have touch support enabled and the overlay takes some time before it's fully loaded and ready to accept touches?

**Comment by sergiobenrocha2** [comment] 2015-07-23 16:13
Overlay does not depend of touch support?

**Comment by micechal** [comment] 2015-07-23 18:11
It doesn't. This setting toggles whether the menu driver will react to touches so you can navigate the menus without any overlay at all. The touch navigation is suspended if an overlay is displayed to use only one input method at a time.

**Comment by sergiobenrocha2** [comment] 2015-07-24 04:28
For some reason this touch support option is locked, I can't change it.

**Comment by micechal** [comment] 2015-07-24 12:23
Yeah me too. Not sure if it's by design though. I think it was possible to turn it off in the previous version. It also doesn't seem to appear in the config file (searched for "touch" and "menu". Maybe it's now hardcoded on Android.

**Comment by sergiobenrocha2** [comment] 2015-08-18 04:46
I chose the snes overlay and it's much better now, very responsive. So the retropad overlay causes some slowdown. I never imagined that this would be the problem, thanks to @fr500 

I was having some slowdown right after loading a core in the nightly, now it's gone with snes overlay.

**Comment by fr500** [comment] 2015-10-09 18:16
I would assume we should keep the loaded overlay in memory instead of reloading

**Comment by sergiobenrocha2** [comment] 2015-10-09 18:20
And in the case you use config overrides?

**Comment by sergiobenrocha2** [comment] 2015-10-09 18:27
RA should give you a "Load, wait" screen instead. Keep the loaded overlay in memory only if it will not change it.

**Comment by fr500** [comment] 2015-10-09 19:03
I mean keep the loaded overlay in memory as long as it's loaded, should
make no difference for overrides or core specific

**Comment by sergiobenrocha2** [comment] 2015-10-09 19:09
override files example:

Open RA: it will load retropad-fast.cfg overlay
Open a genesis game: it loads genesis.cfg overlay
Open a gba game: it loads gba.cfg overlay
Close the content: it come back to retropad-fast.cfg

Maintaining the overlay in the memory will only work if you don't change the overlays, right?

**Comment by fr500** [comment] 2015-10-10 00:07
Yes but loading an overlay while loading a game and having a delay is fine, a one time slowdown at startup.

My idea would stop the overlay from reloading when going back to the menu.

**Comment by twinaphex** [comment] 2015-12-01 16:06
Going to close this, I think the issue was resolved with enygmatas data runloop anyway.

Reopen if there is still an issue.

**Closed by twinaphex** 2015-12-01 16:06 UTC
Labels: minor bug
