### ISSUE TITLE
[Enhancement request] Keep Win32 Window and Video Driver alive until actually closing the program

### ISSUE THREAD

**Issue by Dwedit** [libretro/RetroArch#7441] opened 2018-10-15 16:00 UTC
## Description

Right now, RetroArch is destroying the Window and de-initializing the Video Driver upon Loading and Unloading each game.  At the very least, there are excessive screen flashes, but recreating the Window all the times confuses the operating system.

Supposedly, this is a relic from supporting SDL, but does not pertain to Windows.

We really need to do something about this.

**Comment by hizzlekizzle** [comment] 2018-10-15 19:15
Despite the complete teardown for loading games, the menu is not torn down, so using core overrides for the video driver crashes the system as the menu has its driver pulled out from under it. It seems we're currently in the worst-of-all-scenarios where we get the flickering of a full teardown but without any of the benefits.

**Comment by twinaphex** [comment] 2018-10-16 01:09
That's right, if the full tear down was the case for the menu too, then we could already close another issue that has been plaguing us for a long time - being able to set another menu driver, loading another game from the history list or content list, and then being able to open the menu.

**Comment by i30817** [comment] 2018-10-16 12:46
I suspect this is the reason why retroarch crashes very easily in KMS without root in linux too.

1. retroarch starts in KMS, driver acquires GPU files for writing on context creation, this succeds because nothing was using the GPU (exclusive access), RA shows GUI.
2. retroarch starts a core that reuses the 'main GUI' context, game runs (cores which recreate at the start or if you use a option that 'requires restart' crash.
3. user ends game, core destroys driver context, tries to start it again (either for RA or the 'new' core/game). Crashes because the file descriptor corresponding to the GPU was not given back/still has a user.

eh

**Comment by orbea** [comment] 2019-01-10 07:04
This is a duplicate of issue https://github.com/libretro/RetroArch/issues/4721.

**Closed by orbea** 2019-01-10 07:04 UTC
Labels: feature request
