### ISSUE TITLE
[QT] Open Qt Desktop menu without RetroArch Menu

### ISSUE THREAD

**Issue by andercard0** [libretro/RetroArch#8736] opened 2019-05-09 18:10 UTC
Feature Request: Open Desktop Menu wihout open Retroarch

I'd like to ask you guys when possible, to add a shortcut or even a separately option (.exe) for open Desktop menu without having to open retroarch. It is not a big deal but, why not add it! 

Since we have to open retroarch by 'F5' to open desktop menu make all the changes I want then, (on linux at least) close retroarch and desktop menu and open it again to make all new things avaiable. Why not only a separate program if that makes sense to call it. 

- OS: 
Currently Linux, sometimes Windows

- Compiler: Actual version, 1.7.7

Thanks in Advance.

**Comment by bparker06** [comment] 2019-05-09 19:52
It wasn't really designed to be used without the main RetroArch window, because that's where the content is displayed and other menus would be used from.

That being said, technically you could set your video driver to `null` and set the desktop menu to open at startup, and that may be enough for you. Or instead of `video_driver = "null"` you could compile RetroArch without HAVE_MENU defined.

Open to thoughts from others though.

**Comment by andercard0** [comment] 2019-05-09 22:08
I see. Thanks for clarifying, there is something that bothers me in this menu the fact that I do not have a button to - after making some change - confirm I want to save what I did. this may be a bug, I do not know.

But my changes do not take any effect after close it! So am I doing something wrong ? cause if not, why implement such a thing that does not save any changes ? 

Again, only tested with Linux.

I'm really unsure if this is something to metion on this treat tbh.

**Comment by bparker06** [comment] 2019-05-09 22:46
Can you give specific examples of what doesn't save?

**Comment by andercard0** [comment] 2019-05-10 02:15
Sure! 
First time in when I tried to configure my BIOS dir. (View > Options...Directory) at Sytem/BiOS I've tried to browse it the path, then realize there was not OK or Apply button in this menu. I thought: hm, maybe It just meant to be this way. let me just close this thing.... 

Then, when I got return to retroarch my bios path wasn't there. 

BUT. It was not cleared enough to me...that I should save any changes made in QT desktop menu
as follows into retroarch: 

Main Menu > Configuration File > Save. 
It is indeed working as it should as described by me now.
So. that said consider to make this whole process easier please in some near feature!

**Comment by bparker06** [comment] 2019-05-16 01:10
@CozmoP Do you have any input here?

**Comment by CozmoP** [comment] 2019-05-16 08:46
I can't reproduce, the settings apply immediately and are reflected on the menu.
For saving them the usual procedure applies (Main Menu > Configuration File > Save or closing RetroArch is saving on exit is enabled)

**Comment by Shideravan** [comment] 2021-01-04 03:22
I think that isn't not only counterintuitive to have another window running in background (even if aren't shown when setting the video display to "null") but also has the potential to cause errors. I would like the option to use the Qt Desktop Menu fully independent as all the features of RetroArch is now possible to use in Qt Desktop menu.

**Comment by Shideravan** [comment] 2021-01-04 03:31
Also, use:

`menu_driver = "null"`

Open the Qt Desktop menu fine, but fails if try to start a core.

**Comment by andercard0** [comment] 2021-01-08 02:55
Pff. Not eve remember of this shit will close it now. I don't care anymore.

**Closed** 2021-01-08 02:55 UTC
Labels: bug: wimp

**Comment by RainbowShatter** [comment] 2024-09-24 17:51
We need this option, i like the way it looks and i think it is quite intuitive for me
