### ISSUE TITLE
Menu entry with no text

### ISSUE THREAD

**Issue by lauren7ino** [libretro/RetroArch#16413] opened 2024-04-05 22:44 UTC
Hi
On the configurations menu I have a menu option with no text.
Check the blue '>' cursor.
I'm using pt-PT language.
Thanks 

![screenshot](https://github.com/libretro/RetroArch/assets/9194198/48651143-6eed-4901-a998-f82738fe8cb1)

**Comment by zoltanvb** [comment] 2024-04-06 05:07
Could not reproduce yet. Can you tell what version are you using (Information / System Information)?

**Comment by lauren7ino** [comment] 2024-04-06 09:02
[INFO] RetroArch 1.18.0 (Git 90b960272f)
[INFO] === Build =======================================
[INFO] Funcionalidades: ASIMD 
[INFO] Version: 1.18.0
[INFO] Git: 90b960272f
[INFO] Built: Mar 29 2024
[INFO] =================================================

**Comment by lauren7ino** [comment] 2024-04-06 11:23
While you are into it, add a > Show 'Local Network' < setting in Menu Item Visibility (is missing).
Thanks

**Comment by zoltanvb** [comment] 2024-04-06 14:30
I can not reproduce via normal builds, I'm afraid. Took the relevant values from your config file, but the 4th menu entry still shows up correctly.
But there is one thing: I can not find the commit ID in RetroArch main repository (i.e. this one), so I can only assume it was built from some fork, but I could not locate the respective source for ArkOS. If you have access to that, maybe you can take a look at the copy of this specific file there:
https://github.com/libretro/RetroArch/blob/45068ee55d1489d82f4350b09c3c75ffd632e810/intl/msg_hash_pt_pt.h#L968

If the value of MENU_ENUM_LABEL_VALUE_RESET_TO_DEFAULT_CONFIG is just whitespace (" "), this causes the entry to be invisible, but normally it is prevented by Crowdin and the translation export scripts, and I can not see any change in this line since 2 years.

**Comment by lauren7ino** [comment] 2024-04-06 14:36
OK, I will see what I can do.
I believe it's something more, have you noticed that the three dots in the right are also missing?

**Comment by sonninnos** [comment] 2024-04-06 15:00
The three dots are only supposed to be there when the option is a submenu, as in not a single action item, but that is not always 100% perfect. And indeed it does not belong there, so it is not missing.

![retroarch_2024_04_06_17_58_30_224](https://github.com/libretro/RetroArch/assets/45124675/6c691b9b-b4fc-4b81-8402-680b34c1e8e0)

**Comment by lauren7ino** [comment] 2024-04-06 15:16
OK. I went back to English and the entry also doesn't appear. It's something else not related with translations.

**Comment by christianhaitian** [comment] 2024-04-06 15:27
In ArkOS, the entry is specifically removed to prevent resetting the configuration as if the user does this, the builtin controller no longer can control the interface.  The patch used for this is here: https://github.com/christianhaitian/rk3566_core_builds/blob/master/patches/retroarch-patch-0003-disable_reset_and_enable_reboot_shutdown_menu_option.patch

**Comment by lauren7ino** [comment] 2024-04-06 15:40
Thanks !

**Comment by lauren7ino** [comment] 2024-04-06 16:03
I'm outside this conversation, but can I suggest keeping the menu entry, and having an optional retroarch.cfg.reset that is configured to the builtin controller.
Then that menu option is set, if this file exists, replaces the existing retroarch.cfg

**Comment by christianhaitian** [comment] 2024-04-06 16:41
> That indeed is not the proper way to hide the item. That only removes the action, but it should rather remove the display item in `menu/menu_displaylist.c`.

Now that I know that, I'll update the patch to remove the display entry from that location in the future.

**Comment by christianhaitian** [comment] 2024-04-06 16:47
The specific line in menu_displaylist.c that should be commented out that removes the display would be helpful as I don't know where that it in looking at the code.

**Comment by sonninnos** [comment] 2024-04-06 16:57
Searching with `MENU_ENUM_LABEL_RESET_TO_DEFAULT_CONFIG` points to this block: https://github.com/libretro/RetroArch/blob/a0dc153508eb365e554054f77535ab615dbd218c/menu/menu_displaylist.c#L10460

So either add a `break` before that or comment out the `if` and the `count++`.

**Comment by sonninnos** [comment] 2024-04-09 15:04
I'll close this since the issue is sorted.

**Closed by sonninnos** 2024-04-09 15:04 UTC
