### ISSUE TITLE
Retroachievements segfault with mame

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#4615] opened 2017-02-11 14:44 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When retroarchievement is enabled, and you load a core that does not support it causes issues and crash. Affected core is mame_libretro.dll (windows - 182 buildbot release) - this crash when running another mame game. 

### Expected behavior

run a game with mame. exit fine. run another mame game and it should play as expected.

### Actual behavior

(retroachievement enabled and logged in) - segfault when running another mame(mame_libretro.dll) game.

### Steps to reproduce the bug

1. run retroarch and load a mame game(has to be mame_libretro)
2. exit or close game using quick menu
3. run another mame game or the same game
4. segfault.

### Bisect Results

does not crash if retroachievement is disabled. 
backtrace - https://hastebin.com/sozuvemulu.css
backtrace -thread 1(windows 10 x64) - https://hastebin.com/iwucusibus.tex
retroarch_log : (cannot get proper log since logging stops writing to file after 1st run of a core)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.4.1 git 25a29a4
### Environment information

- OS: Windows 7 64bit
- Compiler: gcc version 6.3.0 (Rev1, Built by MSYS2 project), mame_libretro is latest from buildbot.

**Comment by fr500** [comment] 2017-02-11 15:23
That "solution" doesn't fix the issue. It only masks it.

**Comment by fr500** [comment] 2017-02-11 15:24
@leiradel

**Comment by fr500** [comment] 2017-02-11 17:26
I can't reproduce this on windows

**Comment by Tatsuya79** [comment] 2017-02-11 23:33
I reproduced this on win7 x64, Mame GIT (0.182).
Cheevos ON = second Mame start crashes Retroarch.

**Comment by retro-wertz** [comment] 2017-02-12 00:02
redid test on fresh install of Windows 10 1607 and still crashes on 2nd mame start when achievements is ON. it does not even need to have username or password to make it cause segfault

turning achievement OFF does not crash mame anymore after 2nd or more runs

more backtrace added:

**Comment by Sanaki** [comment] 2021-06-18 02:21
Is this still valid?

**Comment by LibretroAdmin** [comment] 2022-09-03 13:47
@Jamiras Can this be closed by now?

**Comment by Jamiras** [comment] 2022-09-06 00:06
I could not reproduce on Windows 10 using a game without achievements. I did see an issue loading a game with achievements in MAME, but that happened immediately on step 1. I'm working on a fix.

**Closed** 2022-09-06 03:04 UTC
Labels: bug: major, cheevos
