### ISSUE TITLE
Set Display-Reported Refresh Rate Broken

### ISSUE THREAD

**Issue by BParks21** [libretro/RetroArch#6838] opened 2018-05-29 03:09 UTC
## Description
So basically in the version this feature was added and all following nightlies this feature always reports 1.000hz.

I have a native 144hz asus gaming monitor that supports 60hz, 85hz, 100hz, 120hz and 144hz. With every refresh rate set this feature is always reporting 1.000hz. I remember it working at one point. I believe a Windows 10 update may have broken it. Many others have reported the same behavior on the RetroArch Discord. Even Users with AMD cards. So i don't believe it is an Nvidia driver bug. 

### Expected behavior
Report the correct refresh rate that the monitor is set to. 
Report my monitor running at 144hz

### Actual behavior
Is reporting 1.000hz with all supported refresh rates.

### Steps to reproduce the bug

Run any version of RetroArch 1.7.2 and up with latest version of Windows 10 and view the reported refresh rate

### Bisect Results

Some time during the recent Windows 10 updates following 1.7.2

### Version/Commit
1.7.2 and up

### Environment information
OS: Windows 10 64bit

**Comment by Ryunam** [comment] 2018-05-29 05:55
I can confirm that I’m experiencing the same issue on two Windows 10 1709 (so not the latest April Update) builds. The option in question always reports 1.000 Hz.

Also, it is unlikely that an Nvidia driver might have broken this feature: I have not updated my drivers since quite a long time ago and I remember Set Display-Reported Refresh Rate working before.

**Comment by twinaphex** [comment] 2018-07-11 08:18
@bearoso Can you reproduce this?

**Comment by bearoso** [comment] 2018-07-11 21:01
Yeah. Something's not right with the type structure copies.

**Comment by twinaphex** [comment] 2018-07-11 21:30
Can you push a PR for this?

**Comment by bearoso** [comment] 2018-07-11 21:45
Added PR: #6973. It works for me, at least.

**Comment by BParks21** [comment] 2018-07-11 22:00
Will this be in the nightly so i can test it?

**Comment by rzumer** [comment] 2018-08-30 16:43
Seems fixed in 1.7.4.

**Closed** 2018-08-31 06:25 UTC
Labels: bug: major
