### ISSUE TITLE
Hotkey "Next Overlay" disappeared from Hotkey configuration menu (Settings/input/Hotkeys)

### ISSUE THREAD

**Issue by JoseFC3000** [libretro/RetroArch#15296] opened 2023-05-18 00:47 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hotkey "Next Overlay" disappeared from Hotkey configuration menu (Settings/input/Hotkeys)

### Expected behavior

Next Overlay hotkey mapping expected

### Actual behavior

Not appearing

### Steps to reproduce the bug

1. Go to Retroarch Menu
2. Settings/input/Hotkeys

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15.0

### Environment information

- OS: Retropie on Rasberry
- Compiler:

**Comment by JoseFC3000** [comment] 2023-05-18 12:49
I was using this hotkey in previos versions. Is there some way to remap this function out from the hotkey list? How can I swap between overlay and no-overlay while I'm playing?
Thank you.

**Comment by sonninnos** [comment] 2023-05-18 13:38
Not currently because the hotkey is not being read. Some overlays still do use the same function for toggling between d-pad and analog stick modes, so "next" shouldn't be doing "no-overlay" in any case or ever. Also hotkey binds aren't even read from input overlays.

**Comment by JoseFC3000** [comment] 2023-05-18 14:08
Hi Sonninnos, Im not sure to understnd your explanation. Is there some way to alternate between different overlays in-game without entering in Retroarch menu?
Thank you

**Comment by sonninnos** [comment] 2023-05-18 14:35
According to the code I don't think that has ever been possible. "Next" is doing next index inside the current overlay.

**Comment by JoseFC3000** [comment] 2023-05-18 15:07
Hi Sonninnos. I fixed the issue. I had the code wrong into the overlay.cfg. Now works perfectly. Sorry and thanks :)

**Comment by sonninnos** [comment] 2023-05-18 18:52
Nice, looks like closing time then.

**Comment by f00man** [comment] 2023-07-07 21:14
@sonninnos I am having an issue where I use the hotkey (select + down) as the bind to cycle overlay indexes. I have 4 indexes. When I use the keyboard (select retropad button + down retropad button) it cycles with no problem. The issue is that when I use a gamepad like 8bitdo controllers that the bind doesn't work. All others do (save state, exit game, etc). 

This is the config I'm using in retroarch.cfg:

```
# Toggles to next overlay. Wraps around.
input_overlay_next = "down"
```

**Comment by sonninnos** [comment] 2023-07-07 22:57
Controllers use `*_btn` and `*_axis`, and that one without a suffix is for keyboard keys. The actual functionality hasn't been changed, so no idea what else could it be.

**Comment by michaelbilberry** [comment] 2023-07-08 15:00
Awesome! I will try that. Is it possible to use retropad here so that both keyboard and gamepad work on the bind?

**Comment by sonninnos** [comment] 2023-07-08 16:03
That is how all input binds work.

**Comment by f00man** [comment] 2023-07-08 22:06
Thanks for the response. Just to confirm; you would expect the following to work for input_overlay_next to cycle overlay indexes using a retropad mappings for both keyboard and gamepads?

```
# Toggles to next overlay. Wraps around.
input_overlay_next = "down"
input_overlay_next_btn = "down"
```

It seems to work well with the keyboard but not the gamepad. I was hoping to use retropad so that the hotkey works regardless of which gamepad I use (360, 8bitdo, buffalo).

I also tried commenting out the keyboard one entirely to see if there was conflict but no luck.

**Comment by sonninnos** [comment] 2023-07-08 22:28
"down" is not a valid option for `_btn` or `_axis`. Just look at the others for examples.

**Closed** 2024-04-04 13:37 UTC
