### ISSUE TITLE
Favorites menu: mess in entries after navigating (up/down)

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8407] opened 2019-03-04 19:12 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Favorites menu: mess in entries after navigating (up/down)

### Expected behavior

Entry content should not mix up in screen.

### Actual behavior

![screenshot - 04_03](https://user-images.githubusercontent.com/11790863/53756609-907df300-3eca-11e9-99ec-203c0cf58af9.png)

### Steps to reproduce the bug

content_favorites.lpl

```
{
  "version": "1.0",
  "items": [
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Famicom Disk System\\Ginga Denshou - Galaxy Odyssey (Japan)\\Ginga Denshou - Galaxy Odyssey (Japan).fds",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Valkyrie no Bouken - Toki no Kagi Densetsu (Japan)\\Valkyrie_s_Adventure-Legend_of_the_Time_Key (Japan).nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\GoodPCE v1.09a\\Tower of Druaga, The - Druaga no Tou\\Druaga no Tou (Japan) [En by Procyon Lotor v1.1].pce",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\mednafen_supergrafx_libretro.dll",
      "core_name": "Mednafen SuperGrafx",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Zelda II - The Adventure of Link (USA).zip#Zelda II - The Adventure of Link (USA).nes",
      "label": "Zelda II - The Adventure of Link (USA)",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Ganbare Goemon! - Karakuri Douchuu (Japan)\\Ganbare Goemon! - Karakuri Douchuu (Japan).nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Legend of Zelda, The (USA).zip#Legend of Zelda, The (USA).nes",
      "label": "Legend of Zelda, The (USA)",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Dragon Ball - Daimaou Fukkatsu (Japan)\\Dragon Ball - Revival of the Dark Lord.nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Tombs & Treasure (USA).zip#Tombs & Treasure (USA).nes",
      "label": "Tombs & Treasure (USA)",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\MSX Collection\\MSX\\Various\\[ROM]\\Knightmare III - Shalom (1987)(Konami)(ja)[RC-754]\\Knightmare III - Shalom (English) Beta 4.rom",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fmsx_libretro.dll",
      "core_name": "fMSX",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Famicom Disk System\\Cleopatra no Mahou (Japan) [b]\\The Cursed Treasure of Cleopatra.fds",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\[NES] - GoodNES V3.23b\\NESMerge\\Kaijuu Monogatari\\Kaijuu Monogatari (J) [T+Eng1.0b2_KingMike][a1].nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Last Armageddon (Japan)\\Last Armageddon [T-Eng_v1.1_Chably].nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Gegege no Kitarou 2 - Youkai Gundan no Chousen (Japan)\\Ge Ge Ge no Kitarou 2 (J) [Patch1.2 aishsha+Djinn&D.Augusta (27.03.2010)].nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Momotarou Densetsu (Japan)\\momo-patched.nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Light of Indora - Indora no Hikari (J-Eng)\\Light of Indora - Indora no Hikari (J-Eng).nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Super Nintendo Entertainment System\\Laplace no Ma (Japan) [En by Aeon Genesis v0.95B] (~Laplace's Demon).sfc",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\snes9x_libretro.dll",
      "core_name": "Snes9x",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Nintendo Entertainment System\\Heracles no Eikou - Toujin Makyou Den (Japan)\\The Glory of Heracles - Labors of the Divine Hero.nes",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "core_name": "FCEUmm",
      "crc32": "",
      "db_name": ""
    },
    {
      "path": "C:\\Users\\ofry\\Downloads\\Sega - Master System - Mark III\\Miracle Warriors - Seal of the Dark Lord (USA, Europe).zip#Miracle Warriors - Seal of the Dark Lord (USA, Europe).sms",
      "label": "",
      "core_path": "C:\\retroarch\\cores\\picodrive_libretro.dll",
      "core_name": "PicoDrive",
      "crc32": "",
      "db_name": ""
    }
  ]
}
```

content_runtime.lpl

```
{
  "version": "1.0",
  "items": [
    {
      "path": "C:\\Users\\ofry\\Downloads\\Nintendo - Famicom Disk System\\Ginga Denshou - Galaxy Odyssey (Japan)\\Ginga Denshou - Galaxy Odyssey (Japan).fds",
      "core_path": "C:\\retroarch\\cores\\fceumm_libretro.dll",
      "runtime_hours": 3,
      "runtime_minutes": 6,
      "runtime_seconds": 41
    }
  ]
}
```

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 84d6f6231d

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: [In case you are running local builds]

**Comment by retro-wertz** [comment] 2019-03-04 22:03
huh? how/what mess? and how to reproduce? you just posted lpl. do you mean the sorting of titles?

**Comment by ofry** [comment] 2019-03-04 22:32
@retro-wertz Not only sorting issue.

Label of selected item is "Dragon Ball - Daimaou Fukkatsu (Japan)\\Dragon Ball - Revival of the Dark Lord". But if I launch this title, will launched "Ginga Denshou - Galaxy Odyssey (Japan)" instead.

**Comment by orbea** [comment] 2019-03-04 22:45
Same issue as `5` here.

https://github.com/libretro/RetroArch/issues/8389#issuecomment-468926515

The problem is that xmb only sorts the favorite playlist after navigating inside of it. If you remove your favorites playlist and recreate it the problem will be hidden when the playlist entries are added in alphabetical order.

**Comment by orbea** [comment] 2019-03-05 22:49
Fixed in https://github.com/libretro/RetroArch/pull/8414.

**Closed by orbea** 2019-03-05 22:49 UTC
Labels: bug: ui
