### ISSUE TITLE
RPI/RGUI search box cannot be closed

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#1432] opened 2015-02-21 08:12 UTC
Since last week i have a strange problem with RGUI. If i open RGUI and press X on my joypad a search box opens. I cannot close the box with any keyboard or joypad button. It is only possible to cycle power.

**Comment by gizmo98** [comment] 2015-02-21 08:13
Could be the same problem as https://github.com/libretro/RetroArch/issues/1428.

**Comment by fr500** [comment] 2015-02-21 08:16
yes duplicate of https://github.com/libretro/RetroArch/issues/1428, let's keep one issue per problem

**Closed by fr500** 2015-02-21 08:16 UTC

**Comment by gizmo98** [comment] 2015-02-21 08:20
Sorry. I have seen it to late.
