### ISSUE TITLE
mGBA netplay problums

### ISSUE THREAD

**Issue by Littlemac123** [libretro/RetroArch#7262] opened 2018-09-20 16:21 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

In Mario Golf: Advance Tour, using mGBA 0.7 WIP 4d1d9d3, retroarch 1.7.4, Windows 10, 64 bit, it seems that it crashes in game at random every time I try to play it on netplay with friends or my self for testing witch makes me think it might be a save state bug or something
https://youtu.be/FbyI_-VX1oE?t=1m40s
here is a video with it happening at the right time and a save file in the video so you can do it with out the menus on how to play for you

all the steps are in the short 2 min video really but I shall say it anyways
start the game, play it with netplay not offline, and have some one join, and wait for it to crash playing the game. it will happen more when the game starts to have a bad internet and needs to save state more often.
all so in mario and luigi super star saga netplay I remember on 1.7.1 but can't remember the mGBA build the sprites were flickering A LOT but never crashed but it really flickered on lagy internet as well

and before anyone says mGBA can't netplay , that is not true it can do pass the gameboy multiplayer and you need to turn on >Advance settings in >user interface and then in >Network turn on request devise user 1 for all players

btw a little request: can you add a setting in the core so all controllers can control player 1 in the core settings please that would make meany things easier and allow offline mode to allow more then 1 controller instead of having to pass it and there a are meany other gba games with pass the gameboy like 3 Game Pack! - The Game of Life + Payday + Yahtzee, and 3 Game Pack! - Candy Land + Chutes and Ladders + Original Memory Game, and more and it's a lot less work for netplay.

**Comment by hizzlekizzle** [comment] 2018-09-20 17:31
I think this is actually an okay spot for now. The issue is probably ultimately going to need to be fixed in the core, but if it's not happening with regular savestate actions, it's probably worth looking into both frontend and core activities.

**Comment by fr500** [comment] 2018-10-05 03:10
Core issue, please file into the correct repository

**Comment by RobLoach** [comment] 2018-10-06 03:57
Thanks for testing. Feel free to make the issue in the core queue if it persists.

**Closed by RobLoach** 2018-10-06 03:57 UTC
