### ISSUE TITLE
Auto Save game doesn't happen if exiting Retroarch via hotkey (Windows 10)

### ISSUE THREAD

**Issue by salyangel** [libretro/RetroArch#4820] opened 2017-04-12 07:01 UTC
Hello I try different version of retroarch 1.3.6
1.4.1 and 1.5

My hot key to exit 'escape' won't activate my auto save my game.

I have change my button to "q" it not resolve my problem.

I try with different PC with Windows 10.

**Comment by damopinn** [comment] 2017-04-12 16:23
I have the same issue on debian 9. 
seems to be related to another bug which was fixed, where the first time it saved correctly but next time it just loaded the last save. at least that's what happen for me. using quit from the menu it works correctly.

**Comment by salyangel** [comment] 2017-04-13 11:50
It's from every cores, the last MAME can't autosave... and I don't want to go back with MAME emulator I want to stay with Retroarch only.

In windows 7 it's work one time and second the autosave by "hotkey" won't work too.

**Comment by pantra64** [comment] 2017-04-13 16:56
duplicate of bug #3829

**Comment by salyangel** [comment] 2017-04-13 17:07
This bug is for windows 10 and it's not resolve on stable version... I hope to have a solution because I don't find anything.

**Comment by pantra64** [comment] 2017-04-13 17:11
I've had this problem for a long time, doesn't seem to matter which version of Windows. It's the main reason I'm still on nightly 2016-09-03 for my everyday RetroArch-needs.

**Comment by salyangel** [comment] 2017-04-13 17:15
Yep and I need this fix for my bartop...I always use my hoykey nothing else.

Thank for sharing your link.

**Comment by bparker06** [comment] 2017-04-16 00:50
It seems to work for me if I also have auto load state turned on, but not without it.

**Comment by salyangel** [comment] 2017-04-24 09:56
I have enable auto save and auto load and in the last mame core nothing load because nothing have save before....

**Comment by salyangel** [comment] 2017-05-04 08:49
Anyone have testing on le 1.5.1 version?

**Comment by salyangel** [comment] 2017-05-05 12:49
I want to add an information I use Windows 10 in French langage maybe I have to test it in english.

**Comment by salyangel** [comment] 2017-05-05 22:27
I have testing on windows 7 it's the same problem... 1.5.0 with nestopia...

**Comment by fr500** [comment] 2017-05-09 05:35
It's fixed now
@twinaphex

**Comment by damopinn** [comment] 2017-05-09 08:54
Great thanks!!
Did it have something to do with the undo load/save state feature?

**Comment by salyangel** [comment] 2017-05-09 10:00
hey it's on the 1.5.1 version?

**Comment by damopinn** [comment] 2017-05-09 11:49
You should download the nightly tomorrow. It will be updated by then.

**Comment by damopinn** [comment] 2017-05-09 13:22
Hi, I've been testing and it doesn't seem to work with pce engine cd. 
Other consoles I tried work fine.

**Comment by fr500** [comment] 2017-05-09 14:02
hmmm it only seems to work when no autosave exists.
If an autosave exists it doesn't seem to work

**Comment by pantra64** [comment] 2017-05-09 14:10
sounds like the behavior that nadenislamarre observed here, where the file IS saved each time, but not with the right content: https://github.com/libretro/RetroArch/issues/3829#issuecomment-271138490

**Comment by twinaphex** [comment] 2017-05-09 14:13
' enable auto save state on exit, load something, exit, launch again, load from the auto save slot, that should work, exit again, load again, load the state, it's still in the old save state'

**Comment by damopinn** [comment] 2017-05-09 18:09
I started again i deleted all the saves and load a game and exit the file .state.auto is created 
I look at the time stamp. load the game again play a little exit retroarch with esc key.
look at time stamp it is the same as before the file hasn't been updated.
this happened with beetle pce fast and beetle sgx cores.
Nestopia UE core works correctly. I can test more cores if you are interested.

**Comment by damopinn** [comment] 2017-05-09 19:10
![screenshot_20170509_210915](https://cloud.githubusercontent.com/assets/26623617/25868041/d12092c6-34fb-11e7-8ed1-315d958ba5c2.png)
Is file exists saving to backup buffer a clue to whats happening?

**Comment by fr500** [comment] 2017-05-10 03:03
There is no reason for it to work on one core and fail on another though

**Comment by fr500** [comment] 2017-05-10 03:56
Fixed https://github.com/libretro/RetroArch/pull/4896

**Closed** 2017-05-10 03:59 UTC

**Comment by salyangel** [comment] 2017-05-15 10:06
fr500 je parle francais si besoin... :) merci pour ce fix.

With the last Mame core it's not working just the first auto save state working.

**Comment by fr500** [comment] 2017-05-15 14:21
MAME doesn't have save state support

**Comment by salyangel** [comment] 2017-05-15 17:39
wrong, I have an option on the core to enable the option.

See one retroarch-core-options.cfg

mame_read_config = "enabled"
mame_write_config = "enabled"
mame_saves = "game"
mame_auto_save = "enabled"
mame_mouse_enable = "enabled"
mame_throttle = "disabled"
mame_cheats_enable = "disabled"
mame_alternate_renderer = "disabled"
mame_softlists_enable = "enabled"
mame_softlists_auto_media = "enabled"
mame_media_type = "rom"
mame_boot_to_bios = "disabled"
mame_boot_to_osd = "disabled"
mame_boot_from_cli = "disabled"
mame_altres = "640x480"

**Comment by fr500** [comment] 2017-05-15 17:47
Wrong
Those are not librero savestates.

Those are directly from the core

**Comment by salyangel** [comment] 2017-05-22 13:00
Ok I open a new ticket for this thanks!
