### ISSUE TITLE
RFE: add a way to save a filter into a new playlist

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#12831] opened 2021-08-19 20:21 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Currently we can filter all games with 'explore' and even use multiple filters (though note, negative filters are missing), but we can't save the games found into a new named playlist. I think this is valuable functionality if someone is looking for common games.

### Expected behavior

A new playlist with all the games found is created with a user chosen name. Note that this could be further complicated - i'm not sure it's worth it for the probable pain in C - by making a 'dynamic playlist type that always search all available games for the metadata chosen for the case where the user later added or removed games that would match.

### Actual behavior

Feature does not exist.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by i30817** [comment] 2021-08-20 02:08
Now that i think about this, it's possible this can't be done with normal pIaylists if they associate to cores or platforms too much to get metadata.

**Comment by LibretroAdmin** [comment] 2022-09-01 19:51
I have suggested something similar to @schellingb. I think we're going to see something cool soon.

**Comment by rbreaves** [comment] 2022-10-17 03:10
duplicate of https://github.com/libretro/RetroArch/issues/14178, one of these needs closing.

**Closed** 2022-10-17 07:38 UTC
Labels: feature request, databases, database: explore
