### ISSUE TITLE
[OG Xbox] Crashes, freezes and lost controller input (FIXED)

### ISSUE THREAD

**Issue by tabajara01** [libretro/RetroArch#8757] opened 2019-05-11 14:41 UTC
Here is a fix for the issue  #6323

I've been facing the same problems with the emulator crash/ losing-input on original xbox after load more than 3 games or close the content more than twice. I figure out that the missing .info files for the cores was the problem. So, all you need is make sure that the .info files are included for each core in the info folder or in the same folder of the .xbe, also, make sure to rename the info file as the same name of the core. cheers

Btw, Amazing work twinaphex, and like i said above, your port to the original xbox is working very well, since the reason of the crashes and losing input was the missing info files for the cores. I'm hope you can still working in the xbox port. Sorry for the bad english. Cheers

**Comment by orbea** [comment] 2019-05-11 15:19
I would suggest posting comments in the related issue instead of making a new one. I am going to close this as a duplicate of issue https://github.com/libretro/RetroArch/issues/6323, but thanks for the information!

**Closed by orbea** 2019-05-11 15:19 UTC
