### ISSUE TITLE
Horizontal Screen Tearing

### ISSUE THREAD

**Issue by Steveice10** [libretro/RetroArch#3193] opened 2016-07-06 04:20 UTC
Occasionally, the 3DS nightly builds will have noticeable screen tearing, particularly visible during fade-in/out transitions in games. When this happens, the screen is visibly desynchronized from left to right.

**Comment by fr500** [comment] 2016-07-17 03:04
Hopefully @aliaspider can take a look for 1.3.7
I have a 3DS but my brother updated it to 11.0 and I don't want to hardmod now.

**Comment by 44100hertz** [comment] 2016-08-06 16:50
Confirming this. It's a bug in all stables after 1.3.3, seems to be caused by some part of #2874 

On my o3ds It's always tearing, just not always noticable.

**Comment by aliaspider** [comment] 2016-09-28 18:30
fixed with dc16477c46ffdae0d89e966fbbec66ce9f8a0a49

**Closed by aliaspider** 2016-09-28 18:30 UTC
Labels: 3ds, major bug

**Comment by Jimmy-Z** [comment] 2016-09-29 08:58
nice!
