### ISSUE TITLE
[Feature Request] Apple tvOS Port of RetroArch

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#5519] opened 2017-10-07 19:16 UTC
I wanted to put forward a request for RetroArch to be ported to Apple tvOS. I know this was planned a while back, but development seems to have ceased as there have been no updates.

**Comment by aaronouthier** [comment] 2018-01-12 00:18
I would **love** to see this also!

**Comment by tonycoco** [comment] 2018-01-26 18:13
Any progress on this? Is there a branch I can help contribute to?

**Comment by hizzlekizzle** [comment] 2018-01-26 21:06
@tonycoco It would be the main RetroArch branch. If you know C and can test/deploy to tvOS devices, make a fork and go nuts.

**Comment by aaronouthier** [comment] 2018-01-26 22:46
I am happy to contribute when & where I am able. As I have said elsewhere, however, I stopped coding in the early 90's, and even then, it was under AppleSoft basic for the Apple II series, and a little under MS-DOS in languages like Pascal, and C. I had looked into making Windows programs back when 3.1 was still the most recent Windows version, but never pursued. I digress.

I haven't kept up with the changing environment as far as Programming, but I believe I still understand the concepts involved. Who knows, maybe I'll take the time to start again.

Notwithstanding the forgoing, it would help greatly to know some kind of status of the Apple TV porting efforts, before diving in. Is there an Xcode project file available somewhere? I'm guessing not, since it would likely have been published and included in the Github repo. Still, I wonder if there is an unofficial one that a dev somewhere hasn't finished, and thus hasn't included.

Sure any of us could just dive in, and feel our way in the proverbial dark, but I rather suspect it would be helpful to get some pointers as to where to start looking. I have both a MacBook Pro and an Apple TV 4th Generation for testing.

**Comment by hizzlekizzle** [comment] 2018-01-26 23:22
It looks like you may be able to mostly use the existing iOS code and just create a new target in XCode:
http://terntek.com/blog/blog/2015/11/26/porting-from-ios-to-tvos-apple-tv/

**Comment by tonycoco** [comment] 2018-01-29 18:33
@hizzlekizzle gonna give it a swing this coming weekend if I can get it up and building quickly

**Comment by twinaphex** [comment] 2018-10-17 16:46
I think @stuartcarnie expressed interest in taking the lead with this one.

**Comment by ScarAce1989** [comment] 2018-10-17 16:58
Yeah finally!

**Comment by ScarAce1989** [comment] 2018-10-17 21:06
Created a bounty and added the first 15 dollar. :)

**Comment by ScarAce1989** [comment] 2018-12-02 20:14
Any progress?

**Comment by yoshisuga** [comment] 2019-01-28 09:07
Making some progress! 

https://youtu.be/2mQlcxZQ-W4

**Comment by yoshisuga** [comment] 2019-02-01 20:32
iOS/tvOS install guide for RetroArch here:

https://docs.libretro.com/guides/install-ios/

**Comment by yoshisuga** [comment] 2019-04-01 03:34
Can we close this so I can get the bounty?😄

**Comment by orbea** [comment] 2019-04-02 15:56
@yoshisuga I can't test this, has anyone else confirmed this if this issue is resolved yet?

**Comment by aaronouthier** [comment] 2019-04-02 19:46
I have my trusty MacBook Pro running Mojave and my Apple TV 4th Gen.
I will be testing this shortly. I had to reload my MacOS and am re-setting everything up. Trying to download Xcode now. At 2.8 of 6.08 GB.

**Comment by aaronouthier** [comment] 2019-04-02 21:55
It seems to work fine for me on the latest Xcode.
I should mention: When I open the project, it prompts me to automatically apply some recommended actions. I canceled this, and left things the way they were. Perhaps this is the issue some are having?

Now if you'll excuse me for a moment, I've gotta score to settle with the DragonLord.
I love Dragon Warrior for NES!

**Comment by orbea** [comment] 2019-04-10 13:27
Thanks for testing, given the lack of other replies I'll assume this is fixed. Please anyone make new issues for any followup, thanks!

**Closed by orbea** 2019-04-10 13:27 UTC
Labels: platform: tvos

**Comment by xdccrlz** [comment] 2019-06-05 02:40
Apple tvOS 13 need RetroArch fix. Failed to open libretro core.

**Comment by orbea** [comment] 2019-06-05 04:14
@xdccrlz Please make a new issue and fill out the issue template.
