### ISSUE TITLE
Rom scanner is acting weird

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#5634] opened 2017-11-01 02:38 UTC
From the issue tracker of Lakka: https://github.com/libretro/Lakka-LibreELEC/issues/267

> 
> Just checked on the latest github version on XU4.
> 
> Let's say I have 1500 roms to scan. I point to the directory, and then scan in progress values will look like this:
> 
> 1/1500
> 2/1501
> 3/1502
> 
> After some time the right number will eventually stop and the left number might catch up with it.
> Please note that sometimes the right number won't even match the actual number of roms in the specified folder.

**Comment by rootfather** [comment] 2017-11-01 09:00
I can confirm that. Happened for me too while scanning a zipped rom set on windows.

**Comment by orbea** [comment] 2017-11-01 14:30
@bparker Maybe you can take a look at this? :)

**Comment by retro-wertz** [comment] 2017-11-01 15:04
this behavior started from this commit https://github.com/libretro/RetroArch/commit/fb8fe84684b72111f833feae720a7c98c309e906

counter goes up when scanning archives that does not have crc database(non fba/mame)

**Comment by bparker06** [comment] 2017-11-01 15:49
Since I didn't write those changes, I'm probably not the best to answer this, but my guess is that his logic of "scan zip itself first if core supports, then if it doesn't match, all the files within" is probably what causes the total to go up, because it's adding to the list at runtime based on whether archives match the database or not.

I also don't think his changes exactly kept all the previous behavior working the same and it also seems to slow down the scanning as well, particularly for cores that DO support archives but DON'T have individual archive contents in the database. I could be wrong, but that is just what it appears like to me.

**Comment by orbea** [comment] 2017-11-01 21:35
Thanks for your input.

@aarononeal Can you look at this?

**Comment by aarononeal** [comment] 2017-11-01 22:26
This is by design, it’s just a change in how progress is reported.

The number has never matched the number of files if those files were zips and the core database doesn’t support zips. It now accurately represents what it knows of current state and updates as it processes. Previous design always reported double the number of files because it added the zip plus any contents of the zip before it ever did a CRC scan. That was also inaccurate in some cases and you would see the first half count up really quickly and then the second half go slow (or vice versa).

The reason you might think it appears slower is because you’re not seeing those no-ops count up quickly. I measured total time from previous algorithm and it was significantly less.

**Comment by aarononeal** [comment] 2017-11-01 22:29
Also, you can see my analysis in #5459 on how scanning can further be improved.

**Comment by SpaceAgeHero** [comment] 2018-01-03 12:04
Thanks for the info?
How can I check if core database supports zips and is there anything I can do about it?
I've scanned my PSP directory with 7zipped items and nothing was added to library ...

**Comment by aarononeal** [comment] 2018-01-05 01:03
1. Main Menu > Load Core > PSP
2. Main Menu > Information > Core Information > Supported extensions

--> elf, iso, cso, prx, prx, pbp

**Comment by RobLoach** [comment] 2018-10-05 04:38
Disc media won't scan when compressed. It needs to be unzipped.

**Comment by SpaceAgeHero** [comment] 2018-10-17 06:31
Not even PBP or CSO compressed discs? Is this planned?

**Comment by orbea** [comment] 2018-12-31 15:44
Looks like this is bisected and working as intended so I am going to close this in favor of issue https://github.com/libretro/RetroArch/issues/5459. If there are any improvements left that is where they should be discussed.

**Closed by orbea** 2018-12-31 15:44 UTC
