### ISSUE TITLE
Audio mute toggle doesn't retain its value across game reloads

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4399] opened 2017-01-12 10:49 UTC

**Comment by orbea** [comment] 2017-10-22 08:43
@twinaphex I tested the audio mute toggle across a game reloads, restarts, different RetroArch instances and it retained its value correctly. Can this issue be closed or can you still reproduce it?

**Comment by orbea** [comment] 2018-12-26 05:49
This still seems to be a fixed issue in the master so I am going to close it.

**Closed by orbea** 2018-12-26 05:49 UTC
Labels: bug: minor
