### ISSUE TITLE
Can't play audio on MacOS ventura

### ISSUE THREAD

**Issue by djhan** [libretro/RetroArch#14476] opened 2022-10-04 23:14 UTC
## Description

Retroarch(metal) can't play any audio, on development builds of macOS ventura.

### Expected behavior

Retroarch play audio in game.

### Actual behavior

Retroarch can't play any audio in game. I changed [setting>output>audio] from 'coareaudio 3' to 'coreaudio'. But it can't work too.

### Steps to reproduce the bug

1. Update to latest MacOS ventura (beta 9)
2. Install Retroarch(metal) nightly build
3. Run Retroarch
4. Play any game

### Bisect Results

This symptom was represented in previously openGL version of Retroarch, too.

### Version/Commit

- RetroArch: nightly build

### Environment information

- OS: MacOS ventura beta 9 / Mac Studio

**Comment by LibretroAdmin** [comment] 2022-10-05 00:11
Maybe the issue is with your beta version of MacOS.

I'm on MacOS Monterey (version 12.5.1), sound outputs just fine. MacBook Pro (13-inch, M1, 2020).

**Comment by djhan** [comment] 2022-10-05 04:54
> Maybe the issue is with your beta version of MacOS and it will be resolved once the final version releases.
> 
> I'm on MacOS Monterey (version 12.5.1), sound outputs just fine. MacBook Pro (13-inch, M1, 2020).

Yes. you're right. There's no problem on MacOS Monterey. It's only problem on MacOS ventura.

**Comment by LibretroAdmin** [comment] 2022-10-26 00:46
So audio seems to be fine in the final public version of Ventura. I think we can comfortably close this.

There does seem to be an issue with fullscreen toggling, but that's unrelated to this issue.

**Closed by LibretroAdmin** 2022-10-26 00:46 UTC
Labels: platform: osx, platform: macos ventura (beta)
