### ISSUE TITLE
[iOS/iPadOS/tvOS] Physical keyboards don't work

### ISSUE THREAD

**Issue by kmasaryk** [libretro/RetroArch#16562] opened 2024-05-19 21:55 UTC
## Description

Physical keyboards connected via BT don't work with RA at all.

### Expected behavior

Keyboards should work the same as with non-iOS versions of RA.

### Actual behavior

No real behavior since they simply don't work.

### Steps to reproduce the bug

Good test core is one of the VICE ones (Commodore). Load the core and then "Start without content." Connect a Bluetooth keyboard and try typing anything.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.18.0 / 90fb335271

### Environment information

- OS: iOS 17.4

**Comment by jamescastells** [comment] 2024-05-20 03:03
Apple Magic Keyboard doesn't work as well.

**Comment by tatobox** [comment] 2024-05-20 07:13
Traditional USB keyboard doesn't work as well.
iPad Pro 12.9 1st gen.
iPadOS 16.7.7

**Comment by andahme** [comment] 2024-05-20 16:18
Tried Apple Magic Keyboard on Apple TV, does not work.

**Comment by warmenhoven** [comment] 2024-05-21 14:47
The keyboard handling code is using some private apis and ends up getting removed from the App Store builds. I'm going to need to rewrite it and will plan to include it in the next build.

**Comment by vadershade** [comment] 2024-05-21 22:46
awesome! got some c64 programs to type in. thanks for your hard work.

**Comment by warmenhoven** [comment] 2024-05-22 14:03
Fixed by https://github.com/libretro/RetroArch/pull/16580.

**Comment by jamescastells** [comment] 2024-05-25 14:55
Today, 1.18.3 was released on the App Store which fixes this problem. I had to go to Configuration->Reset to Defaults and re-open RetroArch for the iPad keyboard to kick in, though.

**Comment by HowlinAlan** [comment] 2024-05-25 16:57
Getting nowhere with this. Updated app, reset to defaults. Using Commodore cores, some keys work, most don’t. Deleted and re-installed, no change

**Comment by jamescastells** [comment] 2024-05-25 17:33
Another user posted that some keys were detected on a Commodore core, but not all, but they apparently deleted their post. Anyway, if someone is having issues with it:

- Open the Commodore (or DOS) core until you get a prompt where you can type.
- Open the Quick menu->Controls->Port 1 Controls->Device Type and select “None” or “Disabled”.
- If you return to Commodore/DOS, you’ll see that more keys will be detected. To avoid doing this configuration every time, go to the Quick Menu->Controls->Manage Remap Files->Save Core Remap File.
- If your hot keys are interfering with your keyboard (such as pressing “P” pauses the core instead of typing the letter P), assign a Hotkey. Go to the main menu->Settings->Input->Hotkeys->Hotkeys enable. Assign a key to be your hotkey enable (for example, I set the command key). That way, to pause a core, instead of just pressing P, I have to press Command+P.

With these steps all the keys will be detected in those cores where you need to type.

**Comment by HowlinAlan** [comment] 2024-05-25 17:52
> Another user posted that some keys of the keyboard were detected on a Commodore core, but not all; but they apparently deleted their post. Anyway, if someone is having issues with this:
> 

Sorry, that was me. I stumbled through the settings and managed to get it worked out before your reply. Working great now. Thank you!

**Comment by vadershade** [comment] 2024-05-25 19:17
I don't know.. I reset the config to defaults, start a c64 core as soon as I type "L" the fast forward symbols ">>" appear in the top right corner and I cannot type "L" for anything...

**Comment by HowlinAlan** [comment] 2024-05-25 19:21
For me, the solution was changing “Auto-enable Game Focus” to “Detect” in the input settings.

**Comment by jamescastells** [comment] 2024-05-25 21:24
> I don't know.. I reset the config to defaults, start a c64 core as soon as I type "L" the fast forward symbols ">>" appear in the top right corner and I cannot type "L" for anything...

Set a Hotkey enable, like I specified in my post. Once that’s setup L will be displayed as text.

**Comment by kmasaryk** [comment] 2024-05-25 22:53
> For me, the solution was changing “Auto-enable Game Focus” to “Detect” in the input settings.

That's what I've been using too. I believe cores like Commodore and DOS are what the setting was intended for. By default, you can also toggle the mode on/off with ScrLck. Only downside to this mode is that there doesn't seem to be any way to enable hot keys so you'll have to use the touchscreen to interact with RA.

**Comment by jamescastells** [comment] 2024-05-26 03:08
The solution I provided is better, I think, because it lets me use my full keyboard AND the hot keys.

**Comment by fcprindle** [comment] 2024-05-26 11:18
Could someone PLEASE tell me how to get the new version 1.18.3 on my Apple TV? I've been trying since yesterday morning when it became available for the iPad but the Apple TV App Store still only offers 1.18.2. I've tried uninstalling and re-installing RetroArch, as well as rebooting the Apple TV, all to no avail. I didn't have this trouble when going from 1.18.1 to 1.18.2. Thanks in advance.

**Comment by warmenhoven** [comment] 2024-05-26 13:25
It has not yet been approved for AppleTV but I expect that to happen soon.

**Comment by fcprindle** [comment] 2024-05-26 14:16
Thanks for the info! I was led astray by Apple's 1.18.3 web page ([https://apps.apple.com/ca/app/retroarch/id6499539433 ](url) which says for Apple TV at the top. I'll keep an eye out.

**Comment by fcprindle** [comment] 2024-05-27 13:21
Version 1.18.3 finally downloaded to Apple TV this morning. But :( no joy. Bluetooth keyboard is connected and can be used to navigate Apple TV menus and enter text where necessary, but as soon as I run RetroArch, no keys on the keyboard work any more - can't even move up/down menu items using up/down arrows. Another clue is that the mouse cursor does not show (whereas it does on iPad with same keyboard). Somehow, RetroArch is simply not seeing it.

**Comment by warmenhoven** [comment] 2024-05-27 13:44
If the menus and on-screen keyboards respond to the keys but the games don't then it sounds like a mapping problem and should be able to be solved via config rather than a code change. However that's all the information I can give you off-hand at the moment. I would need to research the config settings to see where it might be going awry.

**Comment by fcprindle** [comment] 2024-05-27 14:08
Just to clarify... only the **Apple TV** menus and **Apple TV** on-screen keyboards respond to the keys. Once I launch RetroArch, **its** menus respond to the Apple TV remote but not the keyboard. If I go to a RetroArch setting that puts up an on-screen keyboard (for example, Import Content/Manual Scan/Custom System Name), the keys have no effect there either.

**Comment by warmenhoven** [comment] 2024-05-27 15:37
Ah, sorry, misunderstood, thanks for the clarification.

**Comment by fcprindle** [comment] 2024-05-27 16:35
Reset configuration, swipe away app, launch app: no effect - kbd still doesn't work.
Delete app, re-download app, launch app: no effect - kbd still doesn't work.

FWIW, the BT keyboard I'm using is an iPazzPort KP-810-21BT with built-in touchpad.

**Comment by leandrinux** [comment] 2024-05-30 02:15
Unfortunately I'm using the latest version (1.18.3) in my Apple TV and I can't get my magic keyboard to work properly. I can't type in any core (tried amstrad, C64 and dosbox). Since perhaps is relevant I'd like to add that my Apple remote is broken so I am also using my TV remote to control the device.

**Comment by warmenhoven** [comment] 2024-05-30 16:27
@leandrinux are you in game focus mode?

**Comment by leandrinux** [comment] 2024-05-30 21:57
@warmenhoven I tried with that option off and also in detect mode. When using detect mode not only it doesn't work, I can't quit properly the app and I have to force close it.

I just tried with another Magic Keyboard (the newer version with built in batteries) and I had the same results.

I've noticed that using the apple remote (which I fixed yesterday) causes some letters to appear on screen in the C64 emulator, like s and x

**Comment by warmenhoven** [comment] 2024-05-30 21:59
Yeah that's an artifact of handling the Siri Remote like a keyboard instead of a game controller. I should clean that up.

**Comment by fcprindle** [comment] 2024-05-30 22:09
I can corroborate every symptom that @leandrinux is experiencing, but in my case using an IPazzPort keyboard with my Apple TV 4K.

**Comment by warmenhoven** [comment] 2024-05-30 22:14
Thanks. I'm currently preparing the 1.19.0 App Store submission but will be keep this on my list. There are a few input problems including this and the iPad Magic Keyboard touchpad that need to get cleaned up.

**Comment by fcprindle** [comment] 2024-05-31 13:36
Ok, so there is now a 1.19.0 for the Apple TV but not only does the keyboard not work (I didn't expect it to), but now the Apple TV remote doesn't work (in any usable fashion) either. Sometimes, you can navigate into a sub-menu, select stuff there, but the MENU button on the remote doesn't go back to the previous menu as it previously did, so you're stuck there. Also, in the C64 core, the up/down/left/right on the remote no longer work!

**Comment by warmenhoven** [comment] 2024-05-31 13:39
Hm, very odd, it was working for me when I tested it. I will check again.

**Comment by warmenhoven** [comment] 2024-05-31 14:30
@fcprindle can you send me a log? Please include level 0,debug logs.

**Comment by fcprindle** [comment] 2024-05-31 15:01
I look in the "logs" directory and it's empty. Need to turn on logging somehow?

**Comment by warmenhoven** [comment] 2024-05-31 15:02
Sorry, yes, in settings under logging. Please turn everything on and all levels to 0. Thanks!

**Comment by warmenhoven** [comment] 2024-05-31 15:47
Ok, I just tested on my atv4kgen1 and my Siri Remote is working fine. The log will be immensely helpful in determining what's going wrong. Thanks.

**Comment by fcprindle** [comment] 2024-05-31 19:03
4 log files attachedFrank
    On Friday, May 31, 2024 at 11:47:50 AM EDT, Eric Warmenhoven ***@***.***> wrote:  
 
 


Ok, I just tested on my atv4kgen1 and my Siri Remote is working fine. The log will be immensely helpful in determining what's going wrong. Thanks.

**Comment by fcprindle** [comment] 2024-05-31 19:04
One more try - 4 log files attached.
Frank
[retroarch.log](https://github.com/user-attachments/files/15517755/retroarch.log)
[retroarch__2024_05_31__14_51_06.log](https://github.com/user-attachments/files/15517756/retroarch__2024_05_31__14_51_06.log)
[retroarch__2024_05_31__14_52_37.log](https://github.com/user-attachments/files/15517757/retroarch__2024_05_31__14_52_37.log)
[retroarch__2024_05_31__14_53_13.log](https://github.com/user-attachments/files/15517758/retroarch__2024_05_31__14_53_13.log)

**Comment by leandrinux** [comment] 2024-05-31 19:11
what you describe @fcprindle happened to me after enabling the game focus mode. I had to revert it back to off to allow the back button on the remote to work

**Comment by warmenhoven** [comment] 2024-05-31 19:27
Ok, I see the menu button issue and why it was working for me. Thanks very much. I'm putting together a fix now.

**Comment by jamescastells** [comment] 2024-06-05 04:08
1.90.1 was released and it solved the back button on the Apple TV remote. No idea about external keyboards, though.

**Comment by warmenhoven** [comment] 2024-06-05 04:19
I haven't addressed the external keyboards issue yet (nor physical mice, nor a number of other input bugs...).

These things are all on my list, which unfortunately is growing faster than I can reasonably work through, and I'm the only one working on macOS/iOS/tvOS right now.

**Comment by mdrejhon** [comment] 2024-06-10 20:16
> With these steps all the keys will be detected in those cores where you need to type.

Thank you so much -- I have some old programs from 1980s I wrote that I wanted to be able to run on the Vice x64 core.   I've 'slightly' improved your instructions for RetroArch newbies unfamiliar with the interface, since some Lemon64 forum members were using Vice x64 directly and not everyone is familiar with RetroArch, so here goes:

> Install Version 1.18.3 or newer, and start the core needing keyboard
> -
> You have to disable Port 1 joystick interference with keyboard, as keyboard is emulating port 1 joystick.
> **Quick Menu Button (👾) -> Controls -> Port 1 Controls -> Device Type -> None**
> Or reassign to your favourite Bluetooth joypad.
> -
> Then save this by default for the core so I don't have to repeat the above step every time.
> **Quick Menu Button (👾) -> Controls -> Manage Remap Files -> Save Core Remap File**
> -
> Then have to put all hotkeys (e.g. pause P key) behind a modifier key.
> **Settings Button (⚙️) -> Input -> Hotkeys -> Hotkeys Enable -> Press modifier such as COMMAND (⌘)**
> Then next time you want to pause, you have to hit ⌘+P. Maybe reassign it to spacebar (⌘+Space)

**Closed** 2024-06-27 23:33 UTC

**Comment by mdrejhon** [comment] 2024-07-15 18:14
www.libretro.com shows 1.19.1 is the latest release for all platforms (including Windows) so I guess we have to hang tight a bit longer.

**Comment by fcprindle** [comment] 2025-01-25 16:16
So now that 1.20.0 is out, the bluetooth keyboard finally works (almost) in Retroarch running on an Apple TV 4K. By "almost", I mean the ESC is non-functional. It seems to be mapped to some Apple TV functionality that simulates the MENU button (go back one) but isn't usable either in the Retroarch GUI (where it cannot be assigned as a hotkey by pressing it during the hotkey set countdown) or in the emulated C64 (where it should function as the C64 RUN/STOP key).

The only time while running Retroarch that the ESC key does not appear dead is when the Retroarch menu item "Main Menu" is selected, in which case it simulates the Apple remote's MENU button (goes back one while leaving Retroarch running in the background).

I don't need it to be a hotkey (I've remapped QUIT/EXIT to lmeta-F2), but not having a RUN/STOP key on the C64 keyboard is somewhat annoying. I've temporarily assigned an unused controller button to serve as RUN/STOP which works but is a bit awkward to use for things like RUN/STOP-Restore or Shift-RUN/STOP.

Is it possible for you to make the ESC key usable in Retroarch on the Apple TV? If there is some setting that might accomplish this, I'd appreciate it if you let me know. If it requires a coding change on your end, I will gladly await a new version.

**Comment by warmenhoven** [comment] 2025-02-03 03:07
> Is it possible for you to make the ESC key usable in Retroarch on the Apple TV?

I've been looking at this. The problem is that it doesn't send a key press event with an Escape key code; it sends a UIPress event with a type of UIPressTypeMenu.

I've been looking at whether it's possible for me to tell the difference between when the Siri Remote sends it and when the keyboard sends it, and I don't think it is without using private APIs. Also I don't think it really matters if I can because the App Store guidelines say I'm supposed to treat the menu button this way.

So I don't think there's really much I can do here. Sory.
