### ISSUE TITLE
White XMB screen after return from GW core

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1910] opened 2015-07-06 05:08 UTC
I loaded a GW content (Donkey Kong (Nintendo, Multi Screen)), and when I return to xmb, I got this screen:

![retroarch - bug 7](https://cloud.githubusercontent.com/assets/5431285/8515975/7c8368f0-2383-11e5-8aed-41d6f477433f.png)

It's random, It happens only a few times.

Tested with 49e35a5

**Comment by sergiobenrocha2** [comment] 2015-07-08 05:56
@Kivutar

**Comment by sergiobenrocha2** [comment] 2015-07-09 02:22
It's happening all the time with GW core now.

**Comment by Kivutar** [comment] 2015-07-09 05:08
Looks like it has been fixed by a very recent commit. Can you try again? I can't reproduce anymore.

**Comment by sergiobenrocha2** [comment] 2015-07-09 05:21
Nope, it's there yet.

**Comment by Kivutar** [comment] 2015-07-10 06:38
I'm still not able to reproduce it. Can you give me more info about the settings that could make a difference?

**Comment by sergiobenrocha2** [comment] 2015-07-10 15:29
I can't reproduce in my core 2 duo T6600 machine :/
It uses Intel graphics onboard.

The other one (buggy) is a core i7 haswell with Nvidia 740M (+intel onboard, hybrid graphic, using bumblebee)

I only changed paths, and maybe Aspect Ratio Index to Core provided. And using pulse

**Comment by sergiobenrocha2** [comment] 2015-07-14 20:42
It's happening to mame cores too (0.155, 0.157, git master)

**Comment by Kivutar** [comment] 2015-07-14 22:15
I can't reproduce on my macbook with arch linux.

**Comment by sergiobenrocha2** [comment] 2015-08-18 02:59
Is it related?

![screenshot_2015-08-17-23-55-44](https://cloud.githubusercontent.com/assets/5431285/9321383/e9ede076-453b-11e5-95e7-dc5b2d5c7fab.png)

**Comment by sergiobenrocha2** [comment] 2015-08-18 03:07
It happened with gambatte too

![screenshot_2015-08-18-00-04-43](https://cloud.githubusercontent.com/assets/5431285/9321452/1723557a-453d-11e5-9e66-e9cf1a31247c.png)

**Comment by sergiobenrocha2** [comment] 2015-08-18 03:10
Tried snes9x next core, same thing, then I tried to load another game in the same core, and I got this:

![screenshot_2015-08-18-00-08-26](https://cloud.githubusercontent.com/assets/5431285/9321481/8d7cebbe-453d-11e5-940e-83270a7382d0.png)

**Comment by fr500** [comment] 2015-10-09 18:22
This is fixed, right? I haven't seen it popup again.
Reopen it otherwise

**Closed by fr500** 2015-10-09 18:22 UTC
