### ISSUE TITLE
Mouse input not passed correctly to the core

### ISSUE THREAD

**Issue by jstolarek** [libretro/RetroArch#10780] opened 2020-06-03 14:51 UTC
In games that use mouse, the initial mouse movement area is restricted. For example, consider this screenshot from Warcraft 2 menu running on DOSBox core:

![war2_2](https://user-images.githubusercontent.com/1597921/83647711-1c3e6d80-a5ad-11ea-834b-6c749d85eeae.jpg)

Notice how the mouse cursor is placed on "Show Credits" button - at this point it is impossible to move the cursor lower, which makes the "Exit Program" button unreachable. After moving the cursor around it unlocks at some point and can move on the whole area of the screen. Same happens to other games that use the mouse (Syndicate, Settlers 2). If I enable Game Focus the problem instantly disappears. It is instructive to enable and then immediately disable Game Focus mode - then you can see both the DOS game cursor and the OS cursor moving at the same time. It is then obvious that the restriction in the game cursor movement comes from the OS cursor reaching the lower border of the screen and not being able to move past it. This is some sort of scaling error. Doesn't happen with standalone DOSBox. Tested on Linux.

I originally reported this as a DOSBox-SVN core bug (https://github.com/libretro/dosbox-svn/issues/58) but the core authors claims this is a limitation of RA and other cores that use the mouse suffer from the same problem.

**Comment by bslenul** [comment] 2020-06-04 10:37
Pretty sure that's normal, you have to either use Game Focus mode like you mentioned, or use the "Grab Mouse Toggle" hotkey (F11 by default). I don't know the specifics but I guess it's because of a mismatch between your screen resolution and the core/game resolution?

**Comment by jstolarek** [comment] 2020-06-04 11:00
> Pretty sure that's normal

Not sure what you mean by "normal". It is what happens at the moment but I claim this definitely isn't what I would expect to happen. When you launch, say, DOSBox core, then RA hides the system mouse cursor and leaves you with emulated in-game mouse cursor only. (The two mouse cursors appear only when you go into and then ouit of Game Focus mode - another glitch.) I expect that RA would scale the cursor movement area to match the whole displayed screen area without the need to go into game focus mode. To me game focus mode is only a mean of disabling RA keyboard shortcuts and nothing else. If mouse cursor is not expected to work correctly without game focus mode then it shouldn't be displayed at all when Game Focus is off, though I think this would be a terrible design decision. Just do the right thing from the start!

**Comment by bslenul** [comment] 2020-06-04 11:24
Oh my bad, I'm used to play in windowed mode, that's probably why I thought it was normal, I'm dumb -_-

But yeah, just tried in fullscreen:

* On Windows: no issue, it automatically "grabs" the mouse and you can go to each corner with no issue.
* On my Linux VM however there's definitely something wrong: https://youtu.be/C-elv0VrM68

On the video I'm first stuck at the "Multi Player Game" menu, then no idea why but by doing some big movements I manage to "unlock" the cursor a bit more (now on the "Exit Game" menu), then more big moves and I'm \*almost\* able to reach the bottom of the screen... :x

**Comment by jstolarek** [comment] 2020-06-04 12:53
> On my Linux VM however there's definitely something wrong: https://youtu.be/C-elv0VrM68

Yes, this is exactly the problem! Here's a bit more insight into what's going on:

When a game launches the (invisible) system cursor is placed in the centre of the screen, but the (visible) in-game DOS cursor is not necessarily centred. In case of Warcraft 2 it is placed towards the upper-left corner on the game logo:

![w](https://user-images.githubusercontent.com/1597921/83758069-58cf9f00-a669-11ea-86aa-8aa183830b94.jpg)

the result is that if you now move the mouse cursor down the invisible OS system will reach the border sooner than the visible in-game cursor. This results in a perceived inability to move the cursor lower - because the system cursor can't be moved past the screen's bottom border.

Interestingly, the in-game cursor moves at a different speed than the system cursor. More specifically it moves faster than than the system screen - this is clearly visible when you enter and exit game focus mode so that both the system and in-game cursors become visible. (Then again, perhaps they move at the same speed in terms of pixels-per-second?) The result is that if you move the mouse cursor up and down several time the in-game cursor finally "overtakes" the system cursor and from now on it will always reach the screen border faster than the system cursor.

Also, when entering game focus mode, RA centres the in-game cursor, which shows RA has the ability to capture and modify that cursor. The question could RA centre the cursor at game startup? This isn't exactly a proper solution but it definitely masks the problem. @realnc, is there anything the DOSBox core can do about initial placement of mouse cursor or is that something on the RA side?

**Comment by i30817** [comment] 2020-08-03 23:01
This is one of the reasons i don't like use mouse cores. Anyway, if you have the unfortunate experience of using hardware with 'quirks' (bug) fixed by libinput, you get a even more 'interesting' experience if you try to run the emulator in KMS (kernel mode setting, what's used if you run retroarch in a tty).

In my case my portable touchpad has several quirks, and i can't right click or make the cursor not jump to another zone of the screen if i pull up the finger and place it somewhere else in scummvm in KMS, it functions like a absolute projection of the game resolution into the touchpad.

**Comment by i30817** [comment] 2020-08-24 09:05
this also happens on desmume on games that use the cursor. `Theresia...` for instance.

**Comment by masaklaw** [comment] 2020-10-14 19:53
Hello, I also reproduce this issue in a different core, see: https://github.com/libretro/libretro-uae/issues/321

It seems that it is a proble under Linux, when using the `x`, `sdl2`  and `linuxraw` input drivers.

The `udev` driver works correctly!

There are were other related issues that seems to have been caused by this problem, see e.g.: https://github.com/libretro/RetroArch/issues/7748.

**Comment by masaklaw** [comment] 2020-10-14 20:02
I also think that there were multiple, as of now closed, issues related to this problem, see e.g.: https://github.com/libretro/RetroArch/issues/3408, https://github.com/libretro/RetroArch/issues/7748.

**Comment by masaklaw** [comment] 2020-10-17 01:03
Update - the `udev` driver is also broken, just in a different way - as of RetroArch 1.8.5 - the mouse clicks do not always work.

The _emulated_ mouse cursor can be in a different position than the _real_ mouse cursor - this can be seen by toggling the grab mouse option. If the _real_ cursor is _off-screen_ - then mouse clicks *do not work* in the emulated cursor in the `udev` driver. If the _real_ cursor is at the _real_ screen boundary then you cannon move the mouse any further in the other drivers.

Grabbing the mouse seems to work for the `x` driver, but it cannot be done automatically.

**Comment by bslenul** [comment] 2020-10-18 15:24
I made a bit more testing, the problem seems to be because the mouse cursor when you launch the game is not at the same place as the ingame cursor, let me try to explain with a save state I made in Monkey Island 2 with PUAE core with the cursor more or less in the middle of the screen:

If I press "Run" when my mouse in the top-left corner:

![image](https://user-images.githubusercontent.com/33353403/96371937-b53ce200-1164-11eb-8af5-b38e9c6dfe01.png)

This is the mouse area that will be available when I'll load my state:

![image](https://user-images.githubusercontent.com/33353403/96371952-cd146600-1164-11eb-82fd-26767d16d0d4.png)

Then if I close and load the game with the cursor in bottom-right:

![image](https://user-images.githubusercontent.com/33353403/96371968-e1f0f980-1164-11eb-80d5-62bfdf6ca62e.png)

The mouse area will be limited to this:

![image](https://user-images.githubusercontent.com/33353403/96371979-ee755200-1164-11eb-86d3-c604c933dd7e.png)

And if I launch the game with the mouse in the middle, it will work fine. And it's the same issue with Warcraft 2 with DOSBox, if I put my cursor around here:

![image](https://user-images.githubusercontent.com/33353403/96372150-ea95ff80-1165-11eb-9fbb-78cb0adb2e91.png)

It will work fine because it will match the default position of the ingame cursor:

![image](https://user-images.githubusercontent.com/33353403/96372140-df42d400-1165-11eb-9738-1b4b7b97d2b9.png)

I made a video with Monkey Island 2 and PUAE core (I show ~middle, then top-left, bottom-right and middle again): https://youtu.be/Bbqr97GJ2po

**Comment by masaklaw** [comment] 2020-10-18 17:30
> I made a bit more testing, the problem seems to be because the mouse cursor when you launch the game is not at the same place as the ingame cursor, let me try to explain with a save state I made in Monkey Island 2 with PUAE core with the ingame cursor more or less in the middle of the screen:

Yes, but I think, that you cannot fix the problem this way (by only setting the starting position) in the general case. For example, if the emulated cursor's speed is set to be **slower** then the real cursor (the PUAE core has emulated mouse speed settings - which is very useful).

Grabbing the mouse seems to work just fine even with the mouse set to 10% speed.

**Comment by bslenul** [comment] 2020-10-18 19:00
Oh yeah, I'm not saying it's a workaround/fix or anything, just saying what seems to triggering the bug, maybe it could give a clue to the devs or something to fix it, idk :p 

For some reason on my VM the mouse is almost impossible to use after I press F11, it becomes waaaaaaaaaaaaay too sensitive, but it could be a bug in my VM.

**Comment by bslenul** [comment] 2020-10-22 10:03
https://github.com/libretro/RetroArch/pull/11471 has fixed this issue for me 👍 I get some weird stuff in RetroArch menu (not related to this PR) but I think this is a VMware issue.

**Comment by sonninnos** [comment] 2020-10-27 21:56
> For some reason on my VM the mouse is almost impossible to use after I press F11, it becomes waaaaaaaaaaaaay too sensitive, but it could be a bug in my VM.

With Oracle VM that is sorted by disabling "Input -> Mouse Integration", which will lock the mouse inside the VM. Better add a shortcut key for the function, or you can't get out easily, since alt-tab n such will go to the VM too.

**Closed** 2020-10-28 15:58 UTC
