### ISSUE TITLE
Segfault in ppsspp_libretro.so

### ISSUE THREAD

**Issue by gilbertoferreira** [libretro/RetroArch#12340] opened 2021-04-29 13:32 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Runing retroarch 1.9.1 with OpenGL or Vulkan.
Hardware: 
Laptop Acer Aspire A515-41G
RAM 16GB
Kubuntu 21.04
Kernel 5.12.0-051200-lowlatency (Have tried with kernel 5.11 too)

When try run PSP game with ppsspp_libretro get the error:
grep retroarch syslog
Apr 26 22:35:15 karis kernel: [ 4225.099426] traps: retroarch[4086] general protection fault ip:7f095a55a4ca sp:7f09a5f69090 error:0 in parallel_n64_libretro.so[7f095a33a000+782000]
Apr 28 22:43:31 karis kernel: [48663.146224] retroarch[75210]: segfault at 0 ip 00007fb005b75706 sp 00007ffcdc5fc030 error 4 in ppsspp_libretro.so[7fb0058e6000+e24000]
Apr 28 22:44:50 karis kernel: [48741.233621] retroarch[75250]: segfault at 0 ip 00007efeba6dd706 sp 00007ffc285f45f0 error 4 in ppsspp_libretro.so[7efeba44e000+e24000]
Apr 28 22:47:30 karis kernel: [  125.387861] retroarch[2005]: segfault at 0 ip 00007f65b2461706 sp 00007ffc31c38560 error 4 in ppsspp_libretro.so[7f65b21d2000+e24000]

### Expected behavior

PSP games run flawless.

### Actual behavior

Get segfault
grep retroarch syslog
Apr 26 22:35:15 karis kernel: [ 4225.099426] traps: retroarch[4086] general protection fault ip:7f095a55a4ca sp:7f09a5f69090 error:0 in parallel_n64_libretro.so[7f095a33a000+782000]
Apr 28 22:43:31 karis kernel: [48663.146224] retroarch[75210]: segfault at 0 ip 00007fb005b75706 sp 00007ffcdc5fc030 error 4 in ppsspp_libretro.so[7fb0058e6000+e24000]
Apr 28 22:44:50 karis kernel: [48741.233621] retroarch[75250]: segfault at 0 ip 00007efeba6dd706 sp 00007ffc285f45f0 error 4 in ppsspp_libretro.so[7efeba44e000+e24000]
Apr 28 22:47:30 karis kernel: [  125.387861] retroarch[2005]: segfault at 0 ip 00007f65b2461706 sp 00007ffc31c38560 error 4 in ppsspp_libretro.so[7f65b21d2000+e24000]

### Steps to reproduce the bug

1. Open retroarch 1.9.1
2. Download and install PPSSPP core
3. Try to run PSP game

### Bisect Results

Never run flawless. With PPSSP solo app works fine.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.1 from ppa (http://ppa.launchpad.net/libretro/stable/ubuntu)

### Environment information

- OS: Kubuntu Linux 21.04
- Compiler: [In case you are running local builds]

**Comment by gouchi** [comment] 2021-05-01 18:50
Hi,

Do you have Rewind enabled (Settings tab > Frame Throttle > Rewind > Rewind Support > On) ? If so please disable it.

Thank you.

**Comment by gouchi** [comment] 2021-05-01 18:52
It seems we get this segfault when it is enabled 

```
#0  0x00007fffee0ee1a9 in __DisplayDoState(PointerWrap&) () from /tmp/ppsspp/libretro/ppsspp_libretro.so
#1  0x00007fffee110dc2 in __KernelDoState(PointerWrap&) () from /tmp/ppsspp/libretro/ppsspp_libretro.so
#2  0x00007fffee1f5e2d in SaveState::SaveStart::DoState(PointerWrap&) () from /tmp/ppsspp/libretro/ppsspp_libretro.so
#3  0x00007fffee2702f2 in retro_serialize_size () from /tmp/ppsspp/libretro/ppsspp_libretro.so
#4  0x0000555555629944 in core_serialize_size (info=0x7fffffffb4b0) at retroarch.c:39085
#5  0x00005555556465b8 in content_get_rastate_size (size=0x7fffffffb4d0) at tasks/task_save.c:602
#6  0x0000555555646668 in content_get_serialized_size () at tasks/task_save.c:622
#7  0x00005555556884e8 in state_manager_event_init (rewind_st=0x5555563b4cf0 <rarch_st+124336>, rewind_buffer_size=20971520) at state_manager.c:590
#8  0x00005555555f1e9a in command_event (cmd=CMD_EVENT_REWIND_INIT, data=0x0) at retroarch.c:13897
#9  0x0000555555621c1a in retroarch_main_init (argc=4, argv=0x7fffffffe108) at retroarch.c:35526
#10 0x00005555556402f4 in content_load (info=0x7fffffffdfc0, p_content=0x5555563b6d70 <rarch_st+132656>) at tasks/task_content.c:607
#11 0x0000555555643004 in task_load_content_internal (content_info=0x7fffffffdfc0, loading_from_menu=true, loading_from_cli=true, loading_from_companion_ui=false) at tasks/task_content.c:2068
#12 0x00005555556432e6 in task_push_load_content_from_cli (core_path=0x0, fullpath=0x0, content_info=0x7fffffffdfc0, type=CORE_TYPE_PLAIN, cb=0x0, user_data=0x0) at tasks/task_content.c:2162
#13 0x00005555555f5083 in rarch_main (argc=4, argv=0x7fffffffe108, data=0x0) at retroarch.c:15506
#14 0x00005555555f5116 in main (argc=4, argv=0x7fffffffe108) at retroarch.c:15604
```

**Comment by gouchi** [comment] 2021-09-12 12:45
I can't reproduce anymore the issue when Rewind is enabled.

@gilbertoferreira Do you reproduce the issue ? If not please close this  issue.

Thank you.

**Closed** 2022-09-02 01:16 UTC
