### ISSUE TITLE
System mouse appears when using onscreen overlays

### ISSUE THREAD

**Issue by RagnaStrife** [libretro/RetroArch#3138] opened 2016-06-22 13:15 UTC
So I ended up bringing this up again anyway since I've just realized the other issue
was incorrectly labeled as Feature Request/Enhancement combined with being to
old to get any attention by the dev community.

This is the original issue opened by **ochief**: #2056
I hope it's okay to open a new issue.

Thank you.

**Comment by fr500** [comment] 2016-07-17 03:13
https://github.com/libretro/RetroArch/issues/2056
It's working as designed.
Overlays are meant for input. Using them for decoration is just an added bonus.

Not a bug

**Comment by RagnaStrife** [comment] 2016-07-17 18:59
Any chance you could add an option for disabling system mouse cursor when overlays are used?
Just thinking that overlays are useful for more than onscreen input, which looks a bit useless for a Windows desktop port anyway.

**Comment by modeler** [comment] 2016-07-20 21:08
I would also prefer an option to disable the mouse cursor. John Merrit's arcade overlays are proving very popular (see http://libretro.com/forums/showthread.php?t=5085) and these are just borders.

**Comment by navy1978** [comment] 2016-08-25 22:12
Hi guys, I have the same problem on windows, is there a possibility to see this done in the future? Thank you...

**Comment by rodnheli** [comment] 2016-08-27 12:47
hi! same here - overlays are perfekt for Input - but for me, it's an optical upgrade. using retroarch for windows from couch - mouse cursor is really annoying.

PLEASE add an option to disable.

**Comment by CharlesBukowski** [comment] 2017-01-04 21:17
I would also like to see an option to disable the mouse when using overlays. Besides being useful for input, overlays are also useful for adding scanlines via a .png. This provides an alternative to using shaders, which benefits low powered platforms like the Raspberry Pi.

**Comment by Tasosgemah** [comment] 2017-02-19 06:22
Any news on this? This is the reason i don't use overlays even though i would like to.

RetroArch is a "couch mode" application, there shouldn't be a need for a keyboard to be nearby to ungrab the mouse.

**Comment by Crono141** [comment] 2017-06-02 19:48
Or as an alternative, have an option for the mouse to be hidden by default.  I just started using mehstation as a frontend on RPi3, and its video overlays produce a mouse cursor (where emulationstation does not).

**Comment by orbea** [comment] 2019-01-04 00:40
Related to https://github.com/libretro/RetroArch/pull/6360.

**Comment by hizzlekizzle** [comment] 2020-04-30 22:44
This has been fixed with an option. Closing.

**Closed by hizzlekizzle** 2020-04-30 22:44 UTC
Labels: followup: enhancement

**Comment by Firefoxian** [comment] 2021-06-20 23:51
input_overlay_show_mouse_cursor = "false"
