### ISSUE TITLE
When loading game retroarch closes, restarts when game starts

### ISSUE THREAD

**Issue by simpledissection** [libretro/RetroArch#9088] opened 2019-07-11 00:34 UTC
### Description

When I load a game the retroarch window closes out.  Once the game begins, retroarch 'restarts' and the game plays.

### Expected behavior

When loading a game Retroarch should remain open.

### Actual behavior

Retroarch window closes when loading a game and then re-opens when the game finishes loading.

### Steps to reproduce the bug

1. Load any ROM for any system

### Bisect Results

This started happening the very first time I attempted to load a game.

### Version/Commit

- RetroArch: 1.7.7 (from Kubuntu software center)

### Environment information

- OS: Kubuntu 19.04
- Snap

**Comment by orbea** [comment] 2019-07-11 13:10
Duplicate of https://github.com/libretro/RetroArch/issues/4721.

**Closed by orbea** 2019-07-11 13:10 UTC

**Comment by simpledissection** [comment] 2019-07-12 01:13
So I can see how this is a similar issue, but you still haven't given any advice on how to resolve the issue.  Even in the other thread.  So how can the issue be resolved?  This is on a linux distro and not windows like the other one.  Does this happen to you when you use the program?

**Comment by orbea** [comment] 2019-07-12 01:32
@simpledissection There is no solution yet, its a known limitation that would require significant work to solve. Hopefully someone with the correct skill set will be able to do it one day. For now we just have to live with how RetroArch needs to destroy and recreate the graphics context when starting or switching content.

**Comment by simpledissection** [comment] 2019-07-12 03:45
Okay!  That makes sense.  Thank you for clarifying!
