### ISSUE TITLE
8bitdo SN30 Pro+ Bluetooth Xinput causes Retroarch to malfunction severely on Linux

### ISSUE THREAD

**Issue by Valrund** [libretro/RetroArch#10808] opened 2020-06-07 17:11 UTC
## Description

8bitdo SN30 Pro+ Bluetooth xinput causes Retroarch to malfunction severely

### Expected behavior

Controller to connect in either Xinput or Dinput mode and Retroarch run normally

### Actual behavior

Using the 8bitdo SN30 Pro+ controller in bluetooth Xinput mode on Ubuntu 20.04/ Manjaro 20 / Pop OS 20.04 causes Retroarch to misbehave badly. If the controller is connected and Retroarch is started afterwards, Retroarch will sit on a black screen for a while then when it eventually loads, menu assets will be missing, loading content will take an extremely long time, downloading cores errors out, save states take upwards of 20 seconds to save. Connecting the controller while Retroarch is already running will immediately do the same. Disconnecting the controller and connecting in Dinput mode, everything works completely normally. I dont have the issue with my xbox one bluetooth controller either.

### Steps to reproduce the bug

1. Connect 8BitDo SN30 Pro+ to PC via Bluetooth Xinput mode
2. Open Retroarch
3. Attempt to start a game or view a thumbnail in playlist

### Bisect Results

Confirmed on 1.7.4 through latest 1.8.8 nightly

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.8-r202006040234-27a0e6a-106~ubuntu20.04.1

### Environment information

- OS: Pop OS 20.04 / Manjaro 20 / Ubuntu 20.04
- Compiler: [In case you are running local builds]

**Comment by cmitu** [comment] 2020-06-08 03:30
Looks like a duplicate of https://github.com/libretro/RetroArch/issues/10408.

**Comment by hizzlekizzle** [comment] 2020-06-08 04:22
closing as duplicate. @Valrund thank you for taking the time to file the report. You can take part in the discussion or just follow the progress in the #10408 thread.

**Closed by hizzlekizzle** 2020-06-08 04:22 UTC
