### ISSUE TITLE
RCHEEVOS hang up at close content

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#8853] opened 2019-05-26 21:30 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Every now and then I have seen this:

![image](https://user-images.githubusercontent.com/1721040/58387398-7b999300-7fd3-11e9-8d02-854dbbf4c9fe.png)

Happens on quit or on close content.

### Expected behavior

I expect whatever is happen to finish so RA can QUIT properly

### Actual behavior

It's hanging.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment] 2019-05-26 21:31
@meleu @leiradel Pinging you guys about this.

**Comment by meleu** [comment] 2019-05-26 22:32
@fr500 can you confirm if this also happens when `cheevos_enable = false`?

**Comment by fr500** [comment] 2019-05-27 00:28
it's not something that happens every time so that won't really tell us anything, it's something that happens once every 10 or so runs and it always stops there.

**Comment by leiradel** [comment] 2019-05-27 08:29
I believe that the three `for` loops here are the cause of the issue: https://github.com/libretro/RetroArch/blob/master/cheevos-new/cheevos.c#L930

The loops are trying to free individual cheevos, unofficial cheevos, and leaderboards, but they're allocated as contiguous elements in arrays in `rcheevos_parse`. I believe that just removing the loops may fix the issue.

**Comment by Jamiras** [comment] 2020-06-06 19:12
I believe this has been fixed via #10399

**Closed** 2020-07-16 19:41 UTC
Labels: cheevos
