### ISSUE TITLE
Segfault when booting a core with a keyboard device [+fix]

### ISSUE THREAD

**Issue by AdrianoML** [libretro/RetroArch#3890] opened 2016-10-29 07:07 UTC
Tyrquake segfaults when attempting to boot with a keyboard device. Reverting the 149e7768a0d54872768c74382f0c6887745b28ae commit fixes the issue. Walking trough the hunks i found out that some values where being miss assigned in a RARCH_LOG call, this patch should fix it:

```
diff --git a/command.c b/command.c
index 5c39309..5609a4f 100644
--- a/command.c
+++ b/command.c
@@ -1166,9 +1166,9 @@ static void command_event_init_controllers(void)
             /* Some cores do not properly range check port argument.
              * This is broken behavior of course, but avoid breaking
              * cores needlessly. */
-            RARCH_LOG("%s %u : %s (ID: %u).\n", i + 1,
-                  msg_hash_to_str(MSG_CONNECTING_TO_PORT),
-                  ident, device, i + 1);
+            RARCH_LOG("%s %u: %s (ID: %u).\n",
+                    msg_hash_to_str(MSG_CONNECTING_TO_PORT),
+                    device, ident, i+1);
             set_controller = true;
             break;
       }
```

**Comment by fr500** [comment] 2016-10-29 20:00
In what platform?

**Comment by AdrianoML** [comment] 2016-10-29 20:36
Tested on x86_64 linux

**Comment by twinaphex** [comment] 2016-10-30 08:43
Merged the patch, thanks. Check to see if it the issue is resolved now in latest trunk.

**Comment by AdrianoML** [comment] 2016-10-30 10:55
Tested it, everything is fine now!

**Closed** 2016-11-01 22:46 UTC
Labels: major bug
