### ISSUE TITLE
Zooming image to crop some game borders is too difficult

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#7368] opened 2018-10-04 22:37 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Many retro games, especially those for micros like the C64 or ZX Spectrum, have large blank borders around the game. Some games have larger borders, some have smaller borders. Many games fit quite nicely onto modern 16:9 displays, if they can be zoomed and centered to crop borders while keeping the aspect ratio correct (mostly at 4:3 for most games).

Currently, the only way to zoom the image in Retroarch is to use a zoom shader, not available on platforms without shaders, or to use the video options "Aspect Ratio: Custom" and adjust "Scale_x," "Scale_y" numbers manually together with "Offset_x" and "Offset_y" to center the zoomed image. But then a calculator is needed to ensure the scale_x and scale_y numbers are correct so that the zoomed picture still has the desired aspect ratio (e.g. 4:3 for most systems).

I think an overall floating point "zoom" option, that could be used together with "offset_x" and "offset_y" to center the zoomed image would be great. It could be used even when AR is fixed to 4:3 under video.

### Expected behavior

I want to zoom and center the image to crop a game's blank borders, while keeping the aspect ratio fixed.

### Actual behavior

Currently, if I try to increase image scale while keeping aspect ratio, I have to first set the aspect ratio to custom. I then have to adjust scale_y and offset_y until the game fits the screen vertically in such a way that the top/bottom blank borders are cropped. Then I have to use a calculator to find the correct scale_x, via scale_x=4 / 3 * scale_y / "original resolution pixel aspect". Then I have to adjust offset_x to center the image manually. This is just too impractical.

### Steps to reproduce the bug

see above

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.5

### Environment information

- OS: Switch and Vita
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment] 2019-01-04 03:39
Duplicate of issue https://github.com/libretro/RetroArch/issues/4158.

**Closed by orbea** 2019-01-04 03:39 UTC
Labels: feature request, followup: enhancement, invalid: duplicate
