### ISSUE TITLE
retroarch-joyconfig missing?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [libretro/RetroArch#1294] opened 2014-12-18 23:04 UTC
Where is retroarch-joyconfig? Installing latest stable version doesn't seem to include it. I see repo "retroarch-joypad-autoconfig" but it doesn't seem to have the binary for configuring buttons.

**Comment by Alcaro** [comment] 2015-01-04 10:31
Closing as duplicate of #1284.

**Closed by Alcaro** 2015-01-04 10:31 UTC
