### ISSUE TITLE
pull-down menu does not directly apply when selected

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#8356] opened 2019-02-24 01:12 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

pull-down menu (or whatever that thing is called when you point to an option and press enter to see option selections) does not directly apply when selected

### Expected behavior

when selecting new options from pull-down menu, settings should apply directly

### Actual behavior

this has been a long standing issue since its introduction. setting only applies when a screen redraw or entering the options again (some options does apply but most do not... dunno if its the actual menu is the problem or this pull-down is missing something that applies new values directl. either way settings are not apply, for most of them (core options included)

### Steps to reproduce the bug

(this happens on most option but this is just a quick example of how to check for it consistently)
1. assuming retroarch is launched. goto settings > video > screen rotation
2. use ENTER to show pulldown menu and choose your new prefered options. upon doing that, it should either apply the new option or apply it after you exit this menu. but nothing happens.
3. re-enter the same option (screen rotation in this case), doing this will now apply the setting you did earlier.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.6 1c9ac4e825

### Environment information

- OS: im using arch btw
- Compiler: gcc version 8.2.1 20181127 (GCC)

**Comment by orbea** [comment] 2019-02-24 01:38
Duplicate of issue https://github.com/libretro/RetroArch/issues/7528?

**Comment by orbea** [comment] 2019-02-25 02:02
After re-reading both issues I still think its a duplicate so I am going to close this issue in favor of the other one, please let me know if you disagree!

**Closed by orbea** 2019-02-25 02:02 UTC
Labels: bug: minor, bug: ui
