### ISSUE TITLE
 Save States not Working Properly in 1.9.6 64 Bit 

### ISSUE THREAD

**Issue by TradeDraft** [libretro/RetroArch#12620] opened 2021-07-06 11:05 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Save States Jumping Slots when Saving State

### Expected behavior

Slots Jump Up from the Number you Have

### Actual behavior

Slot Stays the Same when you Save State

### Steps to reproduce the bug

1. Load up Game and Rom
2. Go Into Menu
3. Press Save State or Press Hotkey for Save State

### Bisect Results

Soon as I updated to Version 1.9.6

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.6 64 Bit

### Environment information

- OS: Windows 10 64 Bit
- Compiler: [In case you are running local builds]

**Comment by bslenul** [comment] 2021-07-06 14:40
Can't reproduce, sure you didn't enable `Settings > Saving > Increment Save State Index Automatically` by accident?

**Comment by TradeDraft** [comment] 2021-07-07 00:00
> Can't reproduce, sure you didn't enable `Settings > Saving > Increment Save State Index Automatically` by accident?

I have never heard of that Option before today but I checked it and it was set to On for some Unknown Reason. Though I sometimes have FPS show up without touching the Option for it.

But Turned it off and Works Fine Now.

Thanks for the Help @bslenul

**Comment by gouchi** [comment] 2021-07-07 08:06
@TradeDraft so please close this issue ;)

**Closed** 2021-07-07 09:59 UTC
