### ISSUE TITLE
Box Art Appears Over Menu Shader Option Text

### ISSUE THREAD

**Issue by shinra358** [libretro/RetroArch#4549] opened 2017-02-02 13:59 UTC
In the newer versions of retroarch, when launching a game and going into the menu shader options, the box art of the game is drawn on top of the menu options.

**Comment by RobLoach** [comment] 2017-02-02 15:18
Happens on Controls too....

![box](https://cloud.githubusercontent.com/assets/25086/22555180/da415a14-e930-11e6-8292-24345563ce81.png)

Not quite sure what the solution for it would be.

**Comment by hizzlekizzle** [comment] 2017-02-02 16:42
I would think the easiest solution would be to change the text to be "on top" of the boxart, though readability would still be a concern.

**Comment by RobLoach** [comment] 2017-02-02 16:48
Don't show the boxart on those game sub-options?

**Comment by bparker06** [comment] 2017-02-02 16:57
@RobLoach Nice battery percentage. What platform is this? Never seen that issue before.

**Comment by JuanVCS** [comment] 2017-02-02 17:51
Duplicate? https://github.com/libretro/RetroArch/issues/4498

**Comment by RobLoach** [comment] 2017-02-02 18:57
> @RobLoach Nice battery percentage. What platform is this? Never seen that issue before.

```
$ uname -a
Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

> Duplicate? #4498

Seems tangential... That one may have to do with the Quick Menu behavior, rather then just being focused on the BoxArt appearance in the sub-menus.

**Comment by Alex793** [comment] 2017-06-25 06:07
Issue is still present on iOS version from 1.4.0 to 1.6.0, no problem on 1.3.6, the text was "on top".

RA 1.3.6 : ![image](https://cloud.githubusercontent.com/assets/428805/26143509/8c54d540-3ae5-11e7-9d8d-679721335fc2.png)

RA 1.4.0-1.6.0 : ![image](https://cloud.githubusercontent.com/assets/428805/26143477/6ccfdb98-3ae5-11e7-968d-b60a503aa5e7.png)

(Look "per bios")

**Comment by orbea** [comment] 2019-01-04 03:00
This is fixed and a duplicate of issue https://github.com/libretro/RetroArch/issues/4498.

**Closed by orbea** 2019-01-04 03:00 UTC
