### ISSUE TITLE
D3D11 will not maintain Aspect Ratio the second time going fullscreen

### ISSUE THREAD

**Issue by James-F2** [libretro/RetroArch#6319] opened 2018-02-20 08:46 UTC
Windows x64 Retroarch v1.7.1

Aspect Ratio is set to 4:3.
Going fullscreen, back to window, then back to fullscreen again using the (F) button, will result in a stretched image to full screen area and will not maintain the 4:3 setting.

Refreshing the Aspect Ratio setting will fix the issue, or restarting the core.
This doesn't happen in D3D9 or GL.

Secondary report:
D3D9 has issue with stretched window (not fullscreen), the image seems to be bigger than the window itself.

**Comment by retro-wertz** [comment] 2018-02-20 09:03
possibly similar/related to this:
https://github.com/libretro/RetroArch/issues/6150

**Comment by James-F2** [comment] 2018-02-20 10:17
Ah yes. thanks for referencing.

**Comment by orbea** [comment] 2019-02-26 23:26
I agree with @retro-wertz that this is a duplicate of issue https://github.com/libretro/RetroArch/issues/6150.

**Closed by orbea** 2019-02-26 23:26 UTC
Labels: platform: windows
