### ISSUE TITLE
Retroarch crashes when scanning .cue files

### ISSUE THREAD

**Issue by externo6** [libretro/RetroArch#5451] opened 2017-09-18 10:49 UTC
## Description

[Description of the bug]
When scanning .cue files, retroarch crashes.

Windows 10
Retroarch 1.6.7 stable (also tested nightly)

### Expected behavior
Continues scanning and populates playlist

### Actual behavior
Crashes with "retroarch_debug.exe has stopped working"
Crashes when scanning a directory, also crashes when scanning an individual .cue

### Steps to reproduce the bug

1. Tell Retroarch to scan directory/ cue file
2. When it hits the cue file crash  occurs

### Bisect Results

Unknown, only just started using Retroarch  on Windows.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
Git Version 836111b

### Environment information

Windows 10 Build 15063

Logs:
When running Retroarch_debug.exe from cmd with --verbose the last lines are:
[INFO] Loading history file: [P:\RetroArch\content_history.lpl].
[INFO] Loading history file: [P:\RetroArch\content_favorites.lpl].
[INFO] Loading history file: [P:\RetroArch\content_music_history.lpl].
[INFO] Loading history file: [P:\RetroArch\content_video_history.lpl].
[INFO] Loading history file: [P:\RetroArch\content_image_history.lpl].
[INFO] [GL]: VSync => off
[INFO] [WGL]: wglSwapInterval(0)
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[INFO] Parsing CUE file 'E:\psx\Crash Bandicoot\Crash Bandicoot (E) (EDC).cue'...

**Comment by frame** [comment] 2017-09-21 18:56
I've encountered the same issue, here some additional information to help fix this bug:

On my Windows 10.0.15063 (64bit) machine Retroarch 1.6.7 (64bit) crashes when scanning .cue files. I've noticed crashes with PCE-CD (.cue, .iso), PS1 (.cue, .bin) and 3DO (.cue, .iso).

Reproduction steps for PCE-CE (mednafen_pce_fast_libretro.dll):

1. Download Retroarch 1.6.7 (64bit)
1. Extract and run
1. Update Core Info Files
1. Update Databases
1. Install PC Engine/PCE-CE (Beetle PCE FAST) Core (mednafen_pce_fast_libretro.dll)
1. Scan a folder with .cue/.iso files*
1. Retroarch will crash

*) I can provide a sample download link if requested by a developer.

I've run Retroarch with --verbose:

Full log: https://gist.github.com/frame/ee17308739efc563fbb90d14df1f3b20

Excerpt:

    [INFO] Parsing CUE file 'U:\Games\RetroArch\test\Gate_of_Thunder_(NTSC-J)_[HCD2025].cue'...
    [INFO] Found first data track on file 'U:\Games\RetroArch\test\GATE_OF_THUNDER_(NTSC-J)_[HCD2025].ISO+0'
    [INFO] Reading first data track...
    [INFO] Comparing with known magic numbers...
    [INFO] Could not find compatible system.

And here's the Application Error in Windows Event Log:

    Faulting application name: retroarch_debug.exe, version: 0.0.0.0, time stamp: 0x599b3864
    Faulting module name: retroarch_debug.exe, version: 0.0.0.0, time stamp: 0x599b3864
    Exception code: 0xc0000005
    Fault offset: 0x00000000000e09bd
    Faulting process id: 0x3e2c
    Faulting application start time: 0x01d32568add825da
    Faulting application path: U:\Games\RetroArch\retroarch_debug.exe
    Faulting module path: U:\Games\RetroArch\retroarch_debug.exe
    Report Id: a77ef4db-2bc3-4391-8ec4-2a88cd4beb53
    Faulting package full name: 
    Faulting package-relative application ID:

**Comment by RobLoach** [comment] 2017-09-21 19:07
Been a lot of changes since [`a235c0b Aug 21`](https://github.com/libretro/RetroArch/commit/a235c0b), even as of today. Mind trying the nightly?

**Comment by frame** [comment] 2017-09-22 21:07
OP already mentioned the nightly.

I've now downloaded the latest nightly (2017-09-22) and I'm getting a slightly different result: It appears there's a 2nd scan attempt now, but the Application does crash too.

Full log: https://gist.github.com/frame/9fffa44d774c2f3b5bc2efe31c6ede5d

Excerpt:

    [INFO] Parsing CUE file 'U:\Games\RetroArch\test\Gate_of_Thunder_(NTSC-J)_[HCD2025].cue'...
    [INFO] Reading first data track...
    [INFO] Comparing with known magic numbers...
    [INFO] Could not find compatible system.
    [INFO] Found disk label 'PRODUCER'
    [INFO] Parsing CUE file 'U:\Games\RetroArch\test\Gate_of_Thunder_(NTSC-J)_[HCD2025].cue'...
    [INFO]

Yes, the last line just ends after [INFO]<EOF>

Application Error in Windows Event Log:

    Faulting application name: retroarch_debug.exe, version: 0.0.0.0, time stamp: 0x59c557a8
    Faulting module name: msvcrt.dll, version: 7.0.15063.0, time stamp: 0x3280d1b7
    Exception code: 0xc0000005
    Fault offset: 0x0000000000050613
    Faulting process id: 0x56c
    Faulting application start time: 0x01d333e60c95dc86
    Faulting application path: U:\Games\RetroArch\retroarch_debug.exe
    Faulting module path: C:\Windows\System32\msvcrt.dll
    Report Id: eff4926d-bf64-4f6e-80c6-fc18282f75d1
    Faulting package full name: 
    Faulting package-relative application ID:

**Comment by externo6** [comment] 2017-09-22 22:12
I'm no longer having crashes on the latest nightly. 
Git version 09e1b2b

**Comment by frame** [comment] 2017-09-23 19:47
I can confirm this. latest nightly works fine.

**Comment by orbea** [comment] 2018-12-31 23:05
Two people have confirmed it now works so I am going to close this.

**Closed by orbea** 2018-12-31 23:05 UTC
