### ISSUE TITLE
RetroArch from version "v1.11.0" to "v1.14" - video problem

### ISSUE THREAD

**Issue by zibijani** [libretro/RetroArch#14892] opened 2023-01-22 21:01 UTC
Up to version "v1.10.3" everything works ok, but from version "v1.11.0" to "v1.14.0" 
the video does not work and by that also the gui. No settings (video) help. 

My system:     XP-SP3
test soft:     RetroArch-MSVC10-Win32  (XP 32 bits)
Graphics card: Ati Mobility Radeon X700

**Comment by RobLoach** [comment] 2023-01-25 16:51
Which video driver in RA are you using?

**Comment by zibijani** [comment] 2023-01-25 20:07
With running versions of RA, I mainly use :
video_driver = "d3d8"

**Comment by gouchi** [comment] 2023-01-26 17:15
Duplicate of #14830 ?

According to this [post](https://forums.libretro.com/t/retroarch-on-winxp-32-bit-transparent-window/40195/6), it should work as fallback with video driver `gdi` and menu driver `rgui`.

**Comment by RobLoach** [comment] 2023-01-26 17:17
Does look similar to the other issue. Thanks zibijani and gouchi!

**Closed by RobLoach** 2023-01-26 17:17 UTC
