### ISSUE TITLE
RetroArch can't handle too many cheat passes

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#6124] opened 2018-01-16 19:09 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When there are too many cheat passes, it starts turning into controller settings! If you scroll down enough, then it crashes as well.

### Expected behavior

The cheats to go on being cheats....

### Actual behavior
This:

![rofl](https://user-images.githubusercontent.com/32988993/35006950-4ff9a854-faf8-11e7-98ef-80980553cc12.png)

### Steps to reproduce the bug

1. Load Pokémon Heart Gold
2. Add the Pokémon Heart Gold cheats preset ( 1229 cheats! Absolutely insane! )
3. Scroll down...

### Bisect Results

Not sure when this started happening.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW 64-bit from the build bot :p

**Comment by bparker06** [comment] 2018-01-18 15:32
duplicate of #6060

**Closed by bparker06** 2018-01-18 15:32 UTC
