### ISSUE TITLE
[Feature request] freedesktop.org screen locking standards

### ISSUE THREAD

**Issue by telanus** [libretro/RetroArch#8460] opened 2019-03-13 07:37 UTC
Using RetroArch (on Kubuntu 18.04.02) The screenblanker would kick in every ten minutes when I use my xbox360 wireless controller. It only happens with RA, PPSSPP, pcsx2 & redream I can use a controller for hours without the screenblanker kicking in.I've disabled the screensaver in the RA config, but it still happens. 

Seems Retroarch only work with xscreensaver not the new freedesktop.org screen locking standards.

could RA be updated to add support for freedesktop.org screen locking standards

**Comment by orbea** [comment] 2019-03-13 15:05
Probably a bug with your DE, you could try building with `--enable-dbus` to see if that helps.

I'm going to close this because its a duplicate of issue https://github.com/libretro/RetroArch/issues/7472, please continue more discussion there, thanks!

**Closed by orbea** 2019-03-13 15:05 UTC
