### ISSUE TITLE
Select File/Run menu stays over the game when the game is selected from the "Load Recent" menu

### ISSUE THREAD

**Issue by yurivict** [libretro/RetroArch#3974] opened 2016-11-09 08:17 UTC
When I select the item from under the "Load Recent" menu, the game starts with the same menu hanging over it.

![libretro-run-menu](https://cloud.githubusercontent.com/assets/271906/20131361/d10002aa-a611-11e6-8674-e06f3b4a4d20.png)

It doesn't go away with any key presses.

This makes this "Load Recent" menu unusable. Using sdl2 in case this matters.

**Comment by lasers** [comment] 2016-11-25 21:16
Confirmed with sdl2 + rgui. Pressing Menu twice (F1) makes it go away. Confirm that?

**Comment by yurivict** [comment] 2016-11-26 07:35
Confirmed.

**Comment by twinaphex** [comment] 2016-12-25 17:49
I think this is fixed by now in the latest nightlies. Reopen if it still happens.

**Closed by twinaphex** 2016-12-25 17:49 UTC

**Comment by alend88** [comment] 2019-12-14 02:46
Looks like this issue is back on the newest build, except it occurs when you  "load any content", not just recent content - main menu gets stuck as overlay:
![image](https://user-images.githubusercontent.com/42618586/70842425-87bf3380-1df1-11ea-915a-e75cfcabf3dd.png)

Here is the dump of my version information and config if that helps with diagnosis at all:

[INFO] RetroArch 1.8.1 (Git bfdc8e6)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Atom(TM) CPU N270   @ 1.60GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3
[INFO] Built: Nov  4 2019
[INFO] Version: 1.8.1
[INFO] Git: bfdc8e6
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [SDL2]: Available renderers (change with $SDL_RENDER_DRIVER):
[INFO] 	opengl
[INFO] 	opengles2
[INFO] 	software
[INFO] [SDL2]: Available displays:
[INFO] 	Display #0 mode: 1024x600@60hz.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Plugged pad: 8Bitdo 8Bitdo SF30 Wireless Controller (11720:12289) on port #0.
[INFO] [Autoconf]: 304 profiles found.
[INFO] [udev]: Pad #0 (/dev/input/event8) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [SDL]: Input driver initialized.
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "null".
[INFO] [LED]: LED driver = 'null' 0x1271d80
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/username/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/username/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/username/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/username/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/home/username/.config/retroarch/content_favorites.lpl].
[INFO] [Autoconf]: selected configuration: /home/username/.config/retroarch/autoconfig/udev/8Bitdo_24G_SF30_USB.cfg
org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[INFO] Updating firmware status for: /home/username/.config/retroarch/cores/nestopia_libretro.so on /home/username/.config/retroarch/downloads/
[INFO] Using content: /home/username/.config/retroarch/downloads/Ice Hockey (USA).nes.
[INFO] arg #0: retroarch
[INFO] arg #1: /home/username/.config/retroarch/downloads/Ice Hockey (USA).nes
[INFO] arg #2: -c
[INFO] arg #3: /home/username/.config/retroarch/retroarch.cfg
[INFO] arg #4: -L
[INFO] arg #5: /home/username/.config/retroarch/cores/nestopia_libretro.so
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : /home/username/.config/retroarch/retroarch.cfg
[INFO] RetroArch 1.8.1 (Git bfdc8e6)
[INFO] Redirecting save file to "/home/username/.config/retroarch/downloads/Ice Hockey (USA).srm".
[INFO] Redirecting savestate to "/home/username/.config/retroarch/downloads/Ice Hockey (USA).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Atom(TM) CPU N270   @ 1.60GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3
[INFO] Built: Nov  4 2019
[INFO] Version: 1.8.1
[INFO] Git: bfdc8e6
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/home/username/.config/retroarch/cores/nestopia_libretro.so"
[INFO] [Overrides] no core-specific overrides found at /home/username/.config/retroarch/config/Nestopia/Nestopia.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /home/username/.config/retroarch/config/Nestopia/downloads.cfg.
[INFO] [Overrides] no game-specific overrides found at /home/username/.config/retroarch/config/Nestopia/Ice Hockey (USA).cfg.
[INFO] [Environ]: SET_VusernameABLES.
[INFO] [Remaps]: remap directory: /home/username/.config/retroarch/config/remaps
[INFO] Redirecting save file to "/home/username/.config/retroarch/downloads/Ice Hockey (USA).srm".
[INFO] Redirecting savestate to "/home/username/.config/retroarch/downloads/Ice Hockey (USA).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 6.
[INFO] Loading content file: /home/username/.config/retroarch/downloads/Ice Hockey (USA).nes.
[INFO] Did not find a valid content patch.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[WARN] SYSTEM DIR is empty, assume CONTENT DIR /home/username/.config/retroarch/downloads/Ice Hockey (USA).nes
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/username/.config/retroarch/downloads/".
[libretro INFO] Custom palette path: /home/username/.config/retroarch/downloads//custom.pal
[libretro WARN] custom.pal not found in system directory.
[libretro INFO] NstDatabase.xml path: /home/username/.config/retroarch/downloads//NstDatabase.xml
[libretro WARN] NstDatabase.xml required to detect region and some mappers.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] SET_GEOMETRY: 256x224, aspect: 1.306.
[INFO] [Environ]: SET_GEOMETRY.
[libretro INFO] [Nestopia]: Machine is NTSC.
[INFO] [RCHEEVOS]: ext_hash 0b88944b ('nes')
[INFO] [RCHEEVOS]: Load task finished
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/username/.config/retroarch/cheats/Nestopia/Ice Hockey (USA).cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [SDL2]: Available renderers (change with $SDL_RENDER_DRIVER):
[INFO] 	opengl
[INFO] 	opengles2
[INFO] 	software
[INFO] [SDL2]: Available displays:
[INFO] 	Display #0 mode: 1024x600@60hz.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Plugged pad: 8Bitdo 8Bitdo SF30 Wireless Controller (11720:12289) on port #0.
[INFO] [Autoconf]: 304 profiles found.
[INFO] [udev]: Pad #0 (/dev/input/event8) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [SDL]: Input driver initialized.
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "null".
[INFO] [LED]: LED driver = 'null' 0x1271d80
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] Loading history file: [/home/username/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/username/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/username/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/username/.config/retroarch/content_image_history.lpl].
[INFO] Loading favorites file: [/home/username/.config/retroarch/content_favorites.lpl].
[INFO] [Autoconf]: selected configuration: /home/username/.config/retroarch/autoconfig/udev/8Bitdo_24G_SF30_USB.cfg
org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[INFO] [config] Saved new config to "/home/username/.config/retroarch/retroarch.cfg".
[INFO] [Cheats]: Save game-specific cheatfile: /home/username/.config/retroarch/cheats/Nestopia/Ice Hockey (USA).cht
[INFO] Content ran for a total of: 00 hours, 00 minutes, 07 seconds.
[INFO] Saving runtime log file: /home/username/.config/retroarch/playlists/logs/Nestopia/Ice Hockey (USA).lrtl
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "/home/username/.config/retroarch/retroarch-core-options.cfg"
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
