### ISSUE TITLE
[Win 10 (probably 8 too)] Low performance if CPU is on low usage

### ISSUE THREAD

**Issue by Fighter19** [libretro/RetroArch#1491] opened 2015-03-11 22:54 UTC
On my Laptop when using Retroarch, the framerate and sound drops when the cpu is tending to have no usage at all. I'm using the nightly build from 03/10/2015. It seems to affect all cores.
I'm running Windows 10 Techincal Preview on a K73SV.
EDIT: The cause seems to be somewhere inside the GL render code

**Comment by fr500** [comment] 2015-03-11 23:01
Probably your PC is throttling down then, change your power profile to high performance... 
Not really a RA bug

**Comment by Fighter19** [comment] 2015-03-11 23:07
You mean my Laptop enters powersave mode when there is not enough usage? This could be right, however even after I selected my High Performance profile it appears to do some Power Saving (seems to improve a little but it still only runs at 48FPS). I wonder why RA doesn't create enough usage to run on a good framerate like 60FPS (I'm not someone who knows much about ressources etc. so pls don't rage at me)

**Comment by Fighter19** [comment] 2015-03-11 23:29
Found out that using one of the other two video drivers works perfect, not sure if solved, or not.

**Comment by twinaphex** [comment] 2015-03-11 23:47
Which video driver did you use that it worked fine on? Radius might want to fill in with his own experiences so far.

**Comment by Fighter19** [comment] 2015-03-12 00:01
d3d and SDL2 worked fine.

**Comment by fr500** [comment] 2015-03-12 00:15
I actually think the GL driver is better optimized for windowed mode, when windowed I get 5% cpu usage in RGUI, so it could be triggering the issue for you.

I just found out the complete opposite problem in fullscreen though, I get 25% usage (100% of a core) in fullscreen mode for RGUI, in game performance seems unaffected though.

**Comment by twinaphex** [comment] 2015-03-15 17:11
What GPU is this?

**Comment by Fighter19** [comment] 2015-03-15 19:10
Um, actually I'm not sure if the Intel HD Graphics is used or the NVidia 530m, but I think it's the first one.

**Comment by twinaphex** [comment] 2015-03-15 22:03
Can you try the nvidia GPU and see how that works?

**Comment by Fighter19** [comment] 2015-03-18 12:32
I tried it with the NVIDIA GPU now, it works perfect, even without Power supply. But sometimes it also does with the Intel GPU :/ (I assured I do this test when it doesn't work fluent with the Intel GPU)

**Comment by RagnaStrife** [comment] 2015-03-25 23:50
It might be a problem with your Intel integrated graphics video driver having issues with OGL or not having enough power to manage whatever cores or shaders you were using.
Doesn't seem like a RA bug.

**Comment by Awakened0** [comment] 2015-09-02 22:42
I have this happening on my desktop since upgrading to Win10. I get minor sound crackling in BSNES Balanced and Mednafen PSX. And major crackling in mGBA. But if I run OBS in the background or antimicro (open source joytokey alternative) there's no crackling. Launching from Big Picture Mode in Steam fixes it too, but not if I launch from the desktop client (or from Retroarch directly).

I tried all the different video driver options in RetroArch as well as windowed and true fullscreen modes and none of them were any better for me. I have the High Performance power profile selected too. This is on a 2500k with a GTX970.

**Comment by twinaphex** [comment] 2015-10-10 06:38
Overaggressive power management ruining runtime performance? Any other projects have experienced similar issues and if so, were they able to come up with some kind of fix?

**Comment by Awakened0** [comment] 2015-10-10 08:27
PCSX2 is the only other one I've encountered the same type of problem with, but they haven't fixed it.

**Comment by Awakened0** [comment] 2015-11-03 00:54
I can't reproduce this on my Win10 desktop anymore. I have full performance without Antimicro, OBS or Chrome in the background. My task manager was clean of everything except Windows stuff when I was testing. Even switching back to the default "Balanced" power profile doesn't hurt performance now. I'm still using the 1.2.2 point release, so it wasn't something that changed in RA.

There have been some KB updates to Win10 the past few weeks, but I don't know if they fixed anything since they were supposed to be security related. The only thing I changed on my system was switching from a Mayflash Wii U Pro adapter to a wired Xbox One controller. That's a different driver, but still xinput. I updated to a new NVidia driver awhile ago, but I tested for this problem directly after updating that and it was still an issue then.

Curious if anyone else no longer has the problem, since different hardware and software configs can affect it.

**Comment by orbea** [comment] 2019-01-11 16:39
This sounded like issues with the OS graphics cards and drivers rather than RetroArch. Given the lack of any updated in about 3 years since @Awakened0 said he could no longer reproduce it I am going to close this.

**Closed by orbea** 2019-01-11 16:39 UTC
Labels: bug: minor

**Comment by Awakened0** [comment] 2019-01-11 22:12
I haven't had those types of issues since then and am still running the same hardware in my desktop. Still running the Balanced power profile too, while some seem to need High Performance.

**Comment by jadamnoah** [comment] 2019-08-29 11:45
> Found out that using one of the other two video drivers works perfect, not sure if solved, or not.

Thanks for posting this -- solved all my issues as well!

**Comment by Fighter19** [comment] 2019-08-29 12:40
I've reverted my laptop to Windows 7 since then.
Optimus Laptops seem to have severe issues with Windows 10 drivers
and apparently never really enter High Performance mode.
This issue wasn't fixed by anyone, and I also now believe it to be solely a problem related to the power-management on Windows 10.
