### ISSUE TITLE
READ_CORE_MEMORY etc acts upon the wrong location if core's memory descriptor is non-contiguous

### ISSUE THREAD

**Issue by strotlog** [libretro/RetroArch#13664] opened 2022-02-24 07:19 UTC
## Description

Cores tell RetroArch about the emulated system memory using SET_MEMORY_MAPS. The emulated system memory can then be accessed by other programs communicating with RetroArch over the UDP Network Commands, without further participation from the core which owns the memory.

Cores may use a large, contiguous buffer, to back an area of emulated system memory that can be accessed non-contiguously in emulation.

In such cores, the core may indicate specific address bits that RetroArch should "disconnect" when translating from the emulated address space to the internal buffer. These bits are specified in the `disconnect` field of a `retro_memory_descriptor`.

Trivial example:
The memory descriptor could describe a "disconnect" of 0x0f0 - bits 4-7 are disconnected.
Emulated address space address: xxxx yyyy zzzz (such as 0x123) maps to an offset in the backing buffer of: xxxx zzzz (0x13).

Bug: The "disconnect" bits are not being honored: RetroArch's READ_CORE_MEMORY handler is attempting to read from 0x123 in the core's backing buffer instead of from 0x13.

Possible cause:

The correct memory descriptor is being retrieved, but then `command_memory_get_pointer()` in command.c ignores the `desc->disconnect` field (representing disconnected memory addressing bits). It instead assumes that the emulated address space covered by the memory descriptor is contiguous. Actually, only the host system storage `desc->ptr` must be contiguous for a given descriptor.

### Expected behavior

Can correctly read any part of the SNES ROM using READ_CORE_MEMORY.

### Actual behavior

The wrong bank's data is being returned unless the first bank (ROM: Bank $80) is requested.

Writable memory may also be accessed non-contiguously in SNES, so WRITE_CORE_MEMORY is likely affected as well, and could be demonstrated if so.

### Steps to reproduce the bug

1. Hex edit a SNES/SFC ROM that uses [SNES LoROM memory mapping](https://en.wikibooks.org/wiki/Super_NES_Programming/SNES_memory_map). Overwrite with some demonstration data (emulated system may crash; that's OK as access to the data from outside doesn't change. Alternatively, you could instead compare the UDP API's result against the ROM's existing data, but sometimes the start of each bank is very similar so pay close attention).
- ROM file offset  0x8000 = Overwrite with 0xBA, 0x81 // our indicator for "bank $81"
- ROM file offset 0x10000 = Overwrite with 0xBA, 0x82 // our indicator for "bank $82"

2. Load the ROM using a SNES core that implements SET_MEMORY_MAPS (and therefore supports READ_CORE_MEMORY), such as bsnes-mercury. The following descriptor, or similar, is reported by the core, as seen with core debug logging enabled:
```
[INFO] [Environ]: SET_MEMORY_MAPS.
[INFO]            ndx flags  ptr              offset   start    select   disconn  len      addrspace
[INFO]            016 M1A1bC 0000019bfbfde040 00000000 00808000 00808000 00008000 00300000
```

3. retroarch.cfg or set in UI: network_cmd_enable=true

4. Execute commands over the UDP Network Commands port (default 55355):

READ_CORE_MEMORY 808000 2
Expected behavior: RetroArch replies with the first 2 bytes of the ROM, which in SNES native terms are accessed at $80:8000.
Actual: As expected.

READ_CORE_MEMORY **81**8000 2
Expected behavior: RetroArch replies with the first 2 bytes of bank $81 ROM space (SNES-native address: $81:8000): BA 81
Actual: (Bug) RetroArch replies with BA **82** // our indicator for "bank $82".

Examining further:
- Operations upon Bank $81 are being directed to Bank $82
- Operations upon Bank $82 are being directed to Bank $84
- ...
- Operations upon Bank $AF are being directed to Bank $DE
- Operations upon the latter half of the ROM are failing with "-1 no data for descriptor"
(Latter half of the ROM would be Bank $B0 onward, given a 3MiB ROM file, whose last bank would be Bank $DF)

### Bisect Results

This appears to have been broken since READ_CORE_MEMORY and WRITE_CORE_MEMORY were implemented (in RetroArch 1.9.2).

### Version/Commit

- RetroArch: ee4486068d

### Environment information

- OS: Windows 10
- Compiler: MinGW 64-bit

**Comment by Jamiras** [comment] 2022-02-24 16:54
As discussed in Discord, the problem is the READ_CORE_MEMORY and WRITE_CORE_MEMORY functions are not honoring the disconnect bits specified in the memory map. I'll try to implement a fix for this in the next couple of days.

**Comment by strotlog** [comment] 2022-02-24 17:52
Thanks Jamiras! I'm looking at preparing a pull request today if you don't mind my trying.

I forgot to include: The regression from a user perspective is that UDP command READ_CORE_RAM was able to read the ROM correctly in older versions of RetroArch. Tools such as [SNI](https://github.com/alttpo/sni) use READ_CORE_RAM for older versions of RetroArch, and READ_CORE_MEMORY for newer. So UDP-based tools were able to read the ROM data successfully before, but cannot in the current version of RA.

I understand it is intended that READ_CORE_MEMORY be the preferred request going forward. Still, I dug into the history to see how READ_CORE_RAM succeeded previously:

- The READ_CORE_RAM implementation in 1.9.0 and prior was specifically [using the memory descriptors](https://github.com/libretro/RetroArch/blob/v1.9.0/cheevos/fixup.c#L238), including honoring the `disconnect` bits, which is what enabled ROM access over UDP for cores that use SET_MEMORY_MAPS.

- The refactor of this implementation, from 1.9.1 to date, does also read the memory descriptors, now in [rc_libretro_memory_get_descriptor()](https://github.com/libretro/RetroArch/blob/600a3365ea3337bc6f8f0be25b82c6573e1781b1/deps/rcheevos/src/rcheevos/rc_libretro.c#L329), but **applies the disconnect bits only to the start address** of each region at init time, rather than to every requested address. So I expect it would experience the same issue.

- That said, READ_CORE_RAM no longer accepts SNES ROM addresses anyway in 1.9.1+, since the table `_rc_memory_regions_snes` does not describe a SNES ROM region, only SNES RAM. However, I'm not sure of all the callers upon the cheevos data for various consoles that may also use disconnect bits. So I wanted to point out that there may be a similar regression in the cheevos implementation.

**Comment by Jamiras** [comment] 2022-02-24 18:18
As far as I know, the only achievement uses that use the disconnect map are the NES mirror RAM and Gameboy echo RAM, both of which share a singular memory pool at multiple addresses. The problem you're reporting with SNES is the different, where a singular memory pool is broken up over multiple addresses.

I agree that changes need to be made to support that behavior in `rc_libretro_memory_get_descriptor`, but I don't believe anything is currently affected by it. I was going to do those changes first as I expect `command_memory_get_descriptor` to reflect the changes made to `rc_libretro_memory_get_descriptor`. It's basically a duplicated function already, but because `rc_libretro_memory_get_descriptor` is a library function that's only included if `HAVE_CHEEVOS` is true, it has to be duplicated.

As such, it'll probably be easier to just let me do it. But if you really want to give it a try, go for it.

**Comment by strotlog** [comment] 2022-02-24 18:25
That makes sense, I'll leave the fix to you Jamiras, with many thanks. Just @ me here, or reach out on discord, if you'd like me to test a code patch!

**Closed** 2022-02-25 17:23 UTC

**Comment by strotlog** [comment] 2022-02-26 00:29
Confirmed that the merged fix:
- allows me to read full ROMs' contents correctly over UDP, and
- re-enables using Archipelago Multiworld + Super Metroid + RetroArch + bsnes-merury core.

Thank you for the discussion and fix Jamiras!! You've been incredibly helpful to work with.
