### ISSUE TITLE
Strange input behavior with DualShock 3 clone

### ISSUE THREAD

**Issue by heuripedes** [libretro/RetroArch#3988] opened 2016-11-12 14:24 UTC
I'm having this strange issue where some keys and buttons work and others don't depending on the driver I use, whether a core is running and even whether I have powered the joypad on by pressing the PS button:

* If I use udev/linuxraw I can't use the Up, Left, Enter, Backspace or Escape keys until I press the PS button. When I load a game Escape and function keys don't work. The only way to quit RetroArch is to close the window and I'm unable to save/load states.

* If I use SDL2 keys always work regardless of the joypad power state but analogs don't work when in-game.

I can reproduce this behavior with all cores.

I have checked the input drivers and they are all receiving input events when I press buttons/keys or move the analogs. My guess is that the input is being lost at a higher level of the input stack or maybe being transformed into some unbound shortcut, but I've been unable to confirm either case.

```
OS: Archlinux
Kernel: Linux 4.8.7-1-ARCH #1 SMP PREEMPT Thu Nov 10 17:22:48 CET 2016 x86_6
Version: git
systemd (provides udev): 231
SDL2: 2.0.5
Joypad: 054c:0268 Gasia Co.,Ltd PS(R) Gamepad  (Sony Corp. Batoh Device / PlayStation 3 Controller)
```

**Comment by heuripedes** [comment] 2016-11-12 14:30
Seems to be related to the joypad driver.

* If I use the udev input driver with sdl2 joypad driver function keys and Esc work in game.
* If I use the udev joypad driver I can't open the menu even if I bind a joypad button to the "toggle menu" shortcut.

**Comment by lasers** [comment] 2016-12-02 12:25
(udev/linuxraw) Confirmed. https://github.com/libretro/RetroArch/issues/3928

_Wild Guess!_
* It might had something to do with that "Left analog stick controls the menu now" changes last month because it'll gimp the keyboard (bad controller axes at startup + deadzone?).

_Home Remedy._ 
* Stay consistent. Always activate the controller after plugging and/or restarting machine. You may be not aware testing things with your controller inactivated so you're potentially getting mixed results. For me, my controller was out of my way, but still plugged in... leaving me with no RetroArch for two days.

_Possibly Related..._
* Not activating the controller early... either before you start RetroArch or a video game could result in saving either RetroArch or a video game with a slightly different controller config? https://github.com/libretro/RetroArch/issues/3958#issuecomment-260114594

**Comment by coreyoconnor** [comment] 2018-09-02 23:55
For the historical record: I am still able to reproduce this issue. I have both a first party and third party controller. Can confirm only third party controller is effected. Restart/Careful activation of the controller makes no difference.

I haven't tried changing any options related to "Left analog stick controls the menu". Haven't tried much in the way of debugging. Since I have a first party controller I just use that XD That said, is there a "log all input events"? I'm happy to log the same input with both for comparison.

**Comment by orbea** [comment] 2018-12-27 01:10
Every single third party ds3 controller I have tried has been broken with every program and with a real PS3 in one way or another. I don't think there is anything that can be done here other than to not buy poorly made hardware so I am going to close this issue.

If anyone wants to take this further it needs to be fixed at the OS or hardware level.

**Closed by orbea** 2018-12-27 01:10 UTC
