### ISSUE TITLE
Have all plugged controllers control the menu

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#3337] opened 2016-08-05 11:18 UTC
Requested by some users on IRC.

Shouldn't be too difficult to implement. And it's convenient when controllers are accidentally swapped by the OS or RA.

**Comment by duduke** [comment] 2016-08-06 18:02
Should also be useful for when RetroPadRemote is used.

**Comment by fr500** [comment] 2016-08-06 18:03
RetroPad remote for P1 can control the GUI already.
TBH I like that only P1 can control the GUI

**Comment by markwkidd** [comment] 2016-08-08 22:34
FWIW I'm in favor of this change. I have a dual SNES->USB adapter that RetroArch likes to swap in terms of Player 1 and 2 between reboots (and sometimes between core launches).

I think the default behavior should be 'All Controllers Control the GUI' and the optional second mode is 'Don't Trust Players Other Than #1 with the GUI'

**Comment by fr500** [comment] 2016-08-09 00:26
RetroArch doesn't swap them.
The OS enumeration dictates the controller order.

**Comment by markwkidd** [comment] 2016-08-09 00:29
Good catch, I should have said "Lakka" instead of "RetroArch." Edited.

**Comment by shinra358** [comment] 2016-08-09 18:33
Hopefully this is optional in the menu and not have all be defaultly on with no other setting.

**Comment by Dagnillo** [comment] 2016-08-12 12:08
Yes it should be optional, I always have problems where my Bluetooth controller turns off and then gets reassigned.  I then lose control of RA.

**Comment by meleu** [comment] 2016-08-28 05:33
I think this issue is somehow related to that one #3014 I opened in May.

**Comment by fr500** [comment] 2016-08-28 06:08
Hmm
I just connected my XBOX 360 controller (wired) and it works fine out of the box.
I also deleted the profile, started with another controller, went to user 2 and selected bind all, I was able to find correctly and the control wasn't handed to it.

Video:
https://goo.gl/photos/5XEsgzzg2DVVp1aj7

**Comment by Dagnillo** [comment] 2016-08-28 22:56
This wouldn't be necessary if gamepad connection problems weren't so prevalent.  I'm fine with fixing one or the other.

**Comment by fr500** [comment] 2016-08-28 22:58
I already showed you it working with no issues and no custom setup, just removed the autoconf to prove it and did it. Not sure what else do you want.

I was a shield portable not the atv but I reckon it should work exactly the same.

**Comment by Dagnillo** [comment] 2016-08-28 23:04
> I already showed you it working with no issues and no custom setup, just removed the autoconf to prove it and did it. Not sure what else do you want.

I was a shield portable not the atv but I reckon it should work exactly the same.

Not sure if you're referring to me?  I did resolve the 360 connection issues, but there are other problems such as #3414.  Basically the only reason I personally have to enable menu control on all controllers is to resolve when problems like this arise.

**Comment by twinaphex** [comment] 2016-09-05 15:52
Addressed by bparker06's PR

**Comment by magwe** [comment] 2016-10-31 18:35
Could we reopen this issue? I can only navigate with player 1's input device even with all_users_control_menu = "true".

**Comment by meleu** [comment] 2016-10-31 18:38
@magwe pkease detail your system and ways to reproduce your issue.

**Comment by lasers** [comment] 2016-10-31 18:48
@magwe  The messy 'all_users_control_menu' hack seems to be removed for now. https://github.com/libretro/RetroArch/commit/d246d320c7541e35a2bee005ce465c17d8a59a8d

**Comment by magwe** [comment] 2016-10-31 18:52
Ubuntu 16.04,  retroarch version: PPA: libretro/testing
connected input devices right now: keyboard, Xbox360 Wireless x2, Custom arcade sticks x2 (DragonRise Inc.   Generic   USB  Joystick  ), NES clone USB gamepad.

retroarch.cfg contains
all_users_control_menu = "true".
menu option "All Users Control Menu (ON)"
changing these values have no effect

UI can be navigated using keyboard or game controller assigend to player 1.
Changing "User 1 Device Index" make the gamepad lose control and a different gamepad needs to be used.

Which gamepad that is assigned to "User 1 Device Index" is guess work because there is no indication, but that is a separate issue that I will file.

**Comment by bparker06** [comment] 2016-10-31 18:55
@lasers It was refactored back in as commit 2a0dba3 in a platform-independent way.

**Comment by magwe** [comment] 2016-10-31 18:57
@lasers OK  I will have to keep a lookout for that merge.    Will check out that branch actually..  there are a number of input inprovements that I would like to suggest (and maybe implement myself ..)

**Comment by bparker06** [comment] 2016-10-31 19:03
And @magwe just FYI that menu_input branch was already merged in.

**Comment by lasers** [comment] 2016-10-31 19:04
Confirmed with 0a637cf -- with Xbox360 (1) and PS3 controller (2).

**Comment by bparker06** [comment] 2016-10-31 19:08
@lasers Please don't add more hardcoded English messages, we are trying hard to get rid of all of those so that they can be translated properly.

Thanks

**Comment by magwe** [comment] 2016-10-31 19:27
My retroarch wasn updated to latest ubuntu/testing.   The feature seems to work now!

**Comment by magwe** [comment] 2016-10-31 19:37
OK, so it is still buggy...  All controllers can controll the UI initially, but if I change "User 1 Device Index" the current USER 1 device looses controll, but the other gamepads can still navigate the UI.

**Comment by meleu** [comment] 2016-11-18 13:28
Could this issue be reopened?

The `all_users_control_menu` (from #3499 PR) doesn't make "**all plugged controllers** control the menu", as the title of this issue says. Actually it just makes "**all controllers bound to a player** control the menu".

It still can bring some unpleasant situations like I detailed in #3014 (the `all_users_control_menu` decreases the chance to make it happen, though).

**Comment by dankcushions** [comment] 2017-07-10 22:10
this doesn't appear to be working on latest master. the setting doesn't do anything. can we re-open?

**Comment by dankcushions** [comment] 2017-07-11 09:04
Thanks :+1: 

Could someone else confirm this? I've never seen this working before so perhaps I'm doing it wrong. My test was:
1) Build master
2) set `all_users_control_menu`
3) launch game
4) confirm option is set via menu
5) try P2: no menu movement
6) try hotkeys on P2: no effect

I'm using the UDEV driver on Raspbian (RPI3), btw. I notice this is separately coded in every input driver so this may be a UDEV issue.

I could try and bisect later.

**Comment by twinaphex** [comment] 2017-07-11 09:16
This indeed no longer works. @bparker06 might be able to do a reimplementation of it since he originally added the feature.

**Comment by meleu** [comment] 2017-07-23 18:28
I saw this line in [CHANGES.md](https://github.com/libretro/RetroArch/blob/master/CHANGES.md):

- INPUT: Fix 'All Users Control Menu' setting

and noticed that @bparker06 made [this commit](https://github.com/libretro/RetroArch/commit/42e56c84321350990afe3d825677b8bdfc2e29fa) saying that `all_users_control_menu` is fixed. Is it already fixed?

**Comment by dankcushions** [comment] 2017-07-24 15:52
Tried with latest master. No change.

**Comment by meleu** [comment] 2017-07-24 16:42
Maybe that message should be removed from `CHANGES.md`...
As far as I understood that option wasn't fixed, but removed.

**Comment by dankcushions** [comment] 2017-07-24 17:08
it's not removed - it's still there.

**Comment by meleu** [comment] 2017-07-24 20:20
it (`all_users_control_menu` option) is not removed, and neither fixed. :)

My suggestion is to remove that message from `CHANGES.md`. I'm doing it right now and submitting a PR.

**Comment by bparker06** [comment] 2017-07-24 21:45
I just tested the option and it's working fine for me to control the menu with two gamepads.

**Comment by dankcushions** [comment] 2017-07-24 21:56
interesting! my test procedure is above: https://github.com/libretro/RetroArch/issues/3337#issuecomment-314381420

can someone else try? perhaps it's udev-specific?

**Comment by bparker06** [comment] 2017-07-24 22:02
@dankcushions I tested successfully with both udev and x drivers. The hotkeys probably still aren't working yet (I think I know what needs to be fixed but just haven't gotten around to it), but menu movement certainly works here.

**Comment by orbea** [comment] 2017-07-24 23:33
This issue is related so I will link it here. It will be nice if this option works well again. The multiplayer aspects of RA I consider to be an important feature.

https://github.com/libretro/RetroArch/issues/5127

**Comment by dankcushions** [comment] 2017-07-27 12:19
@bparker06 I just rebuilt and re-tested and I still can't get P2 to operate the menu. No idea what could be different between our setups! I'm triggering RGUI with the menu hotkey combo, if that makes a difference. Can someone else please test this?

**Comment by BenLinus2** [comment] 2017-08-01 22:23
This is broken I tested it last night for sure can somebody please fix this, or give pointers howto fix. I am very new here but willing to a shot at it.

**Comment by fr500** [comment] 2017-08-02 01:26
Do you have unified menu controls enabled?

**Comment by eddywebs** [comment] 2017-08-07 21:36
> 

Do you have unified menu controls enabled?
--

Whats that @fr500 ? I can give it a shot tonight.

**Comment by eddywebs** [comment] 2017-08-07 21:37
Actually nvm I have `menu_unified_controls = "true"`

**Comment by orbea** [comment] 2017-08-08 15:19
Is there a difference if its disabled?

**Comment by eddywebs** [comment] 2017-08-09 02:09
> Is there a difference if its disabled?

Nopes tried both `menu_unified_controls = `true and false no hot keys on second controller aka cannot exit if controller 1 disconnects
 
The `all_users_control_menu =true` was set both times.
Would it make sense to revert the commit on this file ? I am pretty sure it used to work at one point.

**Comment by JacobAL** [comment] 2017-12-07 13:27
Upgraded to 1.6.9 yesterday and this still doesn't work for me.

**Comment by hizzlekizzle** [comment] 2020-04-30 23:17
I just tested the "all users control the menu" option with udev and it worked fine.

**Comment by dankcushions** [comment] 2020-05-02 12:24
just recreated my test case @ https://github.com/libretro/RetroArch/issues/3337#issuecomment-314381420 - still an issue for me.

**Comment by hizzlekizzle** [comment] 2020-05-02 14:25
Weird. Must be something ARM/RPi-specific then, I guess.

**Comment by Littlemac123** [comment] 2020-11-19 16:33
how is this feature not implemented yet? 
I would love it for my Nintendo switch because switch root Ubuntu joycon driver is virtually always pluged in, and retroarch loves to disable player one when you plug in a controller for Port 1 temp like a pro controller then remove it and then boom I'm locked out of retroarch unless I get a keyboard to fix it for joycons...

or at the very least add a setting so whenever retroarch sees only 1 controller pluged in it auto sets it to player one

**Comment by blacklat** [comment] 2021-03-28 15:47
the retroarch is magnificent but it is these little details and others that make it comparable to shit. Why did they disable that shit? This is an idiot thing

**Comment by hizzlekizzle** [comment] 2021-03-28 18:25
@blacklat the implementation was buggy and broke a lot of stuff, unfortunately. Aside from that, please keep it constructive and professional in the issue tracker.

**Comment by blacklat** [comment] 2021-03-28 21:57
In the middle of the game, the gamepad battery runs out and i have to go to the android tv dashboard and open the app settings and force the retroarch to stop, this option has existed before and it worked perfectly. Everyone knows that you shouldn't touch where everything is right which always ends up causing a problem.
I love retroarch but my indignation is with this type of problem that is very common in projects that involve a lot of people, there is always someone who does shit and shits the whole shit.

**Comment by gouchi** [comment] 2021-10-31 08:33
This [PR](https://github.com/libretro/RetroArch/pull/13173) should help to fix this issue.

**Closed** 2022-09-03 02:45 UTC
Labels: followup: enhancement
