### ISSUE TITLE
[Windows] PS4 controller will not reconnect

### ISSUE THREAD

**Issue by Kevinmk760** [libretro/RetroArch#13067] opened 2021-10-03 21:18 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When my PS4 controller becomes disconnected (connected to PC via USB cord) it does not reconnect once connection is re-established

### Expected behavior

Retroarch should reconnect to controller automatically

### Actual behavior

Controller does not reconnect. I am forced to close content to go back to the main menu in order for the connection to be established again

### Steps to reproduce the bug

1. Load any game
2. Disconnect control via USB cable (Retroarch states device is disconnected)
3. Plug controller back in 
4. Device I will not reconnect
5. Close content 
6. When main menu loads, Retroarch connects to device again

### Bisect Results

When I updated to 1.9.10 nightly. I Confirmed this does not happen on 1.9.9 stable or 1.9.10 stable 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information
Issue is occurring on 1.9.10 nightly

- OS: [WIN10]
- Compiler: [In case you are running local builds]

**Comment by martyfuhry** [comment] 2023-09-18 15:56
Duplicate of https://github.com/libretro/RetroArch/issues/14524?

**Comment by sonninnos** [comment] 2023-09-18 18:41
Pretty sure such Windows issues no longer exist. But with that ancient version, sure.

**Closed** 2023-09-18 18:41 UTC
Labels: platform: windows
