### ISSUE TITLE
RetroArch doesn't show special characters in 1.5

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#4796] opened 2017-04-01 20:34 UTC
## Description

RetroArch 1.5, at least for windows, have problems showing some characters, like: á é í ó ú
It works OK in 1.3.6

### Expected behavior

Show all characters.

### Actual behavior

Show a square: [] and can affect next characters. Here you can see the behaviour: http://imgur.com/SM4bNRL

In 1.3.6 it shows OK: http://imgur.com/mP6v9XZ

### Steps to reproduce the bug

Create a folder with accents, for example: Emulación

### Bisect Results

¿1.4?

### Version/Commit
- RetroArch: Mar 9 2017 / 51581e1

### Environment information

- OS: Windows 10

**Comment by mac1202** [comment] 2017-04-11 17:57
I have the same issue on linux but only with vulkan driver. In opengl they are properly displayed can you test if it s the same thing for you ?

**Comment by bparker06** [comment] 2017-04-11 21:02
@Palatosino Do you have a custom menu font set? If yes can you try the default one? If not can you try updating your assets? The box character means that font is simply missing that character, but RA does support Unicode characters.

@mac1202 Judging from the screenshot it doesn't look like he's using vulkan, but I would guess that the vulkan font renderer does not currently support Unicode like the GL driver does. @aliaspider would know.

**Comment by Palatosino** [comment] 2017-04-14 15:36
@bparker06 I didn't know that I can change the menu font, so no. I didn't changed the menu font.
I updated assets (online updater -> update assets) and no result.
I moved "retrotarch.cfg" and it do nothing (well, disconfigured all, but nothing the squares continue).

I tested something: I put my interface in "Spanish" and I see special characters, but not in the file explorer.
So the menu contains special chars (No core = Sin núcleo, with special char) but the file explorer shows the same behaviour, the path in the top too and retroarch notifications with paths ("Creating configuration in PATH") too.

Is posible that this is a problem with paths with special characters?

**Comment by bparker06** [comment] 2017-04-14 15:41
@Palatosino Ah yes I forgot, unicode paths are not working correctly in windows because windows uses utf16 for the filenames while RA uses utf8 internally. I made some changes a few months back that fixed this, but it broke other things too so it had to be reverted. It is certainly something that can be revisited later though, but for now there isn't a simple solution on windows yet (Linux works fine though).

**Comment by rootfather** [comment] 2017-04-16 05:34
I have a similar issue on Windows when using the vulkan driver. All special characters in the GUI are broken.

**Comment by bparker06** [comment] 2017-09-20 13:20
duplicate of #5019

**Closed by bparker06** 2017-09-20 13:20 UTC
