### ISSUE TITLE
Accessibility & AI Service menu's now missing on RetroArch 1.16.0 Android

### ISSUE THREAD

**Issue by Jetup13** [libretro/RetroArch#15718] opened 2023-09-21 17:38 UTC
## Description

Accessibility & AI Service menu settings no longer appear on Android as of 1.16.0. There seems to be no mention of it in the [changes readme](https://github.com/libretro/RetroArch/blob/master/CHANGES.md) so I'm not sure if they were just removed from Android or a possible oversight. Works fine on Windows RetroArch builds. Haven't tested Linux

### Expected behavior

Accessibility settings is supposed to appear once enabled

### Actual behavior

Both `settings_show_ai_service = "true"` & `settings_show_accessibility = "true"` seemed to be specifically ignored on Android builds

### Steps to reproduce the bug

1. Enable Accessibility & AI Service menus

> RetroArch > Settings > User Interface > Menu Item Visibility > Settings > Enable show Accessibility & Show AI Service

### Bisect Results

The start of 1.16.0 stable or somewhere around 1.15.0 nightly builds when menus were starting to get consolidated together.

### Version/Commit

- RetroArch: 041ae30

### Environment information

- Android 12 (Also tried Android 9 & 11)

**Comment by superruzafa** [comment] 2023-10-03 16:46
The same for the Switch version 1.16.0.

Going back to 1.15.0 solves the problem.

**Comment by hizzlekizzle** [comment] 2023-10-03 20:17
I *think* this was fixed in the later hotfix releases (1.16.0.1+). Could you verify if it shows up in a nightly build?

@sonninnos , you had looked into this one, right?

**Comment by sonninnos** [comment] 2023-10-03 20:26
I only confirmed that it happens on my phone too, but based on the code it can only be the case if `HAVE_ACCESSIBILITY` ifdef is not set, and I have no idea how that can suddenly be..

**Comment by LibretroAdmin** [comment] 2023-10-31 17:45
Can you try tomorrow's APK nightlies? I noticed that ```HAVE_ACCESSIBILITY``` was not defined for Android, so I added it -
https://github.com/libretro/RetroArch/commit/249702a2e91e0ea82bf12f98c781399a2476bf1d

**Comment by Jetup13** [comment] 2023-11-01 00:06
Yup, it's back. Tried out the latest nightly 2a51e66 and Accessibility settings is back

**Closed** 2023-11-01 00:12 UTC

**Comment by LibretroAdmin** [comment] 2023-11-02 00:01
@Jetup13 So things work again for you?

**Comment by Jetup13** [comment] 2023-11-02 04:29
@LibretroAdmin  The menu appears again but there's a few issues.

* AI service options don't seem to work as they used to. Windows & Android both have this issue

Might be related to the commit 274d47f. Seems like it only wants to translate as image regardless of settings. Used ztranslate by itself. It works as intended when used with VG Translate but Android users can't use it.

* Text to speech menu navigation does not work on Android

Not sure if this ever worked on Android. 

Should I create a separate issue for this?

**Comment by LibretroAdmin** [comment] 2023-11-06 07:44
I'm pretty sure Text to Speech never worked on Android before.

@BarryJRowe Any thoughts?

**Comment by LibretroAdmin** [comment] 2023-11-06 18:52
@Jetup13 Check tomorrow's APKs to see if this commit solved smth on your end -
https://github.com/libretro/RetroArch/pull/15879

**Comment by Jetup13** [comment] 2023-11-07 08:06
Seems like it fixed some options

Here's what's working now:

* Image Mode 
* Speech Mode
* Text Mode

Here's what's not working:

* Narrator Mode
* Text + Narrator Mode (Narrator portion does not work)
* Image + Narrator Mode (Narrator portion does not work)

Honestly not sure what's the difference between Speech Mode & Narrator Mode. Or is Narrator Mode linked to the Text to Speech RetroArch feature (which doesn't work on Android)? I should note I've only tested on RetroArch android right now with ztranslate.

**Comment by viachaslavic** [comment] 2023-11-13 07:37
Narrator for Android [is currently not implemented](https://github.com/libretro/RetroArch/blob/f091b5a9e9475255e5efaded5f95c9750fdfe15e/frontend/drivers/platform_unix.c#L2921)

This should be displayed in the log (if __frontend logging level__ is set to 0 or 1)
```log
[NFO] Platform not supported for accessibility.
```

**Comment by watchinofoye** [comment] 2024-02-29 08:26
> The same for the Switch version 1.16.0.
> 
> Going back to 1.15.0 solves the problem.

The problem is still there on the Switch version 1.17.0. No Accessibility nor AI Service.
