### ISSUE TITLE
[Retroachievemen][XMB]Crash exiting game when enabled-Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4231] opened 2016-12-12 14:25 UTC
tested with genesis and nes roms. 

how to replicate? (retroachievement-all ON, properly logged in)
1. load rom(nes with quicknes or fceumm, genesis with picodriv)
2. view game achievements
3. close game

**Comment by RobLoach** [comment] 2016-12-12 15:51
Confirmed...

1. Enabled Achievements
1. Added User account
1. Loaded the rom witht QuickNES
1. Opened menu
1. Viewed Achievements
1. Close
1. Got a segfault...

```
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [PulseAudio]: Pausing.
[1]    30690 segmentation fault (core dumped)  ./retroarch --verbose
```

**Comment by fr500** [comment] 2016-12-12 16:37
I don't get a crash on windows at least.

**Comment by retro-wertz** [comment] 2016-12-12 17:02
if its not happening the 1st time, do it again 2-3 times without closing
retroarch

how to get the crashlog? --menu --verbose does not show anything related on
last lines

**Comment by twinaphex** [comment] 2016-12-13 02:37
@leiradel Is this something you would like looking into?

**Comment by leiradel** [comment] 2016-12-13 19:48
I believe it's related to the menu and not something in `cheevos.c`.

**Comment by fr500** [comment] 2016-12-15 01:30
We would need a backtrace at least

**Comment by retro-wertz** [comment] 2016-12-15 01:45
how to do that?

**Comment by retro-wertz** [comment] 2016-12-15 02:14
-its not necessarily "when enabled" that causes the issue. you can still open rom, close rom, move to another rom if achievemtents are ON(including hardcore mode) and logged in. it's when you visit or see Achievement Lists(non hardcore o hardcore) after successfully loading rom, this will 99% crash retroarch when you close rom 

-how to get mode debug info? normal debug does not show anything related to crash

**Comment by twinaphex** [comment] 2016-12-15 11:32
I can't reproduce this at all.

**Comment by retro-wertz** [comment] 2016-12-25 01:08
retroarch.exe - http://pastebin.com/6pSib5sL
retroarch_debug.exe - http://pastebin.com/H33DTuFu

**Comment by leiradel** [comment] 2016-12-26 12:41
@retro-wertz Since we're having trouble to reproduce the issue, could you put a breakpoint at cheevos_get_description and step until line 2825 (where strlcpy is) and check these variables?

* *desc
* cheevos_locals

Thanks

**Comment by retro-wertz** [comment] 2016-12-26 13:07
@leiradel  how exactly to do that? i see that function in cheevos.c but im not familiar with debugging tools., nor make the result appear at least in debug window.

**Comment by retro-wertz** [comment] 2016-12-27 03:15
@leiradel 
still not sure how to step trace this or get the variables, but hope this gdb full backtrace will give some hints(thanks radius for the help)

[http://pastebin.com/VBMbQLFC](url)

thanks.

**Comment by leiradel** [comment] 2016-12-28 23:41
@retro-wertz It doesn't really add anything new, but it won't take much more than what you already did to get the info:

```
$ gdb retroarch
(gdb) run
<when it crashes>
(gdb) bt full
<get the frame number of cheevos_get_description and use below (should be 1)>
(gdb) frame 1
(gdb) print *desc
<value is printed>
(gdb) print cheevos_locals
<value is printed>
(gdb) quit
```

**Comment by retro-wertz** [comment] 2016-12-29 03:08
here :  [http://pastebin.com/iR2w2XZG](url)

**Comment by leiradel** [comment] 2016-12-29 12:54
@retro-wertz Please change your Retro Achievements password, your token is in the output in clear text. I'm sorry about that.

Which game was that?

**Comment by retro-wertz** [comment] 2016-12-29 13:09
thats another thing, the password is not hidden/encrypted in anyway

-my test posted is usually done with Castlevania(USA) (not the Rev A
version), but this issue happens on NES or Megadrive using any of the cores
on any rom as long as it support or has achievements.

**Comment by leiradel** [comment] 2016-12-29 14:29
> thats another thing, the password is not hidden/encrypted in anyway

That's a constraint imposed by Retro Achievements

> my test posted is usually done with Castlevania(USA)

But that crash where you got the values of `*desc` and `cheevos_locals` was with that game?

**Comment by retro-wertz** [comment] 2016-12-29 14:36
"Second Concealed Meat (Wicked Child)" <- Yes  -> Castlevania (USA)

![ra](https://cloud.githubusercontent.com/assets/23315382/21546052/32dc019a-ce17-11e6-829e-59b40e2d5d31.jpg)

**Comment by leiradel** [comment] 2016-12-29 17:58
I'll take that as an yes :)

**Comment by meleu** [comment] 2017-01-04 03:53
I've got the segfault even with retroachievements disabled. I've made two tests **both with `cheevos_enable = false`**:

1. I've just started retroarch with Castlevania/FCEUmm and then pressed the hotkey to exit retroarch (select+start) and then got the segfault.

2. Started retroarch with Castlevania/FCEUmm and then RGUI -> Quick Menu -> Close. It's enough to crash RetroArch with a segfault.

I think it's unrelated with cheevos.

Git version: 2b25704 compiled today (Jan-3-2017) on my Linux Mint.

**Comment by retro-wertz** [comment] 2017-01-04 05:23
it does not crash when running in rgui, yours is probably an unrelated
issue here.

**Comment by retro-wertz** [comment] 2017-02-06 12:18
up for this. i though that this was just a windows issue, turns out this happens also in linux(ubuntu 16.10)

**Comment by leiradel** [comment] 2017-02-07 10:19
@retro-wertz can you get some additional information for me please?

    $ gdb retroarch
    (gdb) run
    <when it crashes>
    (gdb) bt full
    <get the frame number of cheevos_get_description and use below (should be 1)>
    (gdb) frame 1
    (gdb) print *desc
    <value is printed>
    (gdb) print cheevos_locals
    <value is printed>
    (gdb) print cheevos[desc->idx]
    <value is printed>
    (gdb) quit

Thanks.

**Comment by retro-wertz** [comment] 2017-02-07 11:30
just to remind how i replicate the issue:
preparation: initially setup retroachievement login and password make sure you can connect. enable test and hardcore achievements:

1. run retroarch
2. load nes game with fceumm
3. press quick menu 
4. view Achievement Lists (Hardcore)
5. if no list is seen, bug wont appear. close game and start step #2
6. if list is seen, go back to Quick Menu and choose Close Content
7. this should 99% cause a "Segmentation fault (core dumped)" error!

backtrace -> https://hastebin.com/cudubaqebu.bash

this does not happen with NES only, or fceumm. Any system and/or core that has retroarchievement support has this segfault issue. Test and Hardcore achievements are also not necessary as it will still cause segfault with them off.

thanks.

**Comment by leiradel** [comment] 2017-02-08 19:49
For reasons unknown, `cheevos_get_description` is called after `cheevos_unload` is called, and since the achievements have already been deallocated, their memory contains garbage which causes the crash.

Fixed in https://github.com/libretro/RetroArch/pull/4596 although a proper fix is to avoid `cheevos_get_description` being called after the content is closed.

With this fix, the menu appears empty after the content is closed.

**Comment by retro-wertz** [comment] 2017-02-09 11:49
works great. no more crash and achievements still working. time to finish
some more rewards.

thanks.

**Comment by meleu** [comment] 2017-02-09 13:15
@retro-wertz then you can close this issue, right?

**Comment by retro-wertz** [comment] 2017-02-09 13:48
how to close my email?

**Closed** 2017-02-10 07:13 UTC
Labels: bug: major, followup: needs info or confirmation
