### ISSUE TITLE
[Android] Fingerprint reader activation bound to netplay start despite no key being assigned to it

### ISSUE THREAD

**Issue by lugia19** [libretro/RetroArch#10071] opened 2020-01-27 12:56 UTC
###Description

Touching the fingerprint sensor on my Xiami Pocophone F1 toggles netplay. This causes crashes in certain cores such as VBA next. There is no key/button bound to netplay toggle.

### Steps to reproduce the bug

Simply touching the fingerprint sensor makes the "netplay will be started when a game is started" message appear. If in game (I have only tested this on VBA next so far) it causes a crash.

### Version/Commit

- RetroArch: f425d8d
### Environment information

- OS: Lineage OS 16

**Comment by FreakMegalodon** [comment] 2020-02-13 02:13
Same with Redmi Note 7 (lavender), Pixel Experience 10, Psx rearmed

**Comment by TaylorLewis** [comment] 2020-08-16 18:15
Same on my Xiaomi Pocophone F1 with LineageOS. Starts netplay if in menu. Instant crash if running game.

Seems to be a Xiaomi phone problem?

**Comment by WolfH0wl** [comment] 2020-10-05 18:18
Same on Xiaomi Redmi 7, AOSP extended, mgba.

**Comment by KawaiiDinosaur** [comment] 2021-03-01 02:42
Able to reproduce on a Xiomi Poco F1 running PixelExperince Android 11

**Comment by dontsnm** [comment] 2021-08-05 13:09
Same here. Using Android 11 on Poco X3 Pro. On game, touch the fingerprint sentor, Retroarch crash. On unloaded core, it shows Start netplay.

**Comment by leandrodeassis** [comment] 2022-05-27 19:54
Still having this issue. Xiaomi Mi 9 (cepheus) on PixelExperience 12.1.

Any way to workaround this?

**Comment by markklarsen** [comment] 2022-11-20 16:03
Same here Motorola x30 edge ultra

**Comment by ViniciusALima** [comment] 2023-03-20 01:02
Same here on a Pixel 4a, Android 13, RetroArch version 1.15.0. Touching the fingerprint reader brings up Netplay and crashes the mGBA core.

**Comment by Wattle-bird** [comment] 2023-07-07 09:22
Same as ViniciusALima, I'm am experiencing this on a Pixel 4a with RetroArch 1.9.12

I have a suspicion for the cause. Setting Netplay to a button lead to the fingerprint reader triggering Close Content, which is the second hotkey that's not bound by default. I suspect it is launching whatever the first unbound hotkey is.

As a workaround, I set a keyboard key to Hotkey Enable, and the issue no longer occurs.

**Comment by calichii** [comment] 2023-08-08 10:46
Same here. 
I tried to fix it assigning al the hotkeys to some key. But then fingerprint is used to fire L button.  
This bug is so annoying that I can not use RetroArch on my Android phone. 
BTW the issue is duplicated on Github (https://github.com/libretro/RetroArch/issues/10822) and also on https://forums.libretro.com/t/retroarch-keeps-starting-netplay-automatically/32249

**Comment by Radeoxx** [comment] 2023-09-26 16:06
Same here, Poco F1, the most little accidental touch to fingerprint sensor and everything crashes on retroarch if in game.

if not in game it will keep sayaing retroarch it's not responding till I close it (it do respond).

It's almost impossible to avoid accidental touches on a portable device.

**Closed** 2024-01-25 10:46 UTC
Labels: platform: android, android phone: xiaomi mi 9
