### ISSUE TITLE
Thumbnails displayed with wrong colours on Amazon Fire TV Stick.

### ISSUE THREAD

**Issue by modeler** [libretro/RetroArch#7254] opened 2018-09-19 14:33 UTC
## Description
RetroArch works fine on the Fire TV Stick when installed from the APK. All thumbnails in the menu (box art and screenshots) are displayed with the wrong colours. They look fine on other Android devices.

### Expected behavior
Images should appear as they do on other Android devices and the Windows / Linux ports of RetroArch.

### Actual behavior
Images appear to have their red and blue channel values switched. Reds appear blue, blues appear red, yellow appears cyan and cyan appears yellow. The green channel appears normal.

### Steps to reproduce the bug

1. Copy the RetroArch.apk file to the Fire TV Stick (Remote Manager i.e. FTP server in ES File Explorer works well for this)
2. Install the APK
3. Launch RetroArch and download a core
4. Launch any content and take a screenshot
5. Observe the Screenshots list in the XMB menu

### Bisect Results
Tested on 1.7.4, I haven't tried any earlier builds.

### Version/Commit
1.7.4

### Environment information
- OS: Android

**Comment by modeler** [comment] 2018-09-20 21:46
See [this link](http://www.tootill.co.uk/libretro/issues/xmbcolours.jpg) for an example of this issue.

I was able to work around this by running all of the thumbnails through Imagemagick prior to uploading them to the Fire TV Stick. The following script will flip the red in the blue channel and the blue in the red channel, making the image display correctly (bash shell):

```
$ convert thumbnail_old.png -color-matrix \
"0.00 0.00 1.00 0.00 0.00 0.00 \
 0.00 1.00 0.00 0.00 0.00 0.00 \
 1.00 0.00 0.00 0.00 0.00 0.00 \
 0.00 0.00 0.00 1.00 0.00 0.00 \
 0.00 0.00 0.00 0.00 1.00 0.00 \
 0.00 0.00 0.00 0.00 0.00 1.00" \
thumbnail_new.png
```

**Comment by twinaphex** [comment] 2018-10-15 05:31
Same issue as on Raspberry Pi.

**Comment by twinaphex** [comment] 2018-10-17 06:28
I am hoping @kivutar can look into this, it is likely that if he fixes it on the RPI side, it would work here as well.

**Comment by mamedesigor** [comment] 2018-11-10 05:42
> See [this link](http://www.tootill.co.uk/libretro/issues/xmbcolours.jpg) for an example of this issue.
> 
> I was able to work around this by running all of the thumbnails through Imagemagick prior to uploading them to the Fire TV Stick. The following script will flip the red in the blue channel and the blue in the red channel, making the image display correctly (bash shell):
> 
> ```
> $ convert thumbnail_old.png -color-matrix \
> "0.00 0.00 1.00 0.00 0.00 0.00 \
>  0.00 1.00 0.00 0.00 0.00 0.00 \
>  1.00 0.00 0.00 0.00 0.00 0.00 \
>  0.00 0.00 0.00 1.00 0.00 0.00 \
>  0.00 0.00 0.00 0.00 1.00 0.00 \
>  0.00 0.00 0.00 0.00 0.00 1.00" \
> thumbnail_new.png
> ```

I have this exactly same problem. Dont know how to fix it.

**Comment by markwkidd** [comment] 2019-01-19 17:51
I believe this issue is a duplicate of https://github.com/libretro/RetroArch/issues/6611 which is a few months older

**Comment by orbea** [comment] 2019-01-19 18:07
Sounds likely.

**Closed by orbea** 2019-01-19 18:07 UTC
Labels: platform: android
