### ISSUE TITLE
[Suggestion] Restore last playlist+game index after content close

### ISSUE THREAD

**Issue by capitaineflam25** [libretro/RetroArch#7526] opened 2018-11-04 19:45 UTC
After closing a game it could be interesting to get back to the playlist where you launch the game with this game selected. So you can continue exploring your games list.

![926007e2-b49c-4eac-bf00-e34d49b69e85](https://user-images.githubusercontent.com/985702/47969035-2ebf9080-e072-11e8-8540-b4534f4cd0a1.jpeg)

**Comment by capitaineflam25** [comment] 2018-11-04 19:45
> With XMB, after closing a game it could be interesting to get back to the playlist where you launch the game with this game selected. So you can continue exploring your games list.
> 
> ![926007e2-b49c-4eac-bf00-e34d49b69e85](https://user-images.githubusercontent.com/985702/47969035-2ebf9080-e072-11e8-8540-b4534f4cd0a1.jpeg)

**Comment by capitaineflam25** [comment] 2018-11-04 19:54
An alternative could be to remember each playlist selected index when navigating left/right.
It would also prevent to lost your current game when you press left or right by mistake when scrolling to a specific game.

**Comment by i30817** [comment] 2018-11-05 01:03
Hear hear. There is also this related bug:
https://github.com/libretro/RetroArch/issues/7456

**Comment by capitaineflam25** [comment] 2018-11-05 06:06
Thanks for pointing that. 
As i'm new to retroarch i didn't realised it was a bug.

**Comment by orbea** [comment] 2018-12-26 20:45
I'm going to close this in favor of issue https://github.com/libretro/RetroArch/issues/5596 which this is more or less a duplicate of.

**Closed by orbea** 2018-12-26 20:45 UTC
