### ISSUE TITLE
[core development] how can i request for the highest glcore context available ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#9131] opened 2019-07-18 22:48 UTC
When requesting for a glcore context in a libretro core, how can i request for the highest glcore context available ?

## Why do i need that ?

I need this in kronos for 2 reasons :
- kronos is available from glcore 3.3, however there are additional features at 4.2 (gpu tesselation), 4.3 (compute shaders) and 4.5 (there are some calls to glTextureBarrier which fixes some shadow issues in specific games)
- when i benchmarked on my computer (i7 2600k + gtx 960 + linux), glcore 4.5 was a bit faster than older contexts, so using the most recent context available makes sense if it can improve performance

## Why can't i do that at the moment ?

people on discord have suggested me several things, however none of that worked consistently.

### 1st method : request a specific context :

```
   glsm_ctx_params_t params = {0};
   params.context_reset = context_reset;
   params.context_destroy = context_destroy;
   params.environ_cb = environ_cb;
   params.stencil = true;
   params.major = 4;
   params.minor = 5;
   params.context_type = RETRO_HW_CONTEXT_OPENGL_CORE;
   if (!glsm_ctl(GLSM_CTL_STATE_CONTEXT_INIT, &params))
      return false;
```
One would expect this code to return false if glcore 4.5 in not available, but as seen in https://github.com/FCare/Kronos/issues/391 it's actually wrong : glxinfo shows glcore 3.3 but RA returned true for glcore 4.2

### 2nd method : not specifying major/minor or specifying 0/0

fails like this :
```
[INFO] Requesting core OpenGL context (0.0).
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.95 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[INFO] [GLX]: GLX_EXT_swap_control_tear supported.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 3840x1080.
[INFO] [GLX]: Window manager is GNOME Shell.
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 960/PCIe/SSE2.
[INFO] [GL]: Version: 4.6.0 NVIDIA 430.26.
[INFO] [GL]: Using Core GL context, setting up VAO...
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shaders]: preset directory: /usr/share/libretro/slang-shaders/presets
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 0.
[INFO] Shader log: 0(2) : error C0201: unsupported version 0
0(4) : warning C7532: global type vec2 requires "#version 100" or later
0(4) : warning C7532: global type vec4 requires "#version 100" or later
0(4) : warning C7532: global type mat4 requires "#version 100" or later
0(4) : error C5060: out can't be used with non-varying tex_coord
0(4) : warning C7532: global variable gl_Position requires "#version 100" or later

[ERROR] Failed to compile vertex shader #0
[ERROR] Failed to link program #0.
[ERROR] GLSL stock programs failed to compile.
[ERROR] [GL]: Failed to initialize shader, falling back to stock.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 0.
[INFO] Shader log: 0(2) : error C0201: unsupported version 0
0(4) : warning C7532: global type vec2 requires "#version 100" or later
0(4) : warning C7532: global type vec4 requires "#version 100" or later
0(4) : warning C7532: global type mat4 requires "#version 100" or later
0(4) : error C5060: out can't be used with non-varying tex_coord
0(4) : warning C7532: global variable gl_Position requires "#version 100" or later

[ERROR] Failed to compile vertex shader #0
[ERROR] Failed to link program #0.
[ERROR] GLSL stock programs failed to compile.
[ERROR] [GL]: Shader initialization failed.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
```

### 3nd method : using a core option to set opengl version

Not user friendly, but it does the work until i find a better solution

### 4th method : specifying 3/0 as major/minor ?

Anyone know if it is working consistently ? I noticed this while doing some tests, that was a random try on the basis that glcore3.0 doesn't exist, it seemed to work, but isn't it a weird solution ?
Edit : actually, while `RETRO_HW_CONTEXT_OPENGL_CORE` is requested, this method returns a glcompatibility context

**Comment by orbea** [comment] 2019-07-19 00:50
I'm not sure how, but maybe you can use beetle-psx as an example? It uses a `4.5` core context here.

**Comment by barbudreadmon** [comment] 2019-07-19 06:19
@orbea On my machine, it's requesting and getting a glcore3.3 context : 
https://github.com/libretro/beetle-psx-libretro/blob/3a3e397ca61a8c221f85d706d4536420a4853745/rsx/rsx_intf.cpp#L2047-L2059

```
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting Vulkan context.
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.3).
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44099.31 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[INFO] [GLX]: GLX_EXT_swap_control_tear supported.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 3840x1080.
[INFO] [GLX]: Window manager is GNOME Shell.
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 960/PCIe/SSE2.
[INFO] [GL]: Version: 3.3.0 NVIDIA 430.26.
```

Also, @m4xw inquired me about this on discord, the error for 2nd method is probably about a RA shader (tested with xmb and ozone), there is no `#version 100` shader in kronos. I'll add prior output to the error message in the first post.

**Comment by LazyBumHorse** [comment] 2019-07-19 10:27
My understanding of why you can't really do that: https://github.com/libretro/RetroArch/issues/8839#issuecomment-495996156

In short: Feature deprecation/removal means newer OpenGL (Core Profile) versions are not necessarily backwards compatible, which is why a specific version has to be requested, that's just how OpenGL rolls these days.

RA could try a range/list of versions that a core supports, but that may be hard to implement, #4804 comes to mind, though I haven't dabbled with context creation, so I can't tell.

BTW, the 2nd method fails because of
https://github.com/libretro/RetroArch/blob/88a668f8a96ccfcdd648ec5e2f5da04e6907e50d/gfx/drivers_shader/shader_glsl.c#L282-L301
this uses the version for the context creation, so it gets shader version 0 which doesn't exist.
That can be fixed by using
https://github.com/libretro/RetroArch/blob/88a668f8a96ccfcdd648ec5e2f5da04e6907e50d/gfx/drivers_shader/shader_gl_core.cpp#L89
(we should really put that in gl_common).

I don't think method 2 is legal though, it might just be a happy coincidence that your video driver on your system decided to return the highest version.

**Comment by barbudreadmon** [comment] 2019-07-19 10:51
Ok, following your comments, 1st method seems like the way to go, maybe we need to figure out why it didn't work properly in https://github.com/FCare/Kronos/issues/391 ?

**Comment by orbea** [comment] 2019-07-19 12:59
My understanding is that the graphics driver should provide the most recent core profile available. What video driver do you have? What does this print?


```
glxinfo | grep Core
```

**Comment by barbudreadmon** [comment] 2019-07-19 13:10
In the issue https://github.com/FCare/Kronos/issues/391, it was returning this : 
```
OpenGL core profile version string: 3.3.0 NVIDIA 340.107
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
```
However the following code was returning true : 
```
glsm_ctx_params_t params = {0};
params.context_reset = context_reset;
params.context_destroy = context_destroy;
params.environ_cb = environ_cb;
params.stencil = true;
params.context_type = RETRO_HW_CONTEXT_OPENGL_CORE;
params.major = 4;
params.minor = 2;
if (!glsm_ctl(GLSM_CTL_STATE_CONTEXT_INIT, &params))
   return false;
return true;
```

**Comment by LazyBumHorse** [comment] 2019-07-19 13:22
@orbea You'll usually get the highest possible version for the compatibility profile, but not for the core profile (for OpenGL 3.2+).

Here's a source: https://www.khronos.org/opengl/wiki/OpenGL_Context

> [OpenGL 3.2 wording] (...) [allows] 3.0 and higher versions to be given when not directly asked so long as they support ARB_compatibility or are the compatibility profile of that version of OpenGL.

Core is not directly mentioned, but it does talk about deprecation and feature removal.
In the case the forward compatibility bit is set, the following applies

> For 3.2+ core (...) all functionality that is still deprecated (wide-lines) will be removed.

So if it is forward compatible, it's even less backwards compatible.

That said, if a video driver knows that it's highest core profile version (without forwards compatibility bit) is backwards compatible, it _may_ return a newer version, not sure if that's explicitly forbidden.
At least on Windows with Nvidia drivers this does not happen though.

**Comment by orbea** [comment] 2019-07-19 13:51
I think I confirmed that beetle-psx is a requesting a `3.3` core profile and getting a `4.5` core profile on my system. I added `printf("%s\n", glGetString(GL_VERSION));` to the top of `retro_unload_game` and upon unloading content it printed:
```
4.5 (Core Profile) Mesa 19.2.0-devel (git-37aefb2be1)
```
https://stackoverflow.com/questions/7909358/how-do-i-know-which-version-of-opengl-i-am-using/7909595#7909595

The verbose output is misleading because it seems to be printing what version is requested and not what version is found.

**Comment by barbudreadmon** [comment] 2019-07-19 14:04
@orbea maybe that's what @LazyBumHorse is explaining above : 
> if a video driver knows that it's highest core profile version (without forwards compatibility bit) is backwards compatible, it might return a newer version

In my case, with nvidia proprietary driver, i tried your printf and i'm getting `3.3.0 NVIDIA 430.26` when asking for a `3.3` core profile. Maybe mesa returns the newest version ?

Also, in 
```
[INFO] Requesting core OpenGL context (3.3).
...
[INFO] [GLCore]: Version: 3.3.0 NVIDIA 430.26.
```
I think this last line might be using `glGetString(GL_VERSION)`.

**Comment by orbea** [comment] 2019-07-19 14:24
@barbudreadmon What does glxinfo tell you?

**Comment by barbudreadmon** [comment] 2019-07-19 14:38
> OpenGL core profile version string: 4.6.0 NVIDIA 430.26
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:

**Comment by orbea** [comment] 2019-07-19 14:50
Then I would guess its a difference with mesa and nvidia, sorry I don't know more. You could try asking on a graphics related irc channel like #dri-devel @ freenode where more knowledgeable people could help.

**Comment by LazyBumHorse** [comment] 2019-07-19 14:57
About https://github.com/libretro/RetroArch/issues/9131#issuecomment-513222465, it goes
`glsm_ctl(GLSM_CTL_STATE_CONTEXT_INIT)` --> `glsm_state_ctx_init(params)` and `params->environ_cb(RETRO_ENVIRONMENT_SET_HW_RENDER)` decides if it returns `true` or not.
That thing comes from `retro_set_environment(cb): environ_cb = cb`, so it's very likely this code that does the decision:
https://github.com/libretro/RetroArch/blob/42783fb2258226872b596925e8068947299586dd/retroarch.c#L3400-L3436
So `dynamic_request_hw_context` and `dynamic_verify_hw_context` are good places to start debugging.

**Comment by LazyBumHorse** [comment] 2019-07-19 15:02
Assuming this is actually a RetroArch problem, with all these `Major opcode of failed request:` messages in the Kronos thread this might as well be a video driver problem.

**Comment by orbea** [comment] 2019-07-19 15:10
Is it possible that it fell back to the llvmpipe and is not even using the nvidia driver?

**Comment by bparker06** [comment] 2019-07-25 22:54
We talked about this today with maister, and the general consensus seems to be that you can't.

The suggested approach (which apparently isn't uncommon) is to simply try a bunch of progressively lower versions (starting with the highest you want) until one succeeds. Simply requesting version 0.0 only seems to return the highest version when you don't specify a core context explicitly (seems to fail in that case), and even then, this may be implementation-specific behavior, so other drives might actually return the *lowest* supported version instead, or anything inbetween.

We have a similar issue now in RA related to this with the new "requested api version" support in the core info files, where the frontend checks the current graphics API version to see if it's compatible (and denies loading content if so). The glcore driver specifically requests 3.2, and receives 3.2, but then if a core needs 3.3, this check will fail.

**Closed** 2020-02-17 19:14 UTC
