### ISSUE TITLE
Saving overrides of Game or Core reverts hotkey changes to its original value

### ISSUE THREAD

**Issue by airecajr** [libretro/RetroArch#4263] opened 2016-12-18 03:28 UTC
Hi!, I was using game overrides to modify some hotkeys when i noticed that pressing the Save Game Overrides option the Hotkeys i was going to use were reverted to its original value.

Here are the steps to reproduce:
1 Open Retroarch and load a game
2 Open the menu and edit a Hotkey
3 Return to the quick menu and press the Save Game Overides button
4 Go back to look at the hotkey menu, the hotkey will be back to its original value

After looking at the override file created, the new hotkey is not added either, other modified settings were added correctly
I tested after with the Core Overrides and happens the same thing.
Adding manually the hotkey to the override file works as expected.

Im using Windows 10 64bit, Retroarch X86_64 from buildbot date 15 december, and tested with Mednafen and Bsnes Cores.

PS. i found another thing in the overrides but im going to create another issue for it, im not sure if its related to this one but i tested them independently.

**Comment by fr500** [comment] 2016-12-18 03:41
Keybinds are not saved with overrides.

**Comment by airecajr** [comment] 2016-12-18 03:50
Thanks for the info!

However i find strange that pressing the Save Overides button inmediatly deletes the changes made.
Like if the keybindings are not saved at least it must not delete the keybindings just made.

**Comment by fr500** [comment] 2016-12-18 03:51
Yeah that part seems odd, I don't really load the settings again when saving.

**Comment by airecajr** [comment] 2016-12-18 04:03
i didnt write it in the issue but it happens instantaneusly you dont even have to go back to the game or change anything else

**Comment by fr500** [comment] 2016-12-18 04:12
I just checked the code and there is nothing there that suggests that that could happen but I tested and it does happen
weird...

**Comment by fr500** [comment] 2016-12-18 04:15
Ok I guess I know what the problem is.
Input bindings are loaded directly into global settings by another function, it doesn't use settings_t as a parameter.

I can't really figure this out, it's quite weird (input binding loading and saving) which is why I didn't make it possible to save them in the first place

**Comment by nesrocks** [comment] 2018-01-05 11:29
I'm not sure I'd call this a minor bug. With this bug I can't save any remaps ever. It does not even create rmp files. Whenever I hit save core overrides or save game overrides, it loads remaps to default settings. So, there is no way to remap buttons and keep them like that between play sessions.

**Comment by Quest79** [comment] 2018-05-15 13:13
Retroarch seems to have several very fundamental and basic bugs and this is one of them. Unable to save hotkey binds? This is a ridiculous problem even the most basic 2 decade old emulators have no issue with.

**Comment by fr500** [comment] 2018-05-15 13:31
You have no clue of what you're talking about.
You can save hotkeys just fine.

You can't save them in overrides,  I were the whole override thing and I
haven't figured how.  That's all.

**Comment by nesrocks** [comment] 2018-05-15 13:34
quote from me:
"It does not even create rmp files"

**Comment by nesrocks** [comment] 2018-05-15 14:40
I see. It's been a few months since I've fiddled with this, so I can't remember the details, but key bindings have always been problematic in retroarch for me. The wii version, which I understand has been discontinued, doesn't save key bindings at all. And the one I use on my raspberry pi3 doesn't save overrides, apparently. Which is a big deal when dealing with hundreds of games.

I don't think I understand what a remap is at the moment then.

**Comment by fr500** [comment] 2018-05-15 14:47
Wii version hasn't been discontinued and keybindings are saved just fine.
If you can't save overrides at all you should provide a log at least.

As I commented above saving keybinds in overrides doesn't work.

I asked @twinaphex why is that there are so many things that load directly to other structures (instead of settings_t) he said he doesn't like "pointer grabbing" from the drivers.

Nothing I can do to fix that.

**Comment by nesrocks** [comment] 2018-05-15 14:58
Neither me nor my friend could save keybindings on the wii version (we always have to reassign the buttons when playing arcade games, each time we play). For years we've looked for updates but it remained stale for all that time. If it has been updated I'll try it, but I can't right now as my wii is in another city. :(

As for the pi version I'd really appreciate this issue to move up in priority because it's a big deal for having the arcade cabinet "simply working", but I of course understand that there are countless things I don't know about that could be higher in priority.

**Comment by fr500** [comment] 2018-05-15 22:44
They save just fine in the main config. You are spreading FUD.

**Comment by orbea** [comment] 2019-02-03 18:40
Closing in favor of issue https://github.com/libretro/RetroArch/issues/6641 which followed the template.

**Closed by orbea** 2019-02-03 18:40 UTC
Labels: bug: minor

**Comment by Elmazz37** [comment] 2019-09-28 06:36
so no fix? hotkeys still dont save in core overrides.

**Comment by corgana** [comment] 2021-01-19 23:03
Still no fix for this? Any workarounds?

**Comment by bellydrum** [comment] 2021-02-01 16:30
So no fix?
![So no fix?](https://i.makeagif.com/media/10-16-2017/k4JScf.gif)

**Comment by corgana** [comment] 2021-02-01 16:59
If anyone's curious here's how I worked around it:

I wanted slowdown to be left analog trigger, and fast forward to be right trigger, so I added this code to an empty text document called Nestopia.cfg

```
input_hold_fast_forward_axis = "+5"
input_hold_slowmotion_axis = "+4"
```

Then when I change and save settings I always save to "Content directory" (which creates a different config) as long as you're careful not to save over the "core" settings, it should keep your configs for you.

**Comment by monterman** [comment] 2021-06-10 01:20
my two cents, after doing this  Hotkey binds are persistent.  Did not have time to narrow it down exactly, but works for me!

Hi all, I tried many ways to Save and have persistent HotKey binds, and the only way I was able to get it persistent, even after retroarch reboots and new confirg saves, overrides is to add the values on the retroarch.cfg.  and for good measure I also pasted my values in CORE and Folder Remaps and core cfg. IE NES.cfg and Nestopia.cfg  (remaps on like nes.rmp)   I think that last part is overkill,, but I tried everything and this is now working so overkill made it.   
here are my config for my Ambernic rg351p running ARKOS? 

input_hold_fast_forward_axis = "23"
input_hold_slowmotion_axis = "24"
input_rewind = "26"
input_save_state = "20"
input_state_slot_decrease = "h0left"
input_state_slot_increase = "h0right"
input_shader_prev = "h0down"
input_shader_next = "h0up"

Hope it helps.  The H0 values are for the left D-pad.  That took a while to figure out.
