### ISSUE TITLE
[WiiU] Ozone Menu Driver - Playlists bug

### ISSUE THREAD

**Issue by ShadowOne333** [libretro/RetroArch#8519] opened 2019-03-23 02:35 UTC
## Description

When opening RetroArch, browse to playlists  Names of the games are listed, but as soon as focus is shifted to try to select a game, the names of the games disappear. However, you can see the thumbnails for each one, and even go through them by pressing up/down and the thumbnail changes, the names simply don't show up.

Interestingly enough, if you run up any game, go back to the RA menu while the game/content is loaded and go to playlists, the list with the names shows up just fine.
If you close the content and go to playlists, they disappear again. 

### Expected behavior

see the names of the roms thorugh playlists at all times.

### Actual behavior

Names are only visible when a content is loaded.
Names are invisible when there is no content loaded.

### Steps to reproduce the bug

1. Download latest RA nightly for Wii U and open it thorugh Homebrew Launcher.
2. Go to playlists. Names should be invisible as soon as focus is shifted to the ROM list, but thumbnails load nor ally and you can scroll through each entry. Thumbnails change accordingly
3. Load any content and go back to the RetroArch menu to check playlists (while content is still loaded). Names on the playlist should now appear normally.
4. Close content amd go back to playlists once again. Names should be missing yet again.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: March 18th 2019 nightly build.

**Comment by fr500** [comment] 2019-03-23 02:56
Try taking a picture of the problem if you can

**Comment by ShadowOne333** [comment] 2019-03-23 03:53
Here is the post in Imgur:
https://imgur.com/a/i3z1vw1

And the order of the images:

1) Browsing to playlists with RetroArch just opened:
https://i.imgur.com/bbwOUZ4_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

2) Changing the focus to the game names list triggers the bug:
https://i.imgur.com/MGRwS9x_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

3) However, opening up the list while a game is loaded up as content makes the playlists show up properly:
https://i.imgur.com/XchWtSb_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

**Comment by orbea** [comment] 2019-03-23 14:23
Can you check if this is only ozone or does it affect other menu drivers too?

**Comment by ShadowOne333** [comment] 2019-03-23 16:20
Changed the driver to XMB and they do display fine. Seems to only affect Ozone.

**Comment by twinaphex** [comment] 2019-04-07 18:19
@natinusala What do you think?

**Comment by natinusala** [comment] 2019-04-07 18:42
I need a way to reproduce this on PC as I don't own a WiiU

**Comment by ShadowOne333** [comment] 2019-04-08 16:05
Maybe it could be an endianess issue with playlists for WiiU specifically? I've seen other issues related to that for cores and stuff, maybe it could be affecting playlists as well.

Anyway, I tried to reproduce this on PC (Windows 32bit build through Wine on Gentoo), but sadly it seems to be working fine on PC. 
I will try updating my WiiU build to the latest nightly just in case and see if I am still getting the same bug. I will report back what happens.

**Comment by ShadowOne333** [comment] 2019-04-09 23:13
Mmm no, no luck.
Updated everything to latest nightlies on WiiU and set it up again, but still the same problem.

**Comment by natinusala** [comment] 2019-04-09 23:15
Well it won't magically solve itself, if I can reproduce it on PC then I can fix it :P

Maybe try the gamepad resolution on PC? Or it could be yet another bad typing / rounding / cast situation

**Comment by ShadowOne333** [comment] 2019-04-10 18:08
Tried setting the resolution to 854x480 (WiiU's gamepad resolution) on PC, but I had no luck replication the problem.
I tried other stuff as well, but so far nothing that could replicate it on PC sadly.

**Comment by fr500** [comment] 2019-04-10 19:00
Does RA WiiU work on CEMU?

**Comment by Lolithetrolli** [comment] 2019-08-20 23:33
Having the same issue with 1.7.7.
Playlists will only work correctly after running a game. I know that this problem is likely only on the Wii U and not a priority for the devs, but any chance someone with a Wii U could check this out?

**Comment by hubcappp** [comment] 2020-03-22 18:42
Bug still exists in 1.8.5 even though ozone is now the default menu. Not only that but the menu text is now shifted too far to the left causing it to overlap the menu icons which didn't happen in 1.8.4. This isn't an ozone specific bug though, it happens in xmb and glui as well so there isn't any nice looking menu for Wii U now.

I tried loading retroarch.rpx in cemu with the retroarch folder copied into cemu's sdcard folder and it just crashes.

**Comment by twinaphex** [comment] 2020-03-22 21:00
We need an active WiiU developer to help us with these issues. It likely is an issue that needs to be resolved in the menu display driver - in specific this file - 

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_display/gfx_display_wiiu.c

For now if you can't deal with the visual anomalies you could always use RGUI which is the only menu driver that doesn't use the display driver interface.

**Comment by QuarkTheAwesome** [comment] 2020-04-22 12:29
After much debugging (and trying to understand how the Ozone menu works) I've hit upon the source of this - the thumbnail sidebar on the right is drawing its background gradient too wide, covering the playlist. Still working on a "why", but commenting out the background quads (ozone_entries.c:857) does allow the list to show through.
This doesn't happen when content is running because there's a check that stops the sidebar from drawing a background at all if the core is running. It also checks if the "menu framebuffer opacity" is less than 1 - I don't know if this setting is exposed as a menu item somewhere, but if you can find it, setting it to anything below 1 should work as a quick-fix.

**Comment by natinusala** [comment] 2020-04-22 12:31
Just as I asked Aut to set XMB back to default on Wii U... that would be great if you can fix this issue, good luck :muscle:

**Closed** 2020-04-22 19:16 UTC
Labels: menu: ozone, platform: wiiu
