### ISSUE TITLE
Problem with closing games on PPSSPP core using Gl, Gl core video drivr.

### ISSUE THREAD

**Issue by KamiLordus** [libretro/RetroArch#16504] opened 2024-05-06 17:41 UTC
Using the "close content" option on the PPSSPP core freezes retroarch completely. Only killing the process using alt + delete + ctrl helps.
I'm sure it's not a core problem because its latest version PPSSPP doesn't have this problem on retroarch 1.18 cdd6aed8ec. The problem recently appeared about a week/two ago.
I am currently using retroarch 1.18 version 9ab6c62f which already has the above mentioned problem.
For PPSSPP core I use GL video driver, but I tried others like vulkan, gl and it's the same.

edit:
I also tested older versions of PPSSPP from retroarch buildbot such as 1.17 and 1.16 and there is also the same problem.

Windows 11
Rtx 3070ti

**Comment by sonninnos** [comment] 2024-05-06 17:59
I can't replicate with current versions of RA and core.

**Comment by KamiLordus** [comment] 2024-05-06 18:14
It won't be easy. I only know that retroarch saves the log after closing the game. In this case, I can't save anything because it freezes completely.

**Comment by Jamiras** [comment] 2024-05-06 18:26
I was able to reproduce on latest master (9ab6c62) using glcore. Also Windows 11. RTX 3060.
I was not able to reproduce using Vulkan.

There's not really anything useful in the logs. I did get these stack traces in the debugger:

Exception thrown (thread labelled as `nvoglv64.dll thread`):
![image](https://github.com/libretro/RetroArch/assets/32680403/4bc25e6c-f137-417e-b930-7889f383a18f)

Main thread:
![image](https://github.com/libretro/RetroArch/assets/32680403/af3cf7a8-10b6-4431-9721-a847e7316c5c)

**Comment by Jamiras** [comment] 2024-05-06 18:28
Although, my behavior does differ slightly from the reported behavior. The application only hangs for a second or two then closes itself. I don't have to Ctrl+Alt+Del it.

**Comment by Jamiras** [comment] 2024-05-06 18:31
I see the same problem with the `v1.17.0` and `v1.16.0` tags, so it's probably not a RetroArch change.

**Comment by sonninnos** [comment] 2024-05-06 18:32
Tried gl, glcore, vulkan and d3d11, and all close without problems. Didn't try running much longer than successful start though.

**Comment by KamiLordus** [comment] 2024-05-06 18:50
After longer tests, I noticed that the problem does not occur with the vulkan driver, the same with dx11. It seems that the problem only appears on GL and GL Core.

**Comment by gouchi** [comment] 2024-05-06 20:54
> It seems that the problem only appears on GL and GL Core.

So you should  rename the issue to something `Problem when closing games with PPSSPP core using GL or GLCore video driver on Windows` ;)

P.S =  I can't reproduce the issue on Linux.

**Comment by viachaslavic** [comment] 2024-05-26 11:27
I can randomly reproduce on GNU/Linux with gl drivers with audio on, but I can’t reproduce it when the audio is off.

@KamiLordus could you please tested this on your system with audio off or `null` audio driver?

**Comment by KamiLordus** [comment] 2024-05-26 14:30
@viachaslavic I tested the ppsspp core without sound, and with null sound. The tested games close without any problems every time.
Thanks for your suggestions.
Of course, on the GL Core driver with sound turned on, the games still freeze when you try to close them. Nothing has changed here.

**Comment by KamiLordus** [comment] 2024-05-28 17:44
This PR fixed my problem.

**Closed** 2024-05-28 17:44 UTC
