### ISSUE TITLE
Overall Improvements

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3763] opened 2016-10-09 07:52 UTC
- [X] Improvement
- **FIXED.** Move `Download Content` out of `Add Content` as it is likely not to be utilized much.
  Could be right under `Add Content` as `Download Content`
  Could be inside `Online Updater` as `Download Content` or `Content Updater`

- [X] Improvement
- **OUTDATED.** There is `Scan Directory` tab. I was going to say it might be better to move it at end of the XMB menu... but then I see same thing under `Main Menu`. Is it any different from `Main Menu` --> `Add Content` --> `Scan Directory`? It might be more clean to remove `Scan Directory` off the tabs since it's weird to have it there in middle between options and the scanned games. The users can use Main Menu to scan games. If not...

- [X] Improvement
- **FIXED.** On `Scan Directory` tab, you will get `Import content`.
  On `Scan Directory` menu, you will get `Add content`.
  Fix one to stay consistent?

- [ ] Improvement
- When using `Save New Config`, it will write something like `RetroArch-1009-010413..cfg` with two dots at end. There were no mention about backups. It might be nice to get a notification about a backup too. Something like...
  `Moved backup config to /home/lasers/.config/retroarch/config/RetroArch-1009-010413..cfg`
  `Saved new config to /home/lasers/.config/retroarch/retroarch.cfg`

  `Save Current Config`. It might be possible to omit `Current` as I don't see how I can manually save current config as something else in RetroArch. However, I think this may be there for comfort... to know that you're just saving current configuration. Just something to mention.

  _NOTE_: The code is slightly too straightforward. Saving current config will print `Saved new config to: $PATH` ... and stuffs like that and does not check for permissions.

───── CODE OMITTED ─────
───── CODE OMITTED ─────

- [X] Improvement
- **FIXED.** `Save New Config` and `Save Current Config` are the only two I see that uses the word `Config`. Just something to mention if you want to stay consistent by going with Configuration or Config?

- [X] Improvement
- **FIXED.** In `Main Menu`, Why is `Save New Config` not next to two config-related options (`Load Configuration` and `Save Current Config`)?

- [x] Possible `Oh C'mon` bug
- When clicking `Start Remote RetroPad` for first time and clicking `Guide/PS` button, it will take you to `Shaders` under `Quick Menu`. This always do this on first RetroArch launch. Try pressing `Guide/PS` button again in many different menu places and it'll back out in same place (perfect). Is the inital `Start Remote RetroPad` --> `RetroPad Controller` --> `Shaders` a bug?

- [x] Possible `Oh C'mon` bug
-  ~~Clicking `Start Remote RetroPad` will enable `Quick Menu`.~~ Not a bug.
(It does not pop up Quick Menu, just enabling. I later understand what Remote RetroPad does after seeing its `Options`)

- [ ] Possible `Oh C'mon` bug
-  After enabling `Start Remote RetroPad`, go to `Quick Menu` and `Take Screenshot`. It will create a file `-161009-015824.png` -- Use `RetroArch-161009-015824.png` in the future? ~~Or disable `Quick Menu` somehow?~~

- [ ] Improvement
- When taking a screenshot, print the file path of the newly created screenshot too in the notification to make it more meaningful than a vague `100%: Taking screenshot.`. 
  Use `100%: Saved new screenshot: "Ape Escape (USA)-161009-030050.png"`

- [X] Improvement
* **FIXED.** To stay consistent with what I noticed, there is a vague option `Enable` under `Settings` --> `Retro Achievements`. Rename it to something like `Achievements Enable`?

- [X] Note
- Some options  have missing titlecase to stay consistent with other options.

**Comment by RobLoach** [comment] 2016-10-09 13:21
Testing out the bugs you posted...

> Possible bug: When clicking Start Remote RetroPad for first time and clicking Guide/PS button, it will take you to Shaders under Quick Menu. This always do this on first RetroArch launch. Try pressing Guide/PS button again in many different menu places and it'll back out in same place (perfect). Is the inital Start Remote RetroPad --> RetroPad Controller --> Shaders a bug?

Confirmed... First menu item after opening the menu is Shaders.

> Possible Oh C'mon bug: Clicking Start Remote RetroPad will enable Quick Menu.

Unconfirmed... Does not happen for me on `master`.

> Possible Oh C'mon bug: After enabling Start Remote RetroPad, go to Quick Menu and Take Screenshot. It will create a file -161009-015824.png -- Use RetroArch-161009-015824.png in the future? Or disable Quick Menu somehow?

Confirmed... Also noticed that if the Screenshot Directory is set to "Content Dir", the screenshot saving fails.

> When taking a screenshot, print the file path of the newly created screenshot too in the notification to make it more meaningful than a vague 100%: Taking screenshot..

Works as designed... This is actually because the task is in progress of saving the file. Goes from 0% to 100%, 100% is all you see likely because it saves so fast.

**Comment by lasers** [comment] 2016-10-09 23:08
* Possible `C'mon` bug: When taking a screenshot, it also capture notification. Wanted behavior or not? I used key n/m to toggle shader to trigger a notification if you need a way to trigger/test one.

* Question about `Remote RetroPad`. Do we use that word or `Network Gamepad`?
There is `Network Gamepad` in `Settings`--> `Network` which I believe is related to `Remote RetroPad`. I also see `User 1 Remote Enable` and `User 2 Remote Enable` (I use 2 for max number). What's the difference between `Network Gamepad` and `User _ Remote Enable`? (Lack of word pad).

* Personal issue I don't feel like bothering anyone about at first. Other than extracting everything, Retro can't find my zipped No-Intro roms. Do Retro require that I extract all the zips first (because it works) or to put them in different archive? I recall having no problem scanning zipped archives with `community/retroarch`. I moved  up to `aur/retroarch-git` and absolutely can't pick up any zipped archives. Can somebody confirm this on fresh profile as the testers might kept their content*history.lpl for too long? If wanted, I can try `community/retroarch` again to confirm.

My dir structure.

```
~/Games        (ln -s from /run/media/user/uuid/Games)
.
├── Nintendo - Gamecube/
│   └── Game_Zipped_2 (USA).ciso*     	(Compressed; not likely to be picked up)
│
├── Nintendo - Nintendo Entertainment System.zip*
│										(No Intro; All compressed zips compressed
│										in one zip ; not picked up)
│
├── Nintendo - Nintendo Entertainment System/
│   ├── Game_Zipped_1 (USA).zip*        (No Intro; not picked up)
│   ├── Game_Zipped_2 (USA)/        	(Picked up)
│   │   └── Games_2 (USA).nes
│   │
├── Nintendo - Super Nintendo Entertainment System/
│   ├── Game_Zipped_1 (USA).zip*        (No Intro; not picked up)
│   ├── Game_Zipped_2 (USA)/        	(Picked up)
│   │   └── Games_2 (USA).sfc
│   │
├── Sony - Playstation/
│   ├── Game_1/							(Picked up)
│   │   ├── Game_1.bin*					Question: Is there supported compressed
│   │   └── Game_1.cue*					version for PS1 (and others) in a database? 
│	│
├── Sony - Playstation Portable/
│   ├── Game_1 (USA).cso*				(Compressed ; not likely to be picked up)
│   └── Game_2 (USA).iso*				(Picked up)
├── .../
│   └── ...
├── .../
│    └── ...
└── ... 

```
* When toggling off `Icon Shadows`, it does not apply to notifications.
Does this require a fix to support that too or a new option for `Onscreen Display`?

* Feature Request: To display `Game Title` too in the titlebar.
`RetroArch Mednafen PSX v0.9.38.6 || CTR - Correct The Record || Frame 3840`

* Question: A game I wanted to play crashed when I applied either cheat (There were only two). What do you need to investigate this issue?
```
`RetroArch [INFO] :: Cheat: #1 [ON]: Infinite Lives`
`terminate called after throwing an instance of 'nall::vector<CheatList>::exception_out_of_bounds'`
`[1]    30468 abort (core dumped)  retroarch --appendconfig=$HOME/.config/retroarch/config/RetroArch-local.cfg`
```

**Comment by fr500** [comment] 2016-10-09 23:30
- The notification shows AFTER taking the screenshot, it doesn't screenshot the notifications, unless you take several in succession
- Yes
- For me the no-intro set works, it scans fine, I have a set from 2015 though.
- Why would icon shadows apply to notification text?
- People asked for less stuff on the window title, we did that, now people want more.... I dislike having too much info on the titlebar so I'd vote no.

**Comment by lasers** [comment] 2016-10-10 00:39
> For me the no-intro set works, it scans fine, I have a set from 2015 though.

Got them from 2016-01-03 Fixed. What should I do? Go with older version? It does not pick up one thing from Goodsets (NES, SGEN) either. I'll try `community/retroarch` next. 
**EDIT: IT WORKS!!** **Scanning is borked in aur/retroarch-git here! Why??**

What's the difference between Network Gamepad and User _ Remote Enable?

> Why would icon shadows apply to notification text?

The notification text is already applied with something by default... I mentioned that as a suggestion because "same same but different but still same" with menu by default. From what I see, `Icon Shadows` applies to text too. I mentioned other thing too and that was to to introduce a new option for `Onscreen Display` to turn off shadows.

> People asked for less stuff on the window title, we did that, now people want more.... I dislike having too much info on the titlebar so I'd vote no.

I vote yes. :-) We have different setups and different preferences. Some people like to watch movies/TV shows in fullscreen. Some prefers windowed. With windowed, you can pause things easily, manage windows at your own time, come back later to pick up where you left off. It helps me remember what I was doing here with Retro when I came back to something paused. I then can recall I was playing that game few hours ago before I had to leave for errands or such. It's same as glancing at titles of opened browser tabs when you got on a computer after a long good nap.

* Toggleable options for title? What if somebody does not want to see `Frames: 6912`? 

`RetroArch` (could be ideal default)
`RetroArch Nestopia v1.48-WIP` (could be ideal default)
`RetroArch Nestopia v1.48-WIP || Frames: 24320` (current default)
`RetroArch Nestopia v1.48-WIP || Legend of Zelda, The (USA) || Frames: 24320`
`RetroArch Nestopia v1.48-WIP || Legend of Zelda, The (USA)` (what I wanted)
`RetroArch || Legend of Zelda, The (USA)` (what the others may want)

Also, video players in windowed mode often display nothing more than a content's filename as title... `movieName-year.mkv` or `I_Love_Lucy_S06E27.mkv` along with their name (mpv, vlc, Media Player Classic, etc). You also can see progress bar/slider, ability to glance at OS system clock, etc (but that's not for titlebar anyway).

**Comment by RobLoach** [comment] 2016-10-10 01:34
> Retro can't find my zipped No-Intro roms

Looks like all .zip files didn't work. Maybe because your build wasn't compiled with zlib?

**Comment by lasers** [comment] 2016-10-10 02:44
I'm using this https://aur.archlinux.org/packages/retroarch-git/
The PKGBUILD depends on zlib which is already installed because many other packages requires it too. And this command too.
```
chris@z420 ~ $ retroarch --features | grep -A1 zlib
  zlib:
                .zip extraction support: yes
```
retroarch is the only package changing when switching between `community/retroarch` and `aur/retroarch-git`. I confirmed it again with a different game system romset that the git version does not work for me right now.

**Comment by lasers** [comment] 2016-10-26 12:55
* With Retro Achievements options toggled on, you cannot rewind.
When paused in the game with Retro Achievements toggled on, hitting "rewind" button will fast-forward the frames... An opposite and unwanted behavior.

* The fast-forwarding feature also works under Retro Achievements. This possibly could be considered cheating as one is speeding up through all their gameplays/grinding more than others to get same Retro Achievements.


* Persistent notification when toggled slow motion on.

* Persistent notification when toggled fast forward on.

* Persistent notification when toggled pause on.

**Comment by lasers** [comment] 2016-10-30 13:30
If you `chmod -w retroarch.cfg` and use RetroArch's `Save Current Config`.
You'll get `Failed saving config to "/path/to/home/retroarch.cfg".`
This is true.

If you `chmod -w retroarch.cfg` and use RetroArch's `Save New Config`.
You'll get `Saved new config to "/path/to/home/retroarch.cfg".` 
This is not true.

The file ends up in `config` directory as `RetroArch-1030-081108..cfg`
with two dots at the end. `..cfg`

**Comment by lasers** [comment] 2016-11-01 02:23
All four `content_history` tabs should not come after any systems.
I'm seeing them after a couple of Atari systems and before a couple of NEC systems.

**Comment by lasers** [comment] 2016-11-01 17:57
Burying a possible regression bug in this thread hoping nobody will notice a thing. Due to new changes in menu input, change a number in `Settings` --> `Input` --> `Max Users` to something else and enjoy your new speed. The workaround is to start RetroArch again with the new setting already applied.

**Comment by fr500** [comment] 2016-11-01 18:00
Could you try being  less cryptic and more descriptive of the actual bug?

**Comment by lasers** [comment] 2016-11-01 18:07
No. Maybe. I'll try... The bug is vague. Enjoy your new speed. How you move through a menu, I think, will be decided on a number of `Max Users`. If you pick 2, you'll move maybe 2 times. If you picked 5, you will move maybe 5 times.

If you try a really high number, it seems broken because it's not able to scrollstep ___ times in that limited menu so it just stay still... until you enter number 1 for `Max Users`

**Comment by bparker06** [comment] 2016-11-01 18:24
@lasers What happens if you turn off the "All Users Control Menu" option? Perhaps you have a buggy gamepad setup where it is duplicating your button presses across multiple gamepads (virtual or not).

**Comment by lasers** [comment] 2016-11-01 18:33
`All Users Control Menu` is on for the lines above.

I used the keyboard to navigate in RetroArch. I have two controllers (Xbox360 and PS3) laying around on the desk... and both are plugged in. With `All Users Control Menu` off, I do not have this issue anymore. This is with RetroArch 8d8d91e

**Comment by RobLoach** [comment] 2024-04-20 09:23
I think we can close this now? There were a few All Users Control Menu bugs that had been fixed since.

**Closed by RobLoach** 2024-04-20 09:23 UTC
Labels: followup: enhancement, followup: needs info or confirmation, user interface
