### ISSUE TITLE
Quick menu (gear icon in overlay) causes app to crash

### ISSUE THREAD

**Issue by fabikw** [libretro/RetroArch#3231] opened 2016-07-17 13:31 UTC
Using Version 1.3.6.

When using the quick menu (Gear icon in the overlay), after it is closed (with the arrow in the bottom, gear appears at the bottom) pressing on the gear causes the app to crash. There is no way to use this menu without the app crashing.

EDIT: This is using the Google Play version in an Amazon Kindle Fire.

**Comment by fr500** [comment] 2016-07-17 16:32
I can't reproduce this works fine on my nexus 7 and my shield

**Comment by HoDANG** [comment] 2016-08-26 11:31
I am having the same problem with the android version from the google play store. However, sometimes the ^ arrow will appear after closing the quick menu, and other times the gear icon will appear. Either way, the emulator still crashes after closing the quick menu. The worst part is that even after saving the game in pokemon, the save data is still reset to the point when the emulator was first opened up. So if you missclick the quickmenu button, then all your progress that session will be lost, even if you saved.

**Comment by Aaahh** [comment] 2016-12-25 07:38
Get a logcat
(plug in phone to computer, `adb logcat > mango`, and then do that thing to make it crash again, and when you finish, just unplug from computer and send the file mango)

**Comment by orbea** [comment] 2018-12-16 19:14
Given the lack of reports, info or activity I am going to close this issue. If anyone is still having a problem please open a new issue, fill out the issue template and include a logcat.

**Closed by orbea** 2018-12-16 19:14 UTC
Labels: followup: needs info or confirmation, platform: android
