### ISSUE TITLE
RGUI fonts is corrupted

### ISSUE THREAD

**Issue by Sunderland93** [libretro/RetroArch#8267] opened 2019-02-12 15:58 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Corrupted RGUI fonts

![screenshot_20190212_195449](https://user-images.githubusercontent.com/11344982/52648717-6acf8080-2f00-11e9-90b4-deffde39fd10.png)

### Expected behavior

RGUI fonts must correctly rendering

### Actual behavior

See screenshot

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.6

### Environment information

- OS: Debian 9
- Compiler: GCC 6.3.0

**Comment by orbea** [comment] 2019-02-12 16:13
What language are you using?

**Comment by jdgleaver** [comment] 2019-02-12 16:18
Yes, that's almost certainly a unicode issue. RGUI uses a bitmap font that only supports the following glyphs: https://raw.githubusercontent.com/libretro/RetroArch/master/gfx/drivers_font_renderer/bitmap.bmp

**Comment by Sunderland93** [comment] 2019-02-12 16:18
Russian

**Comment by orbea** [comment] 2019-02-12 20:37
This is actually a duplicate of issue https://github.com/libretro/RetroArch/issues/5643.

**Closed by orbea** 2019-02-12 20:37 UTC
Labels: bug: font rendering, menu : rgui
