### ISSUE TITLE
Enhancement : cores updating semi-automaticA

### ISSUE THREAD

**Issue by lanciaux** [libretro/RetroArch#6100] opened 2018-01-14 08:53 UTC
Enhancement request :

due to frequent update of cores, it is difficult to share same cores versions and so network connecting games is rather pretty difficult to arrange except if you use Lakka official versions with your friends doing same. 

It would be handy to have an option in download cores menu allowing to update automaticaly all your cores upon most recent available except of doing one per one.

A second possibility would be also to have in cores list a trigger/button/selection box in right column showing current version and also showing a newer one is available and you can update with a new key combination

Ludovic

**Comment by julianxhokaxhiu** [comment] 2018-05-11 17:17
I agree and upvote this one. @twinaphex or anyone of the team, can you please consider this?

It would be really handy if you could implement some kind of "update manager" for cores, to keep it MVP, just update what was already download, manually triggered.

At the current status if I have to update the cores, I always have to do to the core update menu and download them one by one, trying to remember which core did I had for which kind of console.

Thank you very much in advance.

**Comment by julianxhokaxhiu** [comment] 2018-05-12 09:00
As always having an option is the best choice. But at least I insist on providing it. Aside of all the good and bad reasons that comes with it. Also, maybe it's time to consider a CDN?

**Comment by orbea** [comment] 2019-01-04 02:59
Duplicate of issue https://github.com/libretro/RetroArch/issues/5346.

**Closed by orbea** 2019-01-04 02:59 UTC
