### ISSUE TITLE
RetroArch keeps creating /storage/emulated/0/RetroArch/ folder on start on Android

### ISSUE THREAD

**Issue by thekiefs** [libretro/RetroArch#9740] opened 2019-11-17 19:09 UTC
## Description
RetroArch keeps creating the /storage/emulated/0/RetroArch/ and associated subfolders (like cheats, screenshots, configs, etc) despite changing the default directory structure to a different location, even after I delete said folder

### Expected behavior
I expect RetroArch to use the custom folders I set

### Actual behavior
RetroArch re-creates the default folders 

### Steps to reproduce the bug
1. In RetroArch, change Settings > Directory > Change all locations of settings to a custom location
2. Delete the /storage/emulated/0/RetroArch/ folder and subfolders
3. Close RetroAch
4 Open RetroArch
5. See that /storage/emulated/0/RetroArch/ and all subfolders are recreated

### Bisect Results
[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information
- RetroArch: 1.8.1
- Build: Nov 2, 2019

### Environment information
- OS: Android TV 9.0, SHIELD Android TV 8.0.1

**Comment by fr500** [comment] 2019-11-24 07:30
That is performed before loading the config and there isn't much that can be done.
The file placement situation is already difficult enough as is to be adding any more weird rules.

**Comment by fr500** [comment] 2019-11-24 07:33
On windows we have this:

```C
void dir_check_defaults(void)
{
   unsigned i;
   /* early return for people with a custom folder setup
      so it doesn't create unnecessary directories
    */
#if defined(ORBIS) || defined(ANDROID)
   if (path_is_valid("host0:app/custom.ini"))
#else
   if (path_is_valid("custom.ini"))
#endif
      return;

   for (i = 0; i < DEFAULT_DIR_LAST; i++)
   {
      char       *new_path = NULL;
      const char *dir_path = g_defaults.dirs[i];

      if (string_is_empty(dir_path))
         continue;

      new_path = (char*)malloc(PATH_MAX_LENGTH * sizeof(char));

      if (!new_path)
         continue;

      new_path[0] = '\0';
      fill_pathname_expand_special(new_path,
            dir_path,
            PATH_MAX_LENGTH * sizeof(char));

      if (!path_is_directory(new_path))
         path_mkdir(new_path);

      free(new_path);
   }
}
```

Basically checks if there is a custom.ini in the retroarch dir.
If such a file exists it doesn't re-create the internal dirs.

I see there is an android implementation but it's wrong. Also were would custom.ini reside?
Actually for my own personal builds I have RetroArch set to store the global config in the RetroArch dir instead of /sdcard/Android/data/com.retroarch/files.

**Comment by fr500** [comment] 2019-11-24 07:34
Anyway imho this should be a wont't fix. plenty of applicatioons create folders in sdcard.

**Comment by thekiefs** [comment] 2020-05-14 13:05
Ok, but if there is an android implementation why not fix it so it is used correctly? 

And I don't know of many applications that create folders in sdcard when the user has purposefully pointed the application to write to another directory / external card.

**Comment by abouvier** [comment] 2022-05-02 01:17
Duplicate of https://github.com/libretro/RetroArch/issues/4610.

**Closed** 2022-10-04 19:17 UTC

**Comment by cesarpx** [comment] 2023-07-20 18:35
The same problem happens on Mac still in 2023. I defined a custom directory for Retroarch-related saves and updated the corresponding configuration file, but the application keeps creating empty folders in my own personal documents folder.

I don't understand why somebody mentioned this should be a won't fix since it looks this was a previous lazy fix to avoid other problems. But honestly, there should be a way to prevent this from happening. It's also confusing having two RetroArch state folders, the one that I'm currently using, and the other one that gets created automatically.
