### ISSUE TITLE
Keyboard hotkeys no longer work in MSVC builds

### ISSUE THREAD

**Issue by bparker06** [libretro/RetroArch#5856] opened 2017-12-04 18:30 UTC
## Description

Keyboard hotkeys like "f" to switch to fullscreen no longer work in MSVC builds of RetroArch due to the commit b0e383d.

To reproduce this test I'm using MSVC 2010 (The x86 or "Win32" target; I'm told x64 doesn't have this problem but I haven't tried myself) with the solution file in pkg/msvc.

From @hiddenasbestos:

>I'd like to know whether I can use a modern version of MSVC to test this and how to build RetroArch on it.

We have a solution file for MSVC 2015 but I have no idea if it works or exhibits the same issue; to my knowledge nobody really uses it.

### Bisect Results

b0e383d

### Environment information

- OS: Windows 8.1
- Compiler: MSVC 2010 x86

**Comment by hiddenasbestos** [comment] 2017-12-04 21:27
Hi, so the issue is caused by calling RARCH_INPUT_STATE_BIT_GET (which returns a uint32_t value) being stored in a 'bool' - which on MSVC is typedefed from a uchar, discarding anything with a value > 255 in each 'bank' of the 256-bit value struct, which happens to be most of the hotkeys.

The compiler isn't complaining about this loss of data afaict, but that's the cause.

My preference to fix this, go through and find all the times RARCH_INPUT_STATE_BIT_GET is tried to be stored into a bool and make sure it's stored in something uint32_t or bigger.

An alternative fix is to redefine RARCH_INPUT_STATE_BIT_GET in input_defines.c from:

`((a).data [((bit) >> 5)] &   (1 << ((bit) & 31)))`
to
`(((a).data [((bit) >> 5)] &   (1 << ((bit) & 31)))?1:0)`
(and the pointer variant too)

It'd be less efficient, but more robust. It's also inconsistent with the BIT128_ get macro.

Happy to implement either (or a third?) change but didn't want to make the call.

**Comment by bparker06** [comment] 2017-12-04 22:15
Paging @twinaphex and @Alcaro for suggestions.

**Comment by Alcaro** [comment] 2017-12-05 07:29
> The compiler isn't complaining about this loss of data afaict, but that's the cause.

Last time I used MSVC, it whined about the exact opposite: storing a non-1/0 to a bool being a performance loss. This quite strongly implies bool is an actual type.

But I used MSVC in C++ mode, maybe it's different in C mode.

Either way, I'd much rather see that one done right beside the bitbanging. There's a good chance that macro is used elsewhere too, and said elsewheres are bugs too, no point fixing this a dozen times.

I'd also do it via foo[bar>>5]>>(bar&31) & 1 rather than (foo[bar>>5] & 1<<(bar&31))?1:0, it's the same number of operations as the current implementation and should get rid of the performance issues. (I doubt there are any actual perf issues, anyways, unless we're calling that macro a million times per second.)

As for the BIT128 inconsistencies, the solution is simple: fix that one too, there's exactly zero chance any caller expects that kind of absurdities. Or even better, replace RARCH_INPUT_STATE_BIT_GET with a call to BIT128_GET, then fix it.

**Comment by Alcaro** [comment] 2017-12-05 07:41
Fixed BIT128 (and the others in that file), I'll leave the RETRO_INPUT stuff to you. Feel free to add a few more BIT128 functions if you need them.

Now, can someone explain why retro_bits_t is 256 bits when the macros are named BIT128?

**Comment by twinaphex** [comment] 2017-12-05 07:42
I guess we are just lacking BIT256_ macros and the actual type was future proofed by maister to be good up to 256 bits.

**Comment by Alcaro** [comment] 2017-12-05 07:51
Then why not future proof it up to 1024 bits? Or 1048576? Or 1073741824? Or 1152921504606846976?

BIT256 macros would be 100% identical, which is a waste of time. Better rename to BITSET or whatever. If we want anything 256-related, we could split it to structs retro_bit128_t and retro_bit256_t. Or just keep it as is, I doubt saving those bytes would make any difference.

**Comment by twinaphex** [comment] 2017-12-05 07:55
Dunno, maister came up with the implementation. I'd suggest we keep it as is but maybe start using BIT256 macros instead. Right now I am first getting rid of all these RARCH_INPUT_STATE_BIT_SET macros though, since a lot of them now just redirect plainly to BIT128_ equivalents anyway. So I am getting that done first.

**Comment by twinaphex** [comment] 2017-12-05 08:25
Pushed these -

https://github.com/libretro/RetroArch/commit/3ccce249ea3e4fd7f67881d3893818009b0c02e5

https://github.com/libretro/RetroArch/commit/e94300a581ca46975a1a07b9b7424e22b6be7e5f

I now no longer get issues with the MSVC build.

Alcaro - would you approve of me changing all BIT128_ references to BIT256_ then? You say BIT256_ macros would be identical to BIT128_, so this would be fine to do yes?

**Comment by Alcaro** [comment] 2017-12-05 08:32
Personally I'd rather shrink the struct, but clarifying that it's 256 is the safer choice. I'm fine with both.

I also recommend moving the other RARCH_INPUT_STATE_ macros to retro_miscellaneous.h, so nothing outside that file touches the struct member.

**Comment by twinaphex** [comment] 2017-12-05 08:51
Yeah, we could do that.

**Comment by hiddenasbestos** [comment] 2017-12-05 09:37
Hi, in commit: https://github.com/libretro/RetroArch/commit/e94300a581ca46975a1a07b9b7424e22b6be7e5f
the BIT128 macros have been used instead of the RARCH_INPUT_STATE ones. 

The RARCH_INPUT_STATE macros are intended to equal the size of the retro_bits_t struct at all times (256 bits last time I looked). Please feel free to come up with a more generic name for those macros but it's an important feature of them that needs to be preserved. 

Using the BIT128 macros now might solve the problem but will be hard to find in future if you break the 128 binds barrier as you're not then clearing the whole struct.

**Comment by twinaphex** [comment] 2017-12-05 09:39
@hiddenasbestos - I'd rather we move immediately then to 256 bit instead. The struct is already set up for this, would just be a matter of replacing all the references.

I am in the process of moving the defines to retro_miscellaneous.h. You could take it from there if you prefer and I would give you the time to do a PR then.

**Comment by twinaphex** [comment] 2017-12-05 09:44
@hiddenasbestos 

Hi there, this is my last commit for this issue -

https://github.com/libretro/RetroArch/commit/6c09661a643f02b0bb92b7802e41022b759b166c

If you want, you could work from here and make the necessary updates/changes which you feel need to be made, then give us a PR.

**Comment by hiddenasbestos** [comment] 2017-12-05 09:47
I'm not really able to work on this much, I've used up my free time today having this discussion :(

I think I'd just like to see a set of clearer, number-less macros that are always equal to the size of the retro_bits_t. Basically BIT128_CLEAR using sizeof and actually clearing 256 bits is really confusing!

**Comment by hiddenasbestos** [comment] 2017-12-05 10:00
Also having RARCH_INPUT_STATE de-coupled from the other uses means if we need to raise the number of input binds, then you don't have to affect everyone else using it for other things.

**Comment by twinaphex** [comment] 2017-12-05 10:16
To address your last point - I think it's best then we just assume 256 bits right from the get go so that raising the number of input binds becomes moot. I very much doubt we will have to exceed 256 bits anytime soon, so that should be adequate enough.

**Comment by twinaphex** [comment] 2017-12-05 10:16
I will try to change most BIT128_ references to BIT256_ then so that the confusion is taken away.

**Comment by hiddenasbestos** [comment] 2017-12-05 10:25
Thanks - I think I'm probably being overly worried. 256 gives a lot more room to fill.

**Comment by twinaphex** [comment] 2017-12-05 11:11
OK, pushed this commit -

https://github.com/libretro/RetroArch/commit/f0c143766e38fb49d8871125bbfa147b7dcc3f5b

**Comment by hiddenasbestos** [comment] 2017-12-05 11:16
Great. you can see by how many changes that's needed why I was a little cautious - but as I think we've agreed "256 should be enough for anybody" !

I guess you could remove the RARCH_INPUT_STATE macros now? I'd be fine with that.

**Comment by twinaphex** [comment] 2017-12-05 11:19
The RARCH_INPUT_STATE macros which were still necessary have been renamed and moved to retro_miscellaneous.h. The other ones which were unneeded were removed in favor of direct BIT256_ calls.

**Comment by Alcaro** [comment] 2017-12-05 12:03
...there's something strange going on in this issue. Fixing the actual problem was a one-line fix in a single file (plus another four copies of the same issue right nearby).

After that, there's been 17 comments and at least four commits in at least 30 files about cleaning up the code.

I may have to reevaluate some of my statements regarding this codebase.

**Comment by twinaphex** [comment] 2017-12-05 12:17
Pushed another commit which does away with some of those dirty macros and instead just uses the inlined function directly -

https://github.com/libretro/RetroArch/commit/53efad05c6b49fe2b7fd912dfd1677f1b9476516

Also made it use INLINE from retro_inline since say C89 doesn't have the 'inline' keyword, so this makes it still work there.

**Comment by Alcaro** [comment] 2017-12-05 13:50
> Pushed another commit which does away with some of those dirty macros and instead just uses the inlined function directly

The point of keeping it as a macro was not having to type p_input->data twice, nor refer to .data outside retro_misc. But that's your choice, I guess.

Though I do agree that ARRAY_SIZE is an improvement. I would've done that myself if I remembered its name and what header it is in.

> C89 doesn't have the 'inline' keyword

I know there is at least one language where inline is screwy and static inline behaves properly. I thought that was c89, but maybe it's gnu89.

**Comment by twinaphex** [comment] 2017-12-07 06:20
I think we can close this issue now that the situation is resolved.

**Closed by twinaphex** 2017-12-07 06:20 UTC
