### ISSUE TITLE
Sony Dualshock 3 not working via BT

### ISSUE THREAD

**Issue by bootsector** [libretro/RetroArch#5063] opened 2017-06-15 22:59 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Dualshock 3 doesn't work via BT. Ubuntu 15.04 64bit. KMS mode.

### Expected behavior

Expected to see it working, as it does with RA version 1.3.6

### Actual behavior

OSD displays the controller detection correctly, but nothing works (no input working)

### Steps to reproduce the bug

1. Pair the controller using sixpair
2. Push PS button. RA detects it as per OSD message
3. Try to use the joystick. Nothing works.

Keyboard and USB pads work fine.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: commit d25a7497020b76f876ae852e66e404652a3a2179

### Environment information

- OS:
Linux retrobox 4.5.3-040503-generic #201605041831 SMP Wed May 4 22:33:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- Compiler: 
sing built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.2-10ubuntu13' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13)

RA log:
```
RetroArch [INFO] :: This is RetroArch version 1.6.0 (Git d25a749)
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Jun 15 2017
RetroArch [INFO] :: Version: 1.6.0
RetroArch [INFO] :: Git: d25a749
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [Config]: loading config from: /opt/retroarch/config/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "/home/retro/retroarch/saves/.srm".
RetroArch [INFO] :: Redirecting savestate to "/home/retro/retroarch/savestates/.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: [Audio]: Set audio input rate to: 30000.00 Hz.
RetroArch [INFO] :: Found shader "/opt/retroarch/shaders/shaders_glsl/bilinear.glslp"
RetroArch [INFO] :: Found shader "/opt/retroarch/shaders/shaders_glsl/nearest.glslp"
RetroArch [INFO] :: Found shader "/opt/retroarch/shaders/shaders_glsl/stock.glsl"
RetroArch [INFO] :: [Video]: Video @ 1280x720
RetroArch [ERROR] :: [Wayland]: Failed to connect to Wayland server.
RetroArch [INFO] :: [DRM]: Found 3 connectors.
RetroArch [INFO] :: [DRM]: Connector 0 connected: no
RetroArch [INFO] :: [DRM]: Connector 0 has 0 modes.
RetroArch [INFO] :: [DRM]: Connector 1 connected: no
RetroArch [INFO] :: [DRM]: Connector 1 has 0 modes.
RetroArch [INFO] :: [DRM]: Connector 2 connected: yes
RetroArch [INFO] :: [DRM]: Connector 2 has 23 modes.
RetroArch [INFO] :: [DRM]: Connector 2 assigned to monitor index: #1.
RetroArch [INFO] :: [DRM]: Mode 0: (1920x1080) 1920 x 1080, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 1: (1920x1080) 1920 x 1080, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 2: (1920x1080i) 1920 x 1080, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 3: (1920x1080i) 1920 x 1080, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 4: (1920x1080) 1920 x 1080, 50 Hz
RetroArch [INFO] :: [DRM]: Mode 5: (1920x1080i) 1920 x 1080, 50 Hz
RetroArch [INFO] :: [DRM]: Mode 6: (1920x1080) 1920 x 1080, 24 Hz
RetroArch [INFO] :: [DRM]: Mode 7: (1920x1080) 1920 x 1080, 24 Hz
RetroArch [INFO] :: [DRM]: Mode 8: (1400x1050) 1400 x 1050, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 9: (1280x1024) 1280 x 1024, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 10: (1280x720) 1280 x 720, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 11: (1280x720) 1280 x 720, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 12: (1280x720) 1280 x 720, 50 Hz
RetroArch [INFO] :: [DRM]: Mode 13: (1024x768) 1024 x 768, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 14: (800x600) 800 x 600, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 15: (720x576) 720 x 576, 50 Hz
RetroArch [INFO] :: [DRM]: Mode 16: (720x576i) 720 x 576, 50 Hz
RetroArch [INFO] :: [DRM]: Mode 17: (720x480) 720 x 480, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 18: (720x480) 720 x 480, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 19: (720x480i) 720 x 480, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 20: (720x480i) 720 x 480, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 21: (640x480) 640 x 480, 60 Hz
RetroArch [INFO] :: [DRM]: Mode 22: (640x480) 640 x 480, 60 Hz
RetroArch [INFO] :: [GL]: Found GL context: kms
RetroArch [INFO] :: [GL]: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x2d66250.
RetroArch [INFO] :: [KMS]: New FB: 1280x720 (stride: 5120).
RetroArch [INFO] :: [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Iris 6100 (Broadwell GT3) .
RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 10.5.9.
RetroArch [INFO] :: [GL]: Using resolution 1280x720
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: [GLSL]: Checking GLSL shader support ...
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
RetroArch [INFO] :: [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
RetroArch [INFO] :: [Joypad]: Found joypad driver: "udev".
RetroArch [INFO] :: [ALSA]: Using signed 16-bit format.
RetroArch [INFO] :: [ALSA]: Period size: 768 frames
RetroArch [INFO] :: [ALSA]: Buffer size: 3072 frames
RetroArch [INFO] :: [ALSA]: Can pause: yes.
RetroArch [INFO] :: [Menu]: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
RetroArch [INFO] :: [Font]: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/opt/retroarch/config/content_history.rpl].
RetroArch [INFO] :: Loading history file: [/opt/retroarch/config/content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [/opt/retroarch/config/content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [KMS]: New FB: 1280x720 (stride: 5120).
RetroArch [INFO] :: [udev]: Hotplug add: /dev/input/js0.
RetroArch [INFO] :: [udev]: Hotplug add: /dev/input/event10.
RetroArch [INFO] :: [udev]: Plugged pad: PLAYSTATION(R)3 Controller (00:26:43:EF:4F:8B) (0:0) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event10) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event10) supports 16 force feedback effects.
RetroArch [INFO] :: [Autodetect]: 184 profiles found.
RetroArch [INFO] :: [Autodetect]: no profiles found for PLAYSTATION(R)3 Controller (00:26:43:EF:4F:8B) (0/0).
```

**Comment by Zapeth** [comment] 2017-07-29 12:34
Does it work with a different input driver (like sdl)?

> RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?

sounds like your user doesn't have the required permission for the input device files, does it work when you add your user to the `input` group? ([https://askubuntu.com/questions/79565/how-to-add-existing-user-to-an-existing-group)](https://askubuntu.com/questions/79565/how-to-add-existing-user-to-an-existing-group))

Alternatively, do other input methods work (like sdl or x)?

**Comment by orbea** [comment] 2019-01-01 22:11
I'm going to close this as a duplicate of issue https://github.com/libretro/RetroArch/issues/5033.

**Closed by orbea** 2019-01-01 22:11 UTC
