### ISSUE TITLE
Beetle PSX HW works with D3D, not with GL ----> game GRANDIA

### ISSUE THREAD

**Issue by Stefano-82** [libretro/RetroArch#7070] opened 2018-08-12 07:40 UTC
Hello again,

i'm sorry for opening another post, but i asked for the previous to be closed thinking i solved the issue  but the answer i received, before closing it,kinda took me off and explained all the slow downs i'm having probably.

I'm running beetle psx hw and as the title suggests it works with d3d not with GL with which i get a black screen.

The issue i'm having is that with d3d i discovered, reading several issues from other users, that the core works software and not hardware at all, which  explains why on my system slows down a lot at some points(10fps, ussually 30)

My specifications ----> I5 4440(HASWELL),8GB RAM,R9 270X 2GB, WIN 10

I will attach the debug, please can you lend a hand?

[debug retroarch.txt](https://github.com/libretro/RetroArch/files/2280799/debug.retroarch.txt)

Thanks again

**Comment by bparker06** [comment] 2018-08-13 02:13
Duplicate of https://github.com/libretro/beetle-psx-libretro/issues/322, this is a known issue with AMD cards.

**Closed** 2018-08-13 02:13 UTC
Labels: invalid: duplicate
