### ISSUE TITLE
BSV recording command code seems wrong

### ISSUE THREAD

**Issue by JoeOsborn** [libretro/RetroArch#14870] opened 2023-01-19 19:44 UTC
https://github.com/libretro/RetroArch/blob/d689a84581c02e7ec76a05eace0723f5ddd5b791/retroarch.c#L2152-L2162

I'm looking into adapting RetroArch for an application that includes input recording and replay, and I'm a bit confused as to why BSV recording seems to trigger command events for toggling video recording.  I don't think those command events should be sent at all, since it seems like `bsv_movie_check` already toggles the recording state for BSV.  If the intent is that BSV recording always comes with video recording, then instead of toggling the video record state it should be forced to match the BSV record state based on the result of `bsv_movie_check`.  But I think those two recording states should be kept separate, since I may want to record BSV but not video.

**Comment by LibretroAdmin** [comment] 2023-01-19 20:01
The BSV code hasnt been tested for a long time so any changes/prs you have there to improve it would be much appreciated

**Comment by LibretroAdmin** [comment] 2023-01-19 20:02
And yes, i believe uncoupling video recording from BSV recording is indeed what we should need

**Comment by JoeOsborn** [comment] 2023-01-19 23:07
Removing the event triggers for video recording did suffice, but now I’m having trouble testing that BSV record and replay work. In Super Mario Bros under fceumm, I see rapid jittering under replay of a trace recorded in RA—so either multiple inputs are recorded in the BSV for each frame during recording (possibly regular inputs plus empty inputs), or the BSV inputs are being interleaved with some other inputs during replay (maybe the controller or maybe empty inputs).

I’m trying to figure out the flow through input_driver.c (the internal and wrap functions particularly) which write and/or read from BSV. Is there any documentation or a person to ask about that?

**Comment by LibretroAdmin** [comment] 2023-01-20 01:12
I think the last person to work on this was @Themaister in 2010-2012 but I'm not sure to what degree he still understands the source code as it exists right now. It's likely that some changes need to be made along the way for BSV to correctly work.

**Comment by hizzlekizzle** [comment] 2023-01-20 03:36
Hmm, I just tested it and there's definitely been some regression in bsv recording at some point, as it desyncs pretty quickly even on snes9x.

To learn about how bsv recordings are supposed to work, it actually might be easiest to look at old bsnes source code, since that's where it originated, though it stopped being a thing there after circa v073, IIRC. It's supposed to be a savestate plus button/frame log, with the savestate ensuring coherence.

Since there's no 'upstream' for bsv anymore, and they've been broken for some unknown amount of time here, I don't think there's much inertia to any sort of changes.

**Comment by JoeOsborn** [comment] 2023-01-20 04:01
Thanks! I only tested my patch #14871 against fceumm, I’ll check how it behaves in other emulators soon.

I also wondered about replacing the bsv playback and recording code outright using a format like bk2 or something—but that seems like a bigger change that would want some design and integration work, especially if (as the comments in input_driver.c suggest) the input reading code is due for rework. Where do discussions like those take place?

**Comment by LibretroAdmin** [comment] 2023-01-20 15:34
Maybe on #programming on Discord but I'd hold off for now on outright replacing entire parts with some new NIH scheme. Instead, I'd advocate first fixing what remains to be fixed in the current codebase. And once things are stable there, then moving onto the next thing. That is a far safer strategy with less regressions along the way.

So I'd prefer for now the strategy first of fixing what remains fixing on BSV before we move onto the next thing.

**Comment by JoeOsborn** [comment] 2023-01-20 16:06
Yes, I agree.  BSV as a format has some unfortunate limitations (e.g. no metadata like emulator version or ROM CRC, not handling resets, maybe won’t work for mouse and keyboard input, etc) so eventually a new format will be needed for record/replay. Maybe at that time some refactor of the input system could happen to smooth out collecting from the different sources for inputs, but it’s not happening as part of my work on “fixing” BSV for the simple case.

**Closed** 2023-01-20 17:20 UTC
