### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#4829] opened 2017-04-17 16:02 UTC
When starting up RetroArch, all three connected monitors goes black screen for a short time (less than 1 second) until XMB is displayed. Even if Windowed Fullscreen Mode is enabled. Turning off that setting (change to true full screen mode) will cause that problem when exiting rather than at starting up and Black screen time extends to around 2 seconds. Alt + Tab is stressful. In either case, I think that this problem is due to RetroArch and the desktop use different refresh rates. Is it due to RetroArch's design, or can it be solved by changing the refresh rate value?

Links that may be helpful
[Windows 10 refresh rate issues](http://forums.guru3d.com/showthread.php?t=401883)

### Version/Commit

- RetroArch: 1.5.0

### Environment information

- Windows 10 Pro 64bit 1607
- SAPPHIRE NITRO R9 390X with Backplate
- DELL U2414H 1920x1080@59Hz via DVI-HDMI (Primary)
- DELL U2414H 1920x1080@59Hz via HDMI
- DELL U2414H 1920x1080@59Hz via DIsplayPort
- Radeon Crimson ReLive 17.2.1 WHQL

（日本人です）

**Comment by bparker06** [comment] 2017-04-18 01:38
Hi @waitingmoon,

If your monitors are going black (changing modes) on startup with Windowed Fullscreen turned on, that is definitely a bug... this should not happen regardless of your monitor resolution. Just to clarify, is alt+tab slow (and also causing a mode change/black screen) with windowed mode on also? Can you paste a full log output (run with --verbose)? The default framerate in RetroArch is 59.94 which should be the same thing your monitors are using.

Can you also try the latest [nightly](http://bot.libretro.com/nightly/windows/x86_64/) build and see if the issue is still there?

**Comment by waitingmoon** [comment] 2017-04-18 13:40
I tested on the fresh install of latest nightly build. However, the black screen problem is not solved.

Behavior when Windowed Fullscreen Mode is enabled
- Starting up: all three monitors are going black screen for a short time. (less than 1s). It is a feeling that a black frame is inserted for a moment on all the monitors rather than switching the refresh rate.
- Alt + Tab: same as above.

Behavior when Windowed Fullscreen Mode is disabled
- Starting up: the black screen problem not occurs.
- Alt + Tab:  all three monitor are going black screen for around 2s.  I heard a relay sound from the monitor.

-v result is follows as (launch and quit immediately)

C:\Users\****\Desktop\RetroArch>RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 7104d32)
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Apr 17 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 7104d32
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "C:\Users\****\Desktop\RetroArch\saves\.srm".
RetroArch [INFO] :: Redirecting savestate to "C:\Users\****\Desktop\RetroArch\states\.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: [Audio]: Set audio input rate to: 29970.03 Hz.
RetroArch [INFO] :: [Video]: Video @ fullscreen
RetroArch [INFO] :: [GL]: Found GL context: wgl
RetroArch [INFO] :: [GL]: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: ATI Technologies Inc., Renderer: AMD Radeon (TM) R9 390 Series.
RetroArch [INFO] :: [GL]: Version: 4.5.13469 Compatibility Profile Context 21.19.519.2.
RetroArch [INFO] :: [GL]: Using resolution 1920x1080
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: [GLSL]: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GLSL]: Found GLSL vertex shader.
RetroArch [INFO] :: [GLSL]: Found GLSL fragment shader.
RetroArch [INFO] :: [GLSL]: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {02FF} VID:{045E}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: [Autodetect]: 40 profiles found.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: XAudio2: Requesting 64 ms latency, using 64 ms latency.
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [C:\Users\****\Desktop\RetroArch\content_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Users\****\Desktop\RetroArch\content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Users\****\Desktop\RetroArch\content_video_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Users\****\Desktop\RetroArch\content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [ERROR] :: failed_to_start_audio_driver
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [INFO] :: Saved new config to "C:\Users\****\Desktop\RetroArch\retroarch.cfg".
RetroArch [INFO] :: Trying to write to playlist file: C:\Users\****\Desktop\RetroArch\content_history.lpl
RetroArch [INFO] :: Trying to write to playlist file: C:\Users\****\Desktop\RetroArch\content_video_history.lpl
RetroArch [INFO] :: Trying to write to playlist file: C:\Users\****\Desktop\RetroArch\content_music_history.lpl
RetroArch [INFO] :: Trying to write to playlist file: C:\Users\****\Desktop\RetroArch\content_image_history.lpl
RetroArch [INFO] :: [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

**Comment by bparker06** [comment] 2017-04-18 16:39
Ok, so it doesn't appear to be trying to actually switch the resolution, or the log would have said "changing resolution to XX". Can you try an [MSVC](http://bot.libretro.com/nightly/windows-msvc2010/x86_64/) build and see if the same issue happens there?

I just tried on a Windows 10 laptop with both a second and third display connected, and I didn't see any black screen at all on any monitor when starting up in windowed fullscreen.

**Comment by waitingmoon** [comment] 2017-04-19 08:39
There is no black screen problem in MSVC build. 

Also, I rolled back the graphics driver to Crimson 16.9.2 because Crimson ReLive is known to have many bugs, in particular R9 390 series. In this driver, tested on RetroArch 1.5.0 stable, the black screen problem occurs only when starting up RetroArch for the first time after turning on the PC.

**Comment by RobLoach** [comment] 2017-10-25 15:36
This should be fixed. Mind testing on the latest?

**Comment by twinaphex** [comment] 2018-10-18 04:34
@waitingmoon I assume this is fixed?

**Comment by waitingmoon** [comment] 2018-10-18 09:34
@twinaphex Yes, Its already fixed. This issue is probably related to intializing process on old Radeon driver

**Comment by orbea** [comment] 2018-12-24 06:09
As this seems to no longer be a problem I am going to close this issue, please let us know if you have any further problems!

**Closed by orbea** 2018-12-24 06:09 UTC
