### ISSUE TITLE
core autodetection when started from the cmdline

### ISSUE THREAD

**Issue by eadmaster** [libretro/RetroArch#1704] opened 2015-05-18 13:31 UTC
When retroarch is started from the commandline with a ROM file passed as argument is it possible to have the correct core auto-selected?
(like when using "Load Content (Detect Core)" in the RGUI)

**Comment by fr500** [comment] 2015-10-09 19:09
What if there's more than one usable core?

**Comment by eadmaster** [comment] 2015-10-10 15:05
in this case the GUI is started and the core selection dialog is shown...

**Comment by AnthraxLeprosyPi** [comment] 2016-11-17 13:40
Any update on this?

**Comment by fr500** [comment] 2016-11-17 16:04
its's a feature request, doesn't mean it's gonna be implemented

**Comment by AnthraxLeprosyPi** [comment] 2016-11-18 08:53
Yeah, I was just curious.

The problem is whenever I looked into some quick old school gaming fun in the last 15 years or so I ended up loosing all my precious time by tinkering with obscure settings and reading hundreds of forum posts before ever starting a game.

So it was just a short glimmer of hope...

best regards
Anthrax

**Comment by RobLoach** [comment] 2018-07-29 19:52
Duplicate of https://github.com/libretro/RetroArch/issues/746 .

**Closed by RobLoach** 2018-07-29 19:52 UTC
Labels: followup: enhancement
