### ISSUE TITLE
Touch input broken on 1.16.0 from F-Droid

### ISSUE THREAD

**Issue by eengnr** [libretro/RetroArch#15757] opened 2023-10-01 09:34 UTC
## Description

After updating from 1.15.0 to 1.16.0 with F-Droid touch input on Android 13 / Pixel 7 doesn't work anymore. Only a USB controller works.

### Expected behavior

Touch input is working

### Actual behavior

Touch input is not working

### Steps to reproduce the bug

Install 1.16.0 on Pixel 7 with Android 13.
Not reproducible on Pixel 3XL with Android 12

### Version/Commit

- RetroArch: 1.16.0
Probably related to this change?
https://github.com/libretro/RetroArch/commit/18414cf526abb759036ecfc1a9bf56335f5555c5

### Environment information

- OS: Android 13 on Pixel 7

**Comment by sonninnos** [comment] 2023-10-01 12:59
That change can't possibly affect anything like that. It only changes the menu default scale.

**Comment by eengnr** [comment] 2023-10-01 17:54
Well it's really strange... if I wipe the app completely and reinstall it, I cannot navigate out of the main menu with touch. The only possibility is to attach the gamepad with USB. Then I can use the d-pad to e.g. switch to the settings menu. But A/B buttons are mapped incorrectly by default, i.e. I also cannot enter any menu with the gamepad. Scrolling however is possible with touch after switching to the settings menu. But it's not possible to select any menu entry... and it feels like scrolling is "absolute". I cannot scroll down completely. No matter where I tap on the screen, the "Playlists" settings menu entry always scrolls to the touch position.
If I switch to another Android app and then back to RetroArch, I can select one menu entry with touch. But only one. Then the weird scrolling continues.

Really weird... 1.15.0 doesn't show this behavior.

**Comment by eengnr** [comment] 2023-10-02 06:05
I managed to get startup logs from 1.15.0 and 1.16.0 Nightly:

1.15.0 (working)
```
Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch/cores/" instead.
RetroArch 1.15.0 (Git 6616b807ed)
=== Build =======================================
Fähigkeiten: ASIMD
[INFO] Built: Apr 29 2023
[INFO] Version: 1.15.0
[INFO] Git: 6616b807ed
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version der Libretro-API: 1, Kompiliert gegen API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x78c494b990.
[GL]: Vendor: ARM, Renderer: Mali-G710.
[GL]: Version: OpenGL ES 3.2 v1.r38p1-01eac0.55eb2d40cce8f18c0f57f61c686a946f.
[GL]: Using resolution 1080x2264.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 512, Blocks = 48, Total = 24576 ...
[Display]: Found display driver: "gl".
[Playlist]: Verlaufs-Datei wird geladen: "/storage/emulated/0/RetroArch/playlists/content_history.lpl".
[Playlist]: Verlaufs-Datei wird geladen: "/storage/emulated/0/Android/data/com.retroarch/files/content_music_history.lpl".
[Playlist]: Verlaufs-Datei wird geladen: "/storage/emulated/0/Android/data/com.retroarch/files/content_image_history.lpl".
[Playlist]: Favoritendatei wird geladen: "/storage/emulated/0/RetroArch/playlists/content_favorites.lpl".
```

1.16.0 (not working)
```
Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch.aarch64/cores/" instead.
RetroArch 1.16.0 (Git 14cb373)
=== Build =======================================
Fähigkeiten: ASIMD 
[INFO] Version: 1.16.0
[INFO] Git: 14cb373
[INFO] Built: Oct  1 2023
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Version der Libretro-API: 1, Kompiliert gegen API: 1
[Core]: Geometry: 320x240, Aspect: 1.333, FPS: 60.00, Sample rate: 48000.00 Hz.
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
Android EGL: GLES version = 2.
[EGL] Falling back to eglGetDisplay
[EGL]: EGL version: 1.4
[GL]: Found GL context: "egl_android".
[GL]: Detecting screen resolution: 0x0.
[EGL]: Current context: 0x78c494cf80.
[GL]: Vendor: ARM, Renderer: Mali-G710.
[GL]: Version: OpenGL ES 3.2 v1.r38p1-01eac0.55eb2d40cce8f18c0f57f61c686a946f.
[GL]: Using resolution 1080x2264.
[GL]: Default shader backend found: glsl.
[Shader driver]: Using GLSL shader backend.
[GL]: Stock GLSL shaders will be used.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GLSL]: Found GLSL vertex shader.
[GLSL]: Found GLSL fragment shader.
[GLSL]: Linking GLSL program.
[GL]: Using 4 textures.
[GL]: Loaded 1 program(s).
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 512, Blocks = 48, Total = 24576 ...
[Audio]: Started synchronous audio driver.
[Display]: Found display driver: "gl".
[Playlist]: Verlaufs-Datei wird geladen: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_history.lpl".
[Playlist]: Verlaufs-Datei wird geladen: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_music_history.lpl".
[Playlist]: Verlaufs-Datei wird geladen: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_image_history.lpl".
[Playlist]: Favoritendatei wird geladen: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_favorites.lpl".
```

Only the additional Geometry line seems to be different.
Is there anything else I should check or provide logs?

**Comment by zzedmore** [comment] 2023-10-09 18:50
Sounds similar to this issue I reported https://github.com/libretro/RetroArch/issues/15672

Good luck getting anything fixed !

**Comment by ItsRogueRen** [comment] 2023-10-12 07:45
Just installed for the first time (f-droid) and I have the exact same issue, touch inputs do absolutely nothing making the entire app useless.

**Comment by GraithTiger** [comment] 2023-10-12 20:08
Same issue here on Pixel 7. Both the website apk and the F-Droid version. 1.15.0 works fine.

**Comment by hizzlekizzle** [comment] 2023-10-13 18:36
Can you try installing the oldest nightly build available from buildbot.libretro.com? It doesn't go back very far, but it's better than nothing. A true bisect would be optimal, of course.

**Comment by eengnr** [comment] 2023-10-15 16:04
The oldest nightly is from 02.10., but the 1.16.0 release is from 30.09.
Why should installing the oldest nightly make a difference? The issue is already in it.

**Comment by hizzlekizzle** [comment] 2023-10-15 21:23
ah, looks like the older ones already got flushed. bummer. guess someone who can both build and reproduce the issue will need to track it down.

**Comment by Lolight2** [comment] 2023-11-03 21:05
Any news on this? It is still broken for me on the newest nightlies :(

**Comment by gamer85** [comment] 2023-12-16 12:48
I can confirm same broken navigation issues on a Samsung Galaxy S23 FE upon updating to Android 14 today.

**Comment by Qwertyto** [comment] 2023-12-28 15:02
I've got the same issue on Galaxy S23 android 14, but I guess I should do a complete form thing just in case:

Description:
When I open the app, I attempt to tap on the options, but the tapping only triggers a scrolling action while still highlighting the option I am attempting to select.

Expected Outcome:
I tap on an option and it registers as selecting the option, taking me to the next corresponding menu.

Actual Outcome:
I tap on a option and it simply scrolls weirdly depending on where I tap on the screen.

I hope this issue gets fixed in the stable fdroid versions, which is what I am currently using.

**Comment by bidinou** [comment] 2024-02-09 08:34
Hi ! What happens here is that touch input works. Until a USB-C controller is connected. Android 14 here.

**Comment by humandib** [comment] 2024-02-20 19:56
> Hi ! What happens here is that touch input works. Until a USB-C controller is connected. Android 14 here. I opened a new bug about this issue, in more general terms.

Hello! New to the Android scene. I have a Nothing Phone 1 and experience this issue for the first time when I upgraded my device to version 14. Retroarch seem to override the touchscreen when input devices are detected; however, I'm not using any external controllers. What I did find was that my bluetooth headphones, SkullCandy Crushe ANC 2, are detected by my Android device as an input device. I went to the settings on the bluetooth, disabled the Input Device option, and Retroarch detected the touchscreen input again.
![Screenshot_20240220-155525](https://github.com/libretro/RetroArch/assets/13650603/00279f28-575c-422c-9ac6-926c0f3c6bbe)

**Comment by robotics13** [comment] 2024-02-28 01:27
Hi, have the same issue here with Galaxy S21 FE and Galaxy Tab S8, both worked fine until the android 14 and One UI 6 update. I have noticed what I have connected and how it is connected makes a difference in whether or not the touch input is bugged.

Symptoms:

On the menu screens when touch is bugged, it will jump the scroll position of the menu to an absolute position. If I touch near the bottom of the screen, it jumps the screen to the top of the menu. If I touch near the top of the screen it jumps the screen to the bottom of the menu.

In games with the overlay, tapping an on screen button registers and shows the button press but acts like I am holding down the button.

#### Galaxy S21 FE

Android 14  
One UI 6.0  
CPU Snapdragon 888 5G  
Retroarch version 1.16.0 Google Play

| Configuration | Touch Behavior |
| --- | --- |
| Just the phone, no peripherals | Works as expected |
| Xbox controller over bluetooth | Bugged |
| Xbox controller over USB | Works as expected |
| Keyboard over USB | Bugged |
| Keyboard over USB + Xbox controller over bluetooth | Bugged |
| Keyboard and Xbox controller over USB | Bugged |
| USB to 3.5mm headphone adapter | Bugged |
| Logitech USB gamepad | Works as expected |
| USB Ethernet Adapter | Works as expected |

Plugging and unplugging USB devices while Retroarch is running seems to change the touch behavior live. I can connect and disconnect the keyboard and break/un-break touch on demand.

#### Galaxy Tab S8

Android 14  
One UI 6.0  
CPU Snapdragon 8 Gen 1  
Retroarch version 1.17.0 APK from Retroarch website

| Configuration | Touch Behavior |
| --- | --- |
| Just the phone, no peripherals | Works as expected |
| Xbox controller over bluetooth | Bugged |
| Xbox controller over USB | Works as expected |
| Keyboard over USB | Bugged |
| Keyboard cover over pogo-pins | Bugged |
| Keyboard over USB + Xbox controller over bluetooth | Bugged |
| Keyboard and Xbox controller over USB | Bugged |
| USB to 3.5mm headphone adapter | Bugged |
| Logitech USB gamepad | Works as expected |
| USB Ethernet Adapter | Works as expected |

I also tested with a really outdated Pixel 3A with the 1.17.0 version of Retroarch APK from the website and touch works as expected with the Xbox controller over blutetooth. Not a true comparison but more data.

Non-gamepad input devices over USB seem to bug out touch on Retroarch, the keyboard cover, USB keyboard, and 3.5mm headphone adapter (mic input). While USB gamepad devices work as expected.

I looked at the Retroarch logs but even on debug level they are identical whether or not the Xbox controller is connected over Bluetooth or not at all.

**Comment by zzedmore** [comment] 2024-02-28 09:56
I also reported a very similar issue https://github.com/libretro/RetroArch/issues/15672 and even posted a video at the bottom but no reply. I gave up asking. I'm now stuck on a stable build that works but can never update because of this issue. 😢 You can't even assign a pause hotkey to a controller on Android because Retroarch freaks out. That hasn't been fixed ever. Oh well.

**Comment by LibretroAdmin** [comment] 2024-02-28 15:28
Probably because we either don't have your specific phone, can't reproduce it, or we simply don't know how to fix the issue and are reliant on PR submitters to help fill the gap.

**Comment by LibretroAdmin** [comment] 2024-02-28 15:29
It seems in your case you're using some kind of Android game handheld device? I'm not sure what device that is and you'd prob have to provide more information. Either way, methinks that the actual issue lies with this device and the Android implementation and driver support. On regular Android phones and tablets touch input doesn't seem to be an issue.

**Comment by robotics13** [comment] 2024-02-28 15:57
I agree the android driver implementation probably changed at some point. The Galaxy One UI 6.0 is clunky to be nice and I noticed the issue right after the update, was running Retroarch 1.16.0 from the Play store before and after the update so something in Android itself changed.

I'm trying to build a version with the changes from #15672 removed to see if that makes any difference.

I did download the 1.15.0 version from Buildbot and touch works as expected with an Xbox controller over bluetooth and the Galaxy keyboard connected. The S pen does exhibit the buggy behavior that pull request fixed.

Is there additional information we could provide that would help identify the issue?

**Comment by LibretroAdmin** [comment] 2024-02-28 18:46
Wel lfirst of all what hardware are you running this on, what Android OS version, etc?

**Comment by zzedmore** [comment] 2024-02-29 13:01
> Wel lfirst of all what hardware are you running this on, what Android OS version, etc?

I'm using a Retroid Pocket 2+ handheld with Android 10. I upgraded to Android 11 and the touch issue is still there. Not sure what the others are using. Also, the pause controller hotkey https://github.com/libretro/RetroArch/issues/9998 has never been fixed on any Android device.

**Comment by ThunderDragonRandy** [comment] 2024-03-04 01:40
> Wel lfirst of all what hardware are you running this on, what Android OS version, etc?

Android 14 here with the Samsung Galaxy S22 Ultra. Among 4 controllers I tested on it so far in RetroArch v1.16 and v1.17—Backbone One, 8bitdo SN30 Pro 2, GameSir G8 Galileo, and Razer Raiju—the touchscreen works fine with the Razer Raiju but not with any other controller. When I use any controller on my Android phone other than the Razer Raiju, the touchscreen is allowed to be touched once but any further taps become unresponsive. Fortunately, you can still scroll through the menus with the touchscreen but that is it while a controller is connected on Android.

Controllers + Touchscreen on Android worked fine in RetroArch v1.15, but the touchscreen issues with controllers happen in v1.16 or v1.17 with certain (or most?) controllers.

**Comment by nvitaterna** [comment] 2024-03-12 17:52
I'm experiencing the same issue on my S22 Ultra with a Gamesir G8. Touch works fine until the controller is plugged in.

**Comment by stefan-girlich** [comment] 2024-03-31 19:38
Issue confirmed on Nothing Phone 1, Android 14, Razer Kishi V2 as USB controller

**Comment by arnaullv** [comment] 2024-04-03 18:33
These are the commits between 1.15 16/03/2023 and 1.16 release 21/09/2023
https://github.com/libretro/RetroArch/commits/master/?since=2023-03-16&until=2023-09-21&before=cdd6aed8ec1607df44fdfb02b96a53dee85ff74d+560

Around here there are commits related to touch drivers...
https://github.com/libretro/RetroArch/commit/42c0c7ee2b173293c701e27933f29a86590c128b

Maybe someone can try to compile a version not including these commits to try to track down when the issue was introduced. I'm trying it but I promise nothing...
https://docs.libretro.com/development/retroarch/compilation/android/

**Comment by DavidRGriswold** [comment] 2024-04-19 02:07
Just another voice to say that I too have this issue, with 1.17.2 installed today on an up to date Galaxy S21 FE. I am using an 8bitdo micro, and this issue happens if I have the device in keyboard mode or dinput mode but it does NOT happen if I pair it in switch mode.

**Comment by starjunn99** [comment] 2024-05-31 23:04
I have same issue 1.15.0 works fine but anything higher i cant tap to screen menus only slides up and down (not using any controller just phone)

Samsung A05S / Android 14 / one ui 6.0

**Comment by starjunn99** [comment] 2024-06-05 10:36
Issue still exist on 1.19.1 still bugged and not usable at all.

**Comment by arnaullv** [comment] 2024-06-08 13:43
> These are the commits between 1.15 16/03/2023 and 1.16 release 21/09/2023 https://github.com/libretro/RetroArch/commits/master/?since=2023-03-16&until=2023-09-21&before=cdd6aed8ec1607df44fdfb02b96a53dee85ff74d+560
> 
> Around here there are commits related to touch drivers... [42c0c7e](https://github.com/libretro/RetroArch/commit/42c0c7ee2b173293c701e27933f29a86590c128b)
> 
> Maybe someone can try to compile a version not including these commits to try to track down when the issue was introduced. I'm trying it but I promise nothing... https://docs.libretro.com/development/retroarch/compilation/android/

Ok, Finally I achieve to set up my build environment.

I compiled 1.19 version which doesn't work, and later I compiled a version between 1.15 and 1.16 passed the mentioned touch related commits and it still works.
As a summary, until commit, 189542ea5f Prevent the android quick tap mouse click emulation while pressing a button on the on-screen overlay (1st June 2023), it still works.
I keep trying to track down when the bug was introduced.

**Comment by hizzlekizzle** [comment] 2024-06-08 20:11
Awesome, this is exactly what we need.

Based on your findings, I *strongly* suspect this is the culprit: https://github.com/libretro/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527

Can you verify whether it works before that one and then breaks after?

**Comment by arnaullv** [comment] 2024-06-08 20:32
Yeah that could be it, as it is related with inputs... I will let you know... compiling...

**Comment by arnaullv** [comment] 2024-06-08 21:03
I can confirm this is the commit that breaks all touchpads when an USB Controller is connected

abcd42777f refactor: rewrite input handling to better support AINPUT_SOURCE_STYLUS (#15597)

This commit should be reverted and apply S-Pen Samsung stylus when it's properly implemented or the fixes do not break other stuff. Any developer can apply the revert of abcd42777f ?

**Comment by arnaullv** [comment] 2024-06-09 07:52
If we revert abcd427, probably this [android] fix d-pad regression introduced in https://github.com/libretro/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527 (https://github.com/libretro/RetroArch/pull/15601) needs to be reverted as well as it intended to fix some of the mess abcd427 created.

**Comment by hizzlekizzle** [comment] 2024-06-09 16:28
Can anyone here try this build? https://github.com/hunterk/RetroArch/actions/runs/9437129093/artifacts/1583131332

**Comment by ThunderDragonRandy** [comment] 2024-06-09 17:02
> Can anyone here try this build? https://github.com/hunterk/RetroArch/actions/runs/9437129093/artifacts/1583131332

Yes. So far, there are no touchscreen issues when I have my Galileo G8 plugged into my Galaxy S21 Ultra (my backup phone for testing) when using this build. 👍 Testing my Backone One: PlayStation Edition controller on my Galaxy S21 next, no issues either. 👍 And testing my Razer Raiju (which was the only one I had that worked fine in the latest main version of RetroArch for Android), also no issues here. 👍

**Comment by arnaullv** [comment] 2024-06-09 17:51
> Can anyone here try this build? https://github.com/hunterk/RetroArch/actions/runs/9437129093/artifacts/1583131332

I can also confirm that no touchscreen problems on Anbernic RG405M

**Comment by hizzlekizzle** [comment] 2024-06-09 18:48
Awesome. Thanks for testing, gang. I'll put a PR in for it.

**Comment by starjunn99** [comment] 2024-06-10 20:39
Fixed for Samsung A05S series as well thanks.

**Comment by zzedmore** [comment] 2024-06-11 11:34
Confirmed fixed. This also closes my issue https://github.com/libretro/RetroArch/issues/15672 Only took 9 months! Thanks to @arnaullv for the extensive testing and @hunterk. I wonder if you Android owners have ever tried to map the 'Pause' key to a controller button ? https://github.com/libretro/RetroArch/issues/14200 This hasn't worked since day 1 of Retroarch. Maybe in a few years time it will get fixed but I doubt it. 😄

**Comment by gouchi** [comment] 2024-06-11 11:47
@eengnr Please close this issue.

Thank you.

**Closed** 2024-06-11 12:00 UTC

**Comment by chamezard** [comment] 2024-06-14 00:22
Nice, finally it's finished (y)
