### ISSUE TITLE
crash on exit when auto save state and achievements enabled

### ISSUE THREAD

**Issue by wec22** [libretro/RetroArch#11081] opened 2020-07-26 15:40 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When both auto save/load state is enabled as well as retro achievements are enabled attempting to exit using esc causes the program to hang.  This occurs across all cores I have tried and several different games in each core.  Only occurs on games that actually have achievements.

### Expected behavior

clean exit

### Actual behavior

hangs and stops responding on exit

### Steps to reproduce the bug

1. enable auto save/load
2. enable achievments and login
3. launch game with achievements
4. exit retroarch without closing content

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.9

### Environment information

- OS: Windows (have not tested other platforms)

**Comment by Jamiras** [comment] 2020-07-26 22:43
duplicate of #10943

**Closed** 2022-09-03 12:31 UTC
