### ISSUE TITLE
Unable to open/browse folder when filename contains a supported extension

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#6725] opened 2018-05-05 09:33 UTC
First and foremost consider this:
Only RetroArch bugs should be filed here. Not core bugs or game bugs
This is not a forum or a help section, this is strictly developer oriented
Description
When browsing a folder with name thats a combination of an existing supported extension, the folder will be empty (expecting this to be a supported file rather than a folder)

Expected behavior
regardless of filename as long as its supported characters, it should open

Actual behavior
actual contents of folder not shown

Steps to reproduce the bug
create a folder name that contains a supported file format and add some stuff to it. filename should have a "." and the supported extension. Example: foldername : FBAlpha 0.2.97.43 (torrentzipped)
open that folder
you should not be able to see contents as retroarch probably assuming this to be a supported extension rather than a folder
Bisect Results
![1111](https://user-images.githubusercontent.com/23315382/39661794-57a70c94-508a-11e8-89f8-7f77765f9b1d.png)

the same folder with "." removed:
![2222](https://user-images.githubusercontent.com/23315382/39661798-61f7d0de-508a-11e8-91f3-d1f4aadb5f35.png)

Version/Commit
You can find this information under Information/System Information

RetroArch: 1.7.3 commit 2771f8cc41
Environment information
OS: linux arch
Compiler: gcc version 7.3.1 20180312 (GCC)

**Comment by orbea** [comment] 2018-05-05 13:46
Can you try git bisecting this?

**Comment by retro-wertz** [comment] 2018-05-05 13:51
this has been actually happening since the qt browser is introduced in
nightly...

**Comment by orbea** [comment] 2018-05-05 13:52
So it didn't occur before this PR was merged? https://github.com/libretro/RetroArch/pull/6668

**Comment by retro-wertz** [comment] 2018-05-05 14:02
not sure what exact pr was, but ive only tested this QT thing since a few
days ago when it got merged with the nightlies(windows version was crashing
since qt libraries were not included), and that has been something i noticed

**Comment by fr500** [comment] 2018-05-05 15:14
You mean the problem is the zip in torrent**zip**ped?

**Comment by retro-wertz** [comment] 2018-05-05 15:15
th combination of a "." and a supported extension( for this example zip in
"torrentzip"

**Comment by i30817** [comment] 2018-05-06 07:26
Another case of bad substring usage?

**Comment by i30817** [comment] 2018-05-06 07:43
It can't be a bad use of `strstr` and `const char *file_path_str(enum file_path_enum enum_idx)` because all uses of zip on that function include the dot https://github.com/libretro/RetroArch/blob/e7272ddefacc0a3f9a160e3d5cb5777a6aba41dc/file_path_str.c#L149

Must be some homebrew 'file' check that doesn't bother with the dot.

**Comment by orbea** [comment] 2019-01-03 20:56
@retro-wertz I think this is fixed, can you confirm?

![1](https://i.imgur.com/WMRlUi7.png)

**Comment by retro-wertz** [comment] 2019-01-03 23:01
nah...

![screenshot_2019-01-04_06-59-45](https://user-images.githubusercontent.com/23315382/50666189-7de05e00-0fee-11e9-9a90-0ceb8a925ae6.png)

**Comment by orbea** [comment] 2019-01-03 23:31
Yes, that's it. I renamed `test.sfc` to `test.zip` and now I can reproduce your issue.

**Comment by orbea** [comment] 2019-01-04 00:09
I went back to `v1.3.6` without finding a good commit.

**Comment by i30817** [comment] 2019-01-04 00:23
I fixed something similar in https://github.com/libretro/RetroArch/pull/6496 but i don't think this is the same. In that case it was skipping showing the dir itself on the parent dir (because any dot in the filename was filtered).

**Comment by orbea** [comment] 2019-01-04 00:44
Its probably more general, see.

https://github.com/libretro/RetroArch/blob/e7272ddefacc0a3f9a160e3d5cb5777a6aba41dc/file_path_str.c#L149

I was also able to reproduce it with `.7z`, but not `.rgb` or `.mp3`.

**Comment by i30817** [comment] 2019-01-04 01:00
Yeah i already linked that. That is *really* weird because what it uses to recognize zip is ".zip"... which means something is bypassing that check if "FBAlpha 0.2.97**.**43 (torrent**zip**ped)" is being recognizes as a mountable zip.

**Closed** 2023-11-05 09:05 UTC
Labels: bug: minor

**Comment by zoltanvb** [comment] 2023-11-05 09:07
This was fixed somewhere along the way. I can open a directory called "FBAlpha 0.2.97.43 (torrentzipped)" normally in current RA. Can be closed, I guess.
