### ISSUE TITLE
Retroarch crashes starting Mupen64Plus

### ISSUE THREAD

**Issue by Makaque** [libretro/RetroArch#7610] opened 2018-11-18 18:31 UTC
## Description

I'm trying to set up an old laptop as a retro gaming machine. 

Retroarch crashes when trying to load a game using the Mupen64Plus core. Mupen64Plus runs properly on my system as a standalone program. It only crashes through Retroarch

### Expected behavior

Retroarch to load and play the game

### Actual behavior

Game window flashes black on the screen and immediately closes.

### Steps to reproduce the bug

1. Launch retroarch
2. Load content
3. Navigate to ROMs folder
4. Select 1080 Snowboarding
5. Select Mupen64Plus

### Bisect Results

It's never worked

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Frontend for libretro -- v1.7.5 -- c9c6c5a --
Compiler: GCC (7.3.0) 32-bitBuilt: Oct  2 2018

### Environment information

- OS: Linux Mint 19

### Hardware ###

- Name: HP Pavillion zd8000
- CPU: Pentium 4 650
- RAM: 1GB DDR2 SDRAM, 533Mhz
- GPU: 256MB ATI Mobility Radeon X600

### Verbose output ###

[INFO] RetroArch 1.7.5 (Git c9c6c5a)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 
Built: Oct  2 2018
[INFO] Version: 1.7.5
[INFO] Git: c9c6c5a
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1680x1050.
[INFO] [GLX]: Window manager is Metacity (Marco).
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [GL]: Vendor: X.Org R300 Project, Renderer: ATI RV380.
[INFO] [GL]: Version: 2.1 Mesa 18.0.5.
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ... 
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0xd77440
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/user/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [PulseAudio]: Unpausing.
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [PulseAudio]: Pausing.
[INFO] Updating firmware status for: /usr/lib/i386-linux-gnu/libretro/mupen64plus_libretro.so on /home/user/Desktop/1080 Snowboarding/
[INFO] Using content: /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].z64.
[INFO] arg #0: retroarch
[INFO] arg #1: /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].z64
[INFO] arg #2: -c
[INFO] arg #3: /home/user/.config/retroarch/retroarch.cfg
[INFO] arg #4: -L
[INFO] arg #5: /usr/lib/i386-linux-gnu/libretro/mupen64plus_libretro.so
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Average monitor Hz: 59.612519 Hz. (14.730 % frame time deviation, based on 2048 last samples).
[INFO] Set config file to : /home/user/.config/retroarch/retroarch.cfg
[INFO] RetroArch 1.7.5 (Git c9c6c5a)
[INFO] Redirecting save file to "/home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].srm".
[INFO] Redirecting savestate to "/home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 
Built: Oct  2 2018
[INFO] Version: 1.7.5
[INFO] Git: c9c6c5a
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/usr/lib/i386-linux-gnu/libretro/mupen64plus_libretro.so"
[INFO] [overrides] no core-specific overrides found at /home/user/.config/retroarch/config/Mupen64Plus OpenGL/Mupen64Plus OpenGL.cfg.
[INFO] [overrides] no content-dir-specific overrides found at /home/user/.config/retroarch/config/Mupen64Plus OpenGL/1080 Snowboarding.cfg.
[INFO] [overrides] no game-specific overrides found at /home/user/.config/retroarch/config/Mupen64Plus OpenGL/1080 Snowboarding (E) (M4) [!].cfg.
[INFO] Shaders: preset directory: /home/user/.config/retroarch/shaders/presets
[INFO] Shaders: no game-specific preset found at /home/user/.config/retroarch/shaders/presets/Mupen64Plus OpenGL/1080 Snowboarding (E) (M4) [!].cgp.
[INFO] Shaders: no game-specific preset found at /home/user/.config/retroarch/shaders/presets/Mupen64Plus OpenGL/1080 Snowboarding (E) (M4) [!].glslp.
[INFO] Shaders: no content-dir-specific preset found at /home/user/.config/retroarch/shaders/presets/Mupen64Plus OpenGL/1080 Snowboarding.cgp.
[INFO] Shaders: no content-dir-specific preset found at /home/user/.config/retroarch/shaders/presets/Mupen64Plus OpenGL/1080 Snowboarding.glslp.
[INFO] Shaders: no core-specific preset found at /home/user/.config/retroarch/shaders/presets/Mupen64Plus OpenGL/Mupen64Plus OpenGL.cgp.
[INFO] Shaders: no core-specific preset found at /home/user/.config/retroarch/shaders/presets/Mupen64Plus OpenGL/Mupen64Plus OpenGL.glslp.
[INFO] Environ SET_VARIABLES.
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 2
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 3
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 4
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Remaps: remap directory: /home/user/.config/retroarch/config/remaps
[INFO] Remaps: no game-specific remap found at /home/user/.config/retroarch/config/remaps/Mupen64Plus OpenGL/1080 Snowboarding (E) (M4) [!].rmp.
[INFO] Remaps: no content-dir-specific remap found at /home/user/.config/retroarch/config/remaps/Mupen64Plus OpenGL/1080 Snowboarding.rmp.
[INFO] Remaps: no core-specific remap found at /home/user/.config/retroarch/config/remaps/Mupen64Plus OpenGL/Mupen64Plus OpenGL.rmp.
[INFO] Redirecting save file to "/home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].srm".
[INFO] Redirecting savestate to "/home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].state".
[WARN] SYSTEM DIR is empty, assume CONTENT DIR /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].z64
[INFO] Environ SYSTEM_DIRECTORY: "/home/user/Desktop/1080 Snowboarding/".
[WARN] SYSTEM DIR is empty, assume CONTENT DIR /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].z64
[INFO] Environ SYSTEM_DIRECTORY: "/home/user/Desktop/1080 Snowboarding/".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ GET_PERF_INTERFACE.
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ GET_RUMBLE_INTERFACE.
[INFO] Loading content file: /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].z64.
[INFO] Did not find a valid content patch.
[INFO] CRC32: 0x75a21679 .
[INFO] Environ GET_VARIABLE mupen64plus-rspmode:
[INFO] 	HLE
[INFO] Environ GET_VARIABLE mupen64plus-BilinearMode:
[INFO] 	standard
[INFO] Environ GET_VARIABLE mupen64plus-MultiSampling:
[INFO] 	0
[INFO] Environ GET_VARIABLE mupen64plus-EnableFBEmulation:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-EnableCopyColorToRDRAM:
[INFO] 	Async
[INFO] Environ GET_VARIABLE mupen64plus-EnableCopyDepthToRDRAM:
[INFO] 	Software
[INFO] Environ GET_VARIABLE mupen64plus-EnableHWLighting:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-CorrectTexrectCoords:
[INFO] 	Off
[INFO] Environ GET_VARIABLE mupen64plus-EnableNativeResTexrects:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-txFilterMode:
[INFO] 	None
[INFO] Environ GET_VARIABLE mupen64plus-txEnhancementMode:
[INFO] 	None
[INFO] Environ GET_VARIABLE mupen64plus-txFilterIgnoreBG:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-txHiresEnable:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-txHiresFullAlphaChannel:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-EnableLegacyBlending:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-EnableFragmentDepthWrite:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-EnableShadersStorage:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-CropMode:
[INFO] 	Auto
[INFO] Environ GET_VARIABLE mupen64plus-cpucore:
[INFO] 	dynamic_recompiler
[INFO] Environ GET_VARIABLE mupen64plus-aspect:
[INFO] 	4:3
[INFO] Environ GET_VARIABLE mupen64plus-43screensize:
[INFO] 	320x240
[INFO] Environ GET_VARIABLE mupen64plus-astick-deadzone:
[INFO] 	15
[INFO] Environ GET_VARIABLE mupen64plus-astick-sensitivity:
[INFO] 	100
[INFO] Environ GET_VARIABLE mupen64plus-CountPerOp:
[INFO] 	0
[INFO] Environ GET_VARIABLE mupen64plus-r-cbutton:
[INFO] 	C1
[INFO] Environ GET_VARIABLE mupen64plus-l-cbutton:
[INFO] 	C2
[INFO] Environ GET_VARIABLE mupen64plus-d-cbutton:
[INFO] 	C3
[INFO] Environ GET_VARIABLE mupen64plus-u-cbutton:
[INFO] 	C4
[INFO] Environ GET_VARIABLE mupen64plus-pak1:
[INFO] 	memory
[INFO] Environ GET_VARIABLE mupen64plus-pak2:
[INFO] 	none
[INFO] Environ GET_VARIABLE mupen64plus-pak3:
[INFO] 	none
[INFO] Environ GET_VARIABLE mupen64plus-pak4:
[INFO] 	none
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.3).
[WARN] SYSTEM DIR is empty, assume CONTENT DIR /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].z64
[INFO] Environ SYSTEM_DIRECTORY: "/home/user/Desktop/1080 Snowboarding/".
[libretro INFO] EmuThread: M64CMD_ROM_OPEN
[libretro INFO] mupen64plus: Goodname: 1080 Snowboarding (E) (M4) [!]
[libretro INFO] mupen64plus: Name: 1080 SNOWBOARDING   
[libretro INFO] mupen64plus: MD5: 632C98CF281CDA776E66685B278A4FA6
[libretro INFO] mupen64plus: CRC: 58FD3F25 D92EAA8D
[libretro INFO] mupen64plus: Imagetype: .z64 (native)
[libretro INFO] mupen64plus: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
[libretro INFO] mupen64plus: ClockRate = F
[libretro INFO] mupen64plus: Version: 1449
[libretro INFO] mupen64plus: Manufacturer: Nintendo
[libretro INFO] mupen64plus: Cartridge_ID: 4554
[libretro INFO] mupen64plus: Country: Europe (0x50)
[libretro INFO] mupen64plus: PC = 80100400
[libretro INFO] mupen64plus: Save type: 2
[libretro INFO] EmuThread: M64CMD_ROM_GET_HEADER
Failed to open /home/user/Desktop/1080 Snowboarding/1080 Snowboarding (E) (M4) [!].srm: No such file or directory
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Timings deviate too much. Will not adjust. (Display = 59.94 Hz, Game = 50.00 Hz)
[INFO] [Video]: Video @ 960x720
[INFO] [Video]: Using HW render, OpenGL driver forced.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1680x1050.
[INFO] [GLX]: Window manager is Metacity (Marco).
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  51
  Current serial number in output stream:  50

**Comment by RobLoach** [comment] 2018-11-18 18:45
Working here...

1. Do any other 3D/OpenGL cores work on your system?
2. What video driver are you using? I see some wayland attempts in that log.
3. Looks like you're using the ppa for the core? There have been some updates to master for it lately, mind trying out the nightly for it? Alternatively, mind trying to build locally and running through that?

**Comment by hizzlekizzle** [comment] 2018-11-18 18:49
He's using an Ati RV380, which supports GL 2.1, but I'm suspicious that this core requires higher GL capabilities.

**Comment by Makaque** [comment] 2018-11-18 19:45
I'm noticing now that my standalone Mupen64Plus installation is not using GlideN64. Both rice and Glide mk2 are working. Is there a way to swap the graphics plugin used by the libretro core?

I'm currently trying to compile GlideN64 for my system to see how that behaves.

**Comment by Makaque** [comment] 2018-11-18 22:12
I've used GLideN64 and know that it works well. No other reason really. 
GlideN64 doesn't seem to want to work in 32 bit linux, so it seems that I'll be using ParaLLEl, or Glide mk 2 with the standalone application.

**Comment by RobLoach** [comment] 2018-12-14 19:00
Would you mind opening up an issue in the core's issue queue? This might be fixed already.

**Comment by jewnersey** [comment] 2018-12-15 06:53
Chiming in as I am having this issue as well:
 
Funny thing for me is that I earlier today I was on xubuntu and I was able to run the Mupen64 core through retroarch.

Then I reinstalled system to lubuntu (did not overwrite my /home directory though) and now it crashes with the same error (X Error of failed request:  GLXBadFBConfig). 

So, I know the system is capable of handling it (I was playing Blast Corps) I just cant seem to get that same setup back.

OpenGl is version 2.1. Haven't had success trying to get on 3.3
My machine is AMD

**Comment by orbea** [comment] 2018-12-21 05:37
The mupen64plus core requires a somewhat modern system as it uses GLideN64 while the parallel-n64 core uses glide64 and other plugins which do not require as modern of a GL.

This is essentially a core problem, but the mupen64plus core is currently not maintained and out of date with GLideN64. I would not expect it to work well with GL 2.1 and my suggestion is to use parallel-n64 with RetroArch instead. If anyone wants to pursue this further try reproducing it with mupen64plus standalone + GLideN64 and report it upstream.

https://github.com/gonetz/GLideN64/issues

As this is a core issue, I am going to close this report.

**Closed by orbea** 2018-12-21 05:37 UTC
