### ISSUE TITLE
Request: RetroArch to accept language translations via Transifex services?

### ISSUE THREAD

**Issue by Hedda** [libretro/RetroArch#4679] opened 2017-02-21 12:05 UTC
Suggest that developers setup a new project for RetroArch on Transifex translation services (and maybe also seperate projects on Transifex for libretro-database and other official projects like Lakka) to get crowdsourced translations from your community.

https://en.wikipedia.org/wiki/Transifex

Many popular open source software projects use Transifex workflows to get free string language translations via crowdsourcing from their communities.

Example of an open source project using Transifex for many years is Kodi as you can read here:
https://kodi.tv/new-translation-service/
and here:
http://kodi.wiki/view/Translation_System

For end-users wanting to help out with the project using Transifex to translate strings is as easy as using a wiki.

Users just need to register an account for free on Transifex then join the project for the languages they know and begin to translate strings they understand.

All you need to do is point to files on GitHub you want translating and then copy/pull them from Transifex on a regular bases (usually before each release).

**Comment by Alcaro** [comment] 2018-02-05 12:58
Duplicate of #5831

(yes, yours came first, but the other one is more active.)

**Closed by Alcaro** 2018-02-05 12:58 UTC
