### ISSUE TITLE
how to get pc engine games working??!!

### ISSUE THREAD

**Issue by brothan323** [libretro/RetroArch#7738] opened 2018-12-13 08:18 UTC
I cannot get pc engine games to work. I'm trying to load Rondo of Blood(japanese version) and either Retroarch crashes or just loads into a black screen. No combination or rom files/cores/bios works for me. Can someone please give me a step-by-step guide on how to get this stupid thing working?

**Comment by gouchi** [comment] 2018-12-13 10:14
Hi,
Did you read the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) ?

> 
> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

If you can reproduce the issue and characterized as bug, you should provide some [log](http://docs.libretro.com/guides/generating-retroarch-logs/) otherwise please use our [forum](https://forums.libretro.com) and read  the [documentation](http://docs.libretro.com/library/beetle_pce_fast/).

Moreover, please try to keep it civilized.

> Can someone please give me a step-by-step guide on how to get this stupid thing working?

Thank you for your consideration.

**Comment by Cee123** [comment] 2018-12-13 10:30
@brothan323 I had a similar problem. Turns out there is one rom set that doesn't work with this. I fixed it by using a different rom set. Don't know if that helps.

**Comment by gouchi** [comment] 2018-12-13 14:53
[Good](https://forums.libretro.com/t/cannot-get-pc-engine-games-working/)...

**Comment by orbea** [comment] 2018-12-14 02:58
This is a question that is better suited for the forum, given the forum thread already exists and has people trying to help I am going to close this. If there are any remaining issues please submit them to the specific core repos.

**Closed by orbea** 2018-12-14 02:58 UTC
