### ISSUE TITLE
Asking for a way to set a core to start in 'game focus on'.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#6132] opened 2018-01-18 10:36 UTC
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I simply find that turning on always 'game focus' mode on certain cores would enhance my usability. For instance scummvm core requires it for the cursor to scale movement to the monitor correctly (instead of reaching the limits of a imaginary square and stopping or clicking on the wrong button regardless of where the cursor is). Dosbox, amiga, pc98, x6800 cores often require the keyboard etc.

### Expected behavior

Simply a setting on the core configuration 'Start with game focus on' or similar

### Actual behavior

I always forget and i am always annoyed.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment] 2018-01-18 14:43
What is Game Focus, and where does one enable it?

**Comment by hyarsan** [comment] 2018-01-18 14:53
@RobLoach You enable it in the hot key settings. It is currently pretty broken though. Turning it back off using the toggle does not work.

**Comment by i30817** [comment] 2018-01-18 14:57
>    @RobLoach You enable it in the hot key settings. It is currently pretty broken though. Turning it back off using the toggle does not work.
It totally does

It's under Input->Input Hotkeys Bind->game focus toggle
The default is scroll lock or something awkward to get to on portables so i changed it to num lock.

What it does is to toggle every single 'hotkey' that is system related off (ie: not retropad controller bindings. The disabled keys *don't* include the menu shortcut for the retropad thankfully).

**Comment by hyarsan** [comment] 2018-01-18 15:02
@i30817 but it doesn't... it's a bug. *insert issue number here*

**Comment by i30817** [comment] 2018-01-18 15:04
It... works for me. That's actually pretty weird to me, because i've been on the other side of features working for everyone but me.

**Comment by fr500** [comment] 2018-01-20 16:16
@hyarsan it works fine but it doesn't work if you have a hotkey enable modifier.

**Comment by i30817** [comment] 2018-01-24 10:32
Well that explains it @fr500 , because most mobile keyboards, including mine, set the scroll lock (the original default) to Fn key + printsc. The first thing i did with the setting was change it to numlock. Maybe a change of default is in order?

**Comment by webdevkit** [comment] 2020-03-21 03:39
I found this GitHub issue because I, too, was looking for a configuration property to enable/disable game focus mode that could be set at the global, core, and game levels.

My specific use case is related to DOSBox. Pretty much everything I launch through DOSBox is designed to be used via a keyboard. Enabling Game Focus Mode allows me to use DOS with my keyboard as I normally would without it triggering all sorts of RetroArch features like fast forward and full screen and whatnot.

I'm going to keep looking for a solution or try some sort of input remapping for DOSBox, but a toggle switch for game focus mode might be the ideal implementation.

**Comment by i30817** [comment] 2020-03-21 03:47
switch it to numlock, it works as a toggle.

**Comment by webdevkit** [comment] 2020-03-21 17:27
Oh, scroll lock works fine for me as well as a toggle, since I'm emulating DOS and am using a keyboard. The problem is remembering to toggle it on whenever I launch a DOSBox game. I'd much prefer to use a configuration setting to enable this setting automatically for me, for DOSBox only.

It's certainly not a priority or a bug in any way. It's more like a usability enhancement, since pretty much everything else is configurable through some property.

**Comment by i30817** [comment] 2020-03-21 17:41
I tend to forget too but it's because i basically removed most 'system' keyboard shortcuts from RA, for simple survival. The 'esc quits the core without confirmation' thing is a abomination, and several other features like video recording, frame advance etc etc i'm simply interested in.

**Comment by sonninnos** [comment] 2021-01-29 07:30
This was sorted with: https://github.com/libretro/RetroArch/pull/11868

**Comment by gouchi** [comment] 2022-05-21 20:53
@i30817 If it is ok for you, please close this issue.

Thank you.

**Closed** 2022-05-21 23:26 UTC
Labels: feature request
